DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50031, 'No organization exists for model provider management seed.', 1;

DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');
DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('ai_providers.view','View AI providers'),('ai_providers.view_details','View AI provider details'),('ai_providers.create','Create AI providers'),('ai_providers.edit','Edit AI providers'),('ai_providers.validate','Validate AI providers'),('ai_providers.discover_models','Discover provider models'),('ai_providers.manage_credentials','Manage provider credentials'),('ai_providers.rotate_credentials','Rotate provider credentials'),('ai_providers.manage_quotas','Manage provider quotas'),('ai_providers.manage_budgets','Manage provider budgets'),('ai_providers.manage_security','Manage provider security'),('ai_providers.manage_residency','Manage provider residency'),('ai_providers.enable','Enable providers'),('ai_providers.disable','Disable providers'),('ai_providers.deprecate','Deprecate providers'),('ai_providers.export','Export providers'),('ai_models.view','View AI models'),('ai_models.view_details','View AI model details'),('ai_models.register','Register AI models'),('ai_models.edit','Edit AI models'),('ai_models.validate','Validate AI models'),('ai_models.benchmark','Benchmark AI models'),('ai_models.compare','Compare AI models'),('ai_models.manage_pricing','Manage model pricing'),('ai_models.manage_compatibility','Manage model compatibility'),('ai_models.mark_preferred','Mark model preferred'),('ai_models.mark_fallback','Mark model fallback'),('ai_models.enable','Enable models'),('ai_models.disable','Disable models'),('ai_models.deprecate','Deprecate models'),('ai_models.export','Export models'),('ai_model_routing.view','View model routing'),('ai_model_routing.manage_policies','Manage routing policies'),('ai_model_routing.recalculate','Recalculate routing'),('ai_model_routing.simulate','Simulate routing'),('ai_model_routing.manage_failover','Manage model failover'),('ai_model_routing.manage_circuit_breakers','Manage circuit breakers'),('ai_model_routing.apply_recommendations','Apply routing recommendations'),('ai_model_routing.manage_governance','Manage routing governance'),('ai_model_routing.emergency_override','Use routing emergency override');
MERGE permissions AS target USING (SELECT code,description FROM @perms) AS source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org AS organization_id, 'ai-model-provider-operations' AS name) AS source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=98, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',98);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('AI_PROVIDER_REGISTRATION','AI Provider Registration'),('AI_PROVIDER_CONNECTION_VALIDATION','AI Provider Connection Validation'),('AI_PROVIDER_CREDENTIAL_ROTATION','AI Provider Credential Rotation'),('AI_PROVIDER_HEALTH_RECOVERY','AI Provider Health Recovery'),('AI_MODEL_REGISTRATION','AI Model Registration'),('AI_MODEL_CAPABILITY_VALIDATION','AI Model Capability Validation'),('AI_MODEL_BENCHMARK','AI Model Benchmark'),('AI_MODEL_ROUTING_DECISION','AI Model Routing Decision'),('AI_MODEL_AUTOMATIC_FAILOVER','AI Model Automatic Failover'),('AI_MODEL_DEPRECATION_MIGRATION','AI Model Deprecation Migration'),('AI_MODEL_ROUTING_OPTIMIZATION','AI Model Routing Optimization'),('AI_MODEL_GOVERNANCE_APPROVAL','AI Model Governance Approval');
MERGE workflow_definitions AS target USING (SELECT @org AS organization_id, code, name, 'ai_model_provider_operations' AS workflow_type FROM @wf) AS source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM ai_model_provider_final_output_impact WHERE organization_id=@org;
DELETE FROM ai_model_provider_recommendations WHERE organization_id=@org;
DELETE FROM ai_model_provider_circuit_breakers WHERE organization_id=@org;
DELETE FROM ai_model_provider_failovers WHERE organization_id=@org;
DELETE FROM ai_model_provider_routing_decisions WHERE organization_id=@org;
DELETE FROM ai_model_provider_routing_policies WHERE organization_id=@org;
DELETE FROM ai_model_provider_benchmarks WHERE organization_id=@org;
DELETE FROM ai_model_operations WHERE organization_id=@org;
DELETE FROM ai_provider_operations WHERE organization_id=@org;
DELETE FROM ai_model_provider_lifecycle WHERE organization_id=@org;
DELETE FROM ai_provider_category_metrics WHERE organization_id=@org;
DELETE FROM ai_models WHERE code LIKE 'MP-MDL-%' AND provider_id IN (SELECT id FROM ai_providers WHERE organization_id=@org AND code LIKE 'MP-PRV-%');
DELETE FROM ai_providers WHERE organization_id=@org AND code LIKE 'MP-PRV-%';

DECLARE @providers TABLE(seq INT, code NVARCHAR(120), name NVARCHAR(180), type NVARCHAR(80), status NVARCHAR(40), region NVARCHAR(120), auth NVARCHAR(120), residency NVARCHAR(120));
INSERT INTO @providers VALUES
(1,'MP-PRV-OPENAI','OpenAI','Cloud','Active','United States','API Key','US/EU approved'),(2,'MP-PRV-AZURE','Azure OpenAI','Enterprise Cloud','Healthy','West Europe','Managed Identity','EU resident'),(3,'MP-PRV-ANTHROPIC','Anthropic','Cloud','Active','United States','API Key','US approved'),(4,'MP-PRV-GOOGLE','Google Vertex AI','Enterprise Cloud','Degraded','europe-west4','Service Account','EU resident'),(5,'MP-PRV-MISTRAL','Mistral','Cloud','Healthy','France','API Key','EU resident'),(6,'MP-PRV-DEEPSEEK','DeepSeek','Cloud','Rate Limited','Singapore','API Key','restricted'),(7,'MP-PRV-GROQ','Groq','Cloud','Healthy','United States','API Key','US approved'),(8,'MP-PRV-OPENROUTER','OpenRouter','Aggregator','Quota Limited','Global','API Key','policy routed'),(9,'MP-PRV-OLLAMA','Ollama Local','Local','Healthy','Lagos Datacenter','Private Token','local only'),(10,'MP-PRV-STABILITY','Stability AI','Cloud','Healthy','United States','API Key','US approved'),(11,'MP-PRV-ELEVEN','ElevenLabs','Cloud','Credential Warning','Europe','API Key','EU approved'),(12,'MP-PRV-CUSTOM','CACSMS Private Model Gateway','Private Endpoint','Healthy','Lagos Private Cloud','mTLS','Nigeria resident');
INSERT INTO ai_providers(organization_id,code,name,provider_name,provider_type,status,base_url,config_json)
SELECT @org,code,name,name,type,status,CONCAT('https://api.',LOWER(REPLACE(REPLACE(name,' ',''),'.','')),'.example/v1'),'{"managedBy":"ai-model-provider-operations"}' FROM @providers;

INSERT INTO ai_provider_operations(provider_id,organization_id,environment,region,endpoint,authentication_type,credential_status,models_available,active_routes,requests_today,success_rate,failure_rate,average_latency_seconds,p95_latency_seconds,spend_today,monthly_spend,quota_usage,rate_limit_status,data_residency,last_health_check,last_failure,owner,organization_scope,health_percent,credential_expiry_days,quota_warning)
SELECT p.id,@org,'production',src.region,p.base_url,src.auth,CASE WHEN p.status='Credential Warning' THEN 'expiring' ELSE 'valid' END,5+(src.seq%6),8+(src.seq%12),1200+(src.seq*341),CASE WHEN p.status IN ('Degraded','Rate Limited','Quota Limited') THEN 91+src.seq%4 ELSE 97+src.seq%2 END,CASE WHEN p.status IN ('Degraded','Rate Limited','Quota Limited') THEN 3+src.seq%5 ELSE src.seq%2 END,CAST(1.2+(src.seq%6)*0.42 AS DECIMAL(8,2)),CAST(2.1+(src.seq%6)*0.75 AS DECIMAL(8,2)),CAST(9.20+src.seq*4.85 AS DECIMAL(18,2)),CAST(180+src.seq*92.50 AS DECIMAL(18,2)),CASE WHEN p.status='Quota Limited' THEN 91 WHEN p.status='Rate Limited' THEN 84 ELSE 42+src.seq%33 END,CASE WHEN p.status='Rate Limited' THEN 'rate limited' WHEN p.status='Quota Limited' THEN 'quota warning' ELSE 'clear' END,src.residency,DATEADD(minute,-src.seq*3,SYSUTCDATETIME()),CASE WHEN p.status IN ('Degraded','Rate Limited') THEN DATEADD(minute,-src.seq*17,SYSUTCDATETIME()) ELSE NULL END,'ai-runtime-ops','AI Media Group',CASE WHEN p.status='Degraded' THEN 88 WHEN p.status IN ('Rate Limited','Quota Limited','Credential Warning') THEN 91 ELSE 97+src.seq%2 END,CASE WHEN p.status='Credential Warning' THEN 9 ELSE 60+src.seq*8 END,CASE WHEN p.status='Quota Limited' THEN 1 ELSE 0 END
FROM ai_providers p JOIN @providers src ON src.code=p.code WHERE p.organization_id=@org;

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<86),
prov AS (SELECT p.id, p.code, ROW_NUMBER() OVER (ORDER BY p.code) rn, COUNT(*) OVER () cnt FROM ai_providers p WHERE p.organization_id=@org AND p.code LIKE 'MP-PRV-%'),
src AS (SELECT n.i, prov.id provider_id, prov.code provider_code FROM n JOIN prov ON prov.rn=((n.i-1)%prov.cnt)+1)
INSERT INTO ai_models(provider_id,code,name,model_name,model_type,context_window,status,quality_tier,latency_tier)
SELECT provider_id,CONCAT('MP-MDL-',RIGHT('0000'+CAST(i AS NVARCHAR(4)),4)),CONCAT(CASE i%14 WHEN 0 THEN 'Reasoning' WHEN 1 THEN 'Text' WHEN 2 THEN 'Vision' WHEN 3 THEN 'Image' WHEN 4 THEN 'Video' WHEN 5 THEN 'Speech' WHEN 6 THEN 'Voice' WHEN 7 THEN 'Embedding' WHEN 8 THEN 'Rerank' WHEN 9 THEN 'Moderation' WHEN 10 THEN 'Multimodal' WHEN 11 THEN 'Classification' WHEN 12 THEN 'Small Language' ELSE 'Large Language' END,' Model ',i),CONCAT('runtime-model-',i),CASE i%14 WHEN 0 THEN 'Reasoning Model' WHEN 1 THEN 'Large Language Model' WHEN 2 THEN 'Vision Model' WHEN 3 THEN 'Image Generation Model' WHEN 4 THEN 'Video Generation Model' WHEN 5 THEN 'Speech-to-Text Model' WHEN 6 THEN 'Text-to-Speech Model' WHEN 7 THEN 'Embedding Model' WHEN 8 THEN 'Reranking Model' WHEN 9 THEN 'Moderation Model' WHEN 10 THEN 'Multimodal Model' WHEN 11 THEN 'Classification Model' WHEN 12 THEN 'Small Language Model' ELSE 'Custom Model' END,CASE WHEN i%5=0 THEN 200000 WHEN i%3=0 THEN 128000 ELSE 32000+(i%8)*8000 END,CASE WHEN i IN (12,31) THEN 'Degraded' WHEN i IN (21,46,72) THEN 'Rate Limited' WHEN i IN (64,78) THEN 'Deprecated' WHEN i%11=0 THEN 'Fallback' WHEN i%7=0 THEN 'Preferred' ELSE 'Available' END,CASE WHEN i%7=0 THEN 'high' ELSE 'standard' END,CASE WHEN i%5=0 THEN 'fast' ELSE 'normal' END FROM src OPTION (MAXRECURSION 0);

INSERT INTO ai_model_operations(model_id,organization_id,model_family,model_version,modality,health_percent,max_output_tokens,structured_output,tool_calling,streaming,vision_support,audio_support,video_support,embedding_support,fine_tuning_support,average_quality,average_confidence,average_latency_seconds,p95_latency_seconds,input_cost,output_cost,average_cost_per_run,requests_today,success_rate,failure_rate,rate_limit_state,deprecation_date,assigned_agents,assigned_capabilities,active_routes,final_output_state)
SELECT m.id,@org,m.model_type,CONCAT('v',1+(ABS(CHECKSUM(m.id))%5),'.',ABS(CHECKSUM(m.code))%10),CASE WHEN m.model_type LIKE '%Image%' THEN 'image' WHEN m.model_type LIKE '%Video%' THEN 'video' WHEN m.model_type LIKE '%Speech%' OR m.model_type LIKE '%Voice%' THEN 'audio' WHEN m.model_type LIKE '%Embedding%' THEN 'embedding' WHEN m.model_type LIKE '%Multimodal%' OR m.model_type LIKE '%Vision%' THEN 'multimodal' ELSE 'text' END,CASE WHEN m.status IN ('Degraded','Rate Limited') THEN 88 ELSE 94+(ABS(CHECKSUM(m.id))%5) END,2048+(ABS(CHECKSUM(m.code))%8)*1024,1,CASE WHEN m.model_type LIKE '%Language%' OR m.model_type LIKE '%Reasoning%' THEN 1 ELSE 0 END,1,CASE WHEN m.model_type LIKE '%Vision%' OR m.model_type LIKE '%Image%' OR m.model_type LIKE '%Multimodal%' THEN 1 ELSE 0 END,CASE WHEN m.model_type LIKE '%Speech%' OR m.model_type LIKE '%Voice%' OR m.model_type LIKE '%Audio%' OR m.model_type LIKE '%Multimodal%' THEN 1 ELSE 0 END,CASE WHEN m.model_type LIKE '%Video%' OR m.model_type LIKE '%Multimodal%' THEN 1 ELSE 0 END,CASE WHEN m.model_type LIKE '%Embedding%' THEN 1 ELSE 0 END,CASE WHEN m.model_type LIKE '%Custom%' THEN 1 ELSE 0 END,88+(ABS(CHECKSUM(m.id))%11),87+(ABS(CHECKSUM(m.code))%12),CAST(0.9+(ABS(CHECKSUM(m.id))%8)*0.34 AS DECIMAL(8,2)),CAST(1.8+(ABS(CHECKSUM(m.code))%8)*0.62 AS DECIMAL(8,2)),CAST(0.0008+(ABS(CHECKSUM(m.id))%12)*0.0005 AS DECIMAL(18,6)),CAST(0.0020+(ABS(CHECKSUM(m.code))%12)*0.0010 AS DECIMAL(18,6)),CAST(0.018+(ABS(CHECKSUM(m.id))%30)*0.006 AS DECIMAL(18,4)),80+(ABS(CHECKSUM(m.id))%1800),CASE WHEN m.status IN ('Degraded','Rate Limited') THEN 90 ELSE 95+(ABS(CHECKSUM(m.code))%4) END,CASE WHEN m.status IN ('Degraded','Rate Limited') THEN 3+ABS(CHECKSUM(m.id))%4 ELSE ABS(CHECKSUM(m.code))%2 END,CASE WHEN m.status='Rate Limited' THEN 'rate limited' ELSE 'clear' END,CASE WHEN m.status='Deprecated' THEN DATEADD(day,45,CAST(SYSUTCDATETIME() AS DATE)) ELSE NULL END,1+(ABS(CHECKSUM(m.id))%9),1+(ABS(CHECKSUM(m.code))%7),1+(ABS(CHECKSUM(m.id,m.code))%5),CASE WHEN m.status IN ('Degraded','Deprecated') THEN 'watch' ELSE 'protected' END FROM ai_models m JOIN ai_providers p ON p.id=m.provider_id WHERE p.organization_id=@org AND m.code LIKE 'MP-MDL-%';

DECLARE @cat TABLE(name NVARCHAR(180), providers INT, active INT, healthy INT, degraded INT, models INT, req INT, success DECIMAL(8,2), latency DECIMAL(8,2), cost DECIMAL(18,4), failovers INT, quota INT, health DECIMAL(8,2));
INSERT INTO @cat VALUES
('Commercial Cloud Providers',6,6,5,1,44,12420,96.8,2.7,0.048,12,1,96),('Enterprise Cloud Providers',2,2,2,0,18,8200,97.4,2.4,0.052,6,0,98),('Aggregator Providers',1,1,0,1,9,4300,94.2,3.6,0.061,8,1,91),('Local and Self-Hosted Providers',1,1,1,0,5,1880,98.8,1.1,0.008,1,0,99),('Text Generation Providers',8,8,7,1,32,10220,96.9,2.4,0.043,9,1,97),('Image Generation Providers',3,3,3,0,8,1460,95.4,4.8,0.084,2,0,96),('Audio and Voice Providers',3,3,2,1,7,1220,94.8,3.9,0.058,3,1,93),('Video Generation Providers',2,2,2,0,5,620,93.8,8.2,0.142,2,0,94),('Embedding Providers',6,6,6,0,6,8400,99.1,0.7,0.006,1,0,99),('Reranking Providers',4,4,4,0,4,6400,98.4,0.9,0.008,1,0,98),('Moderation Providers',5,5,5,0,5,9200,99.4,0.5,0.004,0,0,99),('Speech-to-Text Providers',3,3,2,1,4,980,95.2,2.8,0.032,2,1,94),('Text-to-Speech Providers',3,3,2,1,4,780,94.8,3.1,0.041,2,1,93),('Multimodal Providers',5,5,4,1,12,3600,96.0,3.2,0.066,4,0,95),('Custom API Providers',2,2,2,0,5,1260,98.1,1.6,0.022,1,0,98);
INSERT INTO ai_provider_category_metrics(organization_id,category_name,provider_count,active_providers,healthy_providers,degraded_providers,available_models,requests_today,success_rate,average_latency_seconds,average_cost,failover_count,quota_risk,health_percent)
SELECT @org,name,providers,active,healthy,degraded,models,req,success,latency,cost,failovers,quota,health FROM @cat;

DECLARE @stages TABLE(kind NVARCHAR(80), stage NVARCHAR(180), seq INT);
INSERT INTO @stages VALUES
('Provider','Provider Registration',1),('Provider','Credential Validation',2),('Provider','Endpoint Validation',3),('Provider','Model Discovery',4),('Provider','Capability Mapping',5),('Provider','Benchmarking',6),('Provider','Policy Validation',7),('Provider','Route Publication',8),('Provider','Active Monitoring',9),('Provider','Optimization',10),('Provider','Version Update',11),('Provider','Deprecation',12),('Provider','Archive',13),
('Routing','Task Received',1),('Routing','Capability Identified',2),('Routing','Policy Loaded',3),('Routing','Candidate Models Selected',4),('Routing','Health Evaluated',5),('Routing','Quality Predicted',6),('Routing','Cost Predicted',7),('Routing','Latency Predicted',8),('Routing','Route Selected',9),('Routing','Request Executed',10),('Routing','Output Validated',11),('Routing','Metrics Recorded',12),('Routing','Learning Updated',13),
('Failure','Request Failed',1),('Failure','Failure Classified',2),('Failure','Alternate Route Selected',3),('Failure','Context Revalidated',4),('Failure','Request Retried',5),('Failure','Output Compared',6),('Failure','Workflow Resumed',7),('Failure','Incident or Escalation if Exhausted',8);
INSERT INTO ai_model_provider_lifecycle(organization_id,lifecycle_type,stage_name,sequence_no,provider_count,model_count,request_count,failure_count,failover_count,average_duration,health_percent,current_blockers)
SELECT @org,kind,stage,seq,12,86,1200+(seq*71),CASE WHEN kind='Failure' THEN 4 ELSE seq%3 END,CASE WHEN kind='Failure' THEN 3 ELSE seq%2 END,CONCAT(2+seq,'m'),CASE WHEN kind='Failure' THEN 93 ELSE 96 END,CASE WHEN kind='Failure' AND seq=8 THEN 'fallback exhaustion monitored' ELSE 'none' END FROM @stages;

INSERT INTO ai_model_provider_benchmarks(model_id,organization_id,benchmark_name,quality_score,latency_score,cost_score,reliability_score,recommendation)
SELECT id,@org,'Continuous autonomous model benchmark',average_quality,CASE WHEN average_latency_seconds<2 THEN 98 ELSE 90 END,CASE WHEN average_cost_per_run<0.08 THEN 96 ELSE 88 END,success_rate,'route within policy weight and final-output guardrails' FROM vw_ai_models WHERE organization_id=@org;
INSERT INTO ai_model_provider_routing_policies(organization_id,policy_code,policy_name,scope_type,status,current_version,priority,routing_objective,quality_weight,cost_weight,latency_weight,reliability_weight,fallback_enabled,environment) VALUES
(@org,'ROUTE-QUALITY','Quality Optimized Agent Routing','agent','active',4,1,'quality',45,15,15,25,1,'production'),(@org,'ROUTE-COST','Cost Optimized Background Routing','workflow','active',3,2,'cost',25,40,15,20,1,'production'),(@org,'ROUTE-LATENCY','Low Latency Interactive Routing','tool','active',2,3,'latency',25,15,40,20,1,'production'),(@org,'ROUTE-RELIABILITY','Reliability Protected Final Output Routing','final-output','active',5,0,'reliability',30,10,15,45,1,'production');
INSERT INTO ai_model_provider_routing_decisions(organization_id,decision_code,task_name,agent_name,capability,prompt_code,candidate_providers,candidate_models,selected_provider,selected_model,quality_estimate,cost_estimate,latency_estimate_seconds,reliability_estimate,confidence,risk,final_output_impact,outcome)
SELECT TOP 80 @org,CONCAT('RTD-',RIGHT('0000'+CAST(ROW_NUMBER() OVER (ORDER BY m.updated_at DESC) AS NVARCHAR(4)),4)),'content runtime task',COALESCE(a.name,'Autonomous Agent'),'content generation and validation',COALESCE(pr.prompt_code,'PRM-runtime'),6,12,m.provider_name,m.display_name,m.average_quality,m.average_cost_per_run,m.average_latency_seconds,m.success_rate,m.average_confidence,CASE WHEN m.final_output_state='watch' THEN 42 ELSE 12 END,CASE WHEN m.final_output_state='watch' THEN 'watch' ELSE 'protected' END,'completed' FROM vw_ai_models m OUTER APPLY (SELECT TOP 1 name FROM ai_agents WHERE organization_id=@org ORDER BY ABS(CHECKSUM(id,m.id))) a OUTER APPLY (SELECT TOP 1 prompt_code FROM ai_prompts WHERE organization_id=@org ORDER BY ABS(CHECKSUM(id,m.id))) pr WHERE m.organization_id=@org ORDER BY m.updated_at DESC;
INSERT INTO ai_model_provider_failovers(organization_id,from_provider,from_model,to_provider,to_model,failover_reason,failover_state,output_quality_preserved,workflow_resumed,duration_seconds)
SELECT TOP 38 @org,provider_name,display_name,'CACSMS Private Model Gateway','runtime-model-local-fallback',CASE WHEN rate_limit_state='rate limited' THEN 'rate limit detected' ELSE 'provider degradation predicted' END,'completed',1,1,12+(ABS(CHECKSUM(id))%44) FROM vw_ai_models WHERE organization_id=@org ORDER BY CASE WHEN rate_limit_state='rate limited' THEN 0 ELSE 1 END, average_latency_seconds DESC;
INSERT INTO ai_model_provider_circuit_breakers(organization_id,route_name,provider_name,model_name,state,failure_threshold,failure_count,retry_at,fallback_route,final_output_impact)
SELECT TOP 12 @org,CONCAT('route-',model_code),provider_name,display_name,CASE WHEN rate_limit_state='rate limited' THEN 'Half Open' ELSE 'Closed' END,5,CASE WHEN rate_limit_state='rate limited' THEN 3 ELSE 0 END,DATEADD(minute,15,SYSUTCDATETIME()),'private gateway fallback',final_output_state FROM vw_ai_models WHERE organization_id=@org ORDER BY average_latency_seconds DESC;
INSERT INTO ai_model_provider_recommendations(organization_id,recommendation_type,title,description,impact,confidence_percent,inside_guardrails,status) VALUES
(@org,'routing','Shift rate-limited traffic to protected fallback','Autonomous router recommends reducing allocation on rate-limited models until quota resets.','high',94,1,'open'),(@org,'cost','Prefer lower-cost embedding routes','Embedding traffic can move to local/private gateway without final-output loss.','medium',91,1,'open'),(@org,'deprecation','Prepare deprecated model migration','Two deprecated models have safe replacement paths and validation coverage.','high',96,1,'open'),(@org,'latency','Move interactive requests to low-latency route','Interactive agent tasks can use latency-optimized policy for faster completion.','medium',89,1,'open');
INSERT INTO ai_model_provider_final_output_impact(organization_id,provider_name,model_name,workflow_name,output_name,validation_state,quality_state,publishing_state,business_result,readiness)
SELECT TOP 40 @org,provider_name,display_name,'Content Lifecycle Workflow','Validated media output package','validated',CASE WHEN final_output_state='watch' THEN 'watch' ELSE 'protected' END,'ready','business output protected during model routing',CASE WHEN final_output_state='watch' THEN 86 ELSE 96 END FROM vw_ai_models WHERE organization_id=@org ORDER BY requests_today DESC;
