DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50032, 'No organization exists for tool registry seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('ai_tools.view','View AI tools'),('ai_tools.view_details','View AI tool details'),('ai_tools.view_calls','View AI tool calls'),('ai_tools.view_inputs','View tool inputs'),('ai_tools.view_outputs','View tool outputs'),('ai_tools.view_cost','View tool cost'),('ai_tools.view_security','View tool security'),('ai_tools.create','Create AI tools'),('ai_tools.edit','Edit AI tools'),('ai_tools.validate','Validate AI tools'),('ai_tools.test','Test AI tools'),('ai_tools.simulate','Simulate AI tools'),('ai_tools.publish','Publish AI tools'),('ai_tools.enable','Enable AI tools'),('ai_tools.disable','Disable AI tools'),('ai_tools.maintenance','Place tools in maintenance'),('ai_tools.duplicate','Duplicate AI tools'),('ai_tools.deprecate','Deprecate AI tools'),('ai_tools.archive','Archive AI tools'),('ai_tools.manage_credentials','Manage tool credentials'),('ai_tools.rotate_credentials','Rotate tool credentials'),('ai_tools.manage_schemas','Manage tool schemas'),('ai_tools.manage_permissions','Manage tool permissions'),('ai_tools.manage_agent_mappings','Manage agent mappings'),('ai_tools.manage_capability_mappings','Manage capability mappings'),('ai_tools.manage_workflow_mappings','Manage workflow mappings'),('ai_tools.manage_rate_limits','Manage tool rate limits'),('ai_tools.manage_quotas','Manage tool quotas'),('ai_tools.manage_costs','Manage tool costs'),('ai_tools.manage_retries','Manage retries'),('ai_tools.manage_fallbacks','Manage fallbacks'),('ai_tools.manage_circuit_breakers','Manage circuit breakers'),('ai_tools.retry_calls','Retry tool calls'),('ai_tools.recover_calls','Recover tool calls'),('ai_tools.apply_recommendations','Apply tool recommendations'),('ai_tools.generate_ai','Generate tools with AI'),('ai_tools.generate_documentation','Generate tool documentation'),('ai_tools.export','Export tool registry'),('ai_tools.manage_governance','Manage tool governance'),('ai_tools.emergency_override','Use tool emergency override');
MERGE permissions AS target USING (SELECT code,description FROM @perms) AS source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'ai-tool-operations' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=98, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',98);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('AI_TOOL_REGISTRATION','AI Tool Registration'),('AI_TOOL_VALIDATION','AI Tool Validation'),('AI_TOOL_CONNECTION_TEST','AI Tool Connection Test'),('AI_TOOL_SCHEMA_VALIDATION','AI Tool Schema Validation'),('AI_TOOL_PERMISSION_VALIDATION','AI Tool Permission Validation'),('AI_TOOL_TEST_EXECUTION','AI Tool Test Execution'),('AI_TOOL_SIMULATION','AI Tool Simulation'),('AI_TOOL_CALL_EXECUTION','AI Tool Call Execution'),('AI_TOOL_AUTONOMOUS_RECOVERY','AI Tool Autonomous Recovery'),('AI_TOOL_FALLBACK_EXECUTION','AI Tool Fallback Execution'),('AI_TOOL_DEPRECATION_MIGRATION','AI Tool Deprecation Migration'),('AI_TOOL_VERSION_PUBLISH','AI Tool Version Publish'),('AI_TOOL_GOVERNANCE_APPROVAL','AI Tool Governance Approval');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'ai_tool_operations' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM ai_tool_final_output_links WHERE organization_id=@org;
DELETE FROM ai_tool_recommendations WHERE organization_id=@org;
DELETE FROM ai_tool_calls WHERE organization_id=@org;
DELETE FROM ai_tool_security_policies WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_deprecations WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_performance WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_circuit_breakers WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_fallbacks WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_quotas WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_rate_limits WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_workflow_usage WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_capability_mappings WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_agent_assignments WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_permissions WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_schemas WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tool_versions WHERE tool_id IN (SELECT id FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%');
DELETE FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%';
DELETE FROM ai_tool_lifecycle WHERE organization_id=@org;
DELETE FROM ai_tool_categories WHERE organization_id=@org;

DECLARE @cat TABLE(name NVARCHAR(180), tools INT, active INT, healthy INT, degraded INT, calls INT, success DECIMAL(8,2), latency DECIMAL(8,2), cost DECIMAL(18,4), agents INT, fallback DECIMAL(8,2), output DECIMAL(8,2), health DECIMAL(8,2));
INSERT INTO @cat VALUES
('Web Search Tools',5,5,5,0,8200,98.2,1.2,0.012,18,96,92,98),('Research Tools',4,4,4,0,6400,97.8,1.6,0.018,16,95,94,97),('Internal Search Tools',4,4,4,0,7200,98.9,0.7,0.004,14,99,91,99),('Knowledge Base Tools',4,4,4,0,6800,98.6,0.8,0.005,17,99,93,99),('Database Tools',4,4,3,1,4300,96.8,1.1,0.009,12,97,96,96),('File Retrieval Tools',4,4,4,0,3900,98.0,0.9,0.004,11,98,89,98),('Document Processing Tools',4,4,3,1,2400,95.9,2.2,0.026,9,94,88,94),('API Connector Tools',5,5,4,1,5200,96.2,1.9,0.020,18,93,91,95),('Webhook Tools',4,3,3,1,2600,95.8,1.4,0.006,8,92,85,94),('Image Generation Tools',4,4,4,0,1300,96.4,4.2,0.072,7,95,92,96),('Image Processing Tools',4,4,4,0,1800,97.2,2.6,0.028,8,96,90,97),('Voice Generation Tools',4,4,3,1,900,95.4,3.1,0.041,6,92,90,93),('Audio Processing Tools',4,4,3,1,1100,95.7,2.9,0.032,7,93,88,94),('Video Generation Tools',3,3,3,0,430,94.2,8.4,0.142,5,91,87,93),('Video Processing Tools',4,4,4,0,720,96.1,6.1,0.081,6,94,89,95),('Video Rendering Tools',3,3,2,1,620,94.9,9.2,0.116,5,91,91,92),('Publishing Tools',4,4,4,0,2200,98.0,1.7,0.015,12,98,98,98),('Social Media Tools',4,4,3,1,1800,96.1,2.1,0.018,9,94,93,95),('SEO Tools',4,4,4,0,2800,98.1,1.1,0.006,10,96,91,98),('Analytics Tools',4,4,4,0,4800,99.0,0.9,0.004,13,99,90,99),('Reporting Tools',4,4,4,0,1200,97.3,1.8,0.012,8,96,88,97),('Notification Tools',4,4,4,0,6200,99.2,0.6,0.002,14,99,84,99),('Email Tools',4,4,3,1,3200,97.0,1.3,0.003,10,95,83,96),('Messaging Tools',4,4,4,0,4400,98.4,0.8,0.002,12,98,84,98),('Storage Tools',4,4,4,0,5100,98.7,0.9,0.005,13,99,90,99),('Workflow Tools',4,4,4,0,3700,98.0,0.8,0.003,15,98,96,98),('Scheduling Tools',4,4,4,0,900,98.5,0.7,0.002,7,99,85,99),('Moderation Tools',4,4,4,0,4600,99.4,0.5,0.003,16,99,96,99),('Security Tools',4,4,4,0,2100,98.9,0.9,0.007,10,98,95,99),('Code Execution Tools',3,2,2,1,620,94.5,3.2,0.038,4,90,78,91),('Translation Tools',4,4,4,0,1800,97.8,1.4,0.012,7,96,84,97),('OCR Tools',3,3,3,0,960,96.8,2.1,0.019,5,95,82,96),('Monitoring Tools',4,4,4,0,5200,99.1,0.5,0.002,12,99,88,99),('Incident Management Tools',4,4,4,0,430,97.6,1.2,0.006,6,98,92,98),('Recovery Tools',4,4,4,0,740,97.9,1.6,0.009,8,99,94,98),('Custom Organization Tools',4,3,2,1,770,94.8,2.8,0.033,5,88,80,91);
INSERT INTO ai_tool_categories(organization_id,category_name,tool_count,active_tools,healthy_tools,degraded_tools,tool_calls_today,success_rate,average_latency_seconds,average_cost,assigned_agents,fallback_coverage,final_output_contribution,health_percent)
SELECT @org,name,tools,active,healthy,degraded,calls,success,latency,cost,agents,fallback,output,health FROM @cat;

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<142),
cats AS (SELECT id, category_name, ROW_NUMBER() OVER (ORDER BY category_name) rn, COUNT(*) OVER () cnt FROM ai_tool_categories WHERE organization_id=@org),
src AS (SELECT n.i, c.id category_id, c.category_name FROM n JOIN cats c ON c.rn=((n.i-1)%c.cnt)+1)
INSERT INTO ai_tools(organization_id,category_id,tool_code,tool_name,description,tool_type,current_version,status,health_percent,scope_type,environment,authentication_type,credential_status,input_schema_version,output_schema_version,assigned_agents,assigned_capabilities,workflow_usage,rate_limit_status,quota_usage,average_latency_seconds,p95_latency_seconds,success_rate,failure_rate,average_cost,calls_today,retry_policy,fallback_tool,circuit_breaker_state,sensitive_access,final_output_linked,last_health_check,owner,organization_name,human_attention_required)
SELECT @org,category_id,CONCAT('TOOL-',RIGHT('0000'+CAST(i AS NVARCHAR(4)),4)),CONCAT(category_name,' Runtime Tool ',i),CONCAT('Autonomous ',LOWER(category_name),' capability with governed execution, schema validation, audit, recovery, fallback, and final-output linkage.'),CASE i%14 WHEN 0 THEN 'Internal Service' WHEN 1 THEN 'External API' WHEN 2 THEN 'Connector' WHEN 3 THEN 'Function' WHEN 4 THEN 'Webhook' WHEN 5 THEN 'SDK' WHEN 6 THEN 'CLI' WHEN 7 THEN 'Database Procedure' WHEN 8 THEN 'Background Job' WHEN 9 THEN 'Media Service' WHEN 10 THEN 'Storage Service' WHEN 11 THEN 'Publishing Adapter' WHEN 12 THEN 'Monitoring Adapter' ELSE 'Custom Integration' END,CONCAT('v',1+(i%6),'.',i%10),CASE WHEN i<=126 THEN CASE WHEN i%23=0 THEN 'Degraded' WHEN i%31=0 THEN 'Rate Limited' WHEN i%37=0 THEN 'Warning' ELSE 'Active' END WHEN i<=132 THEN 'Degraded' WHEN i<=134 THEN 'Offline' WHEN i<=137 THEN 'Authentication Warning' WHEN i<=140 THEN 'Deprecated' ELSE 'Experimental' END,CASE WHEN i<=126 THEN 94+(i%5) WHEN i<=132 THEN 88 ELSE 76+(i%10) END,CASE WHEN i%6=0 THEN 'Brand' WHEN i%5=0 THEN 'Organization' ELSE 'System' END,'production',CASE WHEN i%5=0 THEN 'OAuth' WHEN i%7=0 THEN 'Managed Identity' WHEN i%9=0 THEN 'mTLS' ELSE 'API Key' END,CASE WHEN i IN (35,78,121) THEN 'expiring' WHEN i=134 THEN 'invalid' ELSE 'valid' END,CONCAT('in-',1+(i%4)),CONCAT('out-',1+(i%4)),1+(i%9),1+(i%7),1+(i%12),CASE WHEN i%31=0 THEN 'rate limited' ELSE 'clear' END,CASE WHEN i%29=0 THEN 91 ELSE 30+(i%48) END,CAST(0.4+(i%12)*0.22 AS DECIMAL(8,2)),CAST(1.1+(i%12)*0.44 AS DECIMAL(8,2)),CASE WHEN i%23=0 THEN 91 ELSE 95+(i%5) END,CASE WHEN i%23=0 THEN 5 ELSE i%3 END,CAST(0.002+(i%28)*0.004 AS DECIMAL(18,4)),120+(i*37)%1800,'retry:3 exponential','approved fallback tool',CASE WHEN i%41=0 THEN 'Open' WHEN i%23=0 THEN 'Half Open' ELSE 'Closed' END,CASE WHEN i%10=0 THEN 1 ELSE 0 END,CASE WHEN i%6=0 THEN 0 ELSE 1 END,DATEADD(minute,-i*2,SYSUTCDATETIME()),'tool-registry','AI Media Group',0 FROM src OPTION (MAXRECURSION 0);

DECLARE @life TABLE(kind NVARCHAR(80), stage NVARCHAR(180), seq INT);
INSERT INTO @life VALUES
('Registry','Tool Discovered',1),('Registry','Registered',2),('Registry','Identity Validated',3),('Registry','Authentication Configured',4),('Registry','Input Schema Validated',5),('Registry','Output Schema Validated',6),('Registry','Permissions Assigned',7),('Registry','Agent Compatibility Validated',8),('Registry','Tested',9),('Registry','Published',10),('Registry','Active',11),('Registry','Monitored',12),('Registry','Optimized',13),('Registry','Superseded',14),('Registry','Deprecated',15),('Registry','Archived',16),
('Execution','Tool Requested',1),('Execution','Permission Evaluated',2),('Execution','Scope Validated',3),('Execution','Input Validated',4),('Execution','Authentication Resolved',5),('Execution','Quota Checked',6),('Execution','Rate Limit Checked',7),('Execution','Tool Executed',8),('Execution','Output Validated',9),('Execution','Result Persisted',10),('Execution','Agent Run Updated',11),('Execution','Metrics Recorded',12),('Execution','Audit Recorded',13),
('Failure','Execution Failed',1),('Failure','Failure Classified',2),('Failure','Retry Evaluated',3),('Failure','Fallback Tool Selected',4),('Failure','Output Revalidated',5),('Failure','Agent Run Resumed',6),('Failure','Incident or Escalation if Exhausted',7);
INSERT INTO ai_tool_lifecycle(organization_id,lifecycle_type,stage_name,sequence_no,tool_count,invocation_count,failure_count,retry_count,failover_count,average_duration,health_percent,current_blockers)
SELECT @org,kind,stage,seq,142,2400+(seq*93),CASE WHEN kind='Failure' THEN 6 ELSE seq%4 END,CASE WHEN kind='Failure' THEN 4 ELSE seq%3 END,CASE WHEN kind='Failure' THEN 3 ELSE seq%2 END,CONCAT(1+seq,'m'),CASE WHEN kind='Failure' THEN 94 ELSE 97 END,CASE WHEN kind='Failure' AND seq=7 THEN 'fallback exhaustion monitored' ELSE 'none' END FROM @life;

INSERT INTO ai_tool_versions(tool_id,version_label,version_state) SELECT id,current_version,status FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%';
INSERT INTO ai_tool_schemas(tool_id,schema_kind,schema_version,validation_state,drift_state,sensitive_fields,provenance_required) SELECT id,'input',input_schema_version,'valid','none',CASE WHEN sensitive_access=1 THEN 2 ELSE 0 END,1 FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%' UNION ALL SELECT id,'output',output_schema_version,'valid','none',0,1 FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%';
INSERT INTO ai_tool_permissions(tool_id,permission_target,target_type,permission_state,governance_state,sensitive_scope) SELECT id,'Autonomous Agent Pool','Agents','Allowed',CASE WHEN sensitive_access=1 THEN 'Approval Required' ELSE 'Within Guardrails' END,sensitive_access FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%';
INSERT INTO ai_tool_agent_assignments(tool_id,agent_name,assignment_state,compatibility_percent) SELECT t.id,COALESCE(a.name,'Autonomous Agent'),'active',90+(ABS(CHECKSUM(t.id))%9) FROM ai_tools t OUTER APPLY (SELECT TOP 1 name FROM ai_agents WHERE organization_id=@org ORDER BY ABS(CHECKSUM(id,t.id))) a WHERE t.organization_id=@org AND t.tool_code LIKE 'TOOL-%';
INSERT INTO ai_tool_capability_mappings(tool_id,capability_name,mapping_state,required_permission) SELECT id,category_name,'valid','ai_tools.view' FROM vw_ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_workflow_usage(tool_id,workflow_name,usage_count,final_output_impact) SELECT id,'Content Lifecycle Workflow',workflow_usage*12,CASE WHEN final_output_linked=1 THEN 'protected' ELSE 'watch' END FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%';
INSERT INTO ai_tool_calls(organization_id,tool_id,tool_version,agent_name,workflow_name,status,priority,queue_name,worker_id,started_at,completed_at,duration_ms,retry_count,fallback_tool,rate_limit_state,quota_state,actual_cost,output_validation_status,recovery_state,final_output_impact,correlation_id)
SELECT TOP 220 @org,t.id,t.current_version,COALESCE(a.name,'Autonomous Agent'),'Content Lifecycle Workflow',CASE WHEN t.status IN ('Degraded','Rate Limited') THEN 'retrying' ELSE 'completed' END,'high','ai-tool-operations','tool-worker-01',DATEADD(minute,-ABS(CHECKSUM(t.id))%240,SYSUTCDATETIME()),SYSUTCDATETIME(),CAST(t.average_latency_seconds*1000 AS INT),CASE WHEN t.status IN ('Degraded','Rate Limited') THEN 1 ELSE 0 END,t.fallback_tool,t.rate_limit_status,CASE WHEN t.quota_usage>90 THEN 'quota warning' ELSE 'clear' END,t.average_cost,'valid',CASE WHEN t.status IN ('Degraded','Rate Limited') THEN 'recovering' ELSE 'not required' END,CASE WHEN t.final_output_linked=1 THEN 'protected' ELSE 'watch' END,CONCAT('TOOLCALL-',t.tool_code) FROM ai_tools t OUTER APPLY (SELECT TOP 1 name FROM ai_agents WHERE organization_id=@org ORDER BY ABS(CHECKSUM(id,t.id))) a WHERE t.organization_id=@org ORDER BY t.calls_today DESC;
INSERT INTO ai_tool_rate_limits(tool_id,requests_per_minute,requests_per_day,current_usage,reset_at,status) SELECT id,120+(ABS(CHECKSUM(id))%400),5000+(ABS(CHECKSUM(tool_code))%30000),CASE WHEN rate_limit_status='rate limited' THEN 93 ELSE 40+(ABS(CHECKSUM(id))%35) END,DATEADD(hour,1,SYSUTCDATETIME()),rate_limit_status FROM ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_quotas(tool_id,quota_name,quota_usage,remaining_capacity,predicted_exhaustion_at,status) SELECT id,'daily tool quota',quota_usage,100-quota_usage,CASE WHEN quota_usage>90 THEN DATEADD(hour,4,SYSUTCDATETIME()) ELSE NULL END,CASE WHEN quota_usage>90 THEN 'quota warning' ELSE 'clear' END FROM ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_fallbacks(tool_id,fallback_tool,secondary_fallback,fallback_state,output_preservation) SELECT id,fallback_tool,'safe internal fallback','ready',94+(ABS(CHECKSUM(id))%5) FROM ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_circuit_breakers(tool_id,state,failure_threshold,failure_count,retry_at,fallback_action,final_output_impact) SELECT id,circuit_breaker_state,5,CASE WHEN circuit_breaker_state='Open' THEN 5 WHEN circuit_breaker_state='Half Open' THEN 3 ELSE 0 END,DATEADD(minute,15,SYSUTCDATETIME()),'route to fallback tool',CASE WHEN final_output_linked=1 THEN 'protected' ELSE 'watch' END FROM ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_performance(tool_id,calls,success_rate,failure_rate,average_latency_seconds,average_cost,retry_rate,failover_rate,output_acceptance_rate,final_output_contribution) SELECT id,calls_today,success_rate,failure_rate,average_latency_seconds,average_cost,CASE WHEN status IN ('Degraded','Rate Limited') THEN 6 ELSE 1 END,CASE WHEN status IN ('Degraded','Rate Limited') THEN 4 ELSE 1 END,success_rate-1,CASE WHEN final_output_linked=1 THEN 96 ELSE 82 END FROM ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_deprecations(tool_id,deprecation_state,replacement_tool,migration_state,deadline) SELECT id,'deprecated','approved replacement tool','migration ready',DATEADD(day,45,CAST(SYSUTCDATETIME() AS DATE)) FROM ai_tools WHERE organization_id=@org AND status='Deprecated';
INSERT INTO ai_tool_security_policies(tool_id,data_classification,sensitive_data_support,encryption_state,redaction_state,residency_policy,audit_level,risk_score) SELECT id,CASE WHEN sensitive_access=1 THEN 'sensitive' ELSE 'internal' END,CASE WHEN sensitive_access=1 THEN 'restricted' ELSE 'allowed' END,'encrypted','enabled','tenant isolated','full',CASE WHEN sensitive_access=1 THEN 38 ELSE 8+(ABS(CHECKSUM(id))%20) END FROM ai_tools WHERE organization_id=@org;
INSERT INTO ai_tool_recommendations(organization_id,recommendation_type,title,description,impact,confidence_percent,inside_guardrails,status) VALUES
(@org,'fallback','Add secondary fallback to sensitive tools','Sensitive tools should keep a second fallback route before workflow-critical execution.','high',94,1,'open'),(@org,'schema','Review schema drift watchlist','Autonomous validator found tools that should refresh schema snapshots.','medium',90,1,'open'),(@org,'cost','Route high-volume calls to lower-cost connector','Search and analytics tools can reduce cost without final-output risk.','medium',91,1,'open'),(@org,'credential','Rotate expiring tool credentials','Three tool credentials are inside the warning window.','high',96,1,'open');
INSERT INTO ai_tool_final_output_links(organization_id,tool_id,workflow_name,output_name,validation_state,contribution_state,business_result,readiness) SELECT @org,id,'Content Lifecycle Workflow','Validated media output package','validated',CASE WHEN final_output_linked=1 THEN 'protected' ELSE 'watch' END,'tool output linked to business result',CASE WHEN final_output_linked=1 THEN 96 ELSE 84 END FROM ai_tools WHERE organization_id=@org AND tool_code LIKE 'TOOL-%';
