DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50034, 'No organization exists for knowledge base seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('knowledge_base.view','View knowledge base'),('knowledge_base.view_sources','View knowledge sources'),('knowledge_base.view_objects','View knowledge objects'),('knowledge_base.view_content','View knowledge content'),('knowledge_base.view_sensitive','View sensitive knowledge'),('knowledge_base.create_source','Create knowledge sources'),('knowledge_base.edit_source','Edit knowledge sources'),('knowledge_base.validate_source','Validate knowledge sources'),('knowledge_base.ingest','Run knowledge ingestion'),('knowledge_base.synchronize','Synchronize knowledge'),('knowledge_base.upload','Upload knowledge'),('knowledge_base.reindex','Reindex knowledge'),('knowledge_base.rebuild_embeddings','Rebuild knowledge embeddings'),('knowledge_base.edit_metadata','Edit knowledge metadata'),('knowledge_base.revalidate_object','Revalidate knowledge objects'),('knowledge_base.reembed_object','Reembed knowledge objects'),('knowledge_base.archive_object','Archive knowledge objects'),('knowledge_base.restore_object','Restore knowledge objects'),('knowledge_base.resolve_duplicates','Resolve duplicates'),('knowledge_base.resolve_contradictions','Resolve contradictions'),('knowledge_base.manage_entities','Manage entities'),('knowledge_base.manage_graph','Manage graph'),('knowledge_base.manage_citations','Manage citations'),('knowledge_base.manage_taxonomies','Manage taxonomies'),('knowledge_base.manage_ontologies','Manage ontologies'),('knowledge_base.manage_permissions','Manage permissions'),('knowledge_base.manage_retention','Manage retention'),('knowledge_base.apply_recommendations','Apply recommendations'),('knowledge_base.export','Export knowledge'),('knowledge_base.manage_governance','Manage knowledge governance'),('knowledge_base.emergency_override','Use emergency controls');
MERGE permissions AS target USING (SELECT code,description FROM @perms) AS source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'knowledge-base-operations' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=98, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',98);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('KNOWLEDGE_SOURCE_REGISTRATION','Knowledge Source Registration'),('KNOWLEDGE_INGESTION','Knowledge Ingestion'),('KNOWLEDGE_VALIDATION','Knowledge Validation'),('KNOWLEDGE_DEDUPLICATION','Knowledge Deduplication'),('KNOWLEDGE_CONTRADICTION_RESOLUTION','Knowledge Contradiction Resolution'),('KNOWLEDGE_EMBEDDING','Knowledge Embedding'),('KNOWLEDGE_INDEXING','Knowledge Indexing'),('KNOWLEDGE_GRAPH_UPDATE','Knowledge Graph Update'),('KNOWLEDGE_SYNCHRONIZATION','Knowledge Synchronization'),('KNOWLEDGE_STALE_REFRESH','Knowledge Stale Refresh'),('KNOWLEDGE_RETENTION_ARCHIVE','Knowledge Retention Archive'),('KNOWLEDGE_GAP_RESOLUTION','Knowledge Gap Resolution'),('KNOWLEDGE_GOVERNANCE_APPROVAL','Knowledge Governance Approval');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'knowledge_base_operations' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM knowledge_final_output_traceability WHERE organization_id=@org;
DELETE FROM knowledge_recommendations WHERE organization_id=@org;
DELETE FROM knowledge_gaps WHERE organization_id=@org;
DELETE FROM knowledge_analytics WHERE organization_id=@org;
DELETE FROM knowledge_sync WHERE organization_id=@org;
DELETE FROM knowledge_citations WHERE organization_id=@org;
DELETE FROM knowledge_relationships WHERE organization_id=@org;
DELETE FROM knowledge_entities WHERE organization_id=@org;
DELETE FROM knowledge_embeddings WHERE knowledge_object_id IN (SELECT id FROM knowledge_objects WHERE organization_id=@org);
DELETE FROM knowledge_chunks WHERE knowledge_object_id IN (SELECT id FROM knowledge_objects WHERE organization_id=@org);
DELETE FROM knowledge_validation WHERE organization_id=@org;
DELETE FROM knowledge_ingestion_jobs WHERE organization_id=@org;
DELETE FROM knowledge_objects WHERE organization_id=@org;
DELETE FROM knowledge_sources WHERE organization_id=@org;
DELETE FROM knowledge_source_categories WHERE organization_id=@org;

DECLARE @cats TABLE(name NVARCHAR(160), rn INT);
INSERT INTO @cats VALUES
('Internal Documents',1),('Policies and Procedures',2),('Brand Guidelines',3),('Audience Research',4),('Market Research',5),('Competitor Intelligence',6),('Product Knowledge',7),('Service Knowledge',8),('Editorial Guidelines',9),('SEO Knowledge',10),('Platform Policies',11),('Legal and Compliance',12),('Campaign Knowledge',13),('Content Archive',14),('Analytics History',15),('Workflow History',16),('Agent Output Archive',17),('Learning Archive',18),('External Approved Websites',19),('Databases',20),('File Repositories',21),('APIs',22),('Knowledge Graphs',23),('Structured Datasets',24),('Custom Organization Sources',25);
INSERT INTO knowledge_source_categories(organization_id,category_name,source_count,active_sources,object_count,trusted_percent,stale_percent,citation_coverage,retrieval_usage,last_ingestion,sync_state,health_percent)
SELECT @org,name,2+(rn%3),2+(rn%2),32000+(rn*1377),CASE WHEN rn%7=0 THEN 93.2 ELSE 96.4+(rn%3) END,CASE WHEN rn%6=0 THEN 4.8 ELSE 1.4+(rn%3)*0.4 END,CASE WHEN rn%5=0 THEN 91.8 ELSE 94.2+(rn%4) END,1200+(rn*417),DATEADD(minute,-rn*11,SYSUTCDATETIME()),CASE WHEN rn%8=0 THEN 'syncing' ELSE 'synchronized' END,CASE WHEN rn%7=0 THEN 91 ELSE 96+(rn%4) END FROM @cats;

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<64),
cat AS (SELECT id, category_name, ROW_NUMBER() OVER (ORDER BY category_name) rn, COUNT(*) OVER () cnt FROM knowledge_source_categories WHERE organization_id=@org),
src AS (SELECT n.i, cat.id category_id, cat.category_name FROM n JOIN cat ON cat.rn=((n.i-1)%cat.cnt)+1)
INSERT INTO knowledge_sources(organization_id,category_id,source_code,source_name,description,source_type,scope_type,status,trust_level,authority_score,freshness_score,object_count,document_count,last_ingestion,next_ingestion,ingestion_frequency,parser_name,ocr_enabled,embedding_model,vector_collection,knowledge_graph_enabled,citation_enabled,provenance_coverage,duplicate_rate,contradiction_rate,retrieval_usage,owner,organization_name,brand_name,environment,human_attention_required)
SELECT @org,category_id,CONCAT('KBS-',RIGHT('000'+CAST(i AS NVARCHAR(3)),3)),CONCAT(category_name,' Source ',i),CONCAT('Approved autonomous knowledge source for ',LOWER(category_name),'.'),CASE i%17 WHEN 0 THEN 'File Upload' WHEN 1 THEN 'Folder' WHEN 2 THEN 'SharePoint' WHEN 3 THEN 'OneDrive' WHEN 4 THEN 'Google Drive' WHEN 5 THEN 'Website' WHEN 6 THEN 'Sitemap' WHEN 7 THEN 'RSS' WHEN 8 THEN 'Database' WHEN 9 THEN 'API' WHEN 10 THEN 'Webhook' WHEN 11 THEN 'Object Storage' WHEN 12 THEN 'Internal Application' WHEN 13 THEN 'Knowledge Graph' WHEN 14 THEN 'Manual Entry' WHEN 15 THEN 'Dataset' ELSE 'External Repository' END,CASE WHEN i%5=0 THEN 'Brand' WHEN i%3=0 THEN 'Organization' ELSE 'System' END,CASE WHEN i%31=0 THEN 'Authentication Failed' WHEN i%23=0 THEN 'Degraded' WHEN i%19=0 THEN 'Warning' WHEN i%11=0 THEN 'Syncing' ELSE 'Active' END,CASE WHEN i%13=0 THEN 'Conditional' WHEN i%7=0 THEN 'Approved' WHEN i%5=0 THEN 'Authoritative' ELSE 'Trusted' END,CASE WHEN i%13=0 THEN 84 ELSE 92+(i%7) END,CASE WHEN i%17=0 THEN 86 ELSE 93+(i%6) END,5000+(i*977),700+(i*43),DATEADD(hour,-i,SYSUTCDATETIME()),DATEADD(hour,6+(i%12),SYSUTCDATETIME()),CASE WHEN i%4=0 THEN 'hourly' WHEN i%4=1 THEN 'daily' WHEN i%4=2 THEN 'weekly' ELSE 'event-driven' END,CASE WHEN i%4=0 THEN 'document-parser-v4' WHEN i%4=1 THEN 'html-parser-v3' WHEN i%4=2 THEN 'dataset-parser-v2' ELSE 'media-transcript-parser' END,CASE WHEN i%3=0 THEN 1 ELSE 0 END,CASE WHEN i%3=0 THEN 'text-embedding-3-large' WHEN i%3=1 THEN 'text-embedding-3-small' ELSE 'local-e5-large' END,CONCAT('kb_',LOWER(REPLACE(category_name,' ','_'))),CASE WHEN i%4=0 THEN 0 ELSE 1 END,CASE WHEN i%6=0 THEN 0 ELSE 1 END,CASE WHEN i%6=0 THEN 88 ELSE 94+(i%5) END,CAST((i%9)*0.31 AS DECIMAL(8,2)),CAST((i%7)*0.12 AS DECIMAL(8,2)),1200+(i*71),'Knowledge Governance Engine','AI Media Group','CACSMS Contents','production',0 FROM src OPTION (MAXRECURSION 0);

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<220),
src AS (SELECT s.id source_id, s.organization_id, s.source_code, s.source_name, s.category_name, ROW_NUMBER() OVER (ORDER BY s.source_code) rn, COUNT(*) OVER () cnt FROM vw_knowledge_sources s WHERE s.organization_id=@org),
rows AS (SELECT n.i, src.* FROM n JOIN src ON src.rn=((n.i-1)%src.cnt)+1)
INSERT INTO knowledge_objects(organization_id,source_id,knowledge_code,title,object_type,category,topic,entities,status,version_label,trust_level,authority_score,freshness_score,confidence_percent,citation_count,retrieval_count,chunk_count,embedding_status,index_status,graph_status,contradiction_status,sensitive_classification,owner,organization_name,brand_name,created_at,updated_at,last_accessed_at,final_output_usage)
SELECT @org,source_id,CONCAT('KBO-',RIGHT('000000'+CAST(i AS NVARCHAR(6)),6)),CONCAT(category_name,' Knowledge Object ',i),CASE i%20 WHEN 0 THEN 'Document' WHEN 1 THEN 'Article' WHEN 2 THEN 'Web Page' WHEN 3 THEN 'Policy' WHEN 4 THEN 'Procedure' WHEN 5 THEN 'Guideline' WHEN 6 THEN 'Research Report' WHEN 7 THEN 'Dataset' WHEN 8 THEN 'FAQ' WHEN 9 THEN 'Fact' WHEN 10 THEN 'Definition' WHEN 11 THEN 'Entity' WHEN 12 THEN 'Relationship' WHEN 13 THEN 'Decision' WHEN 14 THEN 'Recommendation' WHEN 15 THEN 'Insight' WHEN 16 THEN 'Citation' WHEN 17 THEN 'Media Transcript' WHEN 18 THEN 'Content Asset' ELSE 'Learning Record' END,category_name,CONCAT('Topic ',1+(i%32)),CONCAT('CACSMS Entity ',i%18,', Brand Entity ',i%9),CASE WHEN i%43=0 THEN 'Contradicted' WHEN i%37=0 THEN 'Stale' WHEN i%31=0 THEN 'Warning' ELSE 'Trusted' END,CONCAT('v',1+(i%5),'.',i%10),CASE WHEN i%13=0 THEN 'Conditional' ELSE 'Trusted' END,CASE WHEN i%13=0 THEN 84 ELSE 92+(i%7) END,CASE WHEN i%37=0 THEN 82 ELSE 93+(i%6) END,CASE WHEN i%43=0 THEN 86 ELSE 92+(i%8) END,1+(i%12),60+(i*19)%3000,4+(i%18),'embedded','indexed',CASE WHEN i%5=0 THEN 'linked' ELSE 'updated' END,CASE WHEN i%43=0 THEN 'open' ELSE 'clear' END,CASE WHEN i%11=0 THEN 'Confidential' WHEN i%7=0 THEN 'Internal' ELSE 'Operational' END,'Knowledge Governance Engine','AI Media Group','CACSMS Contents',DATEADD(day,-i,SYSUTCDATETIME()),DATEADD(hour,-i,SYSUTCDATETIME()),DATEADD(minute,-i*4,SYSUTCDATETIME()),10+(i%90) FROM rows OPTION (MAXRECURSION 0);

INSERT INTO knowledge_ingestion_jobs(organization_id,source_id,object_title,stage,progress_percent,duration_seconds,parser_name,embedding_model,retry_count,cost,error_message,recovery_state)
SELECT TOP 64 @org,id,CONCAT(source_name,' ingestion sample'),CASE WHEN status='Authentication Failed' THEN 'Failed' WHEN status='Syncing' THEN 'Embedding' ELSE 'Published' END,CASE WHEN status='Authentication Failed' THEN 34 WHEN status='Syncing' THEN 72 ELSE 100 END,120+(ABS(CHECKSUM(id))%700),parser_name,embedding_model,CASE WHEN status='Authentication Failed' THEN 2 ELSE 0 END,CAST(0.08+(ABS(CHECKSUM(source_code))%18)*0.05 AS DECIMAL(18,4)),CASE WHEN status='Authentication Failed' THEN 'credential validation failed' ELSE NULL END,CASE WHEN status='Authentication Failed' THEN 'governed retry queued' ELSE 'complete' END FROM knowledge_sources WHERE organization_id=@org;
INSERT INTO knowledge_validation(organization_id,knowledge_object_id,source_id,validation_area,validation_state,score,finding,auto_resolution) SELECT TOP 100 @org,o.id,o.source_id,CASE WHEN o.status='Contradicted' THEN 'Contradiction' WHEN o.status='Stale' THEN 'Freshness' ELSE 'Authority' END,CASE WHEN o.status IN ('Contradicted','Stale') THEN 'warning' ELSE 'passed' END,o.confidence_percent,'Knowledge checked for authority, freshness, duplicates, contradictions, citations, provenance, and security.','route through autonomous validation policy' FROM knowledge_objects o WHERE o.organization_id=@org;
INSERT INTO knowledge_chunks(knowledge_object_id,chunk_key,token_count,chunking_strategy,quality_score) SELECT id,CONCAT(knowledge_code,'-chunk-1'),900+(ABS(CHECKSUM(id))%900),'semantic splitting with metadata inheritance',confidence_percent FROM knowledge_objects WHERE organization_id=@org;
INSERT INTO knowledge_embeddings(knowledge_object_id,embedding_model,dimensions,vector_collection,embedding_status) SELECT o.id,s.embedding_model,CASE WHEN s.embedding_model LIKE '%small%' THEN 1536 ELSE 3072 END,s.vector_collection,o.embedding_status FROM knowledge_objects o JOIN knowledge_sources s ON s.id=o.source_id WHERE o.organization_id=@org;
INSERT INTO knowledge_entities(organization_id,entity_name,entity_type,source_count,object_count,confidence_percent) SELECT TOP 60 @org,CONCAT('Knowledge Entity ',ROW_NUMBER() OVER (ORDER BY title)),CASE ROW_NUMBER() OVER (ORDER BY title)%5 WHEN 0 THEN 'Brand' WHEN 1 THEN 'Audience' WHEN 2 THEN 'Policy' WHEN 3 THEN 'Topic' ELSE 'Workflow' END,2+(ROW_NUMBER() OVER (ORDER BY title)%8),20+(ROW_NUMBER() OVER (ORDER BY title)%120),90+(ROW_NUMBER() OVER (ORDER BY title)%8) FROM knowledge_objects WHERE organization_id=@org;
INSERT INTO knowledge_relationships(organization_id,source_entity,relationship_type,target_entity,evidence_count,confidence_percent) SELECT TOP 60 @org,CONCAT('Knowledge Entity ',ROW_NUMBER() OVER (ORDER BY entity_name)),'supports',CONCAT('Final Output Area ',ROW_NUMBER() OVER (ORDER BY entity_name)%12),3+(ROW_NUMBER() OVER (ORDER BY entity_name)%18),90+(ROW_NUMBER() OVER (ORDER BY entity_name)%8) FROM knowledge_entities WHERE organization_id=@org;
INSERT INTO knowledge_citations(organization_id,knowledge_object_id,citation_format,citation_state,provenance_chain,usage_count,validation_score) SELECT TOP 120 @org,id,'CACSMS evidence citation','validated','source > object > chunk > citation > output',citation_count,confidence_percent FROM knowledge_objects WHERE organization_id=@org;
INSERT INTO knowledge_sync(organization_id,source_id,sync_target,sync_state,lag_seconds) SELECT @org,id,CASE ABS(CHECKSUM(id))%4 WHEN 0 THEN 'Agent Memory' WHEN 1 THEN 'RAG Service' WHEN 2 THEN 'Knowledge Graph' ELSE 'Workflow Engine' END,CASE WHEN status='Syncing' THEN 'running' ELSE 'synchronized' END,ABS(CHECKSUM(id))%120 FROM knowledge_sources WHERE organization_id=@org;
INSERT INTO knowledge_analytics(organization_id,metric_area,metric_name,metric_value,trend,health_percent) VALUES
(@org,'Growth','Knowledge growth',1840000,'stable expansion',97),(@org,'Usage','Retrievals today',284420,'up 8%',98),(@org,'Retrieval','Retrieval success',97.3,'stable',98),(@org,'Accuracy','Citation acceptance',94.6,'up 2%',96),(@org,'Freshness','Fresh knowledge',97.6,'stable',96),(@org,'Coverage','Final-output traceability',94.6,'stable',95),(@org,'Cost','Monthly knowledge cost',128.44,'within budget',98);
INSERT INTO knowledge_gaps(organization_id,gap_title,domain,severity,recommended_source,resolution_state,final_output_risk) VALUES
(@org,'Platform policy delta coverage','Platform Policies','medium','approved platform changelog connectors','queued',18),(@org,'Audience segment refresh','Audience Research','low','latest audience analytics warehouse','in progress',11),(@org,'Competitor benchmark refresh','Competitor Intelligence','medium','approved market intelligence source','queued',16);
INSERT INTO knowledge_recommendations(organization_id,recommendation_type,title,impact,confidence_percent,status) VALUES
(@org,'freshness','Refresh stale legal references','risk reduction',94,'queued'),(@org,'citation','Improve citation coverage on content archive','quality lift',92,'queued'),(@org,'retrieval','Re-rank high usage SEO knowledge','speed and relevance',91,'queued'),(@org,'dedupe','Merge duplicate campaign facts','cost reduction',96,'queued');
INSERT INTO knowledge_final_output_traceability(organization_id,knowledge_object_id,output_name,workflow_name,citation_coverage,provenance_state,traceability_state,business_impact) SELECT TOP 80 @org,id,CONCAT('Output using ',knowledge_code),'Autonomous Content Lifecycle',94+(ABS(CHECKSUM(id))%5),'validated','traceable','reduced hallucination and increased final-output confidence' FROM knowledge_objects WHERE organization_id=@org;
