DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50035, 'No organization exists for RAG seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('rag.view','View RAG'),('rag.view_pipelines','View RAG pipelines'),('rag.view_retrievals','View retrievals'),('rag.view_context','View retrieval context'),('rag.view_citations','View citations'),('rag.view_grounding','View grounding'),('rag.view_cost','View cost'),('rag.create_pipeline','Create RAG pipelines'),('rag.edit_pipeline','Edit RAG pipelines'),('rag.validate_pipeline','Validate pipelines'),('rag.evaluate_pipeline','Evaluate pipelines'),('rag.simulate_pipeline','Simulate pipelines'),('rag.test_query','Test RAG query'),('rag.publish_pipeline','Publish pipelines'),('rag.enable_pipeline','Enable pipelines'),('rag.disable_pipeline','Disable pipelines'),('rag.duplicate_pipeline','Duplicate pipelines'),('rag.deprecate_pipeline','Deprecate pipelines'),('rag.archive_pipeline','Archive pipelines'),('rag.manage_retrievers','Manage retrievers'),('rag.manage_embeddings','Manage embeddings'),('rag.manage_vector_stores','Manage vector stores'),('rag.manage_rerankers','Manage rerankers'),('rag.manage_sources','Manage sources'),('rag.manage_context_policy','Manage context policy'),('rag.manage_citation_policy','Manage citation policy'),('rag.manage_grounding_policy','Manage grounding policy'),('rag.manage_recovery','Manage recovery'),('rag.manage_security','Manage security'),('rag.retry_retrieval','Retry retrieval'),('rag.recover_retrieval','Recover retrieval'),('rag.rebuild_indexes','Rebuild indexes'),('rag.rebuild_embeddings','Rebuild embeddings'),('rag.apply_recommendations','Apply recommendations'),('rag.generate_ai','Generate RAG with AI'),('rag.generate_documentation','Generate RAG documentation'),('rag.compare','Compare pipelines'),('rag.export','Export RAG report'),('rag.manage_governance','Manage RAG governance'),('rag.emergency_override','Use RAG emergency override');
MERGE permissions AS target USING (SELECT code,description FROM @perms) AS source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'rag-operations' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=98, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',98);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('RAG_PIPELINE_VALIDATION','RAG Pipeline Validation'),('RAG_PIPELINE_EVALUATION','RAG Pipeline Evaluation'),('RAG_RETRIEVAL_EXECUTION','RAG Retrieval Execution'),('RAG_QUERY_REWRITE','RAG Query Rewrite'),('RAG_HYBRID_RETRIEVAL','RAG Hybrid Retrieval'),('RAG_CONTEXT_ASSEMBLY','RAG Context Assembly'),('RAG_GROUNDING_VALIDATION','RAG Grounding Validation'),('RAG_AUTONOMOUS_RECOVERY','RAG Autonomous Recovery'),('RAG_INDEX_REBUILD','RAG Index Rebuild'),('RAG_EMBEDDING_MIGRATION','RAG Embedding Migration'),('RAG_VERSION_PUBLISH','RAG Version Publish'),('RAG_GOVERNANCE_APPROVAL','RAG Governance Approval');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'rag_operations' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM rag_final_output_traceability WHERE organization_id=@org;
DELETE FROM rag_recommendations WHERE organization_id=@org;
DELETE FROM rag_performance WHERE organization_id=@org;
DELETE FROM rag_recoveries WHERE organization_id=@org;
DELETE FROM rag_failures WHERE organization_id=@org;
DELETE FROM rag_evaluations WHERE organization_id=@org;
DELETE FROM rag_citations WHERE retrieval_id IN (SELECT id FROM rag_retrieval_requests WHERE organization_id=@org);
DELETE FROM rag_grounding_results WHERE retrieval_id IN (SELECT id FROM rag_retrieval_requests WHERE organization_id=@org);
DELETE FROM rag_contexts WHERE retrieval_id IN (SELECT id FROM rag_retrieval_requests WHERE organization_id=@org);
DELETE FROM rag_query_intelligence WHERE retrieval_id IN (SELECT id FROM rag_retrieval_requests WHERE organization_id=@org);
DELETE FROM rag_retrieval_requests WHERE organization_id=@org;
DELETE FROM rag_pipelines WHERE organization_id=@org;
DELETE FROM rag_rerankers WHERE organization_id=@org;
DELETE FROM rag_vector_collections WHERE organization_id=@org;
DELETE FROM rag_embedding_models WHERE organization_id=@org;
DELETE FROM rag_retrievers WHERE organization_id=@org;
DELETE FROM rag_pipeline_categories WHERE organization_id=@org;

DECLARE @cats TABLE(name NVARCHAR(180), rn INT);
INSERT INTO @cats VALUES
('General Knowledge Retrieval',1),('Brand Knowledge Retrieval',2),('Audience Intelligence Retrieval',3),('Market Research Retrieval',4),('Competitor Intelligence Retrieval',5),('SEO Knowledge Retrieval',6),('Platform Policy Retrieval',7),('Legal and Compliance Retrieval',8),('Product Knowledge Retrieval',9),('Campaign Knowledge Retrieval',10),('Content Archive Retrieval',11),('Analytics Retrieval',12),('Workflow History Retrieval',13),('Agent Memory Retrieval',14),('Shared Team Retrieval',15),('Publishing Knowledge Retrieval',16),('Learning Retrieval',17),('Incident and Recovery Retrieval',18),('Executive Intelligence Retrieval',19),('Custom Organization Retrieval',20);
INSERT INTO rag_pipeline_categories(organization_id,category_name,pipeline_count,active_pipelines,active_retrievals,success_rate,average_relevance,average_authority,average_freshness,grounding_success,citation_coverage,average_latency_ms,average_cost,final_output_contribution,health_percent)
SELECT @org,name,2+(rn%3),2,12+(rn%21),CASE WHEN rn%8=0 THEN 93.8 ELSE 96.4+(rn%3) END,0.84+(rn%7)*0.01,91+(rn%7),90+(rn%8),94+(rn%5),93+(rn%5),360+(rn%8)*24,CAST(0.018+(rn%8)*0.006 AS DECIMAL(18,4)),88+(rn%8),CASE WHEN rn%8=0 THEN 91 ELSE 96+(rn%4) END FROM @cats;

INSERT INTO rag_retrievers(organization_id,retriever_code,retriever_name,retriever_type,status,health_percent,average_latency_ms,success_rate)
SELECT @org,CONCAT('RET-',RIGHT('00'+CAST(v.i AS NVARCHAR(2)),2)),v.name,v.kind,CASE WHEN v.i IN (7,11) THEN 'Warning' ELSE 'Healthy' END,CASE WHEN v.i IN (7,11) THEN 92 ELSE 97 END,80+v.i*19,96+(v.i%4) FROM (VALUES (1,'Vector Search Retriever','Vector'),(2,'Keyword BM25 Retriever','Keyword'),(3,'Hybrid Retriever','Hybrid'),(4,'Knowledge Graph Retriever','Graph'),(5,'SQL Retriever','SQL'),(6,'Metadata Retriever','Metadata'),(7,'External Search Retriever','External'),(8,'Rule-Based Retriever','Rule-Based'),(9,'Agentic Retriever','Agentic'),(10,'Hierarchical Retriever','Hierarchical'),(11,'Archive Retriever','Archive'),(12,'Memory Retriever','Memory')) v(i,name,kind);
INSERT INTO rag_embedding_models(organization_id,model_name,dimensions,version_label,health_percent) VALUES (@org,'text-embedding-3-large',3072,'v3',98),(@org,'text-embedding-3-small',1536,'v3',98),(@org,'local-e5-large',1024,'v2',96),(@org,'domain-content-embedder',1536,'v5',95);
INSERT INTO rag_vector_collections(organization_id,collection_name,vector_store,vector_count,index_type,health_percent) SELECT @org,CONCAT('rag_',LOWER(REPLACE(name,' ','_'))),'MSSQL Vector Store',120000+(rn*6431),'HNSW',CASE WHEN rn%9=0 THEN 93 ELSE 97 END FROM @cats;
INSERT INTO rag_rerankers(organization_id,reranker_name,model_type,status,health_percent) VALUES (@org,'cross-encoder-reranker','cross-encoder','Healthy',98),(@org,'authority-freshness-reranker','policy-reranker','Healthy',97),(@org,'citation-aware-reranker','citation-reranker','Healthy',97),(@org,'local-reranker','local-model','Warning',93);

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<42),
cat AS (SELECT id, category_name, ROW_NUMBER() OVER (ORDER BY category_name) rn, COUNT(*) OVER () cnt FROM rag_pipeline_categories WHERE organization_id=@org),
src AS (SELECT n.i, cat.id category_id, cat.category_name FROM n JOIN cat ON cat.rn=((n.i-1)%cat.cnt)+1)
INSERT INTO rag_pipelines(organization_id,category_id,pipeline_code,pipeline_name,description,scope_type,status,current_version,published_version,retrieval_mode,primary_retriever,fallback_retriever,embedding_model,vector_collection,keyword_index,graph_source,sql_source,reranker,top_k,relevance_threshold,authority_threshold,freshness_threshold,citation_required,grounding_required,assigned_agents,workflow_usage,retrievals_today,success_rate,average_relevance,average_latency_ms,average_cost,failover_count,final_output_linked,health_percent,owner,organization_name,environment,human_attention_required)
SELECT @org,category_id,CONCAT('RAG-',RIGHT('000'+CAST(i AS NVARCHAR(3)),3)),CONCAT(category_name,' Pipeline ',i),CONCAT('Autonomous retrieval pipeline for ',LOWER(category_name),' with grounding, citations, recovery, and final-output traceability.'),CASE WHEN i%5=0 THEN 'Brand' WHEN i%3=0 THEN 'Organization' ELSE 'System' END,CASE WHEN i%29=0 THEN 'Failing' WHEN i%17=0 THEN 'Degraded' WHEN i%11=0 THEN 'Warning' ELSE 'Active' END,CONCAT('v',1+(i%5),'.',i%10),CONCAT('v',1+(i%4),'.',i%7),CASE i%11 WHEN 0 THEN 'Vector' WHEN 1 THEN 'Keyword' WHEN 2 THEN 'Hybrid' WHEN 3 THEN 'Graph' WHEN 4 THEN 'SQL' WHEN 5 THEN 'Metadata' WHEN 6 THEN 'Rule-Based' WHEN 7 THEN 'Multi-Source' WHEN 8 THEN 'Hierarchical' WHEN 9 THEN 'Agentic Retrieval' ELSE 'Adaptive Retrieval' END,CASE WHEN i%4=0 THEN 'Hybrid Retriever' WHEN i%4=1 THEN 'Vector Search Retriever' WHEN i%4=2 THEN 'Knowledge Graph Retriever' ELSE 'Keyword BM25 Retriever' END,'Fallback Hybrid Retriever',CASE WHEN i%3=0 THEN 'text-embedding-3-large' WHEN i%3=1 THEN 'text-embedding-3-small' ELSE 'local-e5-large' END,CONCAT('rag_',LOWER(REPLACE(category_name,' ','_'))),CONCAT('kw_',LOWER(REPLACE(category_name,' ','_'))),'knowledge graph','approved SQL view','citation-aware-reranker',5+(i%12),0.78+(i%8)*0.02,86+(i%9),84+(i%10),CASE WHEN i%6=0 THEN 0 ELSE 1 END,1,2+(i%9),1+(i%14),80+(i*13)%900,CASE WHEN i%17=0 THEN 92 ELSE 96+(i%4) END,0.82+(i%12)*0.01,320+(i%12)*23,CAST(0.011+(i%18)*0.004 AS DECIMAL(18,4)),CASE WHEN i%13=0 THEN 3 ELSE i%4 END,CASE WHEN i%8=0 THEN 0 ELSE 1 END,CASE WHEN i%17=0 THEN 89 ELSE 95+(i%5) END,'RAG Governance Engine','AI Media Group','production',0 FROM src OPTION (MAXRECURSION 0);

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<386),
p AS (SELECT id, organization_id, pipeline_code, pipeline_name, retrieval_mode, ROW_NUMBER() OVER (ORDER BY pipeline_code) rn, COUNT(*) OVER () cnt FROM rag_pipelines WHERE organization_id=@org),
rows AS (SELECT n.i, p.* FROM n JOIN p ON p.rn=((n.i-1)%p.cnt)+1)
INSERT INTO rag_retrieval_requests(organization_id,pipeline_id,retrieval_code,original_query,rewritten_query,agent_name,agent_run_code,workflow_name,workflow_stage,status,detected_intent,retrieval_mode,sources,retriever_count,candidate_count,selected_count,relevance_score,authority_score,freshness_score,grounding_score,citation_count,context_tokens,latency_ms,actual_cost,retry_count,failover_state,final_output_impact,organization_name,brand_name,started_at,completed_at)
SELECT @org,id,CONCAT('RETQ-',RIGHT('000000'+CAST(i AS NVARCHAR(6)),6)),CONCAT('Find trusted evidence for content decision ',i),CONCAT('Retrieve authoritative, fresh, cited evidence for content decision ',i),CONCAT('Autonomous Agent ',1+(i%18)),CONCAT('AAR-',RIGHT('000000'+CAST(i AS NVARCHAR(6)),6)),'Autonomous Content Lifecycle',CONCAT('Stage ',1+(i%20)),CASE WHEN i%31=0 THEN 'Failing Over' WHEN i%23=0 THEN 'Retrying' WHEN i%17=0 THEN 'Validating Grounding' WHEN i%13=0 THEN 'Reranking' ELSE 'Completed' END,CASE WHEN i%5=0 THEN 'policy evidence' WHEN i%5=1 THEN 'brand context' WHEN i%5=2 THEN 'audience insight' WHEN i%5=3 THEN 'workflow history' ELSE 'market intelligence' END,retrieval_mode,'knowledge base, memory, graph, workflow history',2+(i%4),24+(i%130),5+(i%16),0.82+(i%12)*0.01,88+(i%10),86+(i%11),90+(i%9),2+(i%8),3000+(i%9000),330+(i%220),CAST(0.008+(i%16)*0.004 AS DECIMAL(18,4)),CASE WHEN i%23=0 THEN 1 ELSE 0 END,CASE WHEN i%31=0 THEN 'fallback retriever selected' ELSE 'none' END,CASE WHEN i%17=0 THEN 'watch' ELSE 'protected' END,'AI Media Group','CACSMS Contents',DATEADD(minute,-i,SYSUTCDATETIME()),CASE WHEN i%13=0 THEN NULL ELSE DATEADD(second,30,DATEADD(minute,-i,SYSUTCDATETIME())) END FROM rows OPTION (MAXRECURSION 0);

INSERT INTO rag_query_intelligence(retrieval_id,detected_intent,classified_domain,expanded_terms,decomposed_subqueries,confidence_percent) SELECT id,detected_intent,'content intelligence','brand, audience, policy, evidence, citations',1+(ABS(CHECKSUM(id))%4),92+(ABS(CHECKSUM(retrieval_code))%7) FROM rag_retrieval_requests WHERE organization_id=@org;
INSERT INTO rag_contexts(retrieval_id,selected_chunks,duplicate_chunks_removed,contradictions_found,compression_applied,context_tokens,evidence_preservation) SELECT id,selected_count,ABS(CHECKSUM(id))%4,CASE WHEN status='Validating Grounding' THEN 1 ELSE 0 END,CASE WHEN context_tokens>6000 THEN 1 ELSE 0 END,context_tokens,94+(ABS(CHECKSUM(retrieval_code))%5) FROM rag_retrieval_requests WHERE organization_id=@org;
INSERT INTO rag_grounding_results(retrieval_id,claims_evaluated,claims_supported,unsupported_claims,grounding_score,hallucination_risk,validation_state) SELECT id,8+(ABS(CHECKSUM(id))%20),8+(ABS(CHECKSUM(id))%18),CASE WHEN grounding_score<92 THEN 1 ELSE 0 END,grounding_score,100-grounding_score,CASE WHEN grounding_score<92 THEN 'watch' ELSE 'validated' END FROM rag_retrieval_requests WHERE organization_id=@org;
INSERT INTO rag_citations(retrieval_id,citation_count,citation_validity,provenance_chain,source_locations) SELECT id,citation_count,93+(ABS(CHECKSUM(id))%6),'source > chunk > citation > context > output','knowledge source anchors preserved' FROM rag_retrieval_requests WHERE organization_id=@org;
INSERT INTO rag_evaluations(organization_id,pipeline_id,evaluation_name,evaluation_score,grounding_score,citation_score,status) SELECT @org,id,'daily retrieval evaluation',average_relevance*100,success_rate,citation_required*94 + CASE WHEN citation_required=0 THEN 88 ELSE 0 END,'completed' FROM rag_pipelines WHERE organization_id=@org;
INSERT INTO rag_failures(organization_id,pipeline_id,failure_type,failure_state,severity) SELECT @org,id,CASE WHEN status='Failing' THEN 'retriever unavailable' ELSE 'weak context' END,'classified',CASE WHEN status='Failing' THEN 'high' ELSE 'medium' END FROM rag_pipelines WHERE organization_id=@org AND status IN ('Failing','Degraded','Warning');
INSERT INTO rag_recoveries(organization_id,retrieval_id,pipeline_id,recovery_action,recovery_state,failover_used) SELECT TOP 80 @org,r.id,r.pipeline_id,CASE WHEN r.status='Failing Over' THEN 'alternate retriever selected' ELSE 'query rewrite retry' END,'completed',CASE WHEN r.status='Failing Over' THEN 1 ELSE 0 END FROM rag_retrieval_requests r WHERE r.organization_id=@org ORDER BY r.started_at DESC;
INSERT INTO rag_performance(organization_id,pipeline_id,retrieval_count,success_rate,failure_rate,average_relevance,grounding_success,citation_coverage,p95_latency_ms,output_acceptance) SELECT @org,id,retrievals_today,success_rate,100-success_rate,average_relevance*100,success_rate-1,CASE WHEN citation_required=1 THEN 94 ELSE 88 END,average_latency_ms+180,92+(ABS(CHECKSUM(id))%7) FROM rag_pipelines WHERE organization_id=@org;
INSERT INTO rag_recommendations(organization_id,pipeline_id,recommendation_type,title,impact,confidence_percent,status) SELECT TOP 24 @org,id,CASE WHEN status='Degraded' THEN 'recovery' WHEN citation_required=0 THEN 'citation' ELSE 'optimization' END,CONCAT('Optimize ',pipeline_name),'quality, latency, citation, grounding',90+(ABS(CHECKSUM(id))%8),'queued' FROM rag_pipelines WHERE organization_id=@org;
INSERT INTO rag_final_output_traceability(organization_id,pipeline_id,output_name,workflow_name,grounding_score,citation_coverage,traceability_state,business_impact) SELECT @org,id,CONCAT('Output grounded by ',pipeline_code),'Autonomous Content Lifecycle',success_rate-1,CASE WHEN citation_required=1 THEN 94 ELSE 88 END,CASE WHEN final_output_linked=1 THEN 'traceable' ELSE 'watch' END,'reduced hallucination risk and protected final business outcome' FROM rag_pipelines WHERE organization_id=@org;
