DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50039, 'No organization exists for Audit seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES ('audit.view','View audit and decision trace'),('audit.investigate','Investigate decisions'),('audit.export','Export audit evidence'),('audit.compliance','View compliance audit'),('audit.admin','Administer audit controls');
MERGE permissions AS target USING (SELECT code,description FROM @perms) source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'audit-decision-trace' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=99, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',99);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('AUDIT_DECISION_RECORDING','Audit Decision Recording'),('AUDIT_EVIDENCE_PRESERVATION','Audit Evidence Preservation'),('AUDIT_TIMELINE_REPLAY','Audit Timeline Replay'),('AUDIT_FORENSIC_INVESTIGATION','Audit Forensic Investigation'),('AUDIT_COMPLIANCE_REPORT','Audit Compliance Report'),('AUDIT_INTEGRITY_VALIDATION','Audit Integrity Validation'),('AUDIT_EVIDENCE_EXPORT','Audit Evidence Export');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'audit_decision_trace' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM ai_final_output_trace WHERE organization_id=@org; DELETE FROM ai_traceability WHERE organization_id=@org; DELETE FROM ai_compliance WHERE organization_id=@org; DELETE FROM ai_retention WHERE organization_id=@org; DELETE FROM ai_signatures WHERE organization_id=@org; DELETE FROM ai_hashes WHERE organization_id=@org; DELETE FROM ai_integrity WHERE organization_id=@org; DELETE FROM ai_forensics WHERE organization_id=@org; DELETE FROM ai_audit_events WHERE organization_id=@org; DELETE FROM ai_audit_logs WHERE organization_id=@org; DELETE FROM ai_decision_replay WHERE organization_id=@org; DELETE FROM ai_decision_graph WHERE organization_id=@org; DELETE FROM ai_decision_versions WHERE organization_id=@org; DELETE FROM ai_decision_dependencies WHERE organization_id=@org; DELETE FROM ai_decision_evidence WHERE organization_id=@org; DELETE FROM ai_decision_reasoning WHERE organization_id=@org; DELETE FROM ai_decision_scores WHERE organization_id=@org; DELETE FROM ai_decision_steps WHERE organization_id=@org; DELETE FROM ai_decisions WHERE organization_id=@org;

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<420)
INSERT INTO ai_decisions(organization_id,decision_code,decision_type,agent_name,workflow_name,objective,reason,confidence,risk,status,outcome,business_impact,trace_completeness,explainability_score,evidence_integrity,compliance_score,created_at)
SELECT @org,CONCAT('DEC-',RIGHT('000000'+CAST(i AS NVARCHAR(6)),6)),
CASE i%13 WHEN 0 THEN 'Planning' WHEN 1 THEN 'Routing' WHEN 2 THEN 'Retrieval' WHEN 3 THEN 'Reasoning' WHEN 4 THEN 'Prompt' WHEN 5 THEN 'Tool' WHEN 6 THEN 'Workflow' WHEN 7 THEN 'Approval' WHEN 8 THEN 'Recovery' WHEN 9 THEN 'Publishing' WHEN 10 THEN 'Learning' WHEN 11 THEN 'Governance' ELSE 'Security' END,
CONCAT('Autonomous Agent ',1+(i%68)),'Autonomous Content Lifecycle',CONCAT('Deliver business objective ',i),'selected highest confidence governed option from available alternatives',88+(i%12),CASE WHEN i%37=0 THEN 34 ELSE 4+(i%12) END,CASE WHEN i%29=0 THEN 'Investigating' ELSE 'Completed' END,CASE WHEN i%31=0 THEN 'Recovered' ELSE 'Accepted' END,'final output and business KPI protected',92+(i%8),90+(i%9),94+(i%5),93+(i%6),DATEADD(minute,-i,SYSUTCDATETIME()) FROM n OPTION (MAXRECURSION 0);

INSERT INTO ai_decision_steps(organization_id,decision_id,sequence_no,stage_name,component,state,duration_ms,evidence_count)
SELECT @org,d.id,s.seq,s.stage,d.agent_name,'recorded',80+s.seq*22,2+(ABS(CHECKSUM(d.id))%8) FROM ai_decisions d CROSS APPLY (VALUES (1,'Objective'),(2,'Planning'),(3,'Decision'),(4,'Execution'),(5,'Validation'),(6,'Recovery'),(7,'Publishing'),(8,'Learning'),(9,'Business Outcome')) s(seq,stage) WHERE d.organization_id=@org;
INSERT INTO ai_decision_scores(organization_id,decision_id,score_name,score_value,weight_value) SELECT @org,id,'confidence',confidence,0.35 FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'risk',100-risk,0.25 FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'compliance',compliance_score,0.40 FROM ai_decisions WHERE organization_id=@org;
INSERT INTO ai_decision_reasoning(organization_id,decision_id,why_text,why_not_text,alternatives,dependencies) SELECT @org,id,'highest weighted confidence and compliance score','lower ranked alternatives had weaker evidence or higher cost','alternate prompt, alternate model, fallback tool, recovery path','objective, workflow, prompt, model, provider, tools, memory, RAG, validation' FROM ai_decisions WHERE organization_id=@org;
INSERT INTO ai_decision_evidence(organization_id,decision_id,evidence_type,evidence_title,evidence_location,hash_value,integrity_state,retained_until) SELECT @org,id,CASE ABS(CHECKSUM(id))%8 WHEN 0 THEN 'Logs' WHEN 1 THEN 'Prompts' WHEN 2 THEN 'Outputs' WHEN 3 THEN 'Context' WHEN 4 THEN 'Memory' WHEN 5 THEN 'Knowledge' WHEN 6 THEN 'Reports' ELSE 'Media' END,CONCAT('Evidence for ',decision_code),CONCAT('/evidence/',decision_code),CONVERT(NVARCHAR(128),HASHBYTES('SHA2_256',CONVERT(NVARCHAR(80),id)),2),'verified',DATEADD(day,2555,SYSUTCDATETIME()) FROM ai_decisions WHERE organization_id=@org;
INSERT INTO ai_decision_dependencies(organization_id,decision_id,dependency_type,dependency_name,version_label,trace_state) SELECT @org,id,'Prompt','Content Lifecycle Prompt','v3.7','traceable' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'Model','governed-model-route','v2','traceable' FROM ai_decisions WHERE organization_id=@org;
INSERT INTO ai_decision_versions(organization_id,decision_id,prompt_version,model_name,provider_name,tool_versions) SELECT @org,id,'prompt-v3.7','governed-model-route','primary-provider','tool-registry-v5;rag-v4;memory-v3' FROM ai_decisions WHERE organization_id=@org;
INSERT INTO ai_decision_graph(organization_id,decision_id,from_node,to_node,edge_reason) SELECT @org,id,'Objective','Planning','objective decomposed' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'Planning','Prompt','prompt selected' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'Prompt','Model','model routed' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'Model','Tool','tool chosen' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'Tool','RAG','context retrieved' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'RAG','Validation','grounding validated' FROM ai_decisions WHERE organization_id=@org UNION ALL SELECT @org,id,'Validation','Business Result','output accepted' FROM ai_decisions WHERE organization_id=@org;
INSERT INTO ai_decision_replay(organization_id,decision_id,second_offset,replay_stage,actor,event_text,replay_state) SELECT @org,d.id,s.seq*3,s.stage,d.agent_name,CONCAT(s.stage,' recorded for ',d.decision_code),'ready' FROM ai_decisions d CROSS APPLY (VALUES (1,'Workflow'),(2,'Agent'),(3,'Prompt'),(4,'Model'),(5,'Tools'),(6,'Memory'),(7,'Knowledge'),(8,'Outputs'),(9,'Validation'),(10,'Recovery'),(11,'Publishing'),(12,'Learning')) s(seq,stage) WHERE d.organization_id=@org;
INSERT INTO ai_audit_logs(organization_id,decision_id,occurred_at,actor,component,action_name,old_value,new_value,reason,evidence,approval,result) SELECT TOP 1200 @org,id,created_at,agent_name,decision_type,'decision recorded','pending','completed',reason,decision_code,'policy-governed','success' FROM ai_decisions WHERE organization_id=@org ORDER BY created_at DESC;
INSERT INTO ai_audit_events(organization_id,event_name,event_count,last_event_at) VALUES (@org,'decision.created',420,SYSUTCDATETIME()),(@org,'audit.recorded',1200,SYSUTCDATETIME()),(@org,'evidence.saved',420,SYSUTCDATETIME()),(@org,'timeline.updated',420,SYSUTCDATETIME());
INSERT INTO ai_forensics(organization_id,investigation_code,incident,evidence_count,logs_count,prompts_count,models_count,outputs_count,recovery_state,business_impact) SELECT TOP 32 @org,CONCAT('FOR-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY decision_code) AS NVARCHAR(3)),3)),CONCAT('Investigation for ',decision_code),12,24,3,2,4,'reconstructable','no unresolved business risk' FROM ai_decisions WHERE organization_id=@org AND status='Investigating' ORDER BY created_at DESC;
INSERT INTO ai_integrity(organization_id,artifact_name,integrity_score,verification_state) SELECT TOP 80 @org,evidence_title,98,'verified' FROM ai_decision_evidence WHERE organization_id=@org;
INSERT INTO ai_hashes(organization_id,artifact_name,hash_value,hash_algorithm) SELECT TOP 80 @org,evidence_title,hash_value,'SHA2_256' FROM ai_decision_evidence WHERE organization_id=@org;
INSERT INTO ai_signatures(organization_id,artifact_name,signature_value,signature_state) SELECT TOP 80 @org,evidence_title,CONCAT('SIG-',RIGHT(hash_value,16)),'verified' FROM ai_decision_evidence WHERE organization_id=@org;
INSERT INTO ai_retention(organization_id,retention_policy,retention_period_days,legal_hold,archive_state) VALUES (@org,'Short',90,0,'active'),(@org,'Medium',365,0,'active'),(@org,'Long',2555,0,'active'),(@org,'Legal Hold',3650,1,'locked');
INSERT INTO ai_compliance(organization_id,policy_name,approval_state,audit_state,traceability_score,evidence_score,retention_state,legal_hold) VALUES (@org,'AI Decision Traceability','approved','complete',98,99,'active',0),(@org,'Evidence Preservation','approved','complete',97,99,'active',0),(@org,'Legal Discovery Readiness','approved','complete',96,98,'locked',1);
INSERT INTO ai_traceability(organization_id,trace_name,objective_linked,workflow_linked,agent_linked,prompt_linked,model_linked,tool_linked,retrieval_linked,output_linked) SELECT TOP 120 @org,decision_code,1,1,1,1,1,1,1,1 FROM ai_decisions WHERE organization_id=@org ORDER BY created_at DESC;
INSERT INTO ai_final_output_trace(organization_id,output_name,decision_id,objective,workflow_name,agent_name,prompt_version,model_name,provider_name,traceability_score,business_outcome) SELECT TOP 160 @org,CONCAT('Published Output ',ROW_NUMBER() OVER (ORDER BY created_at DESC)),id,objective,workflow_name,agent_name,'prompt-v3.7','governed-model-route','primary-provider',trace_completeness,'accepted business output' FROM ai_decisions WHERE organization_id=@org ORDER BY created_at DESC;
