DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50040, 'No organization exists for Agent Governance seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('agent_governance.view','View Agent Governance Center'),('agent_governance.view_policies','View governance policies'),('agent_governance.view_approvals','View governance approvals'),('agent_governance.view_exceptions','View governance exceptions'),('agent_governance.view_violations','View governance violations'),('agent_governance.view_risks','View governance risks'),('agent_governance.view_controls','View governance controls'),('agent_governance.view_regulatory','View regulatory mappings'),('agent_governance.view_sensitive','View sensitive governance data'),('agent_governance.create_policy','Create governance policy'),('agent_governance.edit_policy','Edit governance policy'),('agent_governance.validate_policy','Validate governance policy'),('agent_governance.simulate_policy','Simulate governance policy'),('agent_governance.test_policy','Test governance policy'),('agent_governance.publish_policy','Publish governance policy'),('agent_governance.suspend_policy','Suspend governance policy'),('agent_governance.deprecate_policy','Deprecate governance policy'),('agent_governance.manage_rules','Manage governance rules'),('agent_governance.manage_scope','Manage governance scope'),('agent_governance.manage_approvals','Manage governance approvals'),('agent_governance.approve','Approve governance request'),('agent_governance.reject','Reject governance request'),('agent_governance.delegate_approval','Delegate governance approval'),('agent_governance.manage_exceptions','Manage governance exceptions'),('agent_governance.manage_violations','Manage governance violations'),('agent_governance.manage_risks','Manage governance risks'),('agent_governance.manage_controls','Manage governance controls'),('agent_governance.test_controls','Test governance controls'),('agent_governance.manage_regulatory','Manage regulatory governance'),('agent_governance.manage_use_cases','Manage AI use-case governance'),('agent_governance.manage_data_governance','Manage data governance'),('agent_governance.manage_model_governance','Manage model governance'),('agent_governance.manage_tool_governance','Manage tool governance'),('agent_governance.manage_prompt_governance','Manage prompt governance'),('agent_governance.manage_publishing_governance','Manage publishing governance'),('agent_governance.manage_learning_governance','Manage learning governance'),('agent_governance.apply_recommendations','Apply governance recommendations'),('agent_governance.generate_ai','Generate governance policy with AI'),('agent_governance.generate_reports','Generate governance reports'),('agent_governance.export','Export governance data'),('agent_governance.emergency_override','Use governance emergency controls');
MERGE permissions AS target USING (SELECT code,description FROM @perms) source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'agent-governance' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=99, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',99);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('GOVERNANCE_POLICY_CREATION','Governance Policy Creation'),('GOVERNANCE_POLICY_VALIDATION','Governance Policy Validation'),('GOVERNANCE_POLICY_SIMULATION','Governance Policy Simulation'),('GOVERNANCE_DECISION_EVALUATION','Governance Decision Evaluation'),('GOVERNANCE_APPROVAL_PROCESS','Governance Approval Process'),('GOVERNANCE_EXCEPTION_PROCESS','Governance Exception Process'),('GOVERNANCE_VIOLATION_RESPONSE','Governance Violation Response'),('GOVERNANCE_RISK_ASSESSMENT','Governance Risk Assessment'),('GOVERNANCE_CONTROL_TESTING','Governance Control Testing'),('GOVERNANCE_POLICY_REVIEW','Governance Policy Review'),('GOVERNANCE_REGULATORY_MAPPING','Governance Regulatory Mapping'),('GOVERNANCE_USE_CASE_ASSESSMENT','Governance Use Case Assessment'),('GOVERNANCE_EMERGENCY_RESPONSE','Governance Emergency Response');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'agent_governance' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM agent_governance_final_output WHERE organization_id=@org; DELETE FROM agent_governance_recommendations WHERE organization_id=@org; DELETE FROM agent_governance_audit_events WHERE organization_id=@org; DELETE FROM agent_governance_coverage WHERE organization_id=@org; DELETE FROM agent_governance_lifecycle WHERE organization_id=@org; DELETE FROM agent_governance_use_cases WHERE organization_id=@org; DELETE FROM agent_governance_regulatory_mappings WHERE organization_id=@org; DELETE FROM agent_governance_controls WHERE organization_id=@org; DELETE FROM agent_governance_risks WHERE organization_id=@org; DELETE FROM agent_governance_violations WHERE organization_id=@org; DELETE FROM agent_governance_exceptions WHERE organization_id=@org; DELETE FROM agent_governance_approvals WHERE organization_id=@org; DELETE FROM agent_governance_conflicts WHERE organization_id=@org; DELETE FROM agent_governance_decisions WHERE organization_id=@org; DELETE FROM agent_governance_policy_versions WHERE organization_id=@org; DELETE FROM agent_governance_policies WHERE organization_id=@org; DELETE FROM agent_governance_domains WHERE organization_id=@org;

DECLARE @domains TABLE(i INT IDENTITY(1,1), name NVARCHAR(160));
INSERT INTO @domains(name) VALUES ('AI Agent Governance'),('Prompt Governance'),('Model Governance'),('Provider Governance'),('Tool Governance'),('Data Governance'),('Memory Governance'),('Knowledge Governance'),('RAG Governance'),('Workflow Governance'),('Approval Governance'),('Publishing Governance'),('Social Platform Governance'),('Content Governance'),('Brand Governance'),('Copyright Governance'),('Privacy Governance'),('Security Governance'),('Financial Governance'),('Cost Governance'),('Risk Governance'),('Autonomous Learning Governance'),('Experiment Governance'),('Release Governance'),('Emergency Governance'),('Business Outcome Governance');

INSERT INTO agent_governance_domains(organization_id,domain_name,active_policies,coverage_percent,open_approvals,exceptions,violations,risk_score,last_review,next_review,final_output_coverage,health_percent)
SELECT @org,name,5+(i%4),95.8+(i%5)*0.7,CASE WHEN i IN (3,6,9,12,15,18,21,24) THEN 1 ELSE 0 END,CASE WHEN i IN (5,8,11,14,17,20,23) THEN 1 ELSE 0 END,CASE WHEN i IN (4,16,25) THEN 1 ELSE 0 END,18+(i%9)*3,DATEADD(day,-i,SYSUTCDATETIME()),DATEADD(day,20+i,SYSUTCDATETIME()),95.4+(i%6)*0.6,96.2+(i%4)*0.8 FROM @domains;

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<148)
INSERT INTO agent_governance_policies(organization_id,policy_code,policy_name,domain,policy_type,scope_text,version_label,status,priority_level,enforcement_mode,risk_level,applies_to,conditions_text,actions_text,approval_requirement,exception_allowed,violation_count,compliance_rate,last_evaluated,last_reviewed,next_review,owner_name,organization_name,environment_name,final_output_impact,business_objective,decision_logic,evidence_required,created_at)
SELECT @org,CONCAT('GOV-',RIGHT('0000'+CAST(n.i AS NVARCHAR(4)),4)),CONCAT(d.name,' Policy ',n.i),d.name,
CASE n.i%21 WHEN 0 THEN 'Permission Policy' WHEN 1 THEN 'Prohibition Policy' WHEN 2 THEN 'Approval Policy' WHEN 3 THEN 'Risk Policy' WHEN 4 THEN 'Security Policy' WHEN 5 THEN 'Data Policy' WHEN 6 THEN 'Privacy Policy' WHEN 7 THEN 'Cost Policy' WHEN 8 THEN 'Quality Policy' WHEN 9 THEN 'Content Policy' WHEN 10 THEN 'Publishing Policy' WHEN 11 THEN 'Model Policy' WHEN 12 THEN 'Provider Policy' WHEN 13 THEN 'Tool Policy' WHEN 14 THEN 'Workflow Policy' WHEN 15 THEN 'Retention Policy' WHEN 16 THEN 'Residency Policy' WHEN 17 THEN 'Copyright Policy' WHEN 18 THEN 'Regulatory Policy' WHEN 19 THEN 'Exception Policy' ELSE 'Emergency Policy' END,
'Organization, brand, environment, agents, workflows, prompts, models, providers, tools, data and final outputs',CONCAT('v',1+(n.i%5),'.',n.i%9),CASE WHEN n.i IN (17,44,91) THEN 'Conflicting' WHEN n.i%37=0 THEN 'Warning' ELSE 'Active' END,CASE WHEN n.i%11=0 THEN 'Critical' WHEN n.i%7=0 THEN 'High' ELSE 'Standard' END,
CASE n.i%9 WHEN 0 THEN 'Allow' WHEN 1 THEN 'Allow with Guardrails' WHEN 2 THEN 'Validate' WHEN 3 THEN 'Require Approval' WHEN 4 THEN 'Restrict' WHEN 5 THEN 'Block' WHEN 6 THEN 'Quarantine' WHEN 7 THEN 'Escalate' ELSE 'Observe' END,
CASE WHEN n.i IN (14,28,42,56) THEN 'High' WHEN n.i%5=0 THEN 'Medium' ELSE 'Low' END,'Autonomous agents, production workflows, content pipelines, RAG sources and publishing paths','risk, confidence, cost, data classification, grounding, platform, jurisdiction and final-output criticality thresholds','allow, validate, restrict, require approval, redact, quarantine, notify, roll back or create incident',
CASE WHEN n.i%8=0 THEN 'Governance Council approval required' WHEN n.i%5=0 THEN 'Policy owner validation required' ELSE 'Autonomous allow within guardrails' END,CASE WHEN n.i%6=0 THEN 1 ELSE 0 END,CASE WHEN n.i IN (17,44,91) THEN 1 ELSE 0 END,96.4+(n.i%5)*0.5,DATEADD(minute,-n.i,SYSUTCDATETIME()),DATEADD(day,-(n.i%30),SYSUTCDATETIME()),DATEADD(day,CASE WHEN n.i%17=0 THEN 7 ELSE 35+(n.i%60) END,SYSUTCDATETIME()),CONCAT('Governance Owner ',1+(n.i%12)),'AI Media Group','Production','final output protected by policy evidence and accountable decision trace','Keep autonomous behavior inside approved business, legal, security, financial, ethical and operational boundaries','policy priority resolves conflicts; mandatory law, security, privacy, organization, brand, environment, workflow, agent and default policies are evaluated in order','decision trace, approval route, evidence hash, risk score, control result, final-output impact and audit event',DATEADD(day,-80+n.i,SYSUTCDATETIME())
FROM n JOIN @domains d ON d.i=1+((n.i-1)%26) OPTION (MAXRECURSION 0);

INSERT INTO agent_governance_policy_versions(organization_id,policy_id,version_label,change_summary,published_at) SELECT @org,id,version_label,'Seeded governed production policy version',last_reviewed FROM agent_governance_policies WHERE organization_id=@org;
;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<420)
INSERT INTO agent_governance_decisions(organization_id,policy_id,decision_code,request_type,route_selected,outcome,risk_score,evidence_hash,decided_at)
SELECT @org,(SELECT TOP 1 id FROM agent_governance_policies WHERE organization_id=@org ORDER BY NEWID()),CONCAT('GDEC-',RIGHT('000000'+CAST(i AS NVARCHAR(6)),6)),CASE i%10 WHEN 0 THEN 'Tool permission change' WHEN 1 THEN 'Prompt version change' WHEN 2 THEN 'Model route change' WHEN 3 THEN 'RAG source access' WHEN 4 THEN 'Publishing action' WHEN 5 THEN 'Autonomous learning rollout' WHEN 6 THEN 'Cost ceiling change' WHEN 7 THEN 'Data access request' WHEN 8 THEN 'Workflow production change' ELSE 'Final output release' END,CASE WHEN i%13=0 THEN 'Approval Required' WHEN i%29=0 THEN 'Rejected' ELSE 'Autonomously Allowed' END,CASE WHEN i%29=0 THEN 'Rejected' WHEN i%13=0 THEN 'Routed' ELSE 'Allowed' END,CASE WHEN i IN (25,50,75,100) THEN 85 ELSE 12+(i%28) END,CONVERT(NVARCHAR(128),HASHBYTES('SHA2_256',CONCAT('GDEC-',i)),2),DATEADD(minute,-i,SYSUTCDATETIME()) FROM n OPTION (MAXRECURSION 0);
INSERT INTO agent_governance_conflicts(organization_id,conflict_code,policy_a,policy_b,severity,resolution_strategy,status,detected_at) SELECT TOP 21 @org,CONCAT('GCON-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY policy_code) AS NVARCHAR(3)),3)),policy_name,'Default autonomy policy',CASE WHEN ROW_NUMBER() OVER (ORDER BY policy_code)%7=0 THEN 'High' ELSE 'Medium' END,'mandatory law and security precedence applied','Auto Resolved',DATEADD(hour,-ROW_NUMBER() OVER (ORDER BY policy_code),SYSUTCDATETIME()) FROM agent_governance_policies WHERE organization_id=@org ORDER BY policy_code;
INSERT INTO agent_governance_approvals(organization_id,approval_code,request_type,requested_by,approval_role,risk_level,sla_minutes,status,evidence_status,created_at) SELECT TOP 12 @org,CONCAT('GAPR-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY decided_at DESC) AS NVARCHAR(3)),3)),request_type,'autonomous-governance-router','Governance Owner',CASE WHEN risk_score>=80 THEN 'High' ELSE 'Medium' END,240,'Pending','Complete',decided_at FROM agent_governance_decisions WHERE organization_id=@org AND route_selected='Approval Required' ORDER BY decided_at DESC;
INSERT INTO agent_governance_exceptions(organization_id,exception_code,policy_code,owner_name,reason,compensating_controls,status,expires_at) SELECT TOP 7 @org,CONCAT('GEX-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY policy_code) AS NVARCHAR(3)),3)),policy_code,owner_name,'temporary governed production exception','extra monitoring, reduced scope, output quarantine and automatic expiry','Active',DATEADD(day,7+ROW_NUMBER() OVER (ORDER BY policy_code),SYSUTCDATETIME()) FROM agent_governance_policies WHERE organization_id=@org AND exception_allowed=1 ORDER BY policy_code;
INSERT INTO agent_governance_violations(organization_id,violation_code,policy_code,severity,action_contained,incident_state,final_output_risk,detected_at) SELECT TOP 3 @org,CONCAT('GVIO-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY policy_code) AS NVARCHAR(3)),3)),policy_code,'High','action quarantined and evidence preserved','Open','Contained',DATEADD(hour,-ROW_NUMBER() OVER (ORDER BY policy_code),SYSUTCDATETIME()) FROM agent_governance_policies WHERE organization_id=@org AND violation_count>0 ORDER BY policy_code;
INSERT INTO agent_governance_risks(organization_id,risk_code,risk_name,category,inherent_score,residual_score,trend,owner_name,treatment_status) SELECT TOP 18 @org,CONCAT('GRSK-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY name) AS NVARCHAR(3)),3)),CONCAT(name,' residual governance risk'),name,64+(i%20),18+(i%18),CASE WHEN i%6=0 THEN 'Increasing' ELSE 'Stable' END,CONCAT('Risk Owner ',i%8+1),'Mitigated by active controls' FROM @domains;
INSERT INTO agent_governance_controls(organization_id,control_code,control_name,control_type,domain,effectiveness,test_status,last_tested) SELECT TOP 32 @org,CONCAT('GCTL-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY name) AS NVARCHAR(3)),3)),CONCAT(name,' control'),CASE i%3 WHEN 0 THEN 'Preventive' WHEN 1 THEN 'Detective' ELSE 'Corrective' END,name,94+(i%5),'Passed',DATEADD(day,-i,SYSUTCDATETIME()) FROM @domains d CROSS JOIN (SELECT 1 x UNION ALL SELECT 2) z;
INSERT INTO agent_governance_regulatory_mappings(organization_id,regulation,requirement_name,mapped_policies,evidence_score,coverage_percent,status) VALUES (@org,'Nigeria Data Protection Act','Personal data access governance',18,98,97,'Covered'),(@org,'Copyright and Licensing','Source and output licensing accountability',14,97,96,'Covered'),(@org,'Internal AI Standard','Autonomous decision traceability',32,99,98,'Covered'),(@org,'Security Baseline','Tool, provider and secret-access controls',21,98,97,'Covered');
INSERT INTO agent_governance_use_cases(organization_id,use_case_name,domain,autonomy_level,approval_gate,risk_score,governance_state) SELECT TOP 18 @org,CONCAT(name,' autonomous use case'),name,'Fully Governed Autonomy',CASE WHEN i%5=0 THEN 'Approval required above threshold' ELSE 'Autonomous within guardrails' END,22+(i%18),'Governed' FROM @domains;
INSERT INTO agent_governance_lifecycle(organization_id,sequence_no,stage_name,request_count,allowed_count,approval_count,rejected_count,exception_count,violation_count,average_duration_ms,health_percent,current_blockers) VALUES
(@org,1,'Action Requested',420,392,24,4,7,3,90,98,'none'),(@org,2,'Context Loaded',420,392,24,4,7,3,120,98,'none'),(@org,3,'Applicable Policies Identified',420,392,24,4,7,3,160,97,'none'),(@org,4,'Permissions Validated',420,392,24,4,7,3,130,98,'none'),(@org,5,'Risk Calculated',420,392,24,4,7,3,180,97,'high-risk routes watched'),(@org,6,'Regulatory Requirements Checked',420,392,24,4,7,3,210,96,'none'),(@org,7,'Policy Conditions Evaluated',420,392,24,4,7,3,240,97,'none'),(@org,8,'Conflicts Resolved',21,21,0,0,0,0,300,96,'none'),(@org,9,'Governance Route Selected',420,392,24,4,7,3,170,98,'none'),(@org,10,'Decision Recorded',420,392,24,4,7,3,95,99,'none'),(@org,11,'Execution Monitored',420,392,24,4,7,3,260,97,'none'),(@org,12,'Final-Output Impact Updated',160,154,5,1,2,0,220,97,'none');
INSERT INTO agent_governance_coverage(organization_id,coverage_area,coverage_percent,gaps_count,final_output_coverage,owner_name,status) SELECT @org,name,95.5+(i%6)*0.6,CASE WHEN i%9=0 THEN 1 ELSE 0 END,95.8+(i%5)*0.7,CONCAT('Coverage Owner ',i%10+1),'Covered' FROM @domains;
INSERT INTO agent_governance_audit_events(organization_id,event_name,event_count,latest_event_at) VALUES (@org,'governance.policy.created',148,SYSUTCDATETIME()),(@org,'governance.decision.allowed',392,SYSUTCDATETIME()),(@org,'governance.approval.requested',12,SYSUTCDATETIME()),(@org,'governance.exception.approved',7,SYSUTCDATETIME()),(@org,'governance.violation.detected',3,SYSUTCDATETIME()),(@org,'governance.coverage.changed',26,SYSUTCDATETIME()),(@org,'governance.final_output.updated',160,SYSUTCDATETIME());
INSERT INTO agent_governance_recommendations(organization_id,recommendation_code,title,priority_level,expected_impact,status,created_at) VALUES (@org,'GREC-001','Tighten high-risk model-route approval threshold','High','reduces model governance residual risk','Open',SYSUTCDATETIME()),(@org,'GREC-002','Add stronger evidence mapping for publishing exceptions','Medium','improves final-output readiness','Open',SYSUTCDATETIME()),(@org,'GREC-003','Recertify policies due within fourteen days','Medium','keeps coverage above target','Scheduled',SYSUTCDATETIME());
;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<160)
INSERT INTO agent_governance_final_output(organization_id,output_name,governance_readiness,unresolved_risk,blocking_policy,traceability_score,decision_state,updated_at)
SELECT @org,CONCAT('Governed Final Output ',i),96+(i%5)*0.4,CASE WHEN i%47=0 THEN 'Contained review risk' ELSE 'None' END,CASE WHEN i%47=0 THEN 'GOV-0017' ELSE 'None' END,96+(i%4)*0.7,'Ready',DATEADD(minute,-i,SYSUTCDATETIME()) FROM n OPTION (MAXRECURSION 0);
