DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50041, 'No organization exists for Agent Security seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('agent_security.view','View Agent Security Center'),('agent_security.view_identities','View AI identities'),('agent_security.view_permissions','View AI permissions'),('agent_security.view_secrets','View security secrets'),('agent_security.view_events','View security events'),('agent_security.view_incidents','View security incidents'),('agent_security.view_evidence','View security evidence'),('agent_security.view_sensitive','View sensitive security data'),('agent_security.view_vulnerabilities','View vulnerabilities'),('agent_security.view_risks','View security risks'),('agent_security.manage_identities','Manage identities'),('agent_security.suspend_identity','Suspend identity'),('agent_security.lock_identity','Lock identity'),('agent_security.revoke_identity','Revoke identity'),('agent_security.terminate_sessions','Terminate sessions'),('agent_security.manage_service_accounts','Manage service accounts'),('agent_security.manage_permissions','Manage permissions'),('agent_security.run_access_reviews','Run access reviews'),('agent_security.manage_jit_access','Manage JIT access'),('agent_security.manage_secrets','Manage secrets'),('agent_security.rotate_secrets','Rotate secrets'),('agent_security.revoke_secrets','Revoke secrets'),('agent_security.manage_zero_trust','Manage zero trust'),('agent_security.manage_prompt_security','Manage prompt security'),('agent_security.manage_tool_security','Manage tool security'),('agent_security.manage_dlp','Manage DLP'),('agent_security.manage_isolation','Manage isolation'),('agent_security.run_threat_hunt','Run threat hunt'),('agent_security.investigate_events','Investigate events'),('agent_security.contain_events','Contain events'),('agent_security.manage_incidents','Manage incidents'),('agent_security.execute_playbooks','Execute playbooks'),('agent_security.manage_vulnerabilities','Manage vulnerabilities'),('agent_security.manage_supply_chain','Manage supply chain'),('agent_security.manage_controls','Manage security controls'),('agent_security.test_controls','Test controls'),('agent_security.manage_risks','Manage risks'),('agent_security.apply_recommendations','Apply recommendations'),('agent_security.generate_reports','Generate reports'),('agent_security.export','Export security data'),('agent_security.manage_settings','Manage security settings'),('agent_security.manage_governance','Manage security governance'),('agent_security.emergency_override','Use emergency override');
MERGE permissions AS target USING (SELECT code,description FROM @perms) source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'agent-security' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=99, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',99);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('SECURITY_IDENTITY_REGISTRATION','Security Identity Registration'),('SECURITY_ACCESS_REVIEW','Security Access Review'),('SECURITY_JIT_ACCESS','Security JIT Access'),('SECURITY_SECRET_ROTATION','Security Secret Rotation'),('SECURITY_ZERO_TRUST_DECISION','Security Zero Trust Decision'),('SECURITY_PROMPT_INJECTION_RESPONSE','Security Prompt Injection Response'),('SECURITY_TOOL_ABUSE_RESPONSE','Security Tool Abuse Response'),('SECURITY_DLP_RESPONSE','Security DLP Response'),('SECURITY_TENANT_ISOLATION_RESPONSE','Security Tenant Isolation Response'),('SECURITY_EVENT_CORRELATION','Security Event Correlation'),('SECURITY_INCIDENT_RESPONSE','Security Incident Response'),('SECURITY_AUTONOMOUS_CONTAINMENT','Security Autonomous Containment'),('SECURITY_VULNERABILITY_REMEDIATION','Security Vulnerability Remediation'),('SECURITY_CONTROL_TESTING','Security Control Testing'),('SECURITY_RISK_ASSESSMENT','Security Risk Assessment'),('SECURITY_EMERGENCY_LOCKDOWN','Security Emergency Lockdown');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'agent_security' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM agent_security_final_output WHERE organization_id=@org; DELETE FROM agent_security_recommendations WHERE organization_id=@org; DELETE FROM agent_security_audit_events WHERE organization_id=@org; DELETE FROM agent_security_risks WHERE organization_id=@org; DELETE FROM agent_security_controls WHERE organization_id=@org; DELETE FROM agent_security_vulnerabilities WHERE organization_id=@org; DELETE FROM agent_security_playbooks WHERE organization_id=@org; DELETE FROM agent_security_containment WHERE organization_id=@org; DELETE FROM agent_security_incidents WHERE organization_id=@org; DELETE FROM agent_security_events WHERE organization_id=@org; DELETE FROM agent_security_threat_intel WHERE organization_id=@org; DELETE FROM agent_security_behavior WHERE organization_id=@org; DELETE FROM agent_security_dlp WHERE organization_id=@org; DELETE FROM agent_security_secrets WHERE organization_id=@org; DELETE FROM agent_security_permissions WHERE organization_id=@org; DELETE FROM agent_security_zero_trust WHERE organization_id=@org; DELETE FROM agent_security_lifecycle WHERE organization_id=@org; DELETE FROM agent_security_identities WHERE organization_id=@org; DELETE FROM agent_security_domains WHERE organization_id=@org;

DECLARE @domains TABLE(i INT IDENTITY(1,1), name NVARCHAR(160));
INSERT INTO @domains(name) VALUES ('Agent Identity Security'),('Service Account Security'),('Access and Authorization'),('Zero-Trust Security'),('Secrets and Credential Security'),('Prompt Security'),('Model and Provider Security'),('Tool Security'),('Memory Security'),('Knowledge Security'),('RAG Security'),('Workflow Security'),('Queue and Worker Security'),('Database Security'),('File and Storage Security'),('API Security'),('Network Security'),('Publishing Security'),('Social Account Security'),('Data-Loss Prevention'),('Vulnerability Management'),('Threat Intelligence'),('Incident Response'),('Recovery Security'),('Audit and Evidence Security'),('Business Output Security');

INSERT INTO agent_security_domains(organization_id,domain_name,assets_count,active_findings,critical_findings,incidents,control_coverage,compliance_percent,risk_score,last_scan,final_output_coverage,health_percent)
SELECT @org,name,28+(i%16),CASE WHEN i%4=0 THEN 2 ELSE 1 END,CASE WHEN i=6 THEN 1 ELSE 0 END,CASE WHEN i IN (6,8,20,23) THEN 1 ELSE 0 END,95.5+(i%5)*0.7,96+(i%4)*0.5,16+(i%9)*4,DATEADD(hour,-i,SYSUTCDATETIME()),95.8+(i%5)*0.6,95.9+(i%4)*0.7 FROM @domains;

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<164)
INSERT INTO agent_security_identities(organization_id,identity_code,identity_name,identity_type,linked_agent,service_account,role_name,team_name,status,authentication_method,trust_level,risk_score,permission_count,excessive_permissions,active_sessions,last_authentication,last_activity,secret_status,organization_scope,brand_scope,environment_scope,owner_name,final_output_access,created_at)
SELECT @org,CONCAT('AID-',RIGHT('0000'+CAST(i AS NVARCHAR(4)),4)),CONCAT('AI Security Identity ',i),
CASE i%11 WHEN 0 THEN 'Agent Identity' WHEN 1 THEN 'Service Account' WHEN 2 THEN 'Worker Identity' WHEN 3 THEN 'Workflow Identity' WHEN 4 THEN 'Tool Identity' WHEN 5 THEN 'Provider Identity' WHEN 6 THEN 'Model Identity' WHEN 7 THEN 'Integration Identity' WHEN 8 THEN 'System Identity' WHEN 9 THEN 'Human Administrator' ELSE 'Emergency Identity' END,
CONCAT('Autonomous Agent ',1+(i%68)),CONCAT('svc-agent-',RIGHT('000'+CAST(i AS NVARCHAR(3)),3)),CASE i%6 WHEN 0 THEN 'Publisher' WHEN 1 THEN 'Researcher' WHEN 2 THEN 'Reviewer' WHEN 3 THEN 'Operator' WHEN 4 THEN 'Security Monitor' ELSE 'Governance Executor' END,CONCAT('Team ',1+(i%12)),CASE WHEN i=19 THEN 'Under Review' WHEN i%53=0 THEN 'Locked' WHEN i%47=0 THEN 'Warning' ELSE 'Active' END,CASE i%4 WHEN 0 THEN 'Managed Identity' WHEN 1 THEN 'mTLS' WHEN 2 THEN 'OIDC Workload Identity' ELSE 'Vault Token' END,CASE WHEN i IN (12,24,36,48,60,72,84) THEN 'Low' WHEN i%9=0 THEN 'Medium' ELSE 'High' END,CASE WHEN i IN (12,24,36,48,60,72,84) THEN 72 ELSE 8+(i%24) END,24+(i%36),CASE WHEN i IN (12,24,36,48,60,72,84) THEN 1 ELSE 0 END,CASE WHEN i%17=0 THEN 4 ELSE 1+(i%3) END,DATEADD(minute,-i*3,SYSUTCDATETIME()),DATEADD(minute,-i,SYSUTCDATETIME()),CASE WHEN i IN (10,20,30,40,50,60) THEN 'Expiring Soon' ELSE 'Healthy' END,'AI Media Group',CASE i%4 WHEN 0 THEN 'All Brands' WHEN 1 THEN 'CACSMS Contents' WHEN 2 THEN 'Build Team' ELSE 'Production Channels' END,'Production',CONCAT('Security Owner ',1+(i%10)),CASE WHEN i%29=0 THEN 'Restricted' ELSE 'Approved' END,DATEADD(day,-i,SYSUTCDATETIME()) FROM n OPTION (MAXRECURSION 0);

INSERT INTO agent_security_lifecycle(organization_id,sequence_no,stage_name,event_count,active_incidents,contained_events,failed_containment,average_response_ms,health_percent,current_blockers) VALUES
(@org,1,'Security Event Detected',420,4,398,1,90,98,'none'),(@org,2,'Event Normalized',420,4,398,1,110,98,'none'),(@org,3,'Identity Resolved',420,4,398,1,135,97,'one identity under review'),(@org,4,'Context Enriched',420,4,398,1,180,97,'none'),(@org,5,'Threat Correlated',420,4,398,1,220,96,'critical threat watched'),(@org,6,'Severity Classified',420,4,398,1,120,98,'none'),(@org,7,'Risk Calculated',420,4,398,1,160,97,'none'),(@org,8,'Policy Evaluated',420,4,398,1,190,97,'none'),(@org,9,'Containment Decision',420,4,398,1,210,97,'none'),(@org,10,'Action Contained or Allowed',420,4,398,1,240,96,'none'),(@org,11,'Evidence Preserved',420,4,398,1,150,99,'none'),(@org,12,'Final-Output Impact Updated',160,1,154,0,190,97,'one output risk requires attention');
;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<420)
INSERT INTO agent_security_events(organization_id,event_code,event_type,identity_code,asset_name,severity,risk_score,containment_state,evidence_hash,occurred_at)
SELECT @org,CONCAT('SEV-',RIGHT('000000'+CAST(i AS NVARCHAR(6)),6)),CASE WHEN i<=28 THEN 'Prompt Injection' WHEN i<=214 THEN 'Unauthorized Action' WHEN i<=225 THEN 'High-Risk Tool Call' WHEN i=226 THEN 'Critical Threat' WHEN i%17=0 THEN 'Data Leakage' WHEN i%19=0 THEN 'Tool Abuse' ELSE 'Zero Trust Decision' END,(SELECT TOP 1 identity_code FROM agent_security_identities WHERE organization_id=@org ORDER BY NEWID()),CONCAT('Security Asset ',1+(i%80)),CASE WHEN i=226 THEN 'Critical' WHEN i%17=0 THEN 'High' WHEN i%7=0 THEN 'Medium' ELSE 'Low' END,CASE WHEN i=226 THEN 92 WHEN i%17=0 THEN 72 ELSE 12+(i%25) END,CASE WHEN i<=186 THEN 'Blocked' WHEN i=226 THEN 'Contained' ELSE 'Allowed' END,CONVERT(NVARCHAR(128),HASHBYTES('SHA2_256',CONCAT('SEC-',i)),2),DATEADD(minute,-i,SYSUTCDATETIME()) FROM n OPTION (MAXRECURSION 0);
INSERT INTO agent_security_zero_trust(organization_id,decision_code,identity_code,resource_name,decision_result,reason,risk_score,decided_at) SELECT TOP 120 @org,CONCAT('ZT-',RIGHT('000000'+CAST(ROW_NUMBER() OVER (ORDER BY occurred_at DESC) AS NVARCHAR(6)),6)),identity_code,asset_name,CASE WHEN containment_state='Blocked' THEN 'Denied' ELSE 'Allowed' END,'continuous identity, context, permission, data sensitivity and final-output checks evaluated',risk_score,occurred_at FROM agent_security_events WHERE organization_id=@org ORDER BY occurred_at DESC;
INSERT INTO agent_security_permissions(organization_id,permission_code,permission_name,category,sensitivity,assigned_identities,excessive_findings,review_status) SELECT TOP 42 @org,CONCAT('sec.permission.',i),CONCAT(name,' permission'),name,CASE WHEN i%5=0 THEN 'Critical' WHEN i%3=0 THEN 'High' ELSE 'Standard' END,8+(i%20),CASE WHEN i%6=0 THEN 1 ELSE 0 END,'Review Scheduled' FROM @domains;
INSERT INTO agent_security_secrets(organization_id,secret_code,secret_name,secret_type,owner_name,rotation_state,days_to_expiry,risk_level,last_rotated) SELECT TOP 36 @org,CONCAT('SEC-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY identity_code) AS NVARCHAR(3)),3)),CONCAT('Credential for ',identity_name),CASE ROW_NUMBER() OVER (ORDER BY identity_code)%6 WHEN 0 THEN 'API Key' WHEN 1 THEN 'Provider Credential' WHEN 2 THEN 'Tool Secret' WHEN 3 THEN 'Database Credential' WHEN 4 THEN 'Publishing Token' ELSE 'Webhook Secret' END,owner_name,CASE WHEN ROW_NUMBER() OVER (ORDER BY identity_code)<=6 THEN 'Expiring Soon' ELSE 'Healthy' END,CASE WHEN ROW_NUMBER() OVER (ORDER BY identity_code)<=6 THEN 7 ELSE 60+(ROW_NUMBER() OVER (ORDER BY identity_code)%120) END,CASE WHEN ROW_NUMBER() OVER (ORDER BY identity_code)<=6 THEN 'High' ELSE 'Low' END,DATEADD(day,-ROW_NUMBER() OVER (ORDER BY identity_code),SYSUTCDATETIME()) FROM agent_security_identities WHERE organization_id=@org ORDER BY identity_code;
INSERT INTO agent_security_dlp(organization_id,dlp_code,source_name,data_classification,action_taken,final_output_impact,detected_at) SELECT TOP 18 @org,CONCAT('DLP-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY event_code) AS NVARCHAR(3)),3)),asset_name,'Confidential','redacted and output blocked until revalidation','contained',occurred_at FROM agent_security_events WHERE organization_id=@org AND event_type='Data Leakage';
INSERT INTO agent_security_behavior(organization_id,entity_name,anomaly_type,baseline_score,observed_score,risk_level,detected_at) SELECT TOP 24 @org,asset_name,event_type,20,72,CASE WHEN severity='High' THEN 'High' ELSE 'Medium' END,occurred_at FROM agent_security_events WHERE organization_id=@org AND severity IN ('High','Medium') ORDER BY occurred_at DESC;
INSERT INTO agent_security_threat_intel(organization_id,intel_code,threat_name,threat_type,confidence,mapped_controls,status) VALUES (@org,'TI-001','Prompt injection campaign','Prompt Attack',96,8,'Active'),(@org,'TI-002','Tool abuse pattern','Tool Abuse',92,6,'Active'),(@org,'TI-003','RAG poisoning indicator','Knowledge Poisoning',89,5,'Watched'),(@org,'TI-004','Credential stuffing signature','Authentication Attack',94,7,'Active');
INSERT INTO agent_security_incidents(organization_id,incident_code,title,severity,status,contained,affected_assets,final_output_risk,opened_at) VALUES (@org,'SINC-001','Critical prompt-injection attempt against publishing workflow','Critical','Contained',1,4,'Contained review risk',DATEADD(hour,-4,SYSUTCDATETIME())),(@org,'SINC-002','Excessive permission path in tool identity','High','Investigating',0,3,'No released output impact',DATEADD(hour,-8,SYSUTCDATETIME())),(@org,'SINC-003','Credential expiry risk for provider route','Medium','Open',0,6,'No output impact',DATEADD(hour,-12,SYSUTCDATETIME())),(@org,'SINC-004','Data leakage attempt blocked during final output','High','Contained',1,2,'Contained final-output risk',DATEADD(hour,-16,SYSUTCDATETIME()));
INSERT INTO agent_security_containment(organization_id,containment_code,incident_code,action_name,target_name,state,executed_at) VALUES (@org,'SCON-001','SINC-001','quarantine prompt input','Publishing workflow','Completed',DATEADD(hour,-4,SYSUTCDATETIME())),(@org,'SCON-002','SINC-004','block output and redact data','Final output pipeline','Completed',DATEADD(hour,-15,SYSUTCDATETIME())),(@org,'SCON-003','SINC-002','restrict tool permission','Tool identity','Running',DATEADD(hour,-7,SYSUTCDATETIME()));
INSERT INTO agent_security_playbooks(organization_id,playbook_code,playbook_name,trigger_type,automation_level,success_rate,last_executed) VALUES (@org,'SPB-001','Prompt Injection Response','Prompt Injection','Fully Autonomous',96,DATEADD(hour,-4,SYSUTCDATETIME())),(@org,'SPB-002','Credential Rotation','Secret Expiry','Autonomous with Guardrails',94,DATEADD(day,-1,SYSUTCDATETIME())),(@org,'SPB-003','Database Compromise Containment','Database Compromise','Approval-Gated Emergency',91,DATEADD(day,-3,SYSUTCDATETIME()));
INSERT INTO agent_security_vulnerabilities(organization_id,vulnerability_code,asset_name,vulnerability_type,severity,remediation_state,detected_at) SELECT TOP 22 @org,CONCAT('VUL-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY name) AS NVARCHAR(3)),3)),name,CASE i%4 WHEN 0 THEN 'Dependency' WHEN 1 THEN 'Configuration' WHEN 2 THEN 'Permission' ELSE 'Supply Chain' END,CASE WHEN i%11=0 THEN 'High' ELSE 'Medium' END,'Queued for autonomous remediation',DATEADD(day,-i,SYSUTCDATETIME()) FROM @domains;
INSERT INTO agent_security_controls(organization_id,control_code,control_name,control_type,domain,effectiveness,test_status,last_tested) SELECT TOP 32 @org,CONCAT('SCTL-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY name) AS NVARCHAR(3)),3)),CONCAT(name,' control'),CASE i%3 WHEN 0 THEN 'Preventive' WHEN 1 THEN 'Detective' ELSE 'Corrective' END,name,94+(i%5),'Passed',DATEADD(day,-i,SYSUTCDATETIME()) FROM @domains d CROSS JOIN (SELECT 1 x UNION ALL SELECT 2) z;
INSERT INTO agent_security_risks(organization_id,risk_code,risk_name,category,inherent_score,residual_score,treatment_status) SELECT TOP 18 @org,CONCAT('SRISK-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY name) AS NVARCHAR(3)),3)),CONCAT(name,' residual security risk'),name,64+(i%20),16+(i%18),'Mitigated by zero-trust controls' FROM @domains;
INSERT INTO agent_security_audit_events(organization_id,event_name,event_count,latest_event_at) VALUES (@org,'security.identity.risk_changed',7,SYSUTCDATETIME()),(@org,'security.authorization.denied',186,SYSUTCDATETIME()),(@org,'security.prompt_injection.detected',28,SYSUTCDATETIME()),(@org,'security.secret.expiring',6,SYSUTCDATETIME()),(@org,'security.incident.created',4,SYSUTCDATETIME()),(@org,'security.incident.contained',2,SYSUTCDATETIME()),(@org,'security.final_output.updated',160,SYSUTCDATETIME());
INSERT INTO agent_security_recommendations(organization_id,recommendation_code,title,priority_level,expected_impact,status,created_at) VALUES (@org,'SREC-001','Reduce excessive permissions on seven identities','High','lowers identity compromise blast radius','Open',SYSUTCDATETIME()),(@org,'SREC-002','Rotate six expiring provider and publishing secrets','High','prevents credential-expiry disruption','Scheduled',SYSUTCDATETIME()),(@org,'SREC-003','Tighten prompt-injection quarantine threshold','Medium','improves autonomous containment precision','Open',SYSUTCDATETIME());
;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<160)
INSERT INTO agent_security_final_output(organization_id,output_name,security_readiness,unresolved_risk,blocking_control,traceability_score,decision_state,updated_at)
SELECT @org,CONCAT('Secured Final Output ',i),96+(i%5)*0.45,CASE WHEN i=19 THEN 'Human attention required' WHEN i%47=0 THEN 'Contained security review' ELSE 'None' END,CASE WHEN i=19 THEN 'SCTL-019' WHEN i%47=0 THEN 'SCTL-006' ELSE 'None' END,96+(i%4)*0.7,CASE WHEN i=19 THEN 'Review Required' ELSE 'Ready' END,DATEADD(minute,-i,SYSUTCDATETIME()) FROM n OPTION (MAXRECURSION 0);
