DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50043, 'No organization exists for Agent Version Release seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('version_release.view','View Agent Version and Release Management'),('version_release.view_versions','View component versions'),('version_release.view_releases','View releases'),('version_release.view_artifacts','View release artifacts'),('version_release.view_configuration','View release configuration'),('version_release.view_migrations','View release migrations'),('version_release.view_sensitive','View sensitive release metadata'),('version_release.create_version','Create component versions'),('version_release.edit_version','Edit component versions'),('version_release.validate_version','Validate component versions'),('version_release.publish_version','Publish component versions'),('version_release.promote_version','Promote component versions'),('version_release.restore_version','Restore component versions'),('version_release.compare_versions','Compare versions'),('version_release.create_release','Create releases'),('version_release.edit_release','Edit releases'),('version_release.build_package','Build release packages'),('version_release.validate_release','Validate releases'),('version_release.simulate_release','Simulate releases'),('version_release.run_tests','Run release tests'),('version_release.request_approval','Request release approval'),('version_release.approve_release','Approve releases'),('version_release.reject_release','Reject releases'),('version_release.schedule_release','Schedule releases'),('version_release.deploy_release','Deploy releases'),('version_release.pause_release','Pause releases'),('version_release.resume_release','Resume releases'),('version_release.expand_rollout','Expand rollout'),('version_release.rollback_release','Rollback releases'),('version_release.manage_environments','Manage environments'),('version_release.promote_environment','Promote environments'),('version_release.manage_strategies','Manage strategies'),('version_release.manage_feature_flags','Manage feature flags'),('version_release.manage_migrations','Manage migrations'),('version_release.execute_migrations','Execute migrations'),('version_release.manage_configuration','Manage configuration'),('version_release.resolve_drift','Resolve drift'),('version_release.manage_freezes','Manage freezes'),('version_release.manage_emergency_releases','Manage emergency releases'),('version_release.apply_recommendations','Apply recommendations'),('version_release.generate_notes','Generate release notes'),('version_release.generate_reports','Generate reports'),('version_release.export','Export release data'),('version_release.manage_governance','Manage release governance'),('version_release.emergency_override','Use emergency release override');
MERGE permissions AS target USING (SELECT code,description FROM @perms) source ON target.code=source.code
WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (code,description) VALUES (source.code,source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id,permission_id)
SELECT @adminRole,p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

MERGE job_queues AS target USING (SELECT @org organization_id, 'version-release-operations' name) source
ON target.organization_id=source.organization_id AND target.name=source.name
WHEN MATCHED THEN UPDATE SET status='running', health_percent=99, updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',99);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES
('COMPONENT_VERSION_CREATION','Component Version Creation'),('COMPONENT_VERSION_VALIDATION','Component Version Validation'),('COMPONENT_VERSION_PROMOTION','Component Version Promotion'),('RELEASE_PLANNING','Release Planning'),('RELEASE_PACKAGE_BUILD','Release Package Build'),('RELEASE_DEPENDENCY_ANALYSIS','Release Dependency Analysis'),('RELEASE_VALIDATION','Release Validation'),('RELEASE_APPROVAL','Release Approval'),('ENVIRONMENT_PROMOTION','Environment Promotion'),('RELEASE_DEPLOYMENT','Release Deployment'),('CANARY_DEPLOYMENT','Canary Deployment'),('BLUE_GREEN_DEPLOYMENT','Blue Green Deployment'),('PROGRESSIVE_DELIVERY','Progressive Delivery'),('DATABASE_MIGRATION','Database Migration'),('POST_RELEASE_VALIDATION','Post Release Validation'),('RELEASE_REGRESSION_RESPONSE','Release Regression Response'),('RELEASE_AUTONOMOUS_ROLLBACK','Release Autonomous Rollback'),('RELEASE_RECOVERY','Release Recovery'),('EMERGENCY_RELEASE','Emergency Release'),('RELEASE_GOVERNANCE_APPROVAL','Release Governance Approval');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'version_release_operations' workflow_type FROM @wf) source
ON target.organization_id=source.organization_id AND target.code=source.code
WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME()
WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);

DELETE FROM ai_release_autonomous_decisions WHERE organization_id=@org; DELETE FROM ai_release_final_output_traceability WHERE organization_id=@org; DELETE FROM ai_release_analytics WHERE organization_id=@org; DELETE FROM ai_release_notes WHERE organization_id=@org; DELETE FROM ai_release_recoveries WHERE organization_id=@org; DELETE FROM ai_release_rollbacks WHERE organization_id=@org; DELETE FROM ai_release_regressions WHERE organization_id=@org; DELETE FROM ai_release_health WHERE organization_id=@org; DELETE FROM ai_release_approvals WHERE organization_id=@org; DELETE FROM ai_release_risk_assessments WHERE organization_id=@org; DELETE FROM ai_release_validation_gates WHERE organization_id=@org; DELETE FROM ai_release_configuration_drift WHERE organization_id=@org; DELETE FROM ai_release_database_migrations WHERE organization_id=@org; DELETE FROM ai_release_feature_flags WHERE organization_id=@org; DELETE FROM ai_release_deployments WHERE organization_id=@org; DELETE FROM ai_release_environment_promotions WHERE organization_id=@org; DELETE FROM ai_release_environments WHERE organization_id=@org; DELETE FROM ai_release_packages WHERE organization_id=@org; DELETE FROM ai_release_dependency_impacts WHERE organization_id=@org; DELETE FROM ai_release_lifecycle WHERE organization_id=@org; DELETE FROM ai_release_version_domains WHERE organization_id=@org; DELETE FROM ai_release_releases WHERE organization_id=@org; DELETE FROM ai_release_component_versions WHERE organization_id=@org;

DECLARE @types TABLE(i INT IDENTITY(1,1), name NVARCHAR(120));
INSERT INTO @types(name) VALUES ('Agent'),('Capability'),('Role'),('Team'),('Prompt'),('Model Route'),('Provider Configuration'),('Tool'),('Tool Schema'),('Memory Policy'),('Knowledge Configuration'),('RAG Pipeline'),('Workflow'),('Approval Policy'),('Recovery Policy'),('Governance Policy'),('Security Policy'),('Learning Model'),('Analytics Definition'),('Publishing Configuration'),('Brand Configuration'),('Database Migration'),('Infrastructure Configuration');
;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<486)
INSERT INTO ai_release_component_versions(organization_id,component_code,component_name,component_type,current_version,published_version,production_version,latest_version,status,environment_name,change_type,compatibility,dependency_count,validation_status,test_status,security_status,governance_status,rollback_ready,version_drift,released_by,release_code,owner_name,organization_name,final_output_impact,health_percent,updated_at)
SELECT @org, CONCAT('CMP-',RIGHT('000000'+CAST(n.i AS NVARCHAR(6)),6)), CONCAT(t.name,' component ',n.i), t.name, CONCAT('v',1+(n.i%4),'.',n.i%10,'.',n.i%7), CONCAT('v',1+(n.i%4),'.',n.i%10,'.',n.i%7), CONCAT('v',1+(n.i%4),'.',n.i%10,'.',n.i%7), CONCAT('v',1+(n.i%4),'.',n.i%10,'.',1+(n.i%8)),
CASE n.i%13 WHEN 0 THEN 'Blocked' WHEN 1 THEN 'Draft' WHEN 2 THEN 'Validating' WHEN 3 THEN 'Testing' WHEN 4 THEN 'Approved' WHEN 5 THEN 'Released' WHEN 6 THEN 'Active' WHEN 7 THEN 'Superseded' WHEN 8 THEN 'Deprecated' WHEN 9 THEN 'Rolled Back' ELSE 'Active' END,
CASE n.i%5 WHEN 0 THEN 'Production' WHEN 1 THEN 'Development' WHEN 2 THEN 'QA' WHEN 3 THEN 'UAT' ELSE 'Staging' END,
CASE n.i%6 WHEN 0 THEN 'Feature' WHEN 1 THEN 'Patch' WHEN 2 THEN 'Security' WHEN 3 THEN 'Configuration' WHEN 4 THEN 'Model Migration' ELSE 'Workflow Release' END,
CASE WHEN n.i%17=0 THEN 'Blocked' WHEN n.i%11=0 THEN 'Warning' ELSE 'Compatible' END, 1+(n.i%18),
CASE WHEN n.i%19=0 THEN 'Failed' WHEN n.i%7=0 THEN 'Running' ELSE 'Passed' END,
CASE WHEN n.i%23=0 THEN 'Failed' WHEN n.i%8=0 THEN 'Running' ELSE 'Passed' END,
CASE WHEN n.i%29=0 THEN 'Failed' ELSE 'Passed' END,
CASE WHEN n.i%31=0 THEN 'Failed' ELSE 'Passed' END,
CASE WHEN n.i%37=0 THEN 0 ELSE 1 END, CASE WHEN n.i<=7 THEN 1 ELSE 0 END, 'Autonomous Release Engine', CONCAT('REL-',RIGHT('000'+CAST(1+(n.i%24) AS NVARCHAR(3)),3)), 'AI Release Operations', 'AI Media Group',
CASE WHEN n.i%17=0 THEN 'At Risk' WHEN n.i%9=0 THEN 'Medium' ELSE 'Protected' END, 90+(n.i%10), DATEADD(minute,-n.i,SYSUTCDATETIME())
FROM n JOIN @types t ON t.i=1+((n.i-1)%23) OPTION (MAXRECURSION 0);

;WITH n AS (SELECT 1 i UNION ALL SELECT i+1 FROM n WHERE i<24)
INSERT INTO ai_release_releases(organization_id,release_code,release_name,release_type,version_number,status,target_environment,component_count,change_risk,dependency_status,validation_status,test_status,security_status,governance_status,migration_status,rollback_status,deployment_strategy,traffic_allocation,duration_minutes,release_health,final_output_impact,owner_name,organization_name,start_time,updated_at)
SELECT @org, CONCAT('REL-',RIGHT('000'+CAST(i AS NVARCHAR(3)),3)), CONCAT('Autonomous AI Platform Release ',i),
CASE i%14 WHEN 0 THEN 'Standard' WHEN 1 THEN 'Feature' WHEN 2 THEN 'Patch' WHEN 3 THEN 'Hotfix' WHEN 4 THEN 'Security' WHEN 5 THEN 'Emergency' WHEN 6 THEN 'Configuration' WHEN 7 THEN 'Model Migration' WHEN 8 THEN 'Provider Migration' WHEN 9 THEN 'Tool Migration' WHEN 10 THEN 'Database Migration' WHEN 11 THEN 'Workflow Release' WHEN 12 THEN 'Policy Release' ELSE 'Multi-Component Release' END,
CONCAT('2026.',7,'.',i),
CASE WHEN i<=3 THEN 'Awaiting Approval' WHEN i<=5 THEN 'Canary' WHEN i<=8 THEN 'Progressive Rollout' WHEN i=9 THEN 'Degraded' WHEN i=10 THEN 'Rolling Back' WHEN i=11 THEN 'Rolled Back' WHEN i=12 THEN 'Scheduled' WHEN i=13 THEN 'Validating' ELSE 'Successful' END,
CASE i%5 WHEN 0 THEN 'Production' WHEN 1 THEN 'Development' WHEN 2 THEN 'QA' WHEN 3 THEN 'UAT' ELSE 'Staging' END,
12+(i%35), CASE WHEN i%9=0 THEN 'High' WHEN i%5=0 THEN 'Medium' ELSE 'Low' END,
CASE WHEN i%11=0 THEN 'Blocked' ELSE 'Clear' END, CASE WHEN i%13=0 THEN 'Failed' ELSE 'Passed' END, CASE WHEN i%10=0 THEN 'Running' ELSE 'Passed' END, CASE WHEN i%17=0 THEN 'Failed' ELSE 'Passed' END, CASE WHEN i%19=0 THEN 'Failed' ELSE 'Passed' END, CASE WHEN i%4=0 THEN 'Pending' ELSE 'Validated' END, CASE WHEN i%8=0 THEN 'Missing' ELSE 'Ready' END,
CASE i%4 WHEN 0 THEN 'Canary' WHEN 1 THEN 'Blue/Green' WHEN 2 THEN 'Progressive' ELSE 'Shadow' END, CASE WHEN i<=8 THEN 10+(i*5) ELSE 100 END, 8+(i%15), 88+(i%12),
CASE WHEN i%9=0 THEN 'At Risk' ELSE 'Protected' END, 'AI Release Operations', 'AI Media Group', DATEADD(hour,-i,SYSUTCDATETIME()), DATEADD(minute,-i,SYSUTCDATETIME())
FROM n OPTION (MAXRECURSION 0);

DECLARE @domains TABLE(i INT IDENTITY(1,1), name NVARCHAR(140));
INSERT INTO @domains(name) VALUES ('Agent Versions'),('Capability Versions'),('Role and Team Versions'),('Task Policy Versions'),('Collaboration Policy Versions'),('Prompt Versions'),('Model Route Versions'),('Provider Configuration Versions'),('Tool Versions'),('Tool Schema Versions'),('Tool Permission Versions'),('Memory Policy Versions'),('Knowledge Configuration Versions'),('RAG Pipeline Versions'),('Workflow Versions'),('Approval Policy Versions'),('Recovery Policy Versions'),('Governance Policy Versions'),('Security Policy Versions'),('Learning Model Versions'),('Analytics Definition Versions'),('Publishing Configuration Versions'),('Brand Configuration Versions'),('Database Migration Versions'),('Infrastructure Configuration Versions');
INSERT INTO ai_release_version_domains(organization_id,domain_name,total_versions,active_version,draft_versions,validating_versions,production_versions,deprecated_versions,drift_findings,rollback_coverage,final_output_coverage,health_percent)
SELECT @org,name,14+(i%22),CONCAT('v',2+(i%4),'.',i%10,'.0'),i%4,i%3,2+(i%5),i%2,CASE WHEN i%7=0 THEN 1 ELSE 0 END,94+(i%6),93+(i%7),91+(i%9) FROM @domains;

DECLARE @stages TABLE(i INT IDENTITY(1,1), name NVARCHAR(160));
INSERT INTO @stages(name) VALUES ('Change Detected'),('Version Created'),('Dependency Impact Calculated'),('Release Package Built'),('Artifact Integrity Verified'),('Configuration Validated'),('Simulation Executed'),('Benchmarks Executed'),('Regression Tests Executed'),('Security Tests Executed'),('Governance Checks Executed'),('Database Migration Validated'),('Rollback Plan Validated'),('Release Approved'),('Promoted to Development'),('Promoted to QA'),('Promoted to UAT'),('Promoted to Staging'),('Canary or Blue/Green Deployment'),('Production Deployment'),('Post-Release Validation'),('Health Monitoring'),('Retain or Roll Back'),('Release Closed'),('Learning Updated');
INSERT INTO ai_release_lifecycle(organization_id,sequence_no,stage_name,release_count,component_count,passed_count,failed_count,blocked_count,average_duration_minutes,health_percent,current_blockers)
SELECT @org,i,name,8+(i%12),120+(i*6),8+(i%10),CASE WHEN i%9=0 THEN 1 ELSE 0 END,CASE WHEN i%11=0 THEN 1 ELSE 0 END,2+(i%14),91+(i%8),CASE WHEN i%11=0 THEN 'dependency compatibility guardrail' ELSE 'none' END FROM @stages;

INSERT INTO ai_release_environments(organization_id,environment_name,active_release,active_versions,drift_findings,health_percent,promotion_eligible) VALUES
(@org,'Development','REL-016',86,1,98,1),(@org,'QA','REL-015',74,1,97,1),(@org,'UAT','REL-014',66,0,98,1),(@org,'Staging','REL-013',58,2,96,1),(@org,'Production','REL-011',486,3,99,1);
INSERT INTO ai_release_packages(organization_id,package_code,release_code,artifact_count,checksum_status,signature_status,build_status,package_size_mb) SELECT TOP 24 @org,CONCAT('PKG-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,component_count,'Verified','Signed','Built',80+component_count*1.7 FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_dependency_impacts(organization_id,release_code,impacted_component,upstream_count,downstream_count,compatibility_status,risk_level) SELECT TOP 36 @org,release_code,release_name,2+(ROW_NUMBER() OVER (ORDER BY release_code)%8),4+(ROW_NUMBER() OVER (ORDER BY release_code)%12),CASE WHEN ROW_NUMBER() OVER (ORDER BY release_code)%9=0 THEN 'Blocked' ELSE 'Compatible' END,change_risk FROM ai_release_releases CROSS JOIN (SELECT 1 a UNION ALL SELECT 2) x WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_environment_promotions(organization_id,release_code,from_environment,to_environment,status,validation_score,promoted_at) SELECT TOP 18 @org,release_code,'QA','Staging',CASE WHEN status='Awaiting Approval' THEN 'Pending' ELSE 'Completed' END,92+(ROW_NUMBER() OVER (ORDER BY release_code)%8),DATEADD(hour,-ROW_NUMBER() OVER (ORDER BY release_code),SYSUTCDATETIME()) FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_deployments(organization_id,deployment_code,release_code,strategy,environment_name,status,traffic_allocation,health_percent,rollback_ready) SELECT TOP 18 @org,CONCAT('DEP-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,deployment_strategy,target_environment,status,traffic_allocation,release_health,CASE WHEN rollback_status='Ready' THEN 1 ELSE 0 END FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_feature_flags(organization_id,flag_code,flag_name,release_code,status,targeting_rule,exposure_percent) SELECT TOP 20 @org,CONCAT('FLG-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY component_code) AS NVARCHAR(3)),3)),component_name,release_code,CASE WHEN ROW_NUMBER() OVER (ORDER BY component_code)%5=0 THEN 'Disabled' ELSE 'Enabled' END,'tenant, role, channel and workload guarded rollout',10+(ROW_NUMBER() OVER (ORDER BY component_code)%9)*10 FROM ai_release_component_versions WHERE organization_id=@org ORDER BY component_code;
INSERT INTO ai_release_database_migrations(organization_id,migration_code,release_code,status,rollback_eligible,order_no,validation_status) SELECT TOP 18 @org,CONCAT('MIG-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,CASE WHEN migration_status='Pending' THEN 'Pending' ELSE 'Validated' END,CASE WHEN ROW_NUMBER() OVER (ORDER BY release_code)%6=0 THEN 0 ELSE 1 END,ROW_NUMBER() OVER (ORDER BY release_code),'Passed' FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_configuration_drift(organization_id,drift_code,component_name,environment_name,drift_type,severity,resolution_status) SELECT TOP 14 @org,CONCAT('DRF-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY component_code) AS NVARCHAR(3)),3)),component_name,environment_name,'version/configuration mismatch',CASE WHEN ROW_NUMBER() OVER (ORDER BY component_code)%5=0 THEN 'High' ELSE 'Medium' END,CASE WHEN ROW_NUMBER() OVER (ORDER BY component_code)%3=0 THEN 'Resolved' ELSE 'Queued' END FROM ai_release_component_versions WHERE organization_id=@org AND version_drift=1 ORDER BY component_code;
INSERT INTO ai_release_validation_gates(organization_id,gate_name,release_code,gate_status,pass_rate,blocker_count) SELECT TOP 40 @org,gate,release_code,CASE WHEN ROW_NUMBER() OVER (ORDER BY release_code,gate)%13=0 THEN 'Blocked' ELSE 'Passed' END,93+(ROW_NUMBER() OVER (ORDER BY release_code,gate)%7),CASE WHEN ROW_NUMBER() OVER (ORDER BY release_code,gate)%13=0 THEN 1 ELSE 0 END FROM ai_release_releases CROSS JOIN (VALUES('Dependency'),('Simulation'),('Benchmark'),('Regression'),('Security'),('Governance'),('Migration'),('Rollback'),('Final Output')) g(gate) WHERE organization_id=@org ORDER BY release_code,gate;
INSERT INTO ai_release_risk_assessments(organization_id,release_code,risk_score,risk_level,primary_risk,mitigation_status) SELECT @org,release_code,CASE change_risk WHEN 'High' THEN 82 WHEN 'Medium' THEN 58 ELSE 24 END,change_risk,'dependency, migration, provider route or publishing continuity','Guardrails active' FROM ai_release_releases WHERE organization_id=@org;
INSERT INTO ai_release_approvals(organization_id,release_code,approval_type,status,approver_role,sla_minutes) SELECT TOP 18 @org,release_code,'Governance Production Approval',CASE WHEN status='Awaiting Approval' THEN 'Pending' ELSE 'Completed' END,'Release Governance',240 FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_health(organization_id,release_code,availability,quality,cost_change,latency_change,reliability,error_rate,final_output_performance) SELECT @org,release_code,99.1+(release_health%1),release_health,-1*(component_count%5),component_count%7,release_health,0.1+(component_count%4)*0.05,92+(component_count%8) FROM ai_release_releases WHERE organization_id=@org;
INSERT INTO ai_release_regressions(organization_id,regression_code,release_code,detected_area,severity,rollback_recommended,status) SELECT TOP 6 @org,CONCAT('REG-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,'quality, latency or final-output variance',CASE WHEN ROW_NUMBER() OVER (ORDER BY release_code)%3=0 THEN 'Critical' ELSE 'Warning' END,CASE WHEN ROW_NUMBER() OVER (ORDER BY release_code)%3=0 THEN 1 ELSE 0 END,'Contained' FROM ai_release_releases WHERE organization_id=@org AND status IN ('Degraded','Rolling Back','Rolled Back','Canary','Progressive Rollout') ORDER BY release_code;
INSERT INTO ai_release_rollbacks(organization_id,rollback_code,release_code,previous_release,trigger_reason,status,automatic_rollback,completed_at) SELECT TOP 3 @org,CONCAT('RBK-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,CONCAT('REL-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code)+1 AS NVARCHAR(3)),3)),'regression threshold exceeded','Completed',1,DATEADD(hour,-ROW_NUMBER() OVER (ORDER BY release_code),SYSUTCDATETIME()) FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code DESC;
INSERT INTO ai_release_recoveries(organization_id,recovery_code,release_code,recovery_path,status,recovery_minutes) SELECT TOP 8 @org,CONCAT('REC-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,'freeze traffic, protect in-flight work, restore previous version, validate health','Ready',4+(ROW_NUMBER() OVER (ORDER BY release_code)%8) FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_notes(organization_id,release_code,note_title,audience,generated_status) SELECT TOP 18 @org,release_code,CONCAT('Release notes for ',release_name),'operators, governance and audit','Generated' FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_analytics(organization_id,metric_name,metric_value,metric_unit,trend) VALUES (@org,'deployment_success_rate',98.6,'percent','stable'),(@org,'rollback_readiness',97.2,'percent','improving'),(@org,'average_deployment_time',768,'seconds','improving'),(@org,'final_output_readiness',96.8,'percent','stable'),(@org,'human_attention_required',0,'count','exception-only');
INSERT INTO ai_release_final_output_traceability(organization_id,release_code,business_outcome,quality_delta,audience_delta,revenue_delta,status) SELECT TOP 24 @org,release_code,'publishing continuity, audience experience and revenue assurance',0.8+(component_count%5)*0.1,1.2+(component_count%6)*0.1,2.1+(component_count%8)*0.1,'Linked' FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
INSERT INTO ai_release_autonomous_decisions(organization_id,decision_code,release_code,decision_name,decision_status,queue_name,event_name,decided_at) SELECT TOP 12 @org,CONCAT('DEC-',RIGHT('000'+CAST(ROW_NUMBER() OVER (ORDER BY release_code) AS NVARCHAR(3)),3)),release_code,'Autonomous release guardrail evaluation','Approved for governed path','version-release-operations',CASE ROW_NUMBER() OVER (ORDER BY release_code)%5 WHEN 0 THEN 'version.created' WHEN 1 THEN 'release.validation_completed' WHEN 2 THEN 'release.deployment_progress' WHEN 3 THEN 'release.final_output.updated' ELSE 'release.completed' END,DATEADD(minute,-ROW_NUMBER() OVER (ORDER BY release_code),SYSUTCDATETIME()) FROM ai_release_releases WHERE organization_id=@org ORDER BY release_code;
