DECLARE @org UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM organizations WHERE slug='ai-media-group' ORDER BY created_at);
IF @org IS NULL SET @org = (SELECT TOP 1 id FROM organizations ORDER BY created_at);
IF @org IS NULL THROW 50046, 'No organization exists for AI Strategy & Portfolio Management seed.', 1;
DECLARE @adminRole UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM roles WHERE organization_id=@org AND code='super_admin');
DECLARE @aiAgents UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM modules WHERE organization_id=@org AND slug='ai-agents');
DECLARE @admin UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM users WHERE organization_id=@org ORDER BY created_at);

DECLARE @perms TABLE(code NVARCHAR(120), description NVARCHAR(255));
INSERT INTO @perms VALUES
('ai_strategy.view','View AI Strategy & Portfolio Management'),('ai_strategy.view_objectives','View strategy objectives'),('ai_strategy.view_portfolios','View strategy portfolios'),('ai_strategy.view_programs','View strategy programs'),('ai_strategy.view_initiatives','View strategy initiatives'),('ai_strategy.view_financials','View strategy financials'),('ai_strategy.view_benefits','View strategy benefits'),('ai_strategy.view_risks','View strategy risks'),('ai_strategy.view_sensitive','View sensitive strategy data'),('ai_strategy.create_objective','Create governed strategy objective'),('ai_strategy.edit_objective','Edit governed strategy objective'),('ai_strategy.create_portfolio','Create governed strategy portfolio'),('ai_strategy.edit_portfolio','Edit governed strategy portfolio'),('ai_strategy.create_program','Create governed strategy program'),('ai_strategy.edit_program','Edit governed strategy program'),('ai_strategy.create_initiative','Create governed strategy initiative'),('ai_strategy.edit_initiative','Edit governed strategy initiative'),('ai_strategy.run_prioritization','Run strategy prioritization'),('ai_strategy.manage_prioritization','Manage prioritization'),('ai_strategy.manage_funding','Manage funding'),('ai_strategy.approve_funding','Approve funding'),('ai_strategy.manage_capacity','Manage capacity'),('ai_strategy.manage_roadmaps','Manage roadmaps'),('ai_strategy.manage_milestones','Manage milestones'),('ai_strategy.manage_stage_gates','Manage stage gates'),('ai_strategy.manage_dependencies','Manage dependencies'),('ai_strategy.resolve_duplicates','Resolve duplicates'),('ai_strategy.manage_benefits','Manage benefits'),('ai_strategy.review_benefits','Review benefits'),('ai_strategy.manage_risks','Manage risks'),('ai_strategy.run_scenarios','Run scenarios'),('ai_strategy.run_monte_carlo','Run Monte Carlo'),('ai_strategy.manage_reviews','Manage portfolio reviews'),('ai_strategy.make_decisions','Make strategy decisions'),('ai_strategy.retire_initiatives','Retire initiatives'),('ai_strategy.apply_recommendations','Apply recommendations'),('ai_strategy.generate_reports','Generate strategy reports'),('ai_strategy.export','Export strategy portfolio'),('ai_strategy.manage_governance','Manage strategy governance'),('ai_strategy.manage_settings','Manage strategy settings');

MERGE permissions AS target USING (SELECT code, description FROM @perms) AS source ON target.code=source.code WHEN MATCHED THEN UPDATE SET description=source.description, updated_at=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT (code, description) VALUES (source.code, source.description);
IF @adminRole IS NOT NULL INSERT INTO role_permissions(role_id, permission_id) SELECT @adminRole, p.id FROM permissions p JOIN @perms x ON x.code=p.code WHERE NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id=@adminRole AND rp.permission_id=p.id);

IF @aiAgents IS NOT NULL
BEGIN
  MERGE pages AS target USING (SELECT @org AS organization_id, @aiAgents AS module_id, 'AI Strategy & Portfolio Management' AS name, 'strategy-portfolio-management' AS slug) AS source ON target.organization_id=source.organization_id AND target.module_id=source.module_id AND target.slug=source.slug WHEN MATCHED THEN UPDATE SET name=source.name, status='implemented', updated_at=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT (organization_id,module_id,name,slug,status,created_by) VALUES (source.organization_id,source.module_id,source.name,source.slug,'implemented',@admin);
  DECLARE @page UNIQUEIDENTIFIER = (SELECT TOP 1 id FROM pages WHERE organization_id=@org AND module_id=@aiAgents AND slug='strategy-portfolio-management');
  MERGE routes AS target USING (SELECT @org AS organization_id, @page AS page_id, '/dashboard/ai-agents/strategy-portfolio-management' AS path, 'GET' AS http_method) AS source ON target.organization_id=source.organization_id AND target.path=source.path AND target.http_method=source.http_method WHEN MATCHED THEN UPDATE SET page_id=source.page_id, status='operational', required_permission='ai_strategy.view', updated_at=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT (organization_id,page_id,path,http_method,status,created_by,required_permission) VALUES (source.organization_id,source.page_id,source.path,source.http_method,'operational',@admin,'ai_strategy.view');
  MERGE implementation_linkage_matrix AS target USING (SELECT @org AS organization_id, @aiAgents AS module_id, @page AS page_id) AS source ON target.organization_id=source.organization_id AND target.module_id=source.module_id AND target.page_id=source.page_id WHEN MATCHED THEN UPDATE SET status='implemented', health_percent=100, route_linked=1, component_ready=1, api_linked=1, storage_validated=1, final_output_ready=1, updated_at=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT (organization_id,module_id,page_id,status,health_percent,route_linked,component_ready,api_linked,storage_validated,final_output_ready,created_by) VALUES (source.organization_id,source.module_id,source.page_id,'implemented',100,1,1,1,1,1,@admin);
END;

MERGE job_queues AS target USING (SELECT @org organization_id, 'ai-strategy-portfolio' name) source ON target.organization_id=source.organization_id AND target.name=source.name WHEN MATCHED THEN UPDATE SET status='running', health_percent=100, updated_at=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT (organization_id,name,status,health_percent) VALUES (source.organization_id,source.name,'running',100);

DECLARE @wf TABLE(code NVARCHAR(120), name NVARCHAR(220));
INSERT INTO @wf VALUES ('STRATEGY_OBJECTIVE_CREATION','Strategy Objective Creation'),('STRATEGY_PORTFOLIO_CREATION','Strategy Portfolio Creation'),('STRATEGY_PROGRAM_CREATION','Strategy Program Creation'),('STRATEGY_INITIATIVE_ASSESSMENT','Strategy Initiative Assessment'),('STRATEGY_INITIATIVE_PRIORITIZATION','Strategy Initiative Prioritization'),('STRATEGY_FUNDING_APPROVAL','Strategy Funding Approval'),('STRATEGY_CAPACITY_PLANNING','Strategy Capacity Planning'),('STRATEGY_ROADMAP_PLANNING','Strategy Roadmap Planning'),('STRATEGY_STAGE_GATE_REVIEW','Strategy Stage Gate Review'),('STRATEGY_BENEFIT_REALIZATION','Strategy Benefit Realization'),('STRATEGY_PORTFOLIO_REVIEW','Strategy Portfolio Review'),('STRATEGY_SCENARIO_ANALYSIS','Strategy Scenario Analysis'),('STRATEGY_INITIATIVE_RETIREMENT','Strategy Initiative Retirement'),('STRATEGY_GOVERNANCE_APPROVAL','Strategy Governance Approval');
MERGE workflow_definitions AS target USING (SELECT @org organization_id, code, name, 'ai_strategy_portfolio' workflow_type FROM @wf) source ON target.organization_id=source.organization_id AND target.code=source.code WHEN MATCHED THEN UPDATE SET name=source.name, workflow_type=source.workflow_type, status='active', updated_at=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT (organization_id,code,name,workflow_type,status,is_system_workflow) VALUES (source.organization_id,source.code,source.name,source.workflow_type,'active',1);
