export interface SubpageItem {
  id: string
  label: string
}

export interface ModuleItem {
  id: string
  label: string
  subpages: SubpageItem[]
}

export const moduleData: ModuleItem[] = [
  {
    id: 'executive-office',
    label: 'Executive Office',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'executive-assistant', label: 'Executive Assistant' },
      { id: 'organization-health', label: 'Organization Health' },
      { id: 'business-intelligence', label: 'Business Intelligence' },
      { id: 'strategic-recommendations', label: 'Strategic Recommendations' },
      { id: 'revenue-overview', label: 'Revenue Overview' },
      { id: 'cost-overview', label: 'Cost Overview' },
      { id: 'growth-forecast', label: 'Growth Forecast' },
      { id: 'risk-center', label: 'Risk Center' },
      { id: 'daily-executive-brief', label: 'Daily Executive Brief' },
      { id: 'kpi-center', label: 'KPI Center' },
      { id: 'executive-reports', label: 'Executive Reports' },
      { id: 'ai-business-advisor', label: 'AI Business Advisor' },
      { id: 'investment-recommendations', label: 'Investment Recommendations' },
      { id: 'platform-performance', label: 'Platform Performance' },
      { id: 'ai-utilization', label: 'AI Utilization' },
      { id: 'opportunity-center', label: 'Opportunity Center' },
      { id: 'decision-center', label: 'Decision Center' },
    ],
  },
  {
    id: 'organization-management',
    label: 'Organization Management',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'organizations', label: 'Organizations' },
      { id: 'business-units', label: 'Business Units' },
      { id: 'departments', label: 'Departments' },
      { id: 'teams', label: 'Teams' },
      { id: 'office-locations', label: 'Office Locations' },
      { id: 'regional-settings', label: 'Regional Settings' },
      { id: 'fiscal-calendar', label: 'Fiscal Calendar' },
      { id: 'subscription-management', label: 'Subscription Management' },
      { id: 'billing-invoicing', label: 'Billing & Invoicing' },
      { id: 'license-management', label: 'License Management' },
      { id: 'tenant-management', label: 'Tenant Management' },
      { id: 'organization-settings', label: 'Organization Settings' },
      { id: 'usage-limits', label: 'Usage Limits' },
      { id: 'credit-management', label: 'Credit Management' },
      { id: 'plan-management', label: 'Plan Management' },
      { id: 'organization-audit', label: 'Organization Audit' },
    ],
  },
  {
    id: 'brand-management',
    label: 'Brand Management',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'brands', label: 'Brands' },
      { id: 'brand-guidelines', label: 'Brand Guidelines' },
      { id: 'brand-voice', label: 'Brand Voice' },
      { id: 'brand-personality', label: 'Brand Personality' },
      { id: 'brand-assets', label: 'Brand Assets' },
      { id: 'logos', label: 'Logos' },
      { id: 'color-palettes', label: 'Color Palettes' },
      { id: 'typography', label: 'Typography' },
      { id: 'brand-templates', label: 'Brand Templates' },
      { id: 'brand-approval', label: 'Brand Approval' },
      { id: 'tone-rules', label: 'Tone Rules' },
      { id: 'visual-identity', label: 'Visual Identity' },
      { id: 'brand-channels', label: 'Brand Channels' },
      { id: 'brand-campaigns', label: 'Brand Campaigns' },
      { id: 'brand-performance', label: 'Brand Performance' },
      { id: 'brand-compliance', label: 'Brand Compliance' },
    ],
  },
  {
    id: 'channel-management',
    label: 'Channel Management',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'youtube-channels', label: 'YouTube Channels' },
      { id: 'facebook-pages', label: 'Facebook Pages' },
      { id: 'tiktok-accounts', label: 'TikTok Accounts' },
      { id: 'instagram-accounts', label: 'Instagram Accounts' },
      { id: 'linkedin-pages', label: 'LinkedIn Pages' },
      { id: 'x-accounts', label: 'X Accounts' },
      { id: 'threads-accounts', label: 'Threads Accounts' },
      { id: 'pinterest-accounts', label: 'Pinterest Accounts' },
      { id: 'podcast-channels', label: 'Podcast Channels' },
      { id: 'websites', label: 'Websites' },
      { id: 'wordpress-sites', label: 'WordPress Sites' },
      { id: 'medium-accounts', label: 'Medium Accounts' },
      { id: 'ghost-sites', label: 'Ghost Sites' },
      { id: 'channel-connections', label: 'Channel Connections' },
      { id: 'api-connections', label: 'API Connections' },
      { id: 'channel-health', label: 'Channel Health' },
      { id: 'channel-analytics', label: 'Channel Analytics' },
      { id: 'posting-rules', label: 'Posting Rules' },
      { id: 'channel-permissions', label: 'Channel Permissions' },
    ],
  },
  {
    id: 'research-intelligence',
    label: 'Research Intelligence',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'trend-discovery', label: 'Trend Discovery' },
      { id: 'google-trends', label: 'Google Trends' },
      { id: 'youtube-trends', label: 'YouTube Trends' },
      { id: 'tiktok-trends', label: 'TikTok Trends' },
      { id: 'facebook-trends', label: 'Facebook Trends' },
      { id: 'x-trends', label: 'X Trends' },
      { id: 'reddit-intelligence', label: 'Reddit Intelligence' },
      { id: 'quora-intelligence', label: 'Quora Intelligence' },
      { id: 'news-intelligence', label: 'News Intelligence' },
      { id: 'industry-reports', label: 'Industry Reports' },
      { id: 'market-research', label: 'Market Research' },
      { id: 'competitor-intelligence', label: 'Competitor Intelligence' },
      { id: 'audience-research', label: 'Audience Research' },
      { id: 'keyword-research', label: 'Keyword Research' },
      { id: 'opportunity-finder', label: 'Opportunity Finder' },
      { id: 'topic-discovery', label: 'Topic Discovery' },
      { id: 'niche-research', label: 'Niche Research' },
      { id: 'question-research', label: 'Question Research' },
      { id: 'consumer-behavior', label: 'Consumer Behavior' },
      { id: 'gap-analysis', label: 'Gap Analysis' },
      { id: 'viral-analysis', label: 'Viral Analysis' },
      { id: 'source-management', label: 'Source Management' },
      { id: 'research-archive', label: 'Research Archive' },
    ],
  },
  {
    id: 'content-strategy',
    label: 'Content Strategy',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'content-calendar', label: 'Content Calendar' },
      { id: 'editorial-calendar', label: 'Editorial Calendar' },
      { id: 'campaign-planner', label: 'Campaign Planner' },
      { id: 'topic-planner', label: 'Topic Planner' },
      { id: 'content-roadmap', label: 'Content Roadmap' },
      { id: 'publishing-timeline', label: 'Publishing Timeline' },
      { id: 'seasonal-planner', label: 'Seasonal Planner' },
      { id: 'evergreen-planner', label: 'Evergreen Planner' },
      { id: 'content-goals', label: 'Content Goals' },
      { id: 'ai-recommendations', label: 'AI Recommendations' },
      { id: 'niche-strategy', label: 'Niche Strategy' },
      { id: 'platform-strategy', label: 'Platform Strategy' },
      { id: 'audience-strategy', label: 'Audience Strategy' },
      { id: 'content-pillars', label: 'Content Pillars' },
      { id: 'content-formats', label: 'Content Formats' },
      { id: 'series-planner', label: 'Series Planner' },
      { id: 'content-prioritization', label: 'Content Prioritization' },
      { id: 'strategy-reports', label: 'Strategy Reports' },
    ],
  },
  {
    id: 'content-production',
    label: 'Content Production',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'content-requests', label: 'Content Requests' },
      { id: 'ideas-inbox', label: 'Ideas Inbox' },
      { id: 'script-generator', label: 'Script Generator' },
      { id: 'script-library', label: 'Script Library' },
      { id: 'story-builder', label: 'Story Builder' },
      { id: 'storyboard', label: 'Storyboard' },
      { id: 'outline-builder', label: 'Outline Builder' },
      { id: 'article-generator', label: 'Article Generator' },
      { id: 'blog-generator', label: 'Blog Generator' },
      { id: 'newsletter-generator', label: 'Newsletter Generator' },
      { id: 'podcast-scripts', label: 'Podcast Scripts' },
      { id: 'book-generator', label: 'Book Generator' },
      { id: 'course-generator', label: 'Course Generator' },
      { id: 'social-post-generator', label: 'Social Post Generator' },
      { id: 'caption-generator', label: 'Caption Generator' },
      { id: 'email-copy-generator', label: 'Email Copy Generator' },
      { id: 'ad-copy-generator', label: 'Ad Copy Generator' },
      { id: 'translation', label: 'Translation' },
      { id: 'localization', label: 'Localization' },
      { id: 'fact-checker', label: 'Fact Checker' },
      { id: 'citation-manager', label: 'Citation Manager' },
      { id: 'plagiarism-detection', label: 'Plagiarism Detection' },
      { id: 'readability-checker', label: 'Readability Checker' },
      { id: 'ai-content-review', label: 'AI Content Review' },
      { id: 'content-approval', label: 'Content Approval' },
    ],
  },
  {
    id: 'creative-studio',
    label: 'Creative Studio',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'thumbnail-designer', label: 'Thumbnail Designer' },
      { id: 'image-generator', label: 'Image Generator' },
      { id: 'illustration-generator', label: 'Illustration Generator' },
      { id: 'infographic-generator', label: 'Infographic Generator' },
      { id: 'character-studio', label: 'Character Studio' },
      { id: 'avatar-studio', label: 'Avatar Studio' },
      { id: 'background-generator', label: 'Background Generator' },
      { id: 'banner-designer', label: 'Banner Designer' },
      { id: 'logo-designer', label: 'Logo Designer' },
      { id: 'social-graphics', label: 'Social Graphics' },
      { id: 'carousel-designer', label: 'Carousel Designer' },
      { id: 'poster-designer', label: 'Poster Designer' },
      { id: 'presentation-designer', label: 'Presentation Designer' },
      { id: 'creative-templates', label: 'Creative Templates' },
      { id: 'prompt-to-image', label: 'Prompt to Image' },
      { id: 'image-editor', label: 'Image Editor' },
      { id: 'image-upscaler', label: 'Image Upscaler' },
      { id: 'brand-visuals', label: 'Brand Visuals' },
      { id: 'creative-approval', label: 'Creative Approval' },
    ],
  },
  {
    id: 'video-studio',
    label: 'Video Studio',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'video-projects', label: 'Video Projects' },
      { id: 'storyboard-manager', label: 'Storyboard Manager' },
      { id: 'scene-builder', label: 'Scene Builder' },
      { id: 'video-generator', label: 'Video Generator' },
      { id: 'video-editor', label: 'Video Editor' },
      { id: 'motion-graphics', label: 'Motion Graphics' },
      { id: 'animation-studio', label: 'Animation Studio' },
      { id: 'shorts-generator', label: 'Shorts Generator' },
      { id: 'long-form-videos', label: 'Long Form Videos' },
      { id: 'documentary-builder', label: 'Documentary Builder' },
      { id: 'whiteboard-videos', label: 'Whiteboard Videos' },
      { id: 'cinematic-studio', label: 'Cinematic Studio' },
      { id: 'caption-generator', label: 'Caption Generator' },
      { id: 'subtitle-manager', label: 'Subtitle Manager' },
      { id: 'b-roll-manager', label: 'B-roll Manager' },
      { id: 'intro-outro-builder', label: 'Intro/Outro Builder' },
      { id: 'lower-thirds', label: 'Lower Thirds' },
      { id: 'video-templates', label: 'Video Templates' },
      { id: 'render-queue', label: 'Render Queue' },
      { id: 'render-history', label: 'Render History' },
      { id: 'quality-review', label: 'Quality Review' },
      { id: 'video-archive', label: 'Video Archive' },
    ],
  },
  {
    id: 'audio-voice-studio',
    label: 'Audio & Voice Studio',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'voice-library', label: 'Voice Library' },
      { id: 'voice-generator', label: 'Voice Generator' },
      { id: 'voice-cloning', label: 'Voice Cloning' },
      { id: 'narration-studio', label: 'Narration Studio' },
      { id: 'dubbing', label: 'Dubbing' },
      { id: 'translation-voices', label: 'Translation Voices' },
      { id: 'music-library', label: 'Music Library' },
      { id: 'sound-effects', label: 'Sound Effects' },
      { id: 'audio-cleanup', label: 'Audio Cleanup' },
      { id: 'audio-mastering', label: 'Audio Mastering' },
      { id: 'podcast-production', label: 'Podcast Production' },
      { id: 'pronunciation-manager', label: 'Pronunciation Manager' },
      { id: 'accent-control', label: 'Accent Control' },
      { id: 'emotion-control', label: 'Emotion Control' },
      { id: 'audio-templates', label: 'Audio Templates' },
      { id: 'background-music', label: 'Background Music' },
      { id: 'audio-licensing', label: 'Audio Licensing' },
      { id: 'audio-archive', label: 'Audio Archive' },
    ],
  },
  {
    id: 'seo-intelligence',
    label: 'SEO Intelligence',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'keyword-optimizer', label: 'Keyword Optimizer' },
      { id: 'title-optimizer', label: 'Title Optimizer' },
      { id: 'description-generator', label: 'Description Generator' },
      { id: 'tags-generator', label: 'Tags Generator' },
      { id: 'hashtag-generator', label: 'Hashtag Generator' },
      { id: 'search-ranking', label: 'Search Ranking' },
      { id: 'competitor-seo', label: 'Competitor SEO' },
      { id: 'backlink-opportunities', label: 'Backlink Opportunities' },
      { id: 'content-optimization', label: 'Content Optimization' },
      { id: 'readability-analysis', label: 'Readability Analysis' },
      { id: 'serp-monitoring', label: 'SERP Monitoring' },
      { id: 'seo-audit', label: 'SEO Audit' },
      { id: 'metadata-manager', label: 'Metadata Manager' },
      { id: 'platform-seo', label: 'Platform SEO' },
      { id: 'youtube-seo', label: 'YouTube SEO' },
      { id: 'blog-seo', label: 'Blog SEO' },
      { id: 'social-seo', label: 'Social SEO' },
      { id: 'seo-reports', label: 'SEO Reports' },
    ],
  },
  {
    id: 'publishing-center',
    label: 'Publishing Center',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'draft-queue', label: 'Draft Queue' },
      { id: 'approval-queue', label: 'Approval Queue' },
      { id: 'scheduled-posts', label: 'Scheduled Posts' },
      { id: 'publishing-queue', label: 'Publishing Queue' },
      { id: 'live-publishing', label: 'Live Publishing' },
      { id: 'failed-publications', label: 'Failed Publications' },
      { id: 'cross-platform-publishing', label: 'Cross-platform Publishing' },
      { id: 'publishing-history', label: 'Publishing History' },
      { id: 'content-archive', label: 'Content Archive' },
      { id: 'platform-rules', label: 'Platform Rules' },
      { id: 'publishing-calendar', label: 'Publishing Calendar' },
      { id: 'bulk-publishing', label: 'Bulk Publishing' },
      { id: 'retry-center', label: 'Retry Center' },
      { id: 'publishing-logs', label: 'Publishing Logs' },
      { id: 'publishing-approval', label: 'Publishing Approval' },
      { id: 'content-status', label: 'Content Status' },
      { id: 'publishing-analytics', label: 'Publishing Analytics' },
    ],
  },
  {
    id: 'marketing-automation',
    label: 'Marketing Automation',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'campaign-manager', label: 'Campaign Manager' },
      { id: 'email-campaigns', label: 'Email Campaigns' },
      { id: 'newsletter-manager', label: 'Newsletter Manager' },
      { id: 'social-campaigns', label: 'Social Campaigns' },
      { id: 'landing-pages', label: 'Landing Pages' },
      { id: 'cta-manager', label: 'CTA Manager' },
      { id: 'lead-generation', label: 'Lead Generation' },
      { id: 'affiliate-campaigns', label: 'Affiliate Campaigns' },
      { id: 'referral-campaigns', label: 'Referral Campaigns' },
      { id: 'promotional-calendar', label: 'Promotional Calendar' },
      { id: 'funnel-builder', label: 'Funnel Builder' },
      { id: 'audience-segments', label: 'Audience Segments' },
      { id: 'retargeting', label: 'Retargeting' },
      { id: 'influencer-outreach', label: 'Influencer Outreach' },
      { id: 'campaign-automation', label: 'Campaign Automation' },
      { id: 'campaign-analytics', label: 'Campaign Analytics' },
      { id: 'marketing-reports', label: 'Marketing Reports' },
    ],
  },
  {
    id: 'community-management',
    label: 'Community Management',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'comments', label: 'Comments' },
      { id: 'replies', label: 'Replies' },
      { id: 'direct-messages', label: 'Direct Messages' },
      { id: 'community-inbox', label: 'Community Inbox' },
      { id: 'spam-moderation', label: 'Spam Moderation' },
      { id: 'sentiment-analysis', label: 'Sentiment Analysis' },
      { id: 'engagement-reports', label: 'Engagement Reports' },
      { id: 'audience-feedback', label: 'Audience Feedback' },
      { id: 'faq-automation', label: 'FAQ Automation' },
      { id: 'moderation-rules', label: 'Moderation Rules' },
      { id: 'pinned-comments', label: 'Pinned Comments' },
      { id: 'auto-responses', label: 'Auto Responses' },
      { id: 'complaint-management', label: 'Complaint Management' },
      { id: 'community-health', label: 'Community Health' },
      { id: 'audience-questions', label: 'Audience Questions' },
      { id: 'community-reports', label: 'Community Reports' },
    ],
  },
  {
    id: 'monetization-center',
    label: 'Monetization Center',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'ad-revenue', label: 'Ad Revenue' },
      { id: 'adsense', label: 'AdSense' },
      { id: 'affiliate-revenue', label: 'Affiliate Revenue' },
      { id: 'sponsorships', label: 'Sponsorships' },
      { id: 'memberships', label: 'Memberships' },
      { id: 'digital-products', label: 'Digital Products' },
      { id: 'course-sales', label: 'Course Sales' },
      { id: 'merchandise', label: 'Merchandise' },
      { id: 'donations', label: 'Donations' },
      { id: 'consulting-revenue', label: 'Consulting Revenue' },
      { id: 'subscription-revenue', label: 'Subscription Revenue' },
      { id: 'licensing-revenue', label: 'Licensing Revenue' },
      { id: 'revenue-forecasting', label: 'Revenue Forecasting' },
      { id: 'revenue-attribution', label: 'Revenue Attribution' },
      { id: 'payout-tracking', label: 'Payout Tracking' },
      { id: 'pricing-intelligence', label: 'Pricing Intelligence' },
      { id: 'monetization-opportunities', label: 'Monetization Opportunities' },
      { id: 'financial-reports', label: 'Financial Reports' },
    ],
  },
  {
    id: 'analytics-intelligence',
    label: 'Analytics & Intelligence',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'channel-analytics', label: 'Channel Analytics' },
      { id: 'audience-analytics', label: 'Audience Analytics' },
      { id: 'content-analytics', label: 'Content Analytics' },
      { id: 'revenue-analytics', label: 'Revenue Analytics' },
      { id: 'watch-time', label: 'Watch Time' },
      { id: 'retention-analysis', label: 'Retention Analysis' },
      { id: 'ctr-analysis', label: 'CTR Analysis' },
      { id: 'conversion-analytics', label: 'Conversion Analytics' },
      { id: 'trend-reports', label: 'Trend Reports' },
      { id: 'predictive-analytics', label: 'Predictive Analytics' },
      { id: 'ai-insights', label: 'AI Insights' },
      { id: 'cohort-analysis', label: 'Cohort Analysis' },
      { id: 'platform-comparison', label: 'Platform Comparison' },
      { id: 'performance-scorecards', label: 'Performance Scorecards' },
      { id: 'funnel-analytics', label: 'Funnel Analytics' },
      { id: 'growth-analytics', label: 'Growth Analytics' },
      { id: 'anomaly-detection', label: 'Anomaly Detection' },
      { id: 'custom-analytics', label: 'Custom Analytics' },
    ],
  },
  {
    id: 'ai-learning-center',
    label: 'AI Learning Center',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'learning-models', label: 'Learning Models' },
      { id: 'feedback-loop', label: 'Feedback Loop' },
      { id: 'reinforcement-learning', label: 'Reinforcement Learning' },
      { id: 'prompt-optimization', label: 'Prompt Optimization' },
      { id: 'agent-performance', label: 'Agent Performance' },
      { id: 'best-practices', label: 'Best Practices' },
      { id: 'knowledge-extraction', label: 'Knowledge Extraction' },
      { id: 'continuous-improvement', label: 'Continuous Improvement' },
      { id: 'performance-learning', label: 'Performance Learning' },
      { id: 'thumbnail-learning', label: 'Thumbnail Learning' },
      { id: 'title-learning', label: 'Title Learning' },
      { id: 'hook-learning', label: 'Hook Learning' },
      { id: 'timing-learning', label: 'Timing Learning' },
      { id: 'audience-learning', label: 'Audience Learning' },
      { id: 'model-evaluation', label: 'Model Evaluation' },
      { id: 'learning-reports', label: 'Learning Reports' },
    ],
  },
  {
    id: 'ai-agents',
    label: 'AI Agents',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'agent-marketplace', label: 'Agent Marketplace' },
      { id: 'executive-agents', label: 'Executive Agents' },
      { id: 'research-agents', label: 'Research Agents' },
      { id: 'writing-agents', label: 'Writing Agents' },
      { id: 'creative-agents', label: 'Creative Agents' },
      { id: 'video-agents', label: 'Video Agents' },
      { id: 'audio-agents', label: 'Audio Agents' },
      { id: 'publishing-agents', label: 'Publishing Agents' },
      { id: 'marketing-agents', label: 'Marketing Agents' },
      { id: 'revenue-agents', label: 'Revenue Agents' },
      { id: 'analytics-agents', label: 'Analytics Agents' },
      { id: 'compliance-agents', label: 'Compliance Agents' },
      { id: 'agent-workflows', label: 'Agent Workflows' },
      { id: 'agent-monitoring', label: 'Agent Monitoring' },
      { id: 'agent-logs', label: 'Agent Logs' },
      { id: 'agent-prompts', label: 'Agent Prompts' },
      { id: 'agent-tools', label: 'Agent Tools' },
      { id: 'agent-permissions', label: 'Agent Permissions' },
      { id: 'agent-costs', label: 'Agent Costs' },
      { id: 'agent-testing', label: 'Agent Testing' },
    ],
  },
  {
    id: 'workflow-automation',
    label: 'Workflow Automation',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'workflow-designer', label: 'Workflow Designer' },
      { id: 'approval-workflows', label: 'Approval Workflows' },
      { id: 'ai-workflows', label: 'AI Workflows' },
      { id: 'automation-rules', label: 'Automation Rules' },
      { id: 'triggers', label: 'Triggers' },
      { id: 'actions', label: 'Actions' },
      { id: 'scheduled-jobs', label: 'Scheduled Jobs' },
      { id: 'queue-monitor', label: 'Queue Monitor' },
      { id: 'workflow-logs', label: 'Workflow Logs' },
      { id: 'workflow-templates', label: 'Workflow Templates' },
      { id: 'workflow-versions', label: 'Workflow Versions' },
      { id: 'workflow-testing', label: 'Workflow Testing' },
      { id: 'workflow-permissions', label: 'Workflow Permissions' },
      { id: 'failed-workflows', label: 'Failed Workflows' },
      { id: 'retry-rules', label: 'Retry Rules' },
      { id: 'workflow-reports', label: 'Workflow Reports' },
    ],
  },
  {
    id: 'digital-asset-management',
    label: 'Digital Asset Management',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'image-library', label: 'Image Library' },
      { id: 'video-library', label: 'Video Library' },
      { id: 'audio-library', label: 'Audio Library' },
      { id: 'script-library', label: 'Script Library' },
      { id: 'templates', label: 'Templates' },
      { id: 'brand-assets', label: 'Brand Assets' },
      { id: 'fonts', label: 'Fonts' },
      { id: 'icons', label: 'Icons' },
      { id: 'ai-prompts', label: 'AI Prompts' },
      { id: 'stock-library', label: 'Stock Library' },
      { id: 'upload-center', label: 'Upload Center' },
      { id: 'asset-versions', label: 'Asset Versions' },
      { id: 'asset-search', label: 'Asset Search' },
      { id: 'asset-permissions', label: 'Asset Permissions' },
      { id: 'license-tracking', label: 'License Tracking' },
      { id: 'duplicate-detection', label: 'Duplicate Detection' },
      { id: 'asset-tags', label: 'Asset Tags' },
      { id: 'asset-usage', label: 'Asset Usage' },
      { id: 'asset-approval', label: 'Asset Approval' },
      { id: 'asset-archive', label: 'Asset Archive' },
    ],
  },
  {
    id: 'knowledge-hub',
    label: 'Knowledge Hub',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'knowledge-graph', label: 'Knowledge Graph' },
      { id: 'research-database', label: 'Research Database' },
      { id: 'ai-memory', label: 'AI Memory' },
      { id: 'topic-library', label: 'Topic Library' },
      { id: 'entity-library', label: 'Entity Library' },
      { id: 'prompt-library', label: 'Prompt Library' },
      { id: 'documentation', label: 'Documentation' },
      { id: 'sops', label: 'SOPs' },
      { id: 'playbooks', label: 'Playbooks' },
      { id: 'training-center', label: 'Training Center' },
      { id: 'source-library', label: 'Source Library' },
      { id: 'fact-library', label: 'Fact Library' },
      { id: 'citation-library', label: 'Citation Library' },
      { id: 'glossary', label: 'Glossary' },
      { id: 'taxonomy', label: 'Taxonomy' },
      { id: 'knowledge-review', label: 'Knowledge Review' },
      { id: 'knowledge-reports', label: 'Knowledge Reports' },
    ],
  },
  {
    id: 'integrations',
    label: 'Integrations',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'ai-providers', label: 'AI Providers' },
      { id: 'social-platforms', label: 'Social Platforms' },
      { id: 'storage-providers', label: 'Storage Providers' },
      { id: 'cloud-services', label: 'Cloud Services' },
      { id: 'cms-integrations', label: 'CMS Integrations' },
      { id: 'crm-integrations', label: 'CRM Integrations' },
      { id: 'erp-integrations', label: 'ERP Integrations' },
      { id: 'email-services', label: 'Email Services' },
      { id: 'webhooks', label: 'Webhooks' },
      { id: 'api-keys', label: 'API Keys' },
      { id: 'oauth-management', label: 'OAuth Management' },
      { id: 'payment-gateways', label: 'Payment Gateways' },
      { id: 'analytics-integrations', label: 'Analytics Integrations' },
      { id: 'video-providers', label: 'Video Providers' },
      { id: 'voice-providers', label: 'Voice Providers' },
      { id: 'image-providers', label: 'Image Providers' },
      { id: 'integration-logs', label: 'Integration Logs' },
      { id: 'connection-health', label: 'Connection Health' },
      { id: 'integration-settings', label: 'Integration Settings' },
    ],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'notification-center', label: 'Notification Center' },
      { id: 'alerts', label: 'Alerts' },
      { id: 'ai-recommendations', label: 'AI Recommendations' },
      { id: 'system-messages', label: 'System Messages' },
      { id: 'approval-requests', label: 'Approval Requests' },
      { id: 'failed-jobs', label: 'Failed Jobs' },
      { id: 'scheduled-notifications', label: 'Scheduled Notifications' },
      { id: 'email-notifications', label: 'Email Notifications' },
      { id: 'push-notifications', label: 'Push Notifications' },
      { id: 'in-app-notifications', label: 'In-App Notifications' },
      { id: 'notification-rules', label: 'Notification Rules' },
      { id: 'notification-templates', label: 'Notification Templates' },
      { id: 'escalation-rules', label: 'Escalation Rules' },
      { id: 'notification-history', label: 'Notification History' },
      { id: 'notification-settings', label: 'Notification Settings' },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'executive-reports', label: 'Executive Reports' },
      { id: 'research-reports', label: 'Research Reports' },
      { id: 'content-reports', label: 'Content Reports' },
      { id: 'seo-reports', label: 'SEO Reports' },
      { id: 'marketing-reports', label: 'Marketing Reports' },
      { id: 'revenue-reports', label: 'Revenue Reports' },
      { id: 'ai-performance-reports', label: 'AI Performance Reports' },
      { id: 'compliance-reports', label: 'Compliance Reports' },
      { id: 'custom-reports', label: 'Custom Reports' },
      { id: 'report-scheduler', label: 'Report Scheduler' },
      { id: 'report-builder', label: 'Report Builder' },
      { id: 'report-templates', label: 'Report Templates' },
      { id: 'exported-reports', label: 'Exported Reports' },
      { id: 'scheduled-delivery', label: 'Scheduled Delivery' },
      { id: 'report-permissions', label: 'Report Permissions' },
    ],
  },
  {
    id: 'compliance-governance',
    label: 'Compliance & Governance',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'copyright-management', label: 'Copyright Management' },
      { id: 'license-management', label: 'License Management' },
      { id: 'ai-usage-policies', label: 'AI Usage Policies' },
      { id: 'content-moderation', label: 'Content Moderation' },
      { id: 'privacy-compliance', label: 'Privacy Compliance' },
      { id: 'data-retention', label: 'Data Retention' },
      { id: 'audit-logs', label: 'Audit Logs' },
      { id: 'legal-documents', label: 'Legal Documents' },
      { id: 'policy-center', label: 'Policy Center' },
      { id: 'platform-policy-checks', label: 'Platform Policy Checks' },
      { id: 'plagiarism-review', label: 'Plagiarism Review' },
      { id: 'source-verification', label: 'Source Verification' },
      { id: 'consent-management', label: 'Consent Management' },
      { id: 'data-processing', label: 'Data Processing' },
      { id: 'takedown-requests', label: 'Takedown Requests' },
      { id: 'compliance-approval', label: 'Compliance Approval' },
      { id: 'governance-reports', label: 'Governance Reports' },
    ],
  },
  {
    id: 'security-center',
    label: 'Security Center',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'users', label: 'Users' },
      { id: 'roles', label: 'Roles' },
      { id: 'permissions', label: 'Permissions' },
      { id: 'teams', label: 'Teams' },
      { id: 'single-sign-on', label: 'Single Sign-On' },
      { id: 'multi-factor-authentication', label: 'Multi-Factor Authentication' },
      { id: 'api-security', label: 'API Security' },
      { id: 'secrets-manager', label: 'Secrets Manager' },
      { id: 'session-management', label: 'Session Management' },
      { id: 'access-logs', label: 'Access Logs' },
      { id: 'security-events', label: 'Security Events' },
      { id: 'password-policies', label: 'Password Policies' },
      { id: 'login-history', label: 'Login History' },
      { id: 'device-management', label: 'Device Management' },
      { id: 'ip-allowlist', label: 'IP Allowlist' },
      { id: 'threat-monitoring', label: 'Threat Monitoring' },
      { id: 'permission-audit', label: 'Permission Audit' },
      { id: 'security-reports', label: 'Security Reports' },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'system-settings', label: 'System Settings' },
      { id: 'organization-settings', label: 'Organization Settings' },
      { id: 'ai-configuration', label: 'AI Configuration' },
      { id: 'default-templates', label: 'Default Templates' },
      { id: 'theme-manager', label: 'Theme Manager' },
      { id: 'localization', label: 'Localization' },
      { id: 'time-zones', label: 'Time Zones' },
      { id: 'storage-management', label: 'Storage Management' },
      { id: 'queue-management', label: 'Queue Management' },
      { id: 'cache-management', label: 'Cache Management' },
      { id: 'backup-restore', label: 'Backup & Restore' },
      { id: 'system-maintenance', label: 'System Maintenance' },
      { id: 'environment-settings', label: 'Environment Settings' },
      { id: 'feature-flags', label: 'Feature Flags' },
      { id: 'audit-settings', label: 'Audit Settings' },
      { id: 'cost-settings', label: 'Cost Settings' },
      { id: 'billing-settings', label: 'Billing Settings' },
      { id: 'admin-logs', label: 'Admin Logs' },
    ],
  },
  {
    id: 'developer-center',
    label: 'Developer Center',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'api-explorer', label: 'API Explorer' },
      { id: 'sdks', label: 'SDKs' },
      { id: 'webhooks', label: 'Webhooks' },
      { id: 'event-bus', label: 'Event Bus' },
      { id: 'plugin-marketplace', label: 'Plugin Marketplace' },
      { id: 'extensions', label: 'Extensions' },
      { id: 'custom-ai-agents', label: 'Custom AI Agents' },
      { id: 'prompt-templates', label: 'Prompt Templates' },
      { id: 'developer-documentation', label: 'Developer Documentation' },
      { id: 'sandbox', label: 'Sandbox' },
      { id: 'api-monitoring', label: 'API Monitoring' },
      { id: 'api-logs', label: 'API Logs' },
      { id: 'app-registration', label: 'App Registration' },
      { id: 'developer-keys', label: 'Developer Keys' },
      { id: 'rate-limits', label: 'Rate Limits' },
      { id: 'test-console', label: 'Test Console' },
      { id: 'changelog', label: 'Changelog' },
    ],
  },
  {
    id: 'system-monitoring',
    label: 'System Monitoring',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'operations-dashboard', label: 'Operations Dashboard' },
      { id: 'ai-model-health', label: 'AI Model Health' },
      { id: 'service-health', label: 'Service Health' },
      { id: 'api-status', label: 'API Status' },
      { id: 'queue-status', label: 'Queue Status' },
      { id: 'background-jobs', label: 'Background Jobs' },
      { id: 'render-farm', label: 'Render Farm' },
      { id: 'storage-usage', label: 'Storage Usage' },
      { id: 'cost-monitoring', label: 'Cost Monitoring' },
      { id: 'performance-metrics', label: 'Performance Metrics' },
      { id: 'error-tracking', label: 'Error Tracking' },
      { id: 'audit-timeline', label: 'Audit Timeline' },
      { id: 'uptime-monitoring', label: 'Uptime Monitoring' },
      { id: 'worker-health', label: 'Worker Health' },
      { id: 'scheduler-health', label: 'Scheduler Health' },
      { id: 'database-health', label: 'Database Health' },
      { id: 'logs', label: 'Logs' },
      { id: 'incident-management', label: 'Incident Management' },
    ],
  },
  {
    id: 'help-support',
    label: 'Help & Support',
    subpages: [
      { id: 'dashboard', label: 'Dashboard' },
      { id: 'help-center', label: 'Help Center' },
      { id: 'ai-assistant', label: 'AI Assistant' },
      { id: 'user-guides', label: 'User Guides' },
      { id: 'tutorials', label: 'Tutorials' },
      { id: 'video-academy', label: 'Video Academy' },
      { id: 'knowledge-base', label: 'Knowledge Base' },
      { id: 'release-notes', label: 'Release Notes' },
      { id: 'feature-requests', label: 'Feature Requests' },
      { id: 'support-tickets', label: 'Support Tickets' },
      { id: 'contact-support', label: 'Contact Support' },
      { id: 'onboarding', label: 'Onboarding' },
      { id: 'faqs', label: 'FAQs' },
      { id: 'troubleshooting', label: 'Troubleshooting' },
      { id: 'product-tour', label: 'Product Tour' },
      { id: 'support-reports', label: 'Support Reports' },
    ],
  },
]

export const moduleMap = new Map(moduleData.map((module) => [module.id, module]))
