export const workflowAnalyticsMockData = {
  summary: {},
  intelligenceStatus: {},
  performanceTrend: [],
  categories: [],
  workflowPerformance: [],
  workflowDetails: {},
  bottlenecks: [],
  durationAnalytics: [],
  reliabilityAnalytics: [],
  costAnalytics: [],
  autonomyAnalytics: [],
  slaAnalytics: [],
  finalOutputAnalytics: [],
  agentAnalytics: [],
  approvalAnalytics: [],
  queueAnalytics: [],
  workerAnalytics: [],
  recoveryAnalytics: [],
  predictions: [],
  recommendations: [],
  comparisons: [],
  autonomousDecisions: [],
  businessImpact: [],
}

