export type OpacityVariants = {
  100: string
  90: string
  80: string
  70: string
  60: string
  50: string
  40: string
  30: string
  20: string
  10: string
  5: string
}

export interface ColorToken {
  name: string
  hex: string
  rgb: string
  hsl: string
  opacity: OpacityVariants
  tailwind: string
  cssVariable: string
  figmaVariable: string
  darkEquivalent: string
  contrastOn: string
  accessible: boolean
}

export interface TypographyToken {
  name: string
  fontFamily: string
  fontWeight: number
  fontSize: string
  lineHeight: string
  letterSpacing: string
  paragraphSpacing?: string
}

export interface ShadowToken {
  name: string
  value: string
  description: string
}

export interface RadiusToken {
  name: string
  value: string
}

export interface SpacingToken {
  name: string
  value: string
}

export interface IconToken {
  name: string
  size: number
  strokeWidth: number
  spacing: string
}

export interface BreakpointToken {
  name: string
  minWidth: string
}

const baseOpacity = (hex: string): OpacityVariants => ({
  100: `${hex}FF`,
  90: `${hex}E6`,
  80: `${hex}CC`,
  70: `${hex}B3`,
  60: `${hex}99`,
  50: `${hex}80`,
  40: `${hex}66`,
  30: `${hex}4D`,
  20: `${hex}33`,
  10: `${hex}1A`,
  5: `${hex}0D`,
})

export const colorTokens = {
  primary: {
    50: {
      name: 'Primary 50',
      hex: '#EEF3FF',
      rgb: '238, 243, 255',
      hsl: '223, 100%, 96%',
      opacity: baseOpacity('EEF3FF'),
      tailwind: 'primary-50',
      cssVariable: '--cacs-color-primary-50',
      figmaVariable: 'Primary/50',
      darkEquivalent: '#1F2A56',
      contrastOn: '#0B1F4B',
      accessible: true,
    },
    100: {
      name: 'Primary 100',
      hex: '#E0E9FF',
      rgb: '224, 233, 255',
      hsl: '223, 100%, 92%',
      opacity: baseOpacity('E0E9FF'),
      tailwind: 'primary-100',
      cssVariable: '--cacs-color-primary-100',
      figmaVariable: 'Primary/100',
      darkEquivalent: '#273B6E',
      contrastOn: '#102D65',
      accessible: true,
    },
    300: {
      name: 'Primary 300',
      hex: '#8EA9FF',
      rgb: '142, 169, 255',
      hsl: '226, 100%, 79%',
      opacity: baseOpacity('8EA9FF'),
      tailwind: 'primary-300',
      cssVariable: '--cacs-color-primary-300',
      figmaVariable: 'Primary/300',
      darkEquivalent: '#5A76C9',
      contrastOn: '#071D5F',
      accessible: true,
    },
    500: {
      name: 'Primary 500',
      hex: '#3B5BFF',
      rgb: '59, 91, 255',
      hsl: '227, 100%, 61%',
      opacity: baseOpacity('3B5BFF'),
      tailwind: 'primary-500',
      cssVariable: '--cacs-color-primary-500',
      figmaVariable: 'Primary/500',
      darkEquivalent: '#3661E1',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
    700: {
      name: 'Primary 700',
      hex: '#1332D1',
      rgb: '19, 50, 209',
      hsl: '228, 91%, 45%',
      opacity: baseOpacity('1332D1'),
      tailwind: 'primary-700',
      cssVariable: '--cacs-color-primary-700',
      figmaVariable: 'Primary/700',
      darkEquivalent: '#8EA9FF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  secondary: {
    100: {
      name: 'Secondary 100',
      hex: '#F4F7FF',
      rgb: '244, 247, 255',
      hsl: '221, 100%, 97%',
      opacity: baseOpacity('F4F7FF'),
      tailwind: 'secondary-100',
      cssVariable: '--cacs-color-secondary-100',
      figmaVariable: 'Secondary/100',
      darkEquivalent: '#212B47',
      contrastOn: '#0E1B3B',
      accessible: true,
    },
    300: {
      name: 'Secondary 300',
      hex: '#A9C1FF',
      rgb: '169, 193, 255',
      hsl: '222, 100%, 84%',
      opacity: baseOpacity('A9C1FF'),
      tailwind: 'secondary-300',
      cssVariable: '--cacs-color-secondary-300',
      figmaVariable: 'Secondary/300',
      darkEquivalent: '#6A7FCC',
      contrastOn: '#0E1B3B',
      accessible: true,
    },
    500: {
      name: 'Secondary 500',
      hex: '#6174F0',
      rgb: '97, 116, 240',
      hsl: '229, 87%, 66%',
      opacity: baseOpacity('6174F0'),
      tailwind: 'secondary-500',
      cssVariable: '--cacs-color-secondary-500',
      figmaVariable: 'Secondary/500',
      darkEquivalent: '#8EA9FF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  accent: {
    500: {
      name: 'Accent 500',
      hex: '#D667FF',
      rgb: '214, 103, 255',
      hsl: '286, 100%, 70%',
      opacity: baseOpacity('D667FF'),
      tailwind: 'accent-500',
      cssVariable: '--cacs-color-accent-500',
      figmaVariable: 'Accent/500',
      darkEquivalent: '#C17CFF',
      contrastOn: '#1A053F',
      accessible: true,
    },
  },
  success: {
    500: {
      name: 'Success 500',
      hex: '#1EB980',
      rgb: '30, 185, 128',
      hsl: '163, 72%, 42%',
      opacity: baseOpacity('1EB980'),
      tailwind: 'success-500',
      cssVariable: '--cacs-color-success-500',
      figmaVariable: 'Success/500',
      darkEquivalent: '#1ED0A1',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  warning: {
    500: {
      name: 'Warning 500',
      hex: '#F2B10F',
      rgb: '242, 177, 15',
      hsl: '44, 88%, 50%',
      opacity: baseOpacity('F2B10F'),
      tailwind: 'warning-500',
      cssVariable: '--cacs-color-warning-500',
      figmaVariable: 'Warning/500',
      darkEquivalent: '#F6C751',
      contrastOn: '#1F1A00',
      accessible: true,
    },
  },
  danger: {
    500: {
      name: 'Danger 500',
      hex: '#EF4F5F',
      rgb: '239, 79, 95',
      hsl: '354, 84%, 63%',
      opacity: baseOpacity('EF4F5F'),
      tailwind: 'danger-500',
      cssVariable: '--cacs-color-danger-500',
      figmaVariable: 'Danger/500',
      darkEquivalent: '#FF6E82',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  info: {
    500: {
      name: 'Info 500',
      hex: '#2C90FF',
      rgb: '44, 144, 255',
      hsl: '209, 100%, 59%',
      opacity: baseOpacity('2C90FF'),
      tailwind: 'info-500',
      cssVariable: '--cacs-color-info-500',
      figmaVariable: 'Info/500',
      darkEquivalent: '#61A7FF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  neutral: {
    0: {
      name: 'Neutral 0',
      hex: '#FFFFFF',
      rgb: '255, 255, 255',
      hsl: '0, 0%, 100%',
      opacity: baseOpacity('FFFFFF'),
      tailwind: 'neutral-0',
      cssVariable: '--cacs-color-neutral-0',
      figmaVariable: 'Neutral/0',
      darkEquivalent: '#0B1220',
      contrastOn: '#0B1220',
      accessible: true,
    },
    100: {
      name: 'Neutral 100',
      hex: '#F4F6FB',
      rgb: '244, 246, 251',
      hsl: '219, 48%, 96%',
      opacity: baseOpacity('F4F6FB'),
      tailwind: 'neutral-100',
      cssVariable: '--cacs-color-neutral-100',
      figmaVariable: 'Neutral/100',
      darkEquivalent: '#111827',
      contrastOn: '#0B1220',
      accessible: true,
    },
    300: {
      name: 'Neutral 300',
      hex: '#B9C1D9',
      rgb: '185, 193, 217',
      hsl: '220, 26%, 78%',
      opacity: baseOpacity('B9C1D9'),
      tailwind: 'neutral-300',
      cssVariable: '--cacs-color-neutral-300',
      figmaVariable: 'Neutral/300',
      darkEquivalent: '#4F5C7A',
      contrastOn: '#0B1220',
      accessible: true,
    },
    500: {
      name: 'Neutral 500',
      hex: '#6F7C9A',
      rgb: '111, 124, 154',
      hsl: '222, 16%, 52%',
      opacity: baseOpacity('6F7C9A'),
      tailwind: 'neutral-500',
      cssVariable: '--cacs-color-neutral-500',
      figmaVariable: 'Neutral/500',
      darkEquivalent: '#B4BFE1',
      contrastOn: '#0B1220',
      accessible: true,
    },
    800: {
      name: 'Neutral 800',
      hex: '#1B2440',
      rgb: '27, 36, 64',
      hsl: '224, 42%, 17%',
      opacity: baseOpacity('1B2440'),
      tailwind: 'neutral-800',
      cssVariable: '--cacs-color-neutral-800',
      figmaVariable: 'Neutral/800',
      darkEquivalent: '#E8EDF9',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  surface: {
    background: {
      name: 'Surface Background',
      hex: '#FFFFFF',
      rgb: '255, 255, 255',
      hsl: '0, 0%, 100%',
      opacity: baseOpacity('FFFFFF'),
      tailwind: 'surface-background',
      cssVariable: '--cacs-color-surface-background',
      figmaVariable: 'Surface/Background',
      darkEquivalent: '#0C152E',
      contrastOn: '#0B1220',
      accessible: true,
    },
    level1: {
      name: 'Surface Level 1',
      hex: '#F8FAFF',
      rgb: '248, 250, 255',
      hsl: '221, 100%, 98%',
      opacity: baseOpacity('F8FAFF'),
      tailwind: 'surface-level-1',
      cssVariable: '--cacs-color-surface-level-1',
      figmaVariable: 'Surface/Level 1',
      darkEquivalent: '#141C33',
      contrastOn: '#0B1220',
      accessible: true,
    },
    level2: {
      name: 'Surface Level 2',
      hex: '#EEF3FF',
      rgb: '238, 243, 255',
      hsl: '223, 100%, 96%',
      opacity: baseOpacity('EEF3FF'),
      tailwind: 'surface-level-2',
      cssVariable: '--cacs-color-surface-level-2',
      figmaVariable: 'Surface/Level 2',
      darkEquivalent: '#192545',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  border: {
    subtle: {
      name: 'Border Subtle',
      hex: '#E1E8FF',
      rgb: '225, 232, 255',
      hsl: '223, 100%, 93%',
      opacity: baseOpacity('E1E8FF'),
      tailwind: 'border-subtle',
      cssVariable: '--cacs-color-border-subtle',
      figmaVariable: 'Border/Subtle',
      darkEquivalent: '#2C3D72',
      contrastOn: '#0B1220',
      accessible: true,
    },
    strong: {
      name: 'Border Strong',
      hex: '#BAC2E3',
      rgb: '186, 194, 227',
      hsl: '221, 45%, 80%',
      opacity: baseOpacity('BAC2E3'),
      tailwind: 'border-strong',
      cssVariable: '--cacs-color-border-strong',
      figmaVariable: 'Border/Strong',
      darkEquivalent: '#3F5598',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  state: {
    hover: {
      name: 'State Hover',
      hex: '#E8EDFF',
      rgb: '232, 237, 255',
      hsl: '223, 100%, 95%',
      opacity: baseOpacity('E8EDFF'),
      tailwind: 'state-hover',
      cssVariable: '--cacs-color-state-hover',
      figmaVariable: 'State/Hover',
      darkEquivalent: '#1E2B58',
      contrastOn: '#0B1220',
      accessible: true,
    },
    focus: {
      name: 'State Focus',
      hex: '#C7D4FF',
      rgb: '199, 212, 255',
      hsl: '224, 100%, 90%',
      opacity: baseOpacity('C7D4FF'),
      tailwind: 'state-focus',
      cssVariable: '--cacs-color-state-focus',
      figmaVariable: 'State/Focus',
      darkEquivalent: '#30479C',
      contrastOn: '#0B1220',
      accessible: true,
    },
    selected: {
      name: 'State Selected',
      hex: '#D6E4FF',
      rgb: '214, 228, 255',
      hsl: '223, 100%, 92%',
      opacity: baseOpacity('D6E4FF'),
      tailwind: 'state-selected',
      cssVariable: '--cacs-color-state-selected',
      figmaVariable: 'State/Selected',
      darkEquivalent: '#2A3F7C',
      contrastOn: '#0B1220',
      accessible: true,
    },
    disabled: {
      name: 'State Disabled',
      hex: '#D9E1F5',
      rgb: '217, 225, 245',
      hsl: '219, 54%, 90%',
      opacity: baseOpacity('D9E1F5'),
      tailwind: 'state-disabled',
      cssVariable: '--cacs-color-state-disabled',
      figmaVariable: 'State/Disabled',
      darkEquivalent: '#2A3156',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  chart: {
    blue: {
      name: 'Chart Blue',
      hex: '#4D7BFF',
      rgb: '77, 123, 255',
      hsl: '223, 100%, 65%',
      opacity: baseOpacity('4D7BFF'),
      tailwind: 'chart-blue',
      cssVariable: '--cacs-color-chart-blue',
      figmaVariable: 'Chart/Blue',
      darkEquivalent: '#7F9BFF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
    green: {
      name: 'Chart Green',
      hex: '#22C58E',
      rgb: '34, 197, 142',
      hsl: '162, 75%, 45%',
      opacity: baseOpacity('22C58E'),
      tailwind: 'chart-green',
      cssVariable: '--cacs-color-chart-green',
      figmaVariable: 'Chart/Green',
      darkEquivalent: '#5AE0AD',
      contrastOn: '#0B1220',
      accessible: true,
    },
    orange: {
      name: 'Chart Orange',
      hex: '#FF9A3D',
      rgb: '255, 154, 61',
      hsl: '30, 100%, 62%',
      opacity: baseOpacity('FF9A3D'),
      tailwind: 'chart-orange',
      cssVariable: '--cacs-color-chart-orange',
      figmaVariable: 'Chart/Orange',
      darkEquivalent: '#FFC573',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  analytics: {
    highlight: {
      name: 'Analytics Highlight',
      hex: '#1AA8FF',
      rgb: '26, 168, 255',
      hsl: '202, 100%, 55%',
      opacity: baseOpacity('1AA8FF'),
      tailwind: 'analytics-highlight',
      cssVariable: '--cacs-color-analytics-highlight',
      figmaVariable: 'Analytics/Highlight',
      darkEquivalent: '#5CC7FF',
      contrastOn: '#0B1220',
      accessible: true,
    },
    contrast: {
      name: 'Analytics Contrast',
      hex: '#0B2E64',
      rgb: '11, 46, 100',
      hsl: '215, 81%, 22%',
      opacity: baseOpacity('0B2E64'),
      tailwind: 'analytics-contrast',
      cssVariable: '--cacs-color-analytics-contrast',
      figmaVariable: 'Analytics/Contrast',
      darkEquivalent: '#A9C1FF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  ai: {
    knowledge: {
      name: 'AI Knowledge',
      hex: '#7F62FF',
      rgb: '127, 98, 255',
      hsl: '259, 100%, 69%',
      opacity: baseOpacity('7F62FF'),
      tailwind: 'ai-knowledge',
      cssVariable: '--cacs-color-ai-knowledge',
      figmaVariable: 'AI/Knowledge',
      darkEquivalent: '#B89CFF',
      contrastOn: '#0B1220',
      accessible: true,
    },
    reasoning: {
      name: 'AI Reasoning',
      hex: '#2ED8FF',
      rgb: '46, 216, 255',
      hsl: '189, 100%, 59%',
      opacity: baseOpacity('2ED8FF'),
      tailwind: 'ai-reasoning',
      cssVariable: '--cacs-color-ai-reasoning',
      figmaVariable: 'AI/Reasoning',
      darkEquivalent: '#72E8FF',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  workflow: {
    active: {
      name: 'Workflow Active',
      hex: '#4EA1FF',
      rgb: '78, 161, 255',
      hsl: '211, 100%, 65%',
      opacity: baseOpacity('4EA1FF'),
      tailwind: 'workflow-active',
      cssVariable: '--cacs-color-workflow-active',
      figmaVariable: 'Workflow/Active',
      darkEquivalent: '#8CB8FF',
      contrastOn: '#0B1220',
      accessible: true,
    },
    pending: {
      name: 'Workflow Pending',
      hex: '#FFB63A',
      rgb: '255, 182, 58',
      hsl: '38, 100%, 61%',
      opacity: baseOpacity('FFB63A'),
      tailwind: 'workflow-pending',
      cssVariable: '--cacs-color-workflow-pending',
      figmaVariable: 'Workflow/Pending',
      darkEquivalent: '#FFD077',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  status: {
    success: {
      name: 'Status Success',
      hex: '#22C58E',
      rgb: '34, 197, 142',
      hsl: '162, 75%, 45%',
      opacity: baseOpacity('22C58E'),
      tailwind: 'status-success',
      cssVariable: '--cacs-color-status-success',
      figmaVariable: 'Status/Success',
      darkEquivalent: '#5AE0AD',
      contrastOn: '#0B1220',
      accessible: true,
    },
    warning: {
      name: 'Status Warning',
      hex: '#F2B10F',
      rgb: '242, 177, 15',
      hsl: '44, 88%, 50%',
      opacity: baseOpacity('F2B10F'),
      tailwind: 'status-warning',
      cssVariable: '--cacs-color-status-warning',
      figmaVariable: 'Status/Warning',
      darkEquivalent: '#F6C751',
      contrastOn: '#1F1A00',
      accessible: true,
    },
    danger: {
      name: 'Status Danger',
      hex: '#EF4F5F',
      rgb: '239, 79, 95',
      hsl: '354, 84%, 63%',
      opacity: baseOpacity('EF4F5F'),
      tailwind: 'status-danger',
      cssVariable: '--cacs-color-status-danger',
      figmaVariable: 'Status/Danger',
      darkEquivalent: '#FF6E82',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  notification: {
    badge: {
      name: 'Notification Badge',
      hex: '#FF5E7A',
      rgb: '255, 94, 122',
      hsl: '347, 100%, 68%',
      opacity: baseOpacity('FF5E7A'),
      tailwind: 'notification-badge',
      cssVariable: '--cacs-color-notification-badge',
      figmaVariable: 'Notification/Badge',
      darkEquivalent: '#FF8A9C',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
    alert: {
      name: 'Notification Alert',
      hex: '#FF9F1C',
      rgb: '255, 159, 28',
      hsl: '35, 100%, 56%',
      opacity: baseOpacity('FF9F1C'),
      tailwind: 'notification-alert',
      cssVariable: '--cacs-color-notification-alert',
      figmaVariable: 'Notification/Alert',
      darkEquivalent: '#FFC265',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  badge: {
    default: {
      name: 'Badge Default',
      hex: '#6F7C9A',
      rgb: '111, 124, 154',
      hsl: '222, 16%, 52%',
      opacity: baseOpacity('6F7C9A'),
      tailwind: 'badge-default',
      cssVariable: '--cacs-color-badge-default',
      figmaVariable: 'Badge/Default',
      darkEquivalent: '#D9E1F5',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  progress: {
    track: {
      name: 'Progress Track',
      hex: '#E9EEF8',
      rgb: '233, 238, 248',
      hsl: '214, 46%, 92%',
      opacity: baseOpacity('E9EEF8'),
      tailwind: 'progress-track',
      cssVariable: '--cacs-color-progress-track',
      figmaVariable: 'Progress/Track',
      darkEquivalent: '#162442',
      contrastOn: '#0B1220',
      accessible: true,
    },
    indicator: {
      name: 'Progress Indicator',
      hex: '#3B5BFF',
      rgb: '59, 91, 255',
      hsl: '227, 100%, 61%',
      opacity: baseOpacity('3B5BFF'),
      tailwind: 'progress-indicator',
      cssVariable: '--cacs-color-progress-indicator',
      figmaVariable: 'Progress/Indicator',
      darkEquivalent: '#7C8EFF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  statusTokens: {
    neutral: {
      name: 'Status Neutral',
      hex: '#9CA7C3',
      rgb: '156, 167, 195',
      hsl: '226, 24%, 69%',
      opacity: baseOpacity('9CA7C3'),
      tailwind: 'status-neutral',
      cssVariable: '--cacs-color-status-neutral',
      figmaVariable: 'Status/Neutral',
      darkEquivalent: '#D9E1F5',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  revenue: {
    forecast: {
      name: 'Revenue Forecast',
      hex: '#2BAF85',
      rgb: '43, 175, 133',
      hsl: '163, 58%, 43%',
      opacity: baseOpacity('2BAF85'),
      tailwind: 'revenue-forecast',
      cssVariable: '--cacs-color-revenue-forecast',
      figmaVariable: 'Revenue/Forecast',
      darkEquivalent: '#54C19B',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  marketing: {
    campaign: {
      name: 'Marketing Campaign',
      hex: '#FF5C93',
      rgb: '255, 92, 147',
      hsl: '340, 100%, 68%',
      opacity: baseOpacity('FF5C93'),
      tailwind: 'marketing-campaign',
      cssVariable: '--cacs-color-marketing-campaign',
      figmaVariable: 'Marketing/Campaign',
      darkEquivalent: '#FF84B1',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  research: {
    insight: {
      name: 'Research Insight',
      hex: '#635BFF',
      rgb: '99, 91, 255',
      hsl: '250, 100%, 68%',
      opacity: baseOpacity('635BFF'),
      tailwind: 'research-insight',
      cssVariable: '--cacs-color-research-insight',
      figmaVariable: 'Research/Insight',
      darkEquivalent: '#978CFF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  publishing: {
    publish: {
      name: 'Publishing Publish',
      hex: '#FFA94E',
      rgb: '255, 169, 78',
      hsl: '32, 100%, 65%',
      opacity: baseOpacity('FFA94E'),
      tailwind: 'publishing-publish',
      cssVariable: '--cacs-color-publishing-publish',
      figmaVariable: 'Publishing/Publish',
      darkEquivalent: '#FFC47D',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  community: {
    engagement: {
      name: 'Community Engagement',
      hex: '#5D8AFA',
      rgb: '93, 138, 250',
      hsl: '221, 91%, 67%',
      opacity: baseOpacity('5D8AFA'),
      tailwind: 'community-engagement',
      cssVariable: '--cacs-color-community-engagement',
      figmaVariable: 'Community/Engagement',
      darkEquivalent: '#8FA5FF',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  monetization: {
    growth: {
      name: 'Monetization Growth',
      hex: '#FFD55F',
      rgb: '255, 213, 95',
      hsl: '43, 100%, 68%',
      opacity: baseOpacity('FFD55F'),
      tailwind: 'monetization-growth',
      cssVariable: '--cacs-color-monetization-growth',
      figmaVariable: 'Monetization/Growth',
      darkEquivalent: '#FFDC84',
      contrastOn: '#0B1220',
      accessible: true,
    },
  },
  security: {
    shield: {
      name: 'Security Shield',
      hex: '#1D4E89',
      rgb: '29, 78, 137',
      hsl: '212, 67%, 32%',
      opacity: baseOpacity('1D4E89'),
      tailwind: 'security-shield',
      cssVariable: '--cacs-color-security-shield',
      figmaVariable: 'Security/Shield',
      darkEquivalent: '#5793D4',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  administration: {
    control: {
      name: 'Administration Control',
      hex: '#5C6DF1',
      rgb: '92, 109, 241',
      hsl: '229, 82%, 66%',
      opacity: baseOpacity('5C6DF1'),
      tailwind: 'administration-control',
      cssVariable: '--cacs-color-administration-control',
      figmaVariable: 'Administration/Control',
      darkEquivalent: '#8FA0FF',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
  developer: {
    console: {
      name: 'Developer Console',
      hex: '#0A2540',
      rgb: '10, 37, 64',
      hsl: '211, 74%, 14%',
      opacity: baseOpacity('0A2540'),
      tailwind: 'developer-console',
      cssVariable: '--cacs-color-developer-console',
      figmaVariable: 'Developer/Console',
      darkEquivalent: '#E8EEF8',
      contrastOn: '#FFFFFF',
      accessible: true,
    },
  },
}

export const typographyTokens: Record<string, TypographyToken> = {
  displayXXL: { name: 'Display XXL', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 700, fontSize: '72px', lineHeight: '88px', letterSpacing: '-0.04em' },
  displayXL: { name: 'Display XL', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 700, fontSize: '56px', lineHeight: '68px', letterSpacing: '-0.03em' },
  displayL: { name: 'Display L', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 700, fontSize: '44px', lineHeight: '56px', letterSpacing: '-0.03em' },
  heading1: { name: 'Heading 1', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 700, fontSize: '36px', lineHeight: '44px', letterSpacing: '-0.02em' },
  heading2: { name: 'Heading 2', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 700, fontSize: '30px', lineHeight: '38px', letterSpacing: '-0.02em' },
  heading3: { name: 'Heading 3', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '24px', lineHeight: '32px', letterSpacing: '-0.01em' },
  heading4: { name: 'Heading 4', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '20px', lineHeight: '28px', letterSpacing: '-0.01em' },
  heading5: { name: 'Heading 5', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '18px', lineHeight: '26px', letterSpacing: '0em' },
  heading6: { name: 'Heading 6', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '16px', lineHeight: '24px', letterSpacing: '0em' },
  subtitle: { name: 'Subtitle', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 500, fontSize: '15px', lineHeight: '22px', letterSpacing: '0em' },
  bodyLarge: { name: 'Body Large', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '16px', lineHeight: '28px', letterSpacing: '0em' },
  bodyMedium: { name: 'Body Medium', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '15px', lineHeight: '24px', letterSpacing: '0em' },
  bodySmall: { name: 'Body Small', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '14px', lineHeight: '20px', letterSpacing: '0em' },
  caption: { name: 'Caption', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '13px', lineHeight: '18px', letterSpacing: '0.01em' },
  overline: { name: 'Overline', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '12px', lineHeight: '16px', letterSpacing: '0.08em' },
  button: { name: 'Button', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '15px', lineHeight: '20px', letterSpacing: '0.02em' },
  navigation: { name: 'Navigation', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '15px', lineHeight: '20px', letterSpacing: '0.02em' },
  sidebar: { name: 'Sidebar', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 500, fontSize: '15px', lineHeight: '22px', letterSpacing: '0.01em' },
  table: { name: 'Table', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 500, fontSize: '14px', lineHeight: '20px', letterSpacing: '0em' },
  card: { name: 'Card', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 500, fontSize: '15px', lineHeight: '22px', letterSpacing: '0em' },
  chart: { name: 'Chart', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '13px', lineHeight: '18px', letterSpacing: '0.01em' },
  badge: { name: 'Badge', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '12px', lineHeight: '16px', letterSpacing: '0.04em' },
  tooltip: { name: 'Tooltip', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '13px', lineHeight: '18px', letterSpacing: '0em' },
  input: { name: 'Input', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '15px', lineHeight: '24px', letterSpacing: '0em' },
  error: { name: 'Error', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '13px', lineHeight: '18px', letterSpacing: '0em' },
  success: { name: 'Success', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 600, fontSize: '13px', lineHeight: '18px', letterSpacing: '0em' },
  helper: { name: 'Helper', fontFamily: 'Inter, system-ui, sans-serif', fontWeight: 400, fontSize: '13px', lineHeight: '18px', letterSpacing: '0em' },
  code: { name: 'Code', fontFamily: 'JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace', fontWeight: 400, fontSize: '13px', lineHeight: '20px', letterSpacing: '0em' },
}

export const spacingTokens: Record<string, SpacingToken> = {
  spacing2: { name: 'Spacing 2', value: '2px' },
  spacing4: { name: 'Spacing 4', value: '4px' },
  spacing6: { name: 'Spacing 6', value: '6px' },
  spacing8: { name: 'Spacing 8', value: '8px' },
  spacing10: { name: 'Spacing 10', value: '10px' },
  spacing12: { name: 'Spacing 12', value: '12px' },
  spacing16: { name: 'Spacing 16', value: '16px' },
  spacing20: { name: 'Spacing 20', value: '20px' },
  spacing24: { name: 'Spacing 24', value: '24px' },
  spacing32: { name: 'Spacing 32', value: '32px' },
  spacing40: { name: 'Spacing 40', value: '40px' },
  spacing48: { name: 'Spacing 48', value: '48px' },
  spacing56: { name: 'Spacing 56', value: '56px' },
  spacing64: { name: 'Spacing 64', value: '64px' },
  spacing72: { name: 'Spacing 72', value: '72px' },
  spacing80: { name: 'Spacing 80', value: '80px' },
  spacing96: { name: 'Spacing 96', value: '96px' },
  spacing128: { name: 'Spacing 128', value: '128px' },
  spacing160: { name: 'Spacing 160', value: '160px' },
  spacing192: { name: 'Spacing 192', value: '192px' },
  spacing256: { name: 'Spacing 256', value: '256px' },
}

export const radiusTokens: Record<string, RadiusToken> = {
  none: { name: 'Radius None', value: '0' },
  xs: { name: 'Radius XS', value: '4px' },
  sm: { name: 'Radius SM', value: '8px' },
  md: { name: 'Radius MD', value: '12px' },
  lg: { name: 'Radius LG', value: '16px' },
  xl: { name: 'Radius XL', value: '20px' },
  '2xl': { name: 'Radius 2XL', value: '24px' },
  '3xl': { name: 'Radius 3XL', value: '32px' },
  full: { name: 'Radius Full', value: '9999px' },
}

export const shadowTokens: Record<string, ShadowToken> = {
  none: { name: 'Shadow None', value: 'none', description: 'No elevation' },
  level1: { name: 'Shadow 1', value: '0 1px 4px rgba(15, 23, 42, 0.06)', description: 'Subtle surface separation for cards and panels' },
  level2: { name: 'Shadow 2', value: '0 4px 16px rgba(15, 23, 42, 0.08)', description: 'Light elevation for cards and flyouts' },
  level3: { name: 'Shadow 3', value: '0 8px 32px rgba(15, 23, 42, 0.12)', description: 'Medium elevation for drawers and dialogs' },
  level4: { name: 'Shadow 4', value: '0 16px 48px rgba(15, 23, 42, 0.16)', description: 'Strong elevation for modals and overlays' },
  level5: { name: 'Shadow 5', value: '0 24px 80px rgba(15, 23, 42, 0.18)', description: 'Highest elevation for mega overlays and full-screen panels' },
  floating: { name: 'Shadow Floating', value: '0 20px 64px rgba(15, 23, 42, 0.16)', description: 'Floating cards and modular widgets' },
  popover: { name: 'Shadow Popover', value: '0 12px 36px rgba(15, 23, 42, 0.14)', description: 'Popover and menu elevation' },
  modal: { name: 'Shadow Modal', value: '0 24px 72px rgba(15, 23, 42, 0.18)', description: 'Modal and dialog elevation' },
  drawer: { name: 'Shadow Drawer', value: '0 20px 56px rgba(15, 23, 42, 0.16)', description: 'Drawer and side-sheet elevation' },
  megaPanel: { name: 'Shadow Mega Panel', value: '0 28px 96px rgba(15, 23, 42, 0.20)', description: 'Large panel and dashboard overlay elevation' },
  glass: { name: 'Shadow Glass', value: '0 2px 24px rgba(15, 23, 42, 0.12)', description: 'Glass and translucent surface elevation' },
}

export const iconTokens: Record<string, IconToken> = {
  xs: { name: 'Icon XS', size: 12, strokeWidth: 1.5, spacing: '4px' },
  sm: { name: 'Icon SM', size: 16, strokeWidth: 1.5, spacing: '6px' },
  md: { name: 'Icon MD', size: 20, strokeWidth: 1.5, spacing: '8px' },
  lg: { name: 'Icon LG', size: 24, strokeWidth: 1.5, spacing: '10px' },
  xl: { name: 'Icon XL', size: 28, strokeWidth: 2, spacing: '12px' },
  xxl: { name: 'Icon XXL', size: 32, strokeWidth: 2, spacing: '14px' },
}

export const breakpoints: Record<string, BreakpointToken> = {
  mobile: { name: 'Mobile', minWidth: '320px' },
  phone: { name: 'Phone', minWidth: '480px' },
  tablet: { name: 'Tablet', minWidth: '768px' },
  laptop: { name: 'Laptop', minWidth: '1024px' },
  desktop: { name: 'Desktop', minWidth: '1280px' },
  widescreen: { name: 'Widescreen', minWidth: '1440px' },
  ultraWide: { name: 'Ultra Wide', minWidth: '1920px' },
  tv: { name: 'TV', minWidth: '2560px' },
}
