SET NOCOUNT ON;

IF OBJECT_ID('workflow_queue_categories', 'U') IS NULL
  CREATE TABLE workflow_queue_categories (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, category_name NVARCHAR(160) NOT NULL, description NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queues', 'U') IS NULL
  CREATE TABLE workflow_queues (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, category_id UNIQUEIDENTIFIER NULL, queue_code NVARCHAR(120) NOT NULL, queue_name NVARCHAR(220) NOT NULL, category NVARCHAR(160) NOT NULL, status NVARCHAR(40) NOT NULL DEFAULT 'Healthy', waiting_count INT NOT NULL DEFAULT 0, active_count INT NOT NULL DEFAULT 0, delayed_count INT NOT NULL DEFAULT 0, retrying_count INT NOT NULL DEFAULT 0, failed_count INT NOT NULL DEFAULT 0, dead_letter_count INT NOT NULL DEFAULT 0, workers INT NOT NULL DEFAULT 0, desired_workers INT NOT NULL DEFAULT 0, throughput_per_minute DECIMAL(18,2) NOT NULL DEFAULT 0, average_wait_seconds DECIMAL(18,2) NOT NULL DEFAULT 0, oldest_item_at DATETIME2 NULL, sla_risk_count INT NOT NULL DEFAULT 0, health_percent DECIMAL(8,2) NOT NULL DEFAULT 100, rebalancing_state NVARCHAR(120) NULL, last_autonomous_action NVARCHAR(500) NULL, environment NVARCHAR(80) NOT NULL DEFAULT 'production', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NULL, is_deleted BIT NOT NULL DEFAULT 0);
IF OBJECT_ID('workflow_queue_versions', 'U') IS NULL
  CREATE TABLE workflow_queue_versions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, version_number INT NOT NULL, status NVARCHAR(40) NOT NULL DEFAULT 'published', change_summary NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_policies', 'U') IS NULL
  CREATE TABLE workflow_queue_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, policy_type NVARCHAR(120) NOT NULL, policy_value NVARCHAR(500) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_priority_policies', 'U') IS NULL
  CREATE TABLE workflow_queue_priority_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(160) NOT NULL, factor_json NVARCHAR(MAX) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_capacity_policies', 'U') IS NULL
  CREATE TABLE workflow_queue_capacity_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, desired_workers INT NOT NULL DEFAULT 1, scale_out_threshold INT NOT NULL DEFAULT 100, scale_in_threshold INT NOT NULL DEFAULT 10, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_rebalance_policies', 'U') IS NULL
  CREATE TABLE workflow_queue_rebalance_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, strategy NVARCHAR(180) NOT NULL, guardrail NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_retry_policies', 'U') IS NULL
  CREATE TABLE workflow_queue_retry_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(160) NOT NULL, max_attempts INT NOT NULL DEFAULT 3, current_retries INT NOT NULL DEFAULT 0, success_after_retry DECIMAL(8,2) NOT NULL DEFAULT 0, average_recovery_seconds INT NOT NULL DEFAULT 0, dead_letter_rate DECIMAL(8,2) NOT NULL DEFAULT 0, cost_impact DECIMAL(18,4) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_sla_policies', 'U') IS NULL
  CREATE TABLE workflow_queue_sla_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(160) NOT NULL, deadline_minutes INT NOT NULL DEFAULT 60, protection_action NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('workflow_queue_items', 'U') IS NULL
  CREATE TABLE workflow_queue_items (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, queue_id UNIQUEIDENTIFIER NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL,
    workflow_stage_id UNIQUEIDENTIFIER NULL, workflow_name NVARCHAR(220) NOT NULL, workflow_version INT NOT NULL DEFAULT 1, reference_type NVARCHAR(120) NULL, reference_id NVARCHAR(180) NULL,
    status NVARCHAR(40) NOT NULL DEFAULT 'Waiting', base_priority NVARCHAR(40) NOT NULL DEFAULT 'Normal', effective_priority NVARCHAR(40) NOT NULL DEFAULT 'Normal',
    current_stage NVARCHAR(180) NULL, progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, scheduled_at DATETIME2 NULL, available_at DATETIME2 NULL, sla_deadline DATETIME2 NULL,
    sla_status NVARCHAR(80) NOT NULL DEFAULT 'within_sla', required_worker_type NVARCHAR(160) NULL, assigned_worker_id NVARCHAR(160) NULL, retry_count INT NOT NULL DEFAULT 0,
    recovery_state NVARCHAR(120) NULL, idempotency_key NVARCHAR(240) NULL, checkpoint_id NVARCHAR(180) NULL, estimated_duration_ms INT NOT NULL DEFAULT 0, estimated_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    final_output_impact NVARCHAR(120) NULL, organization_name NVARCHAR(180) NULL, brand NVARCHAR(180) NULL, correlation_id NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NULL
  );
IF OBJECT_ID('workflow_queue_item_context', 'U') IS NULL
  CREATE TABLE workflow_queue_item_context (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, context_json NVARCHAR(MAX) NULL, required_capabilities NVARCHAR(MAX) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_dependencies', 'U') IS NULL
  CREATE TABLE workflow_queue_item_dependencies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, dependency_name NVARCHAR(180) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'ready', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_leases', 'U') IS NULL
  CREATE TABLE workflow_queue_item_leases (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, worker_id NVARCHAR(160) NULL, lease_expires_at DATETIME2 NULL, heartbeat_at DATETIME2 NULL, status NVARCHAR(80) NOT NULL DEFAULT 'active', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_checkpoints', 'U') IS NULL
  CREATE TABLE workflow_queue_item_checkpoints (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, checkpoint_name NVARCHAR(180) NOT NULL, checkpoint_state NVARCHAR(80) NOT NULL DEFAULT 'saved', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_priority_history', 'U') IS NULL
  CREATE TABLE workflow_queue_item_priority_history (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, original_priority NVARCHAR(40) NOT NULL, adjustment NVARCHAR(240) NULL, policy_used NVARCHAR(180) NULL, final_priority NVARCHAR(40) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, expected_impact NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_assignments', 'U') IS NULL
  CREATE TABLE workflow_queue_item_assignments (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, candidate_workers INT NOT NULL DEFAULT 0, selected_worker NVARCHAR(160) NULL, match_score DECIMAL(8,2) NOT NULL DEFAULT 0, estimated_completion_at DATETIME2 NULL, cost DECIMAL(18,4) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, fallback_worker NVARCHAR(160) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_failures', 'U') IS NULL
  CREATE TABLE workflow_queue_item_failures (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, failure_code NVARCHAR(120) NOT NULL, failure_summary NVARCHAR(500) NOT NULL, probable_cause NVARCHAR(240) NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_retries', 'U') IS NULL
  CREATE TABLE workflow_queue_item_retries (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, retry_number INT NOT NULL, strategy NVARCHAR(180) NULL, next_retry_at DATETIME2 NULL, status NVARCHAR(80) NOT NULL DEFAULT 'scheduled', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_item_recoveries', 'U') IS NULL
  CREATE TABLE workflow_queue_item_recoveries (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, diagnosis NVARCHAR(240) NULL, recovery_policy NVARCHAR(180) NULL, rebalance_decision NVARCHAR(240) NULL, reassignment NVARCHAR(180) NULL, recovery_status NVARCHAR(80) NOT NULL DEFAULT 'in_progress', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_dead_letters', 'U') IS NULL
  CREATE TABLE workflow_queue_dead_letters (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, workflow_name NVARCHAR(220) NOT NULL, stage NVARCHAR(180) NULL, queue_name NVARCHAR(220) NOT NULL, failure_code NVARCHAR(120) NOT NULL, failure_summary NVARCHAR(500) NOT NULL, attempts INT NOT NULL DEFAULT 0, first_failed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), last_failed_at DATETIME2 NULL, recoverability NVARCHAR(80) NOT NULL DEFAULT 'Recoverable', recommended_recovery NVARCHAR(240) NULL, related_incident NVARCHAR(180) NULL, final_output_impact NVARCHAR(120) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'New', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_rebalance_events', 'U') IS NULL
  CREATE TABLE workflow_queue_rebalance_events (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, queue_id UNIQUEIDENTIFIER NOT NULL, detection NVARCHAR(240) NOT NULL, workflows_affected INT NOT NULL DEFAULT 0, strategy NVARCHAR(180) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, items_moved INT NOT NULL DEFAULT 0, workers_added INT NOT NULL DEFAULT 0, expected_wait_reduction_seconds INT NOT NULL DEFAULT 0, cost_impact DECIMAL(18,4) NOT NULL DEFAULT 0, final_outcome NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_congestion_predictions', 'U') IS NULL
  CREATE TABLE workflow_queue_congestion_predictions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, queue_id UNIQUEIDENTIFIER NOT NULL, current_depth INT NOT NULL DEFAULT 0, forecast_depth_15m INT NOT NULL DEFAULT 0, forecast_depth_1h INT NOT NULL DEFAULT 0, average_wait_increase_seconds INT NOT NULL DEFAULT 0, sla_breach_probability DECIMAL(8,2) NOT NULL DEFAULT 0, worker_capacity_shortfall INT NOT NULL DEFAULT 0, risk_level NVARCHAR(80) NOT NULL DEFAULT 'low', time_to_congestion_minutes INT NOT NULL DEFAULT 0, affected_workflows INT NOT NULL DEFAULT 0, final_output_impact NVARCHAR(120) NULL, autonomous_mitigation NVARCHAR(240) NULL, expected_improvement NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_capacity_forecasts', 'U') IS NULL
  CREATE TABLE workflow_queue_capacity_forecasts (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, queue_id UNIQUEIDENTIFIER NOT NULL, required_capability NVARCHAR(160) NOT NULL, candidate_workers INT NOT NULL DEFAULT 0, selected_worker NVARCHAR(160) NULL, match_score DECIMAL(8,2) NOT NULL DEFAULT 0, estimated_completion_at DATETIME2 NULL, cost DECIMAL(18,4) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, fallback_worker NVARCHAR(160) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_autonomous_decisions', 'U') IS NULL
  CREATE TABLE workflow_queue_autonomous_decisions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, queue_id UNIQUEIDENTIFIER NULL, queue_item_id UNIQUEIDENTIFIER NULL, workflow_name NVARCHAR(220) NULL, detection NVARCHAR(240) NOT NULL, decision NVARCHAR(240) NOT NULL, policy NVARCHAR(180) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, action_taken NVARCHAR(240) NULL, outcome NVARCHAR(180) NULL, human_input_required BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_metrics', 'U') IS NULL
  CREATE TABLE workflow_queue_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, metric_date DATE NOT NULL DEFAULT CAST(SYSUTCDATETIME() AS DATE), queue_depth INT NOT NULL DEFAULT 0, dispatch_rate DECIMAL(18,2) NOT NULL DEFAULT 0, throughput DECIMAL(18,2) NOT NULL DEFAULT 0, completion_rate DECIMAL(8,2) NOT NULL DEFAULT 0, retry_rate DECIMAL(8,2) NOT NULL DEFAULT 0, recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, dead_letter_rate DECIMAL(8,2) NOT NULL DEFAULT 0, sla_compliance DECIMAL(8,2) NOT NULL DEFAULT 0, worker_utilization DECIMAL(8,2) NOT NULL DEFAULT 0, cost_today DECIMAL(18,4) NOT NULL DEFAULT 0, final_output_completion_rate DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_recommendations', 'U') IS NULL
  CREATE TABLE workflow_queue_recommendations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, recommendation_type NVARCHAR(120) NOT NULL, title NVARCHAR(220) NOT NULL, description NVARCHAR(800) NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, impact NVARCHAR(80) NULL, inside_guardrails BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_change_history', 'U') IS NULL
  CREATE TABLE workflow_queue_change_history (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_queue_id UNIQUEIDENTIFIER NOT NULL, change_type NVARCHAR(120) NOT NULL, change_summary NVARCHAR(500) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_final_output_links', 'U') IS NULL
  CREATE TABLE workflow_queue_final_output_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, queue_item_id UNIQUEIDENTIFIER NOT NULL, workflow_stage NVARCHAR(180) NULL, action_or_agent NVARCHAR(180) NULL, output_state NVARCHAR(80) NULL, publishing_state NVARCHAR(80) NULL, analytics_state NVARCHAR(80) NULL, learning_state NVARCHAR(80) NULL, business_result_state NVARCHAR(80) NULL, readiness_percent DECIMAL(8,2) NOT NULL DEFAULT 0, impact_status NVARCHAR(120) NOT NULL DEFAULT 'on_track', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('vw_workflow_queue_health', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_health;
EXEC('CREATE VIEW vw_workflow_queue_health AS SELECT q.*, org.name AS organization FROM workflow_queues q JOIN organizations org ON org.id = q.organization_id WHERE q.is_deleted = 0');
IF OBJECT_ID('vw_workflow_queue_summary', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_summary;
EXEC('CREATE VIEW vw_workflow_queue_summary AS SELECT organization_id, SUM(waiting_count + active_count + delayed_count + retrying_count) AS total_queued_workflows, SUM(active_count) AS active_executions, SUM(waiting_count) AS waiting, SUM(delayed_count) AS delayed, SUM(retrying_count) AS retrying, SUM(dead_letter_count) AS dead_lettered, SUM(sla_risk_count) AS sla_at_risk, CAST(AVG(average_wait_seconds) AS DECIMAL(18,2)) AS average_queue_wait, COUNT(CASE WHEN status IN (''Failed'',''Offline'') THEN 1 END) AS human_attention_required, MAX(updated_at) AS last_queue_event FROM workflow_queues WHERE is_deleted = 0 GROUP BY organization_id');
IF OBJECT_ID('vw_workflow_queue_items', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_items;
EXEC('CREATE VIEW vw_workflow_queue_items AS SELECT i.*, q.queue_code, q.queue_name, q.category AS queue_category, org.name AS organization FROM workflow_queue_items i JOIN workflow_queues q ON q.id = i.queue_id JOIN organizations org ON org.id = i.organization_id');
IF OBJECT_ID('vw_workflow_queue_congestion', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_congestion;
EXEC('CREATE VIEW vw_workflow_queue_congestion AS SELECT p.*, q.queue_name, q.category FROM workflow_queue_congestion_predictions p JOIN workflow_queues q ON q.id = p.queue_id');
IF OBJECT_ID('vw_workflow_queue_sla_risk', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_sla_risk;
EXEC('CREATE VIEW vw_workflow_queue_sla_risk AS SELECT * FROM vw_workflow_queue_items WHERE sla_status IN (''at_risk'',''breached'')');
IF OBJECT_ID('vw_workflow_queue_recoveries', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_recoveries;
EXEC('CREATE VIEW vw_workflow_queue_recoveries AS SELECT r.*, i.organization_id, i.workflow_name, i.status, q.queue_name FROM workflow_queue_item_recoveries r JOIN workflow_queue_items i ON i.id = r.queue_item_id JOIN workflow_queues q ON q.id = i.queue_id');
IF OBJECT_ID('vw_workflow_queue_dead_letters', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_dead_letters;
EXEC('CREATE VIEW vw_workflow_queue_dead_letters AS SELECT d.*, i.organization_id FROM workflow_queue_dead_letters d JOIN workflow_queue_items i ON i.id = d.queue_item_id');
IF OBJECT_ID('vw_workflow_queue_capacity', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_capacity;
EXEC('CREATE VIEW vw_workflow_queue_capacity AS SELECT c.*, q.queue_name, q.category FROM workflow_queue_capacity_forecasts c JOIN workflow_queues q ON q.id = c.queue_id');
IF OBJECT_ID('vw_workflow_queue_final_output_impact', 'V') IS NOT NULL DROP VIEW vw_workflow_queue_final_output_impact;
EXEC('CREATE VIEW vw_workflow_queue_final_output_impact AS SELECT l.*, i.organization_id, i.workflow_name, i.reference_id, q.queue_name FROM workflow_queue_final_output_links l JOIN workflow_queue_items i ON i.id = l.queue_item_id JOIN workflow_queues q ON q.id = i.queue_id');
