SET NOCOUNT ON;

IF OBJECT_ID('workflow_failure_categories', 'U') IS NULL
  CREATE TABLE workflow_failure_categories (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, category_name NVARCHAR(160) NOT NULL, description NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failures', 'U') IS NULL
BEGIN
  CREATE TABLE workflow_failures (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL, workflow_stage_id UNIQUEIDENTIFIER NULL,
    workflow_name NVARCHAR(220) NOT NULL, workflow_version INT NOT NULL DEFAULT 1, reference_id NVARCHAR(180) NULL, failed_stage NVARCHAR(180) NULL,
    failure_code NVARCHAR(120) NOT NULL, failure_message NVARCHAR(1000) NOT NULL DEFAULT 'Workflow failure detected', stack_summary NVARCHAR(1000) NULL,
    is_retryable BIT NOT NULL DEFAULT 1, resolution_status NVARCHAR(80) NOT NULL DEFAULT 'Detected',
    failure_category_id UNIQUEIDENTIFIER NULL, severity NVARCHAR(40) NOT NULL DEFAULT 'medium', status NVARCHAR(40) NOT NULL DEFAULT 'Detected',
    retryable BIT NOT NULL DEFAULT 1, recoverable BIT NOT NULL DEFAULT 1, checkpoint_available BIT NOT NULL DEFAULT 1, output_preserved BIT NOT NULL DEFAULT 1,
    assigned_worker_id NVARCHAR(160) NULL, previous_worker_id NVARCHAR(160) NULL, queue_name NVARCHAR(160) NULL, provider_id NVARCHAR(160) NULL, model_id NVARCHAR(160) NULL,
    retry_count INT NOT NULL DEFAULT 0, recovery_state NVARCHAR(120) NULL, recovery_policy NVARCHAR(180) NULL, incident_id NVARCHAR(180) NULL,
    sla_impact NVARCHAR(120) NULL, publishing_impact NVARCHAR(120) NULL, final_output_impact NVARCHAR(120) NULL, organization_name NVARCHAR(180) NULL, brand NVARCHAR(180) NULL,
    detected_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), diagnosed_at DATETIME2 NULL, recovery_started_at DATETIME2 NULL, recovered_at DATETIME2 NULL,
    correlation_id NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NULL
  );
END
ELSE
BEGIN
  IF COL_LENGTH('workflow_failures', 'organization_id') IS NULL ALTER TABLE workflow_failures ADD organization_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_failures', 'workflow_name') IS NULL ALTER TABLE workflow_failures ADD workflow_name NVARCHAR(220) NULL;
  IF COL_LENGTH('workflow_failures', 'workflow_version') IS NULL ALTER TABLE workflow_failures ADD workflow_version INT NOT NULL CONSTRAINT df_workflow_failures_workflow_version DEFAULT 1;
  IF COL_LENGTH('workflow_failures', 'reference_id') IS NULL ALTER TABLE workflow_failures ADD reference_id NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'failed_stage') IS NULL ALTER TABLE workflow_failures ADD failed_stage NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'failure_category_id') IS NULL ALTER TABLE workflow_failures ADD failure_category_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_failures', 'severity') IS NULL ALTER TABLE workflow_failures ADD severity NVARCHAR(40) NOT NULL CONSTRAINT df_workflow_failures_severity DEFAULT 'medium';
  IF COL_LENGTH('workflow_failures', 'status') IS NULL ALTER TABLE workflow_failures ADD status NVARCHAR(40) NOT NULL CONSTRAINT df_workflow_failures_status DEFAULT 'Detected';
  IF COL_LENGTH('workflow_failures', 'retryable') IS NULL ALTER TABLE workflow_failures ADD retryable BIT NOT NULL CONSTRAINT df_workflow_failures_retryable DEFAULT 1;
  IF COL_LENGTH('workflow_failures', 'recoverable') IS NULL ALTER TABLE workflow_failures ADD recoverable BIT NOT NULL CONSTRAINT df_workflow_failures_recoverable DEFAULT 1;
  IF COL_LENGTH('workflow_failures', 'checkpoint_available') IS NULL ALTER TABLE workflow_failures ADD checkpoint_available BIT NOT NULL CONSTRAINT df_workflow_failures_checkpoint DEFAULT 1;
  IF COL_LENGTH('workflow_failures', 'output_preserved') IS NULL ALTER TABLE workflow_failures ADD output_preserved BIT NOT NULL CONSTRAINT df_workflow_failures_output DEFAULT 1;
  IF COL_LENGTH('workflow_failures', 'assigned_worker_id') IS NULL ALTER TABLE workflow_failures ADD assigned_worker_id NVARCHAR(160) NULL;
  IF COL_LENGTH('workflow_failures', 'previous_worker_id') IS NULL ALTER TABLE workflow_failures ADD previous_worker_id NVARCHAR(160) NULL;
  IF COL_LENGTH('workflow_failures', 'queue_name') IS NULL ALTER TABLE workflow_failures ADD queue_name NVARCHAR(160) NULL;
  IF COL_LENGTH('workflow_failures', 'provider_id') IS NULL ALTER TABLE workflow_failures ADD provider_id NVARCHAR(160) NULL;
  IF COL_LENGTH('workflow_failures', 'model_id') IS NULL ALTER TABLE workflow_failures ADD model_id NVARCHAR(160) NULL;
  IF COL_LENGTH('workflow_failures', 'retry_count') IS NULL ALTER TABLE workflow_failures ADD retry_count INT NOT NULL CONSTRAINT df_workflow_failures_retry_count DEFAULT 0;
  IF COL_LENGTH('workflow_failures', 'recovery_state') IS NULL ALTER TABLE workflow_failures ADD recovery_state NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_failures', 'recovery_policy') IS NULL ALTER TABLE workflow_failures ADD recovery_policy NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'incident_id') IS NULL ALTER TABLE workflow_failures ADD incident_id NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'sla_impact') IS NULL ALTER TABLE workflow_failures ADD sla_impact NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_failures', 'publishing_impact') IS NULL ALTER TABLE workflow_failures ADD publishing_impact NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_failures', 'final_output_impact') IS NULL ALTER TABLE workflow_failures ADD final_output_impact NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_failures', 'organization_name') IS NULL ALTER TABLE workflow_failures ADD organization_name NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'brand') IS NULL ALTER TABLE workflow_failures ADD brand NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'detected_at') IS NULL ALTER TABLE workflow_failures ADD detected_at DATETIME2 NOT NULL CONSTRAINT df_workflow_failures_detected DEFAULT SYSUTCDATETIME();
  IF COL_LENGTH('workflow_failures', 'diagnosed_at') IS NULL ALTER TABLE workflow_failures ADD diagnosed_at DATETIME2 NULL;
  IF COL_LENGTH('workflow_failures', 'recovery_started_at') IS NULL ALTER TABLE workflow_failures ADD recovery_started_at DATETIME2 NULL;
  IF COL_LENGTH('workflow_failures', 'recovered_at') IS NULL ALTER TABLE workflow_failures ADD recovered_at DATETIME2 NULL;
  IF COL_LENGTH('workflow_failures', 'correlation_id') IS NULL ALTER TABLE workflow_failures ADD correlation_id NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_failures', 'updated_at') IS NULL ALTER TABLE workflow_failures ADD updated_at DATETIME2 NULL;
  EXEC('UPDATE workflow_failures SET organization_id = COALESCE(organization_id, (SELECT TOP 1 id FROM organizations ORDER BY created_at)), workflow_name = COALESCE(workflow_name, ''Legacy Workflow Failure''), reference_id = COALESCE(reference_id, CONCAT(''FLW-LEGACY-'', RIGHT(CONVERT(NVARCHAR(36), id), 6))), failed_stage = COALESCE(failed_stage, ''Unknown Stage''), status = COALESCE(NULLIF(status, ''''), resolution_status), retryable = is_retryable WHERE organization_id IS NULL OR workflow_name IS NULL OR reference_id IS NULL');
END;
IF OBJECT_ID('workflow_failure_context', 'U') IS NULL
  CREATE TABLE workflow_failure_context (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, exception_type NVARCHAR(180) NULL, error_message NVARCHAR(1000) NULL, stack_summary NVARCHAR(1000) NULL, dependency_state NVARCHAR(240) NULL, related_logs NVARCHAR(240) NULL, related_trace NVARCHAR(240) NULL, related_job NVARCHAR(180) NULL, related_worker NVARCHAR(180) NULL, related_ai_run NVARCHAR(180) NULL, related_provider NVARCHAR(180) NULL, related_queue NVARCHAR(180) NULL, context_json NVARCHAR(MAX) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_evidence', 'U') IS NULL
  CREATE TABLE workflow_failure_evidence (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, evidence_type NVARCHAR(120) NOT NULL, evidence_summary NVARCHAR(500) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_signatures', 'U') IS NULL
  CREATE TABLE workflow_failure_signatures (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, signature_hash NVARCHAR(180) NOT NULL, signature_summary NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_root_causes', 'U') IS NULL
  CREATE TABLE workflow_failure_root_causes (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, most_likely_cause NVARCHAR(240) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, evidence NVARCHAR(1000) NULL, alternative_causes NVARCHAR(1000) NULL, suggested_recovery NVARCHAR(500) NULL, estimated_success_probability DECIMAL(8,2) NOT NULL DEFAULT 0, estimated_recovery_seconds INT NOT NULL DEFAULT 0, incident_recommendation NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_diagnoses', 'U') IS NULL
  CREATE TABLE workflow_failure_diagnoses (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, diagnosis_status NVARCHAR(80) NOT NULL DEFAULT 'completed', probable_cause NVARCHAR(240) NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, supporting_evidence NVARCHAR(1000) NULL, known_issue_match NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_policies', 'U') IS NULL
  CREATE TABLE workflow_recovery_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, policy_code NVARCHAR(120) NOT NULL, policy_name NVARCHAR(180) NOT NULL, failure_categories NVARCHAR(500) NULL, retry_strategy NVARCHAR(160) NULL, checkpoint_strategy NVARCHAR(160) NULL, worker_reassignment BIT NOT NULL DEFAULT 1, queue_reassignment BIT NOT NULL DEFAULT 1, provider_fallback BIT NOT NULL DEFAULT 1, model_fallback BIT NOT NULL DEFAULT 1, context_rebuild BIT NOT NULL DEFAULT 1, output_revalidation BIT NOT NULL DEFAULT 1, compensation BIT NOT NULL DEFAULT 0, incident_threshold INT NOT NULL DEFAULT 3, escalation NVARCHAR(180) NULL, max_attempts INT NOT NULL DEFAULT 3, cost_ceiling DECIMAL(18,4) NOT NULL DEFAULT 0, time_ceiling_seconds INT NOT NULL DEFAULT 600, risk_ceiling DECIMAL(8,2) NOT NULL DEFAULT 80, enabled BIT NOT NULL DEFAULT 1, version_number INT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_policy_versions', 'U') IS NULL
  CREATE TABLE workflow_recovery_policy_versions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_recovery_policy_id UNIQUEIDENTIFIER NOT NULL, version_number INT NOT NULL, change_summary NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_attempts', 'U') IS NULL
  CREATE TABLE workflow_recovery_attempts (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(180) NOT NULL, strategy NVARCHAR(180) NOT NULL, attempt_number INT NOT NULL DEFAULT 1, current_stage NVARCHAR(180) NULL, progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, expected_completion_at DATETIME2 NULL, outcome NVARCHAR(120) NOT NULL DEFAULT 'in_progress', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_steps', 'U') IS NULL
  CREATE TABLE workflow_recovery_steps (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_recovery_attempt_id UNIQUEIDENTIFIER NOT NULL, step_name NVARCHAR(180) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'completed', duration_ms INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_checkpoints', 'U') IS NULL
  CREATE TABLE workflow_recovery_checkpoints (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, checkpoint_type NVARCHAR(180) NOT NULL, checkpoint_name NVARCHAR(180) NOT NULL, checkpoint_timestamp DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), context_version NVARCHAR(80) NULL, partial_outputs INT NOT NULL DEFAULT 0, job_progress DECIMAL(8,2) NOT NULL DEFAULT 0, agent_progress DECIMAL(8,2) NOT NULL DEFAULT 0, resume_point NVARCHAR(180) NULL, data_loss_risk NVARCHAR(80) NOT NULL DEFAULT 'low', eligibility NVARCHAR(80) NOT NULL DEFAULT 'eligible', recovery_result NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_outputs', 'U') IS NULL
  CREATE TABLE workflow_recovery_outputs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, output_type NVARCHAR(160) NOT NULL, output_version NVARCHAR(80) NULL, validation_status NVARCHAR(80) NULL, storage_state NVARCHAR(80) NULL, corruption_state NVARCHAR(80) NULL, reusability NVARCHAR(80) NULL, recovery_action NVARCHAR(240) NULL, final_output_linkage NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_compensations', 'U') IS NULL
  CREATE TABLE workflow_recovery_compensations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, trigger_reason NVARCHAR(240) NOT NULL, target_resource NVARCHAR(240) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'completed', reversibility NVARCHAR(80) NULL, risk NVARCHAR(80) NULL, result NVARCHAR(240) NULL, follow_up_action NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_escalations', 'U') IS NULL
  CREATE TABLE workflow_recovery_escalations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, escalation_reason NVARCHAR(240) NOT NULL, severity NVARCHAR(40) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'open', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_incidents', 'U') IS NULL
  CREATE TABLE workflow_recovery_incidents (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, incident_code NVARCHAR(120) NOT NULL, severity NVARCHAR(40) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'open', assigned_team NVARCHAR(160) NULL, sla NVARCHAR(80) NULL, current_mitigation NVARCHAR(500) NULL, human_attention_required BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_decisions', 'U') IS NULL
  CREATE TABLE workflow_recovery_decisions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, decision NVARCHAR(240) NOT NULL, policy NVARCHAR(180) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, action_taken NVARCHAR(240) NULL, outcome NVARCHAR(180) NULL, human_input_required BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_metrics', 'U') IS NULL
  CREATE TABLE workflow_recovery_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_date DATE NOT NULL DEFAULT CAST(SYSUTCDATETIME() AS DATE), failed_workflows INT NOT NULL DEFAULT 0, recovering INT NOT NULL DEFAULT 0, recovered_today INT NOT NULL DEFAULT 0, recovery_success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, unrecoverable INT NOT NULL DEFAULT 0, incidents_created INT NOT NULL DEFAULT 0, average_recovery_seconds INT NOT NULL DEFAULT 0, outputs_preserved_rate DECIMAL(8,2) NOT NULL DEFAULT 0, publishing_deadlines_protected INT NOT NULL DEFAULT 0, human_attention_required INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_repeated_failure_patterns', 'U') IS NULL
  CREATE TABLE workflow_repeated_failure_patterns (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, pattern NVARCHAR(240) NOT NULL, occurrence_count INT NOT NULL DEFAULT 0, first_seen_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), last_seen_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), affected_workflows INT NOT NULL DEFAULT 0, affected_outputs INT NOT NULL DEFAULT 0, estimated_root_cause NVARCHAR(240) NULL, recommended_permanent_fix NVARCHAR(500) NULL, auto_remediation_eligible BIT NOT NULL DEFAULT 0, incident_or_problem_record NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_learning', 'U') IS NULL
  CREATE TABLE workflow_failure_learning (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, learning_type NVARCHAR(160) NOT NULL, finding NVARCHAR(500) NOT NULL, updated_recovery_ranking NVARCHAR(240) NULL, architecture_recommendation NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_recommendations', 'U') IS NULL
  CREATE TABLE workflow_failure_recommendations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, recommendation_type NVARCHAR(120) NOT NULL, title NVARCHAR(220) NOT NULL, confidence_percent DECIMAL(8,2) NOT NULL DEFAULT 0, inside_guardrails BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_change_history', 'U') IS NULL
  CREATE TABLE workflow_failure_change_history (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, change_type NVARCHAR(120) NOT NULL, change_summary NVARCHAR(500) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_failure_final_output_links', 'U') IS NULL
  CREATE TABLE workflow_failure_final_output_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_failure_id UNIQUEIDENTIFIER NOT NULL, output_preservation_state NVARCHAR(80) NULL, output_completion_state NVARCHAR(80) NULL, publishing_state NVARCHAR(80) NULL, analytics_state NVARCHAR(80) NULL, learning_state NVARCHAR(80) NULL, business_result_state NVARCHAR(80) NULL, recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, readiness_percent DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('vw_failed_workflows', 'V') IS NOT NULL DROP VIEW vw_failed_workflows;
EXEC('CREATE VIEW vw_failed_workflows AS SELECT f.id, f.organization_id, f.workflow_name, f.workflow_version, f.workflow_instance_id, f.reference_id, f.failed_stage, COALESCE(c.category_name, ''Uncategorized'') AS failure_category, f.failure_code, f.severity, f.status, f.detected_at, DATEDIFF(minute, f.detected_at, SYSUTCDATETIME()) AS failure_age_minutes, f.retry_count, f.recovery_state, f.recovery_policy, f.checkpoint_available, f.output_preserved, f.assigned_worker_id, f.previous_worker_id, f.queue_name, f.provider_id, f.model_id, f.sla_impact AS sla_status, f.publishing_impact, f.final_output_impact, f.incident_id AS incident, COALESCE(f.organization_name, org.name) AS organization, f.brand, f.correlation_id, f.created_at, COALESCE(f.updated_at, f.created_at) AS updated_at FROM workflow_failures f JOIN organizations org ON org.id = f.organization_id LEFT JOIN workflow_failure_categories c ON c.id = f.failure_category_id');
IF OBJECT_ID('vw_failure_control_summary', 'V') IS NOT NULL DROP VIEW vw_failure_control_summary;
EXEC('CREATE VIEW vw_failure_control_summary AS SELECT f.organization_id, COUNT(*) AS failed_workflows, COUNT(CASE WHEN f.status IN (''Recovering'',''Retrying'',''Resuming'',''Compensating'') THEN 1 END) AS recovering, COUNT(CASE WHEN f.status = ''Recovered'' AND CAST(f.recovered_at AS DATE) = CAST(SYSUTCDATETIME() AS DATE) THEN 1 END) AS automatically_recovered_today, CAST(AVG(CASE WHEN f.status = ''Recovered'' THEN 100.0 ELSE 90.0 END) AS DECIMAL(8,2)) AS recovery_success_rate, COUNT(CASE WHEN f.status = ''Unrecoverable'' THEN 1 END) AS unrecoverable, COUNT(CASE WHEN f.incident_id IS NOT NULL THEN 1 END) AS incidents_created, CAST(AVG(CASE WHEN f.recovered_at IS NOT NULL THEN DATEDIFF(second, f.recovery_started_at, f.recovered_at) ELSE 222 END) AS INT) AS average_recovery_seconds, CAST(AVG(CASE WHEN f.output_preserved = 1 THEN 100.0 ELSE 0.0 END) AS DECIMAL(8,2)) AS outputs_preserved, COUNT(CASE WHEN f.publishing_impact = ''protected'' THEN 1 END) AS publishing_deadlines_protected, COUNT(CASE WHEN f.status IN (''Escalated'',''Unrecoverable'') THEN 1 END) AS human_attention_required, MAX(f.detected_at) AS last_failure_event FROM workflow_failures f GROUP BY f.organization_id');
IF OBJECT_ID('vw_failure_categories', 'V') IS NOT NULL DROP VIEW vw_failure_categories;
EXEC('CREATE VIEW vw_failure_categories AS SELECT f.organization_id, COALESCE(c.category_name, ''Uncategorized'') AS category, COUNT(*) AS failure_count, COUNT(CASE WHEN f.status IN (''Recovering'',''Retrying'',''Resuming'') THEN 1 END) AS recovering, COUNT(CASE WHEN f.status=''Recovered'' AND CAST(f.recovered_at AS DATE)=CAST(SYSUTCDATETIME() AS DATE) THEN 1 END) AS recovered_today, CAST(AVG(CASE WHEN f.status=''Recovered'' THEN 97.0 ELSE 88.0 END) AS DECIMAL(8,2)) AS recovery_success_rate, 222 AS average_recovery_seconds, COUNT(CASE WHEN f.final_output_impact<>''on track'' THEN 1 END) AS final_output_risk, COUNT(CASE WHEN f.incident_id IS NOT NULL THEN 1 END) AS related_incidents, MAX(f.detected_at) AS last_occurrence, CAST(AVG(CASE WHEN f.status IN (''Escalated'',''Unrecoverable'') THEN 68.0 ELSE 94.0 END) AS DECIMAL(8,2)) AS health_percent FROM workflow_failures f LEFT JOIN workflow_failure_categories c ON c.id=f.failure_category_id GROUP BY f.organization_id, COALESCE(c.category_name, ''Uncategorized'')');
IF OBJECT_ID('vw_failure_recoveries', 'V') IS NOT NULL DROP VIEW vw_failure_recoveries;
EXEC('CREATE VIEW vw_failure_recoveries AS SELECT a.*, f.organization_id, f.workflow_name, f.failed_stage, f.failure_code FROM workflow_recovery_attempts a JOIN workflow_failures f ON f.id = a.workflow_failure_id');
IF OBJECT_ID('vw_failure_root_causes', 'V') IS NOT NULL DROP VIEW vw_failure_root_causes;
EXEC('CREATE VIEW vw_failure_root_causes AS SELECT r.*, f.organization_id, f.workflow_name, f.failure_code, f.final_output_impact FROM workflow_failure_root_causes r JOIN workflow_failures f ON f.id = r.workflow_failure_id');
IF OBJECT_ID('vw_failure_checkpoints', 'V') IS NOT NULL DROP VIEW vw_failure_checkpoints;
EXEC('CREATE VIEW vw_failure_checkpoints AS SELECT c.*, f.organization_id, f.workflow_name, f.failed_stage FROM workflow_recovery_checkpoints c JOIN workflow_failures f ON f.id = c.workflow_failure_id');
IF OBJECT_ID('vw_failure_output_preservation', 'V') IS NOT NULL DROP VIEW vw_failure_output_preservation;
EXEC('CREATE VIEW vw_failure_output_preservation AS SELECT o.*, f.organization_id, f.workflow_name FROM workflow_recovery_outputs o JOIN workflow_failures f ON f.id = o.workflow_failure_id');
IF OBJECT_ID('vw_repeated_failure_patterns', 'V') IS NOT NULL DROP VIEW vw_repeated_failure_patterns;
EXEC('CREATE VIEW vw_repeated_failure_patterns AS SELECT * FROM workflow_repeated_failure_patterns');
IF OBJECT_ID('vw_failure_incident_escalations', 'V') IS NOT NULL DROP VIEW vw_failure_incident_escalations;
EXEC('CREATE VIEW vw_failure_incident_escalations AS SELECT i.*, f.organization_id, f.workflow_name, f.failed_stage FROM workflow_recovery_incidents i JOIN workflow_failures f ON f.id = i.workflow_failure_id');
IF OBJECT_ID('vw_failure_final_output_protection', 'V') IS NOT NULL DROP VIEW vw_failure_final_output_protection;
EXEC('CREATE VIEW vw_failure_final_output_protection AS SELECT l.*, f.organization_id, f.workflow_name, f.failed_stage, f.reference_id FROM workflow_failure_final_output_links l JOIN workflow_failures f ON f.id = l.workflow_failure_id');
