SET NOCOUNT ON;

IF OBJECT_ID('workflow_log_sources', 'U') IS NULL
  CREATE TABLE workflow_log_sources (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, source_code NVARCHAR(120) NOT NULL, source_name NVARCHAR(180) NOT NULL, source_type NVARCHAR(80) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'active', last_event_at DATETIME2 NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('workflow_log_entries', 'U') IS NULL
  CREATE TABLE workflow_log_entries (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, timestamp DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    level NVARCHAR(40) NOT NULL, event_type NVARCHAR(160) NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL,
    workflow_version INT NOT NULL DEFAULT 1, workflow_instance_id UNIQUEIDENTIFIER NULL, workflow_stage_id UNIQUEIDENTIFIER NULL, stage_code NVARCHAR(120) NULL,
    transition_id UNIQUEIDENTIFIER NULL, transition_code NVARCHAR(120) NULL, trigger_id UNIQUEIDENTIFIER NULL, trigger_code NVARCHAR(120) NULL, action_id UNIQUEIDENTIFIER NULL,
    action_code NVARCHAR(120) NULL, agent_code NVARCHAR(120) NULL, agent_run_id NVARCHAR(180) NULL, job_id NVARCHAR(180) NULL, queue_name NVARCHAR(160) NULL,
    worker_id NVARCHAR(160) NULL, approval_request_id NVARCHAR(180) NULL, output_id NVARCHAR(180) NULL, incident_id NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL,
    message NVARCHAR(1000) NOT NULL, error_code NVARCHAR(120) NULL, duration_ms INT NOT NULL DEFAULT 0, retry_count INT NOT NULL DEFAULT 0,
    recovery_state NVARCHAR(120) NULL, approval_state NVARCHAR(120) NULL, output_state NVARCHAR(120) NULL, publishing_state NVARCHAR(120) NULL,
    analytics_state NVARCHAR(120) NULL, learning_state NVARCHAR(120) NULL, request_id NVARCHAR(180) NULL, trace_id NVARCHAR(180) NOT NULL,
    span_id NVARCHAR(180) NULL, correlation_id NVARCHAR(180) NULL, user_id NVARCHAR(180) NULL, brand_id NVARCHAR(180) NULL, brand NVARCHAR(180) NULL,
    environment NVARCHAR(80) NOT NULL DEFAULT 'production', confidence DECIMAL(8,2) NULL, risk NVARCHAR(80) NULL, cost DECIMAL(18,4) NULL,
    metadata_json NVARCHAR(MAX) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );

IF OBJECT_ID('workflow_log_properties', 'U') IS NULL
  CREATE TABLE workflow_log_properties (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_log_entry_id UNIQUEIDENTIFIER NOT NULL, property_name NVARCHAR(160) NOT NULL, property_value NVARCHAR(1000) NULL, is_sensitive BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_traces', 'U') IS NULL
  CREATE TABLE workflow_log_traces (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, trace_id NVARCHAR(180) NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL, workflow_name NVARCHAR(220) NULL, status NVARCHAR(80) NOT NULL, started_at DATETIME2 NOT NULL, ended_at DATETIME2 NULL, duration_ms INT NOT NULL DEFAULT 0, event_count INT NOT NULL DEFAULT 0, missing_event_count INT NOT NULL DEFAULT 0, final_output_status NVARCHAR(120) NULL, human_attention_required BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_spans', 'U') IS NULL
  CREATE TABLE workflow_log_spans (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, trace_id NVARCHAR(180) NOT NULL, span_id NVARCHAR(180) NOT NULL, parent_span_id NVARCHAR(180) NULL, span_name NVARCHAR(180) NOT NULL, span_type NVARCHAR(80) NOT NULL, status NVARCHAR(80) NOT NULL, start_time DATETIME2 NOT NULL, end_time DATETIME2 NULL, duration_ms INT NOT NULL DEFAULT 0, retry_count INT NOT NULL DEFAULT 0, recovery_state NVARCHAR(120) NULL, cost DECIMAL(18,4) NULL, output_ref NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_correlations', 'U') IS NULL
  CREATE TABLE workflow_log_correlations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, trace_id NVARCHAR(180) NOT NULL, correlation_id NVARCHAR(180) NOT NULL, request_id NVARCHAR(180) NULL, incident_id NVARCHAR(180) NULL, coverage_percent DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_stage_execution_logs', 'U') IS NULL
  CREATE TABLE workflow_stage_execution_logs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL, stage_code NVARCHAR(120) NOT NULL, stage_name NVARCHAR(180) NOT NULL, queue_wait_ms INT NOT NULL DEFAULT 0, execution_duration_ms INT NOT NULL DEFAULT 0, agent_duration_ms INT NOT NULL DEFAULT 0, approval_wait_ms INT NOT NULL DEFAULT 0, retry_duration_ms INT NOT NULL DEFAULT 0, recovery_duration_ms INT NOT NULL DEFAULT 0, output_validation_ms INT NOT NULL DEFAULT 0, total_duration_ms INT NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL, bottleneck NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_transition_logs', 'U') IS NULL
  CREATE TABLE workflow_transition_logs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL, source_stage NVARCHAR(180) NOT NULL, candidate_transitions NVARCHAR(500) NULL, conditions_evaluated NVARCHAR(1000) NULL, values_used NVARCHAR(1000) NULL, rules_applied NVARCHAR(500) NULL, transition_selected NVARCHAR(180) NOT NULL, alternatives_rejected NVARCHAR(500) NULL, confidence DECIMAL(8,2) NULL, risk NVARCHAR(80) NULL, policy NVARCHAR(180) NULL, guardrail_result NVARCHAR(180) NULL, audit_reference NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_agent_execution_logs', 'U') IS NULL
  CREATE TABLE workflow_agent_execution_logs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, trace_id NVARCHAR(180) NOT NULL, agent_code NVARCHAR(120) NOT NULL, agent_version NVARCHAR(80) NULL, objective NVARCHAR(500) NULL, prompt_version NVARCHAR(80) NULL, provider NVARCHAR(120) NULL, model NVARCHAR(120) NULL, tools_called NVARCHAR(500) NULL, retrieval_context NVARCHAR(500) NULL, started_at DATETIME2 NOT NULL, duration_ms INT NOT NULL DEFAULT 0, input_tokens INT NOT NULL DEFAULT 0, output_tokens INT NOT NULL DEFAULT 0, cost DECIMAL(18,4) NULL, confidence DECIMAL(8,2) NULL, validation_result NVARCHAR(120) NULL, output_ref NVARCHAR(180) NULL, retry_count INT NOT NULL DEFAULT 0, fallback_used BIT NOT NULL DEFAULT 0, error_code NVARCHAR(120) NULL, final_outcome NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_job_execution_logs', 'U') IS NULL
  CREATE TABLE workflow_job_execution_logs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, job_id NVARCHAR(180) NOT NULL, queue_name NVARCHAR(160) NOT NULL, worker_id NVARCHAR(160) NULL, attempts INT NOT NULL DEFAULT 0, lease_state NVARCHAR(120) NULL, heartbeat_count INT NOT NULL DEFAULT 0, progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, checkpoints INT NOT NULL DEFAULT 0, retry_schedule NVARCHAR(240) NULL, recovery_state NVARCHAR(120) NULL, output_ref NVARCHAR(180) NULL, duration_ms INT NOT NULL DEFAULT 0, failure_code NVARCHAR(120) NULL, final_state NVARCHAR(120) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_approval_logs', 'U') IS NULL
  CREATE TABLE workflow_approval_logs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, approval_request_id NVARCHAR(180) NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL, policy NVARCHAR(180) NULL, evaluation_scores NVARCHAR(500) NULL, decision NVARCHAR(120) NULL, decision_reason NVARCHAR(500) NULL, sla_status NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_logs', 'U') IS NULL
  CREATE TABLE workflow_recovery_logs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_instance_id UNIQUEIDENTIFIER NULL, trace_id NVARCHAR(180) NOT NULL, step_name NVARCHAR(180) NOT NULL, evidence NVARCHAR(500) NULL, confidence DECIMAL(8,2) NULL, risk NVARCHAR(80) NULL, outcome NVARCHAR(180) NULL, audit_reference NVARCHAR(180) NULL, duration_ms INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_output_lineage', 'U') IS NULL
  CREATE TABLE workflow_output_lineage (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, output_id NVARCHAR(180) NOT NULL, output_type NVARCHAR(120) NOT NULL, output_version NVARCHAR(80) NULL, source_workflow NVARCHAR(220) NULL, source_stage NVARCHAR(180) NULL, source_actor NVARCHAR(180) NULL, input_sources NVARCHAR(500) NULL, validation_status NVARCHAR(120) NULL, approval_status NVARCHAR(120) NULL, storage_location NVARCHAR(240) NULL, publishing_destination NVARCHAR(240) NULL, analytics_reference NVARCHAR(180) NULL, learning_reference NVARCHAR(180) NULL, final_business_result NVARCHAR(180) NULL, lineage_state NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_output_lineage_links', 'U') IS NULL
  CREATE TABLE workflow_output_lineage_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, parent_output_id NVARCHAR(180) NOT NULL, child_output_id NVARCHAR(180) NOT NULL, relationship_type NVARCHAR(120) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_error_clusters', 'U') IS NULL
  CREATE TABLE workflow_error_clusters (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, cluster_name NVARCHAR(220) NOT NULL, workflow_name NVARCHAR(220) NULL, stage_code NVARCHAR(120) NULL, error_code NVARCHAR(120) NULL, failure_signature NVARCHAR(240) NULL, agent_code NVARCHAR(120) NULL, provider NVARCHAR(120) NULL, model NVARCHAR(120) NULL, queue_name NVARCHAR(160) NULL, worker_id NVARCHAR(160) NULL, occurrence_count INT NOT NULL DEFAULT 0, first_seen_at DATETIME2 NOT NULL, last_seen_at DATETIME2 NOT NULL, affected_workflows INT NOT NULL DEFAULT 0, recovery_rate DECIMAL(8,2) NULL, incident_link NVARCHAR(180) NULL, root_cause NVARCHAR(500) NULL, permanent_fix_status NVARCHAR(120) NULL, final_output_impact NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_saved_views', 'U') IS NULL
  CREATE TABLE workflow_log_saved_views (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, view_name NVARCHAR(180) NOT NULL, query_text NVARCHAR(1000) NULL, filters_json NVARCHAR(MAX) NULL, owner NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_alert_rules', 'U') IS NULL
  CREATE TABLE workflow_log_alert_rules (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, name NVARCHAR(180) NOT NULL, query_text NVARCHAR(1000) NOT NULL, threshold_value DECIMAL(18,4) NOT NULL DEFAULT 0, evaluation_window NVARCHAR(80) NOT NULL, frequency NVARCHAR(80) NOT NULL, severity NVARCHAR(40) NOT NULL, notification NVARCHAR(240) NULL, auto_create_incident BIT NOT NULL DEFAULT 0, auto_run_remediation BIT NOT NULL DEFAULT 0, enabled BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_alert_executions', 'U') IS NULL
  CREATE TABLE workflow_log_alert_executions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_log_alert_rule_id UNIQUEIDENTIFIER NOT NULL, status NVARCHAR(80) NOT NULL, matched_count INT NOT NULL DEFAULT 0, incident_id NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_investigations', 'U') IS NULL
  CREATE TABLE workflow_log_investigations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, investigation_name NVARCHAR(180) NOT NULL, description NVARCHAR(500) NULL, owner NVARCHAR(180) NULL, assigned_team NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL, tags NVARCHAR(500) NULL, export_package NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_investigation_entries', 'U') IS NULL
  CREATE TABLE workflow_log_investigation_entries (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_log_investigation_id UNIQUEIDENTIFIER NOT NULL, workflow_log_entry_id UNIQUEIDENTIFIER NULL, trace_id NVARCHAR(180) NULL, incident_id NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_investigation_notes', 'U') IS NULL
  CREATE TABLE workflow_log_investigation_notes (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_log_investigation_id UNIQUEIDENTIFIER NOT NULL, note NVARCHAR(1000) NOT NULL, author NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_retention_policies', 'U') IS NULL
  CREATE TABLE workflow_log_retention_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, event_class NVARCHAR(180) NOT NULL, hot_days INT NOT NULL DEFAULT 7, warm_days INT NOT NULL DEFAULT 90, archive_days INT NOT NULL DEFAULT 365, retention_days INT NOT NULL, storage_tier NVARCHAR(80) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_exports', 'U') IS NULL
  CREATE TABLE workflow_log_exports (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, export_name NVARCHAR(180) NOT NULL, query_text NVARCHAR(1000) NULL, status NVARCHAR(80) NOT NULL, row_count INT NOT NULL DEFAULT 0, requested_by NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_ingestion_metrics', 'U') IS NULL
  CREATE TABLE workflow_log_ingestion_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_time DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), events_per_second DECIMAL(18,2) NOT NULL DEFAULT 0, ingestion_delay_ms INT NOT NULL DEFAULT 0, dropped_events INT NOT NULL DEFAULT 0, parsing_failures INT NOT NULL DEFAULT 0, storage_usage_gb DECIMAL(18,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_trace_completeness', 'U') IS NULL
  CREATE TABLE workflow_trace_completeness (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, trace_id NVARCHAR(180) NOT NULL, expected_events INT NOT NULL DEFAULT 0, received_events INT NOT NULL DEFAULT 0, missing_events INT NOT NULL DEFAULT 0, completeness_percent DECIMAL(8,2) NOT NULL DEFAULT 0, state NVARCHAR(120) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_log_archives', 'U') IS NULL
  CREATE TABLE workflow_log_archives (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, archive_name NVARCHAR(180) NOT NULL, date_from DATE NOT NULL, date_to DATE NOT NULL, storage_location NVARCHAR(240) NULL, status NVARCHAR(80) NOT NULL, compressed_size_gb DECIMAL(18,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_timestamp') CREATE INDEX ix_workflow_log_entries_timestamp ON workflow_log_entries(timestamp);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_level') CREATE INDEX ix_workflow_log_entries_level ON workflow_log_entries(level);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_event_type') CREATE INDEX ix_workflow_log_entries_event_type ON workflow_log_entries(event_type);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_instance') CREATE INDEX ix_workflow_log_entries_instance ON workflow_log_entries(workflow_instance_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_trace') CREATE INDEX ix_workflow_log_entries_trace ON workflow_log_entries(trace_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_correlation') CREATE INDEX ix_workflow_log_entries_correlation ON workflow_log_entries(correlation_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_agent') CREATE INDEX ix_workflow_log_entries_agent ON workflow_log_entries(agent_run_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_job') CREATE INDEX ix_workflow_log_entries_job ON workflow_log_entries(job_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_output') CREATE INDEX ix_workflow_log_entries_output ON workflow_log_entries(output_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_incident') CREATE INDEX ix_workflow_log_entries_incident ON workflow_log_entries(incident_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='ix_workflow_log_entries_org_brand_status') CREATE INDEX ix_workflow_log_entries_org_brand_status ON workflow_log_entries(organization_id, brand_id, status);

IF OBJECT_ID('vw_workflow_logs_summary', 'V') IS NOT NULL DROP VIEW vw_workflow_logs_summary;
EXEC('CREATE VIEW vw_workflow_logs_summary AS SELECT e.organization_id, COUNT(CASE WHEN CAST(e.timestamp AS DATE)=CAST(SYSUTCDATETIME() AS DATE) THEN 1 END) AS workflow_events_today, COUNT(DISTINCT CASE WHEN t.status<>''closed'' THEN t.trace_id END) AS active_workflow_traces, COUNT(CASE WHEN e.level IN (''error'',''critical'') THEN 1 END) AS failed_workflow_events, COUNT(CASE WHEN e.event_type LIKE ''workflow.recovery%'' THEN 1 END) AS recovery_events, COUNT(CASE WHEN e.event_type LIKE ''workflow.approval%'' THEN 1 END) AS approval_events, COUNT(CASE WHEN e.agent_code IS NOT NULL THEN 1 END) AS ai_agent_events, COUNT(CASE WHEN e.output_state IN (''confirmed'',''ready'') OR e.event_type LIKE ''workflow.output%'' THEN 1 END) AS final_output_confirmations, CAST(AVG(NULLIF(e.duration_ms,0)) AS INT) AS average_trace_duration_ms, COALESCE(MAX(m.ingestion_delay_ms),0) AS log_ingestion_delay_ms, COUNT(CASE WHEN e.status=''human_attention_required'' THEN 1 END) AS human_attention_required, MAX(e.timestamp) AS last_log_event, CAST(AVG(COALESCE(c.completeness_percent,96)) AS DECIMAL(8,2)) AS correlation_coverage FROM workflow_log_entries e LEFT JOIN workflow_log_traces t ON t.organization_id=e.organization_id AND t.trace_id=e.trace_id LEFT JOIN workflow_log_ingestion_metrics m ON m.organization_id=e.organization_id LEFT JOIN workflow_trace_completeness c ON c.organization_id=e.organization_id AND c.trace_id=e.trace_id GROUP BY e.organization_id');
IF OBJECT_ID('vw_workflow_event_stream', 'V') IS NOT NULL DROP VIEW vw_workflow_event_stream;
EXEC('CREATE VIEW vw_workflow_event_stream AS SELECT e.*, COALESCE(org.name,''Unknown Organization'') AS organization FROM workflow_log_entries e LEFT JOIN organizations org ON org.id=e.organization_id');
IF OBJECT_ID('vw_workflow_trace_explorer', 'V') IS NOT NULL DROP VIEW vw_workflow_trace_explorer;
EXEC('CREATE VIEW vw_workflow_trace_explorer AS SELECT s.*, t.workflow_name, t.workflow_instance_id, t.final_output_status, t.human_attention_required FROM workflow_log_spans s LEFT JOIN workflow_log_traces t ON t.organization_id=s.organization_id AND t.trace_id=s.trace_id');
IF OBJECT_ID('vw_workflow_stage_timeline', 'V') IS NOT NULL DROP VIEW vw_workflow_stage_timeline;
EXEC('CREATE VIEW vw_workflow_stage_timeline AS SELECT * FROM workflow_stage_execution_logs');
IF OBJECT_ID('vw_workflow_recovery_history', 'V') IS NOT NULL DROP VIEW vw_workflow_recovery_history;
EXEC('CREATE VIEW vw_workflow_recovery_history AS SELECT * FROM workflow_recovery_logs');
IF OBJECT_ID('vw_workflow_output_lineage', 'V') IS NOT NULL DROP VIEW vw_workflow_output_lineage;
EXEC('CREATE VIEW vw_workflow_output_lineage AS SELECT * FROM workflow_output_lineage');
IF OBJECT_ID('vw_workflow_error_clusters', 'V') IS NOT NULL DROP VIEW vw_workflow_error_clusters;
EXEC('CREATE VIEW vw_workflow_error_clusters AS SELECT * FROM workflow_error_clusters');
IF OBJECT_ID('vw_workflow_trace_completeness', 'V') IS NOT NULL DROP VIEW vw_workflow_trace_completeness;
EXEC('CREATE VIEW vw_workflow_trace_completeness AS SELECT * FROM workflow_trace_completeness');
IF OBJECT_ID('vw_workflow_log_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_log_analytics;
EXEC('CREATE VIEW vw_workflow_log_analytics AS SELECT organization_id, event_type, level, workflow_name, stage_code, queue_name, agent_code, COUNT(*) AS event_count, COUNT(CASE WHEN level IN (''error'',''critical'') THEN 1 END) AS error_count, CAST(AVG(NULLIF(duration_ms,0)) AS INT) AS average_duration_ms, SUM(COALESCE(cost,0)) AS total_cost, CAST(AVG(COALESCE(confidence,90)) AS DECIMAL(8,2)) AS average_confidence FROM workflow_log_entries GROUP BY organization_id, event_type, level, workflow_name, stage_code, queue_name, agent_code');
