SET NOCOUNT ON;

IF OBJECT_ID('workflow_template_categories', 'U') IS NULL
  CREATE TABLE workflow_template_categories (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NULL, category_name NVARCHAR(180) NOT NULL, description NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_templates', 'U') IS NULL
  CREATE TABLE workflow_templates (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NULL, template_code NVARCHAR(120) NOT NULL, template_name NVARCHAR(220) NOT NULL,
    description NVARCHAR(1000) NULL, category_id UNIQUEIDENTIFIER NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Draft', validation_status NVARCHAR(80) NOT NULL DEFAULT 'not_validated',
    scope NVARCHAR(80) NOT NULL DEFAULT 'system', current_version INT NOT NULL DEFAULT 1, published_version INT NULL, complexity NVARCHAR(80) NOT NULL DEFAULT 'medium',
    estimated_duration_ms INT NOT NULL DEFAULT 0, estimated_cost DECIMAL(18,4) NOT NULL DEFAULT 0, stage_count INT NOT NULL DEFAULT 0, ai_agent_count INT NOT NULL DEFAULT 0,
    approval_required BIT NOT NULL DEFAULT 1, approval_configured BIT NOT NULL DEFAULT 1, recovery_enabled BIT NOT NULL DEFAULT 1, publishing_configured BIT NOT NULL DEFAULT 1,
    analytics_configured BIT NOT NULL DEFAULT 1, learning_configured BIT NOT NULL DEFAULT 1, final_output_ready BIT NOT NULL DEFAULT 1, recommended BIT NOT NULL DEFAULT 0,
    usage_count INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, recovery_coverage DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_readiness DECIMAL(8,2) NOT NULL DEFAULT 0,
    owner_id NVARCHAR(180) NULL, owner_name NVARCHAR(180) NULL, organization_scope NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
ELSE
BEGIN
  IF COL_LENGTH('workflow_templates','organization_id') IS NULL ALTER TABLE workflow_templates ADD organization_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_templates','template_code') IS NULL ALTER TABLE workflow_templates ADD template_code NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_templates','template_name') IS NULL ALTER TABLE workflow_templates ADD template_name NVARCHAR(220) NULL;
  IF COL_LENGTH('workflow_templates','description') IS NULL ALTER TABLE workflow_templates ADD description NVARCHAR(1000) NULL;
  IF COL_LENGTH('workflow_templates','category_id') IS NULL ALTER TABLE workflow_templates ADD category_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_templates','category') IS NULL ALTER TABLE workflow_templates ADD category NVARCHAR(180) NOT NULL CONSTRAINT df_workflow_templates_category DEFAULT 'General';
  IF COL_LENGTH('workflow_templates','status') IS NULL ALTER TABLE workflow_templates ADD status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_templates_status DEFAULT 'Draft';
  IF COL_LENGTH('workflow_templates','validation_status') IS NULL ALTER TABLE workflow_templates ADD validation_status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_templates_validation DEFAULT 'not_validated';
  IF COL_LENGTH('workflow_templates','scope') IS NULL ALTER TABLE workflow_templates ADD scope NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_templates_scope DEFAULT 'system';
  IF COL_LENGTH('workflow_templates','current_version') IS NULL ALTER TABLE workflow_templates ADD current_version INT NOT NULL CONSTRAINT df_workflow_templates_current_version DEFAULT 1;
  IF COL_LENGTH('workflow_templates','published_version') IS NULL ALTER TABLE workflow_templates ADD published_version INT NULL;
  IF COL_LENGTH('workflow_templates','complexity') IS NULL ALTER TABLE workflow_templates ADD complexity NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_templates_complexity DEFAULT 'medium';
  IF COL_LENGTH('workflow_templates','estimated_duration_ms') IS NULL ALTER TABLE workflow_templates ADD estimated_duration_ms INT NOT NULL CONSTRAINT df_workflow_templates_duration DEFAULT 0;
  IF COL_LENGTH('workflow_templates','estimated_cost') IS NULL ALTER TABLE workflow_templates ADD estimated_cost DECIMAL(18,4) NOT NULL CONSTRAINT df_workflow_templates_cost DEFAULT 0;
  IF COL_LENGTH('workflow_templates','stage_count') IS NULL ALTER TABLE workflow_templates ADD stage_count INT NOT NULL CONSTRAINT df_workflow_templates_stage_count DEFAULT 0;
  IF COL_LENGTH('workflow_templates','ai_agent_count') IS NULL ALTER TABLE workflow_templates ADD ai_agent_count INT NOT NULL CONSTRAINT df_workflow_templates_agent_count DEFAULT 0;
  IF COL_LENGTH('workflow_templates','approval_required') IS NULL ALTER TABLE workflow_templates ADD approval_required BIT NOT NULL CONSTRAINT df_workflow_templates_approval_required DEFAULT 1;
  IF COL_LENGTH('workflow_templates','approval_configured') IS NULL ALTER TABLE workflow_templates ADD approval_configured BIT NOT NULL CONSTRAINT df_workflow_templates_approval DEFAULT 1;
  IF COL_LENGTH('workflow_templates','recovery_enabled') IS NULL ALTER TABLE workflow_templates ADD recovery_enabled BIT NOT NULL CONSTRAINT df_workflow_templates_recovery DEFAULT 1;
  IF COL_LENGTH('workflow_templates','publishing_configured') IS NULL ALTER TABLE workflow_templates ADD publishing_configured BIT NOT NULL CONSTRAINT df_workflow_templates_publishing DEFAULT 1;
  IF COL_LENGTH('workflow_templates','analytics_configured') IS NULL ALTER TABLE workflow_templates ADD analytics_configured BIT NOT NULL CONSTRAINT df_workflow_templates_analytics DEFAULT 1;
  IF COL_LENGTH('workflow_templates','learning_configured') IS NULL ALTER TABLE workflow_templates ADD learning_configured BIT NOT NULL CONSTRAINT df_workflow_templates_learning DEFAULT 1;
  IF COL_LENGTH('workflow_templates','final_output_ready') IS NULL ALTER TABLE workflow_templates ADD final_output_ready BIT NOT NULL CONSTRAINT df_workflow_templates_output_ready DEFAULT 1;
  IF COL_LENGTH('workflow_templates','recommended') IS NULL ALTER TABLE workflow_templates ADD recommended BIT NOT NULL CONSTRAINT df_workflow_templates_recommended DEFAULT 0;
  IF COL_LENGTH('workflow_templates','usage_count') IS NULL ALTER TABLE workflow_templates ADD usage_count INT NOT NULL CONSTRAINT df_workflow_templates_usage DEFAULT 0;
  IF COL_LENGTH('workflow_templates','success_rate') IS NULL ALTER TABLE workflow_templates ADD success_rate DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_templates_success DEFAULT 0;
  IF COL_LENGTH('workflow_templates','recovery_coverage') IS NULL ALTER TABLE workflow_templates ADD recovery_coverage DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_templates_recovery_coverage DEFAULT 0;
  IF COL_LENGTH('workflow_templates','final_output_readiness') IS NULL ALTER TABLE workflow_templates ADD final_output_readiness DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_templates_final_readiness DEFAULT 0;
  IF COL_LENGTH('workflow_templates','owner_id') IS NULL ALTER TABLE workflow_templates ADD owner_id NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_templates','owner_name') IS NULL ALTER TABLE workflow_templates ADD owner_name NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_templates','organization_scope') IS NULL ALTER TABLE workflow_templates ADD organization_scope NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_templates','created_at') IS NULL ALTER TABLE workflow_templates ADD created_at DATETIME2 NOT NULL CONSTRAINT df_workflow_templates_created DEFAULT SYSUTCDATETIME();
  IF COL_LENGTH('workflow_templates','updated_at') IS NULL ALTER TABLE workflow_templates ADD updated_at DATETIME2 NOT NULL CONSTRAINT df_workflow_templates_updated DEFAULT SYSUTCDATETIME();
  EXEC('UPDATE workflow_templates SET category = COALESCE(NULLIF(category, ''''), ''General''), template_code = COALESCE(template_code, CONCAT(''TPL-LEGACY-'', RIGHT(CONVERT(NVARCHAR(36), id), 6))), template_name = COALESCE(template_name, ''Legacy Workflow Template''), description = COALESCE(description, ''Legacy template upgraded for dashboard compatibility''), validation_status = COALESCE(NULLIF(validation_status, ''''), ''Valid''), owner_name = COALESCE(owner_name, ''Autonomous Template Engine''), organization_scope = COALESCE(organization_scope, ''AI Media Group'') WHERE template_code IS NULL OR template_name IS NULL OR category IS NULL');
END;
IF OBJECT_ID('workflow_template_versions', 'U') IS NULL
  CREATE TABLE workflow_template_versions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, template_id UNIQUEIDENTIFIER NULL, version_number INT NOT NULL, status NVARCHAR(80) NOT NULL, template_json NVARCHAR(MAX) NOT NULL DEFAULT '{}', created_by NVARCHAR(180) NULL, change_summary NVARCHAR(500) NULL, validation_status NVARCHAR(80) NULL, approval_status NVARCHAR(80) NULL, published_environments NVARCHAR(240) NULL, instantiation_count INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, rollback_eligible BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
ELSE
BEGIN
  IF COL_LENGTH('workflow_template_versions','workflow_template_id') IS NULL ALTER TABLE workflow_template_versions ADD workflow_template_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_template_versions','template_id') IS NULL ALTER TABLE workflow_template_versions ADD template_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_template_versions','version_number') IS NULL ALTER TABLE workflow_template_versions ADD version_number INT NOT NULL CONSTRAINT df_workflow_template_versions_number DEFAULT 1;
  IF COL_LENGTH('workflow_template_versions','status') IS NULL ALTER TABLE workflow_template_versions ADD status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_template_versions_status DEFAULT 'Draft';
  IF COL_LENGTH('workflow_template_versions','template_json') IS NULL ALTER TABLE workflow_template_versions ADD template_json NVARCHAR(MAX) NOT NULL CONSTRAINT df_workflow_template_versions_json DEFAULT '{}';
  IF COL_LENGTH('workflow_template_versions','created_by') IS NULL ALTER TABLE workflow_template_versions ADD created_by NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_template_versions','change_summary') IS NULL ALTER TABLE workflow_template_versions ADD change_summary NVARCHAR(500) NULL;
  IF COL_LENGTH('workflow_template_versions','validation_status') IS NULL ALTER TABLE workflow_template_versions ADD validation_status NVARCHAR(80) NULL;
  IF COL_LENGTH('workflow_template_versions','approval_status') IS NULL ALTER TABLE workflow_template_versions ADD approval_status NVARCHAR(80) NULL;
  IF COL_LENGTH('workflow_template_versions','published_environments') IS NULL ALTER TABLE workflow_template_versions ADD published_environments NVARCHAR(240) NULL;
  IF COL_LENGTH('workflow_template_versions','instantiation_count') IS NULL ALTER TABLE workflow_template_versions ADD instantiation_count INT NOT NULL CONSTRAINT df_workflow_template_versions_instantiations DEFAULT 0;
  IF COL_LENGTH('workflow_template_versions','success_rate') IS NULL ALTER TABLE workflow_template_versions ADD success_rate DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_template_versions_success DEFAULT 0;
  IF COL_LENGTH('workflow_template_versions','rollback_eligible') IS NULL ALTER TABLE workflow_template_versions ADD rollback_eligible BIT NOT NULL CONSTRAINT df_workflow_template_versions_rollback DEFAULT 1;
  IF COL_LENGTH('workflow_template_versions','created_at') IS NULL ALTER TABLE workflow_template_versions ADD created_at DATETIME2 NOT NULL CONSTRAINT df_workflow_template_versions_created DEFAULT SYSUTCDATETIME();
END;
IF OBJECT_ID('workflow_template_stages', 'U') IS NULL
  CREATE TABLE workflow_template_stages (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, stage_code NVARCHAR(120) NOT NULL, stage_name NVARCHAR(180) NOT NULL, stage_type NVARCHAR(80) NOT NULL, sequence_no INT NOT NULL, required_agent NVARCHAR(120) NULL, output_schema NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_transitions', 'U') IS NULL
  CREATE TABLE workflow_template_transitions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, source_stage NVARCHAR(120) NOT NULL, target_stage NVARCHAR(120) NOT NULL, condition_expression NVARCHAR(500) NULL, guardrail NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_triggers', 'U') IS NULL
  CREATE TABLE workflow_template_triggers (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, trigger_code NVARCHAR(120) NOT NULL, trigger_type NVARCHAR(80) NOT NULL, default_payload NVARCHAR(MAX) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_actions', 'U') IS NULL
  CREATE TABLE workflow_template_actions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, action_code NVARCHAR(120) NOT NULL, action_type NVARCHAR(80) NOT NULL, tool_permission NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_variables', 'U') IS NULL
  CREATE TABLE workflow_template_variables (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, variable_name NVARCHAR(120) NOT NULL, variable_type NVARCHAR(80) NOT NULL, required BIT NOT NULL DEFAULT 1, default_value NVARCHAR(500) NULL, autonomous_default_available BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_input_schemas', 'U') IS NULL
  CREATE TABLE workflow_template_input_schemas (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, schema_name NVARCHAR(160) NOT NULL, schema_json NVARCHAR(MAX) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_output_schemas', 'U') IS NULL
  CREATE TABLE workflow_template_output_schemas (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, schema_name NVARCHAR(160) NOT NULL, schema_json NVARCHAR(MAX) NOT NULL, final_output BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_agent_mappings', 'U') IS NULL
  CREATE TABLE workflow_template_agent_mappings (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, agent_code NVARCHAR(120) NOT NULL, provider NVARCHAR(120) NULL, model NVARCHAR(120) NULL, prompt_version NVARCHAR(80) NULL, outdated BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_prompt_mappings', 'U') IS NULL
  CREATE TABLE workflow_template_prompt_mappings (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, prompt_code NVARCHAR(120) NOT NULL, prompt_version NVARCHAR(80) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_approval_policies', 'U') IS NULL
  CREATE TABLE workflow_template_approval_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(180) NOT NULL, auto_approval_rules NVARCHAR(500) NULL, quality_gates NVARCHAR(500) NULL, compliance_gates NVARCHAR(500) NULL, escalation NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_recovery_policies', 'U') IS NULL
  CREATE TABLE workflow_template_recovery_policies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(180) NOT NULL, checkpoint_enabled BIT NOT NULL DEFAULT 1, compensation_enabled BIT NOT NULL DEFAULT 1, provider_fallback BIT NOT NULL DEFAULT 1, model_fallback BIT NOT NULL DEFAULT 1, worker_reassignment BIT NOT NULL DEFAULT 1, dead_letter_handling BIT NOT NULL DEFAULT 1, incident_creation BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_quality_gates', 'U') IS NULL
  CREATE TABLE workflow_template_quality_gates (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, gate_name NVARCHAR(180) NOT NULL, threshold_percent DECIMAL(8,2) NOT NULL DEFAULT 0, stage_code NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_dependencies', 'U') IS NULL
  CREATE TABLE workflow_template_dependencies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, dependency_type NVARCHAR(80) NOT NULL, dependency_name NVARCHAR(180) NOT NULL, dependency_version NVARCHAR(80) NULL, status NVARCHAR(80) NOT NULL, impact NVARCHAR(80) NULL, shared_component BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_instantiations', 'U') IS NULL
  CREATE TABLE workflow_template_instantiations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, organization_id UNIQUEIDENTIFIER NULL, brand NVARCHAR(180) NULL, environment NVARCHAR(80) NOT NULL, objective NVARCHAR(500) NULL, status NVARCHAR(80) NOT NULL, created_workflow_definition_id UNIQUEIDENTIFIER NULL, estimated_cost DECIMAL(18,4) NULL, estimated_duration_ms INT NULL, validation_result NVARCHAR(80) NULL, final_output_readiness DECIMAL(8,2) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_instantiation_steps', 'U') IS NULL
  CREATE TABLE workflow_template_instantiation_steps (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_instantiation_id UNIQUEIDENTIFIER NOT NULL, step_name NVARCHAR(180) NOT NULL, status NVARCHAR(80) NOT NULL, sequence_no INT NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_validation_runs', 'U') IS NULL
  CREATE TABLE workflow_template_validation_runs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, status NVARCHAR(80) NOT NULL, validation_score DECIMAL(8,2) NOT NULL DEFAULT 0, error_count INT NOT NULL DEFAULT 0, warning_count INT NOT NULL DEFAULT 0, recommendation_count INT NOT NULL DEFAULT 0, auto_fix_available INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_validation_results', 'U') IS NULL
  CREATE TABLE workflow_template_validation_results (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_validation_run_id UNIQUEIDENTIFIER NOT NULL, result_type NVARCHAR(80) NOT NULL, area NVARCHAR(120) NOT NULL, affected_stage NVARCHAR(120) NULL, message NVARCHAR(500) NOT NULL, suggested_fix NVARCHAR(500) NULL, auto_fix_available BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_simulation_runs', 'U') IS NULL
  CREATE TABLE workflow_template_simulation_runs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, organization_id UNIQUEIDENTIFIER NULL, brand NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL, estimated_duration_ms INT NOT NULL DEFAULT 0, estimated_cost DECIMAL(18,4) NOT NULL DEFAULT 0, final_output_readiness DECIMAL(8,2) NOT NULL DEFAULT 0, risk_summary NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_simulation_steps', 'U') IS NULL
  CREATE TABLE workflow_template_simulation_steps (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_simulation_run_id UNIQUEIDENTIFIER NOT NULL, step_name NVARCHAR(180) NOT NULL, queue_usage NVARCHAR(180) NULL, worker_usage NVARCHAR(180) NULL, duration_ms INT NOT NULL DEFAULT 0, estimated_cost DECIMAL(18,4) NOT NULL DEFAULT 0, final_state NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_performance', 'U') IS NULL
  CREATE TABLE workflow_template_performance (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, metric_date DATE NOT NULL DEFAULT CAST(SYSUTCDATETIME() AS DATE), instantiations INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_duration_ms INT NOT NULL DEFAULT 0, average_cost DECIMAL(18,4) NOT NULL DEFAULT 0, approval_delay_ms INT NOT NULL DEFAULT 0, publishing_completion DECIMAL(8,2) NOT NULL DEFAULT 0, analytics_completion DECIMAL(8,2) NOT NULL DEFAULT 0, learning_completion DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_rate DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_recommendations', 'U') IS NULL
  CREATE TABLE workflow_template_recommendations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, recommendation_type NVARCHAR(120) NOT NULL, title NVARCHAR(220) NOT NULL, recommendation NVARCHAR(500) NOT NULL, match_score DECIMAL(8,2) NULL, estimated_success_rate DECIMAL(8,2) NULL, estimated_duration_ms INT NULL, estimated_cost DECIMAL(18,4) NULL, required_configuration NVARCHAR(500) NULL, risk NVARCHAR(160) NULL, inside_guardrails BIT NOT NULL DEFAULT 1, status NVARCHAR(80) NOT NULL DEFAULT 'open', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_change_history', 'U') IS NULL
  CREATE TABLE workflow_template_change_history (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, change_type NVARCHAR(120) NOT NULL, change_summary NVARCHAR(500) NOT NULL, audit_reference NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_documentation', 'U') IS NULL
  CREATE TABLE workflow_template_documentation (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, doc_type NVARCHAR(120) NOT NULL, title NVARCHAR(220) NOT NULL, content_summary NVARCHAR(1000) NULL, generated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_tags', 'U') IS NULL
  CREATE TABLE workflow_template_tags (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, tag NVARCHAR(120) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_template_final_output_links', 'U') IS NULL
  CREATE TABLE workflow_template_final_output_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_template_id UNIQUEIDENTIFIER NOT NULL, trigger_linked BIT NOT NULL DEFAULT 1, stages_linked BIT NOT NULL DEFAULT 1, agents_linked BIT NOT NULL DEFAULT 1, outputs_linked BIT NOT NULL DEFAULT 1, approval_linked BIT NOT NULL DEFAULT 1, publishing_linked BIT NOT NULL DEFAULT 1, analytics_linked BIT NOT NULL DEFAULT 1, learning_linked BIT NOT NULL DEFAULT 1, business_result_linked BIT NOT NULL DEFAULT 1, readiness_percent DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('vw_workflow_templates_list', 'V') IS NOT NULL DROP VIEW vw_workflow_templates_list;
EXEC('CREATE VIEW vw_workflow_templates_list AS SELECT t.*, COALESCE(c.category_name,''Uncategorized'') AS category_name FROM workflow_templates t LEFT JOIN workflow_template_categories c ON c.id=t.category_id');
IF OBJECT_ID('vw_workflow_template_health', 'V') IS NOT NULL DROP VIEW vw_workflow_template_health;
EXEC('CREATE VIEW vw_workflow_template_health AS SELECT COALESCE(organization_id, CAST(0x0 AS UNIQUEIDENTIFIER)) AS organization_key, COUNT(*) AS total_templates, COUNT(CASE WHEN status IN (''Approved'',''Published'',''Production Ready'') THEN 1 END) AS approved_templates, COUNT(CASE WHEN status=''Production Ready'' THEN 1 END) AS production_ready, COUNT(CASE WHEN status=''Draft'' THEN 1 END) AS draft_templates, COUNT(CASE WHEN validation_status=''Invalid'' THEN 1 END) AS invalid_templates, COUNT(CASE WHEN status=''Deprecated'' THEN 1 END) AS deprecated_templates, COUNT(CASE WHEN recovery_enabled=0 THEN 1 END) AS missing_recovery, COUNT(CASE WHEN approval_configured=0 THEN 1 END) AS missing_approval_logic, COUNT(CASE WHEN publishing_configured=0 THEN 1 END) AS missing_publishing, COUNT(CASE WHEN analytics_configured=0 THEN 1 END) AS missing_analytics, COUNT(CASE WHEN learning_configured=0 THEN 1 END) AS missing_learning, CAST(AVG(success_rate) AS DECIMAL(8,2)) AS average_success_rate, CAST(AVG(final_output_readiness) AS DECIMAL(8,2)) AS average_final_output_rate, CAST(AVG(CASE WHEN validation_status=''Valid'' THEN 96.0 WHEN validation_status=''Warning'' THEN 82.0 ELSE 58.0 END) AS DECIMAL(8,2)) AS average_validation_score, MAX(updated_at) AS last_validation_run, COUNT(CASE WHEN validation_status IN (''Invalid'',''Warning'') THEN 1 END) AS human_attention_required FROM workflow_templates GROUP BY COALESCE(organization_id, CAST(0x0 AS UNIQUEIDENTIFIER))');
IF OBJECT_ID('vw_workflow_template_categories', 'V') IS NOT NULL DROP VIEW vw_workflow_template_categories;
EXEC('CREATE VIEW vw_workflow_template_categories AS SELECT c.id, c.organization_id, c.category_name, COUNT(t.id) AS template_count, COUNT(CASE WHEN t.status IN (''Approved'',''Production Ready'',''Published'') THEN 1 END) AS approved, COUNT(CASE WHEN t.status=''Draft'' THEN 1 END) AS draft, COUNT(CASE WHEN t.validation_status=''Invalid'' THEN 1 END) AS invalid, SUM(COALESCE(t.usage_count,0)) AS instantiations, CAST(AVG(COALESCE(t.success_rate,0)) AS DECIMAL(8,2)) AS success_rate, CAST(AVG(COALESCE(t.estimated_duration_ms,0)) AS INT) AS average_duration_ms, CAST(AVG(COALESCE(t.recovery_coverage,0)) AS DECIMAL(8,2)) AS recovery_coverage, CAST(AVG(COALESCE(t.final_output_readiness,0)) AS DECIMAL(8,2)) AS final_output_readiness, MAX(t.updated_at) AS last_updated, CAST(AVG(CASE WHEN t.validation_status=''Valid'' THEN 96.0 WHEN t.validation_status=''Warning'' THEN 82.0 ELSE 55.0 END) AS DECIMAL(8,2)) AS health_percent FROM workflow_template_categories c LEFT JOIN workflow_templates t ON t.category_id=c.id GROUP BY c.id, c.organization_id, c.category_name');
IF OBJECT_ID('vw_workflow_template_performance', 'V') IS NOT NULL DROP VIEW vw_workflow_template_performance;
EXEC('CREATE VIEW vw_workflow_template_performance AS SELECT p.*, t.template_code, t.template_name, t.organization_id, t.category_id FROM workflow_template_performance p JOIN workflow_templates t ON t.id=p.workflow_template_id');
IF OBJECT_ID('vw_workflow_template_dependencies', 'V') IS NOT NULL DROP VIEW vw_workflow_template_dependencies;
EXEC('CREATE VIEW vw_workflow_template_dependencies AS SELECT d.*, t.template_code, t.template_name, t.organization_id FROM workflow_template_dependencies d JOIN workflow_templates t ON t.id=d.workflow_template_id');
IF OBJECT_ID('vw_workflow_template_recommendations', 'V') IS NOT NULL DROP VIEW vw_workflow_template_recommendations;
EXEC('CREATE VIEW vw_workflow_template_recommendations AS SELECT r.*, t.template_code, t.template_name, t.organization_id, t.final_output_readiness, t.recovery_coverage FROM workflow_template_recommendations r JOIN workflow_templates t ON t.id=r.workflow_template_id');
IF OBJECT_ID('vw_workflow_template_final_output_readiness', 'V') IS NOT NULL DROP VIEW vw_workflow_template_final_output_readiness;
EXEC('CREATE VIEW vw_workflow_template_final_output_readiness AS SELECT l.*, t.template_code, t.template_name, t.organization_id, t.category_id FROM workflow_template_final_output_links l JOIN workflow_templates t ON t.id=l.workflow_template_id');
