SET NOCOUNT ON;

IF OBJECT_ID('workflow_definition_versions', 'U') IS NULL
  CREATE TABLE workflow_definition_versions (
    id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL,
    workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, version_number INT NOT NULL, previous_version_id UNIQUEIDENTIFIER NULL,
    version_status NVARCHAR(80) NOT NULL DEFAULT 'Draft', environment NVARCHAR(80) NOT NULL DEFAULT 'production', validation_status NVARCHAR(80) NOT NULL DEFAULT 'Not Evaluated',
    compatibility_status NVARCHAR(80) NOT NULL DEFAULT 'Unknown', release_status NVARCHAR(80) NOT NULL DEFAULT 'Not Started', rollout_strategy NVARCHAR(120) NULL,
    rollout_percent DECIMAL(8,2) NOT NULL DEFAULT 0, health_percent DECIMAL(8,2) NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0,
    failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_duration_ms INT NOT NULL DEFAULT 0, average_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
    active_instances INT NOT NULL DEFAULT 0, dependency_changes INT NOT NULL DEFAULT 0, agent_changes INT NOT NULL DEFAULT 0, model_changes INT NOT NULL DEFAULT 0,
    prompt_changes INT NOT NULL DEFAULT 0, permission_changes INT NOT NULL DEFAULT 0, output_changes INT NOT NULL DEFAULT 0,
    final_output_compatible DECIMAL(8,2) NOT NULL DEFAULT 0, created_by NVARCHAR(180) NULL, owner NVARCHAR(180) NULL, release_notes NVARCHAR(1000) NULL,
    created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), published_at DATETIME2 NULL, superseded_at DATETIME2 NULL, archived_at DATETIME2 NULL, updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
  );
ELSE
BEGIN
  IF COL_LENGTH('workflow_definition_versions','organization_id') IS NULL ALTER TABLE workflow_definition_versions ADD organization_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_definition_versions','workflow_definition_id') IS NULL ALTER TABLE workflow_definition_versions ADD workflow_definition_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_definition_versions','workflow_code') IS NULL ALTER TABLE workflow_definition_versions ADD workflow_code NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_definition_versions','workflow_name') IS NULL ALTER TABLE workflow_definition_versions ADD workflow_name NVARCHAR(220) NULL;
  IF COL_LENGTH('workflow_definition_versions','version_number') IS NULL ALTER TABLE workflow_definition_versions ADD version_number INT NOT NULL CONSTRAINT df_workflow_definition_versions_number DEFAULT 1;
  IF COL_LENGTH('workflow_definition_versions','previous_version_id') IS NULL ALTER TABLE workflow_definition_versions ADD previous_version_id UNIQUEIDENTIFIER NULL;
  IF COL_LENGTH('workflow_definition_versions','version_status') IS NULL ALTER TABLE workflow_definition_versions ADD version_status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_definition_versions_status DEFAULT 'Draft';
  IF COL_LENGTH('workflow_definition_versions','environment') IS NULL ALTER TABLE workflow_definition_versions ADD environment NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_definition_versions_environment DEFAULT 'production';
  IF COL_LENGTH('workflow_definition_versions','validation_status') IS NULL ALTER TABLE workflow_definition_versions ADD validation_status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_definition_versions_validation DEFAULT 'Not Evaluated';
  IF COL_LENGTH('workflow_definition_versions','compatibility_status') IS NULL ALTER TABLE workflow_definition_versions ADD compatibility_status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_definition_versions_compat DEFAULT 'Unknown';
  IF COL_LENGTH('workflow_definition_versions','release_status') IS NULL ALTER TABLE workflow_definition_versions ADD release_status NVARCHAR(80) NOT NULL CONSTRAINT df_workflow_definition_versions_release DEFAULT 'Not Started';
  IF COL_LENGTH('workflow_definition_versions','rollout_strategy') IS NULL ALTER TABLE workflow_definition_versions ADD rollout_strategy NVARCHAR(120) NULL;
  IF COL_LENGTH('workflow_definition_versions','rollout_percent') IS NULL ALTER TABLE workflow_definition_versions ADD rollout_percent DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_definition_versions_rollout DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','health_percent') IS NULL ALTER TABLE workflow_definition_versions ADD health_percent DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_definition_versions_health DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','success_rate') IS NULL ALTER TABLE workflow_definition_versions ADD success_rate DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_definition_versions_success DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','failure_rate') IS NULL ALTER TABLE workflow_definition_versions ADD failure_rate DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_definition_versions_failure DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','average_duration_ms') IS NULL ALTER TABLE workflow_definition_versions ADD average_duration_ms INT NOT NULL CONSTRAINT df_workflow_definition_versions_duration DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','average_cost') IS NULL ALTER TABLE workflow_definition_versions ADD average_cost DECIMAL(18,4) NOT NULL CONSTRAINT df_workflow_definition_versions_cost DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','active_instances') IS NULL ALTER TABLE workflow_definition_versions ADD active_instances INT NOT NULL CONSTRAINT df_workflow_definition_versions_instances DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','dependency_changes') IS NULL ALTER TABLE workflow_definition_versions ADD dependency_changes INT NOT NULL CONSTRAINT df_workflow_definition_versions_dependency_changes DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','agent_changes') IS NULL ALTER TABLE workflow_definition_versions ADD agent_changes INT NOT NULL CONSTRAINT df_workflow_definition_versions_agent_changes DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','model_changes') IS NULL ALTER TABLE workflow_definition_versions ADD model_changes INT NOT NULL CONSTRAINT df_workflow_definition_versions_model_changes DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','prompt_changes') IS NULL ALTER TABLE workflow_definition_versions ADD prompt_changes INT NOT NULL CONSTRAINT df_workflow_definition_versions_prompt_changes DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','permission_changes') IS NULL ALTER TABLE workflow_definition_versions ADD permission_changes INT NOT NULL CONSTRAINT df_workflow_definition_versions_permission_changes DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','output_changes') IS NULL ALTER TABLE workflow_definition_versions ADD output_changes INT NOT NULL CONSTRAINT df_workflow_definition_versions_output_changes DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','final_output_compatible') IS NULL ALTER TABLE workflow_definition_versions ADD final_output_compatible DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_definition_versions_final_output DEFAULT 0;
  IF COL_LENGTH('workflow_definition_versions','created_by') IS NULL ALTER TABLE workflow_definition_versions ADD created_by NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_definition_versions','owner') IS NULL ALTER TABLE workflow_definition_versions ADD owner NVARCHAR(180) NULL;
  IF COL_LENGTH('workflow_definition_versions','release_notes') IS NULL ALTER TABLE workflow_definition_versions ADD release_notes NVARCHAR(1000) NULL;
  IF COL_LENGTH('workflow_definition_versions','created_at') IS NULL ALTER TABLE workflow_definition_versions ADD created_at DATETIME2 NOT NULL CONSTRAINT df_workflow_definition_versions_created DEFAULT SYSUTCDATETIME();
  IF COL_LENGTH('workflow_definition_versions','published_at') IS NULL ALTER TABLE workflow_definition_versions ADD published_at DATETIME2 NULL;
  IF COL_LENGTH('workflow_definition_versions','superseded_at') IS NULL ALTER TABLE workflow_definition_versions ADD superseded_at DATETIME2 NULL;
  IF COL_LENGTH('workflow_definition_versions','archived_at') IS NULL ALTER TABLE workflow_definition_versions ADD archived_at DATETIME2 NULL;
  IF COL_LENGTH('workflow_definition_versions','updated_at') IS NULL ALTER TABLE workflow_definition_versions ADD updated_at DATETIME2 NOT NULL CONSTRAINT df_workflow_definition_versions_updated DEFAULT SYSUTCDATETIME();
END;

IF OBJECT_ID('workflow_version_status_history', 'U') IS NULL CREATE TABLE workflow_version_status_history (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, status NVARCHAR(80) NOT NULL, reason NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_validations', 'U') IS NULL CREATE TABLE workflow_version_validations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, status NVARCHAR(80) NOT NULL, structural_status NVARCHAR(80) NULL, configuration_status NVARCHAR(80) NULL, business_status NVARCHAR(80) NULL, security_status NVARCHAR(80) NULL, recovery_status NVARCHAR(80) NULL, final_output_status NVARCHAR(80) NULL, error_count INT NOT NULL DEFAULT 0, warning_count INT NOT NULL DEFAULT 0, recommendation_count INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_validation_results', 'U') IS NULL CREATE TABLE workflow_version_validation_results (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_version_validation_id UNIQUEIDENTIFIER NOT NULL, result_type NVARCHAR(80) NOT NULL, component NVARCHAR(180) NOT NULL, message NVARCHAR(500) NOT NULL, suggested_action NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_simulations', 'U') IS NULL CREATE TABLE workflow_version_simulations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, status NVARCHAR(80) NOT NULL, estimated_duration_ms INT NOT NULL DEFAULT 0, estimated_cost DECIMAL(18,4) NOT NULL DEFAULT 0, risk_summary NVARCHAR(500) NULL, final_output_readiness DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_comparisons', 'U') IS NULL CREATE TABLE workflow_version_comparisons (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, compared_to_version_id UNIQUEIDENTIFIER NULL, area NVARCHAR(120) NOT NULL, change_type NVARCHAR(80) NOT NULL, risk NVARCHAR(80) NOT NULL, suggested_action NVARCHAR(500) NULL, breaking_change BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_compatibility', 'U') IS NULL CREATE TABLE workflow_version_compatibility (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, component NVARCHAR(180) NOT NULL, compatibility_status NVARCHAR(80) NOT NULL, change_summary NVARCHAR(500) NULL, impact NVARCHAR(500) NULL, affected_workflows INT NOT NULL DEFAULT 0, required_migration NVARCHAR(240) NULL, auto_migration_available BIT NOT NULL DEFAULT 0, rollback_impact NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_dependencies', 'U') IS NULL CREATE TABLE workflow_version_dependencies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, dependency_type NVARCHAR(80) NOT NULL, dependency_name NVARCHAR(180) NOT NULL, expected_version NVARCHAR(80) NULL, actual_version NVARCHAR(80) NULL, status NVARCHAR(80) NOT NULL, risk NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_release_plans', 'U') IS NULL CREATE TABLE workflow_version_release_plans (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, strategy NVARCHAR(120) NOT NULL, target_environment NVARCHAR(80) NOT NULL, initial_percentage DECIMAL(8,2) NOT NULL DEFAULT 0, step_percentage DECIMAL(8,2) NOT NULL DEFAULT 0, step_duration_minutes INT NOT NULL DEFAULT 0, health_threshold DECIMAL(8,2) NOT NULL DEFAULT 0, failure_threshold DECIMAL(8,2) NOT NULL DEFAULT 0, rollback_threshold DECIMAL(8,2) NOT NULL DEFAULT 0, approval_required BIT NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_rollouts', 'U') IS NULL CREATE TABLE workflow_version_rollouts (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, workflow_name NVARCHAR(220) NULL, version_number INT NOT NULL, strategy NVARCHAR(120) NOT NULL, environment NVARCHAR(80) NOT NULL, status NVARCHAR(80) NOT NULL, progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, health_percent DECIMAL(8,2) NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, active_instances INT NOT NULL DEFAULT 0, current_step NVARCHAR(180) NULL, next_step NVARCHAR(180) NULL, rollback_readiness NVARCHAR(80) NULL, eta_minutes INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_rollout_steps', 'U') IS NULL CREATE TABLE workflow_version_rollout_steps (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_version_rollout_id UNIQUEIDENTIFIER NOT NULL, step_name NVARCHAR(180) NOT NULL, status NVARCHAR(80) NOT NULL, target_percent DECIMAL(8,2) NOT NULL DEFAULT 0, started_at DATETIME2 NULL, completed_at DATETIME2 NULL);
IF OBJECT_ID('workflow_version_rollout_targets', 'U') IS NULL CREATE TABLE workflow_version_rollout_targets (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_version_rollout_id UNIQUEIDENTIFIER NOT NULL, target_type NVARCHAR(80) NOT NULL, target_name NVARCHAR(180) NOT NULL, status NVARCHAR(80) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_canary_metrics', 'U') IS NULL CREATE TABLE workflow_version_canary_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_version_rollout_id UNIQUEIDENTIFIER NOT NULL, sample_size INT NOT NULL DEFAULT 0, health_score DECIMAL(8,2) NOT NULL DEFAULT 0, new_success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, current_success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, regression_detected BIT NOT NULL DEFAULT 0, improvement_detected BIT NOT NULL DEFAULT 0, statistical_confidence DECIMAL(8,2) NOT NULL DEFAULT 0, recommended_action NVARCHAR(240) NULL, auto_promote_eligible BIT NOT NULL DEFAULT 0, auto_rollback_eligible BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_health_metrics', 'U') IS NULL CREATE TABLE workflow_version_health_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_duration_ms INT NOT NULL DEFAULT 0, queue_wait_ms INT NOT NULL DEFAULT 0, average_cost DECIMAL(18,4) NOT NULL DEFAULT 0, agent_success DECIMAL(8,2) NOT NULL DEFAULT 0, output_validation DECIMAL(8,2) NOT NULL DEFAULT 0, approval_completion DECIMAL(8,2) NOT NULL DEFAULT 0, publishing_success DECIMAL(8,2) NOT NULL DEFAULT 0, analytics_completion DECIMAL(8,2) NOT NULL DEFAULT 0, learning_completion DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_rate DECIMAL(8,2) NOT NULL DEFAULT 0, incident_rate DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_rollbacks', 'U') IS NULL CREATE TABLE workflow_version_rollbacks (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, trigger_reason NVARCHAR(240) NOT NULL, evidence NVARCHAR(500) NULL, status NVARCHAR(80) NOT NULL, previous_version_verified BIT NOT NULL DEFAULT 0, instances_stabilized BIT NOT NULL DEFAULT 0, health_revalidated BIT NOT NULL DEFAULT 0, incident_or_learning NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_migrations', 'U') IS NULL CREATE TABLE workflow_version_migrations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, active_instance NVARCHAR(180) NOT NULL, current_stage NVARCHAR(180) NULL, current_version INT NOT NULL, target_version INT NOT NULL, migration_strategy NVARCHAR(180) NOT NULL, compatibility NVARCHAR(80) NOT NULL, risk NVARCHAR(80) NULL, estimated_downtime_seconds INT NOT NULL DEFAULT 0, output_impact NVARCHAR(120) NULL, migration_status NVARCHAR(80) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_drift', 'U') IS NULL CREATE TABLE workflow_version_drift (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, workflow_name NVARCHAR(220) NULL, environment NVARCHAR(80) NOT NULL, expected_version NVARCHAR(80) NOT NULL, actual_version NVARCHAR(80) NOT NULL, component NVARCHAR(180) NOT NULL, drift_type NVARCHAR(120) NOT NULL, risk NVARCHAR(80) NOT NULL, autonomous_correction NVARCHAR(240) NULL, outcome NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_release_notes', 'U') IS NULL CREATE TABLE workflow_version_release_notes (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, title NVARCHAR(220) NOT NULL, summary NVARCHAR(1000) NULL, generated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_documentation', 'U') IS NULL CREATE TABLE workflow_version_documentation (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, doc_type NVARCHAR(120) NOT NULL, title NVARCHAR(220) NOT NULL, summary NVARCHAR(1000) NULL, generated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_governance_approvals', 'U') IS NULL CREATE TABLE workflow_version_governance_approvals (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, approval_reason NVARCHAR(240) NOT NULL, status NVARCHAR(80) NOT NULL, required_for NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_autonomous_decisions', 'U') IS NULL CREATE TABLE workflow_version_autonomous_decisions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, detection NVARCHAR(240) NOT NULL, decision NVARCHAR(240) NOT NULL, policy NVARCHAR(180) NOT NULL, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, outcome NVARCHAR(240) NULL, human_input_required BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_final_output_compatibility', 'U') IS NULL CREATE TABLE workflow_version_final_output_compatibility (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, inputs_compatible BIT NOT NULL DEFAULT 1, execution_compatible BIT NOT NULL DEFAULT 1, outputs_compatible BIT NOT NULL DEFAULT 1, approval_compatible BIT NOT NULL DEFAULT 1, publishing_compatible BIT NOT NULL DEFAULT 1, analytics_compatible BIT NOT NULL DEFAULT 1, learning_compatible BIT NOT NULL DEFAULT 1, business_result_compatible BIT NOT NULL DEFAULT 1, compatibility_percent DECIMAL(8,2) NOT NULL DEFAULT 0, blocked_from_release BIT NOT NULL DEFAULT 0, risk NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_incident_links', 'U') IS NULL CREATE TABLE workflow_version_incident_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, incident_id NVARCHAR(180) NOT NULL, link_reason NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_version_audit_links', 'U') IS NULL CREATE TABLE workflow_version_audit_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, workflow_definition_version_id UNIQUEIDENTIFIER NOT NULL, audit_reference NVARCHAR(180) NOT NULL, event_type NVARCHAR(120) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('vw_workflow_versions_list', 'V') IS NOT NULL DROP VIEW vw_workflow_versions_list;
EXEC('CREATE VIEW vw_workflow_versions_list AS SELECT v.*, COALESCE(wd.code, v.workflow_code) AS definition_code, COALESCE(wd.name, v.workflow_name) AS definition_name FROM workflow_definition_versions v LEFT JOIN workflow_definitions wd ON wd.id = v.workflow_definition_id');
IF OBJECT_ID('vw_workflow_version_summary', 'V') IS NOT NULL DROP VIEW vw_workflow_version_summary;
EXEC('CREATE VIEW vw_workflow_version_summary AS SELECT organization_id, COUNT(*) AS total_versions, COUNT(CASE WHEN version_status IN (''Published'',''Active'') THEN 1 END) AS published_versions, COUNT(CASE WHEN version_status=''Draft'' THEN 1 END) AS draft_versions, COUNT(CASE WHEN version_status=''Validating'' THEN 1 END) AS under_validation, COUNT(CASE WHEN release_status IN (''Canary'',''Rolling Out'') THEN 1 END) AS active_rollouts, COUNT(CASE WHEN version_status=''Rolled Back'' AND CAST(updated_at AS DATE)=CAST(SYSUTCDATETIME() AS DATE) THEN 1 END) AS automatic_rollbacks, CAST(AVG(health_percent) AS DECIMAL(8,2)) AS version_health, CAST(AVG(CASE WHEN compatibility_status IN (''Fully Compatible'',''Compatible with Migration'') THEN 100.0 ELSE 70.0 END) AS DECIMAL(8,2)) AS compatibility_passed, CAST(AVG(final_output_compatible) AS DECIMAL(8,2)) AS final_output_compatible, COUNT(CASE WHEN version_status IN (''Degraded'',''Rollback Pending'') THEN 1 END) AS human_attention_required, MAX(updated_at) AS last_release_event FROM workflow_definition_versions GROUP BY organization_id');
IF OBJECT_ID('vw_workflow_version_health', 'V') IS NOT NULL DROP VIEW vw_workflow_version_health;
EXEC('CREATE VIEW vw_workflow_version_health AS SELECT h.*, v.organization_id, v.workflow_code, v.workflow_name, v.version_number FROM workflow_version_health_metrics h JOIN workflow_definition_versions v ON v.id=h.workflow_definition_version_id');
IF OBJECT_ID('vw_workflow_version_compatibility', 'V') IS NOT NULL DROP VIEW vw_workflow_version_compatibility;
EXEC('CREATE VIEW vw_workflow_version_compatibility AS SELECT c.*, v.organization_id, v.workflow_code, v.workflow_name, v.version_number FROM workflow_version_compatibility c JOIN workflow_definition_versions v ON v.id=c.workflow_definition_version_id');
IF OBJECT_ID('vw_workflow_version_rollouts', 'V') IS NOT NULL DROP VIEW vw_workflow_version_rollouts;
EXEC('CREATE VIEW vw_workflow_version_rollouts AS SELECT r.*, v.organization_id, v.workflow_code FROM workflow_version_rollouts r JOIN workflow_definition_versions v ON v.id=r.workflow_definition_version_id');
IF OBJECT_ID('vw_workflow_version_canary_comparison', 'V') IS NOT NULL DROP VIEW vw_workflow_version_canary_comparison;
EXEC('CREATE VIEW vw_workflow_version_canary_comparison AS SELECT c.*, r.workflow_name, r.version_number, v.organization_id FROM workflow_version_canary_metrics c JOIN workflow_version_rollouts r ON r.id=c.workflow_version_rollout_id JOIN workflow_definition_versions v ON v.id=r.workflow_definition_version_id');
IF OBJECT_ID('vw_workflow_version_drift', 'V') IS NOT NULL DROP VIEW vw_workflow_version_drift;
EXEC('CREATE VIEW vw_workflow_version_drift AS SELECT d.*, v.organization_id, v.workflow_code FROM workflow_version_drift d JOIN workflow_definition_versions v ON v.id=d.workflow_definition_version_id');
IF OBJECT_ID('vw_workflow_version_release_readiness', 'V') IS NOT NULL DROP VIEW vw_workflow_version_release_readiness;
EXEC('CREATE VIEW vw_workflow_version_release_readiness AS SELECT v.id, v.organization_id, v.workflow_code, v.workflow_name, v.version_number, v.validation_status, v.compatibility_status, CASE WHEN v.validation_status=''Passed'' AND v.compatibility_status IN (''Fully Compatible'',''Compatible with Migration'') AND v.final_output_compatible >= 90 THEN ''Ready'' WHEN v.final_output_compatible >= 75 THEN ''Ready with Warnings'' ELSE ''Blocked'' END AS readiness_status, v.health_percent, v.final_output_compatible, v.updated_at FROM workflow_definition_versions v');
IF OBJECT_ID('vw_workflow_version_final_output_compatibility', 'V') IS NOT NULL DROP VIEW vw_workflow_version_final_output_compatibility;
EXEC('CREATE VIEW vw_workflow_version_final_output_compatibility AS SELECT f.*, v.organization_id, v.workflow_code, v.workflow_name, v.version_number FROM workflow_version_final_output_compatibility f JOIN workflow_definition_versions v ON v.id=f.workflow_definition_version_id');
