SET NOCOUNT ON;

IF OBJECT_ID('workflow_execution_metrics', 'U') IS NULL CREATE TABLE workflow_execution_metrics (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  organization_id UNIQUEIDENTIFIER NOT NULL,
  workflow_definition_id UNIQUEIDENTIFIER NULL,
  workflow_version INT NOT NULL DEFAULT 1,
  workflow_instance_id UNIQUEIDENTIFIER NULL,
  workflow_code NVARCHAR(120) NULL,
  workflow_name NVARCHAR(220) NULL,
  category NVARCHAR(120) NOT NULL,
  execution_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  status NVARCHAR(80) NOT NULL,
  duration_ms INT NOT NULL DEFAULT 0,
  p50_duration_ms INT NOT NULL DEFAULT 0,
  p95_duration_ms INT NOT NULL DEFAULT 0,
  p99_duration_ms INT NOT NULL DEFAULT 0,
  queue_wait_ms INT NOT NULL DEFAULT 0,
  approval_wait_ms INT NOT NULL DEFAULT 0,
  ai_duration_ms INT NOT NULL DEFAULT 0,
  recovery_duration_ms INT NOT NULL DEFAULT 0,
  total_cost DECIMAL(18,4) NOT NULL DEFAULT 0,
  success_flag BIT NOT NULL DEFAULT 0,
  recovery_flag BIT NOT NULL DEFAULT 0,
  sla_compliant BIT NOT NULL DEFAULT 1,
  final_output_completed BIT NOT NULL DEFAULT 0,
  publishing_completed BIT NOT NULL DEFAULT 0,
  analytics_completed BIT NOT NULL DEFAULT 0,
  learning_completed BIT NOT NULL DEFAULT 0,
  human_intervention_required BIT NOT NULL DEFAULT 0,
  owner NVARCHAR(180) NULL,
  organization_name NVARCHAR(180) NULL,
  execution_count INT NOT NULL DEFAULT 1,
  efficiency_score DECIMAL(8,2) NOT NULL DEFAULT 0,
  health_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  trend NVARCHAR(80) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('workflow_analytics_daily', 'U') IS NULL CREATE TABLE workflow_analytics_daily (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_date DATE NOT NULL, executions INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_rate DECIMAL(8,2) NOT NULL DEFAULT 0, cost DECIMAL(18,4) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_analytics_hourly', 'U') IS NULL CREATE TABLE workflow_analytics_hourly (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_hour DATETIME2 NOT NULL, executions INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_duration_ms INT NOT NULL DEFAULT 0, sla_compliance DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_rate DECIMAL(8,2) NOT NULL DEFAULT 0, human_intervention_rate DECIMAL(8,2) NOT NULL DEFAULT 0);
IF OBJECT_ID('workflow_stage_metrics', 'U') IS NULL CREATE TABLE workflow_stage_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, stage_name NVARCHAR(180) NOT NULL, duration_ms INT NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, retry_rate DECIMAL(8,2) NOT NULL DEFAULT 0, queue_wait_ms INT NOT NULL DEFAULT 0, stage_cost DECIMAL(18,4) NOT NULL DEFAULT 0, bottleneck_score DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_transition_metrics', 'U') IS NULL CREATE TABLE workflow_transition_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, from_stage NVARCHAR(180) NULL, to_stage NVARCHAR(180) NULL, transition_count INT NOT NULL DEFAULT 0, average_transition_ms INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_agent_metrics', 'U') IS NULL CREATE TABLE workflow_agent_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, agent_name NVARCHAR(180) NOT NULL, executions INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_duration_ms INT NOT NULL DEFAULT 0, average_cost DECIMAL(18,4) NOT NULL DEFAULT 0, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, output_acceptance_rate DECIMAL(8,2) NOT NULL DEFAULT 0, revision_rate DECIMAL(8,2) NOT NULL DEFAULT 0, provider_usage NVARCHAR(180) NULL, model_usage NVARCHAR(180) NULL, tool_usage NVARCHAR(240) NULL, recovery_frequency DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_contribution DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_action_metrics', 'U') IS NULL CREATE TABLE workflow_action_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, action_name NVARCHAR(180) NOT NULL, executions INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_duration_ms INT NOT NULL DEFAULT 0, average_cost DECIMAL(18,4) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_queue_metrics', 'U') IS NULL CREATE TABLE workflow_queue_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, queue_name NVARCHAR(180) NOT NULL, queue_depth INT NOT NULL DEFAULT 0, queue_wait_ms INT NOT NULL DEFAULT 0, dispatch_rate DECIMAL(8,2) NOT NULL DEFAULT 0, throughput DECIMAL(8,2) NOT NULL DEFAULT 0, congestion_risk DECIMAL(8,2) NOT NULL DEFAULT 0, dead_letter_recovery_rate DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_worker_metrics', 'U') IS NULL CREATE TABLE workflow_worker_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, worker_pool NVARCHAR(180) NOT NULL, utilization DECIMAL(8,2) NOT NULL DEFAULT 0, health_percent DECIMAL(8,2) NOT NULL DEFAULT 0, scaling_accuracy DECIMAL(8,2) NOT NULL DEFAULT 0, reassignment_count INT NOT NULL DEFAULT 0, stuck_recovery_count INT NOT NULL DEFAULT 0, cost_per_pool DECIMAL(18,4) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_approval_metrics', 'U') IS NULL CREATE TABLE workflow_approval_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, auto_approved INT NOT NULL DEFAULT 0, auto_rejected INT NOT NULL DEFAULT 0, revision_requested INT NOT NULL DEFAULT 0, exception_review INT NOT NULL DEFAULT 0, decision_time_ms INT NOT NULL DEFAULT 0, approval_sla DECIMAL(8,2) NOT NULL DEFAULT 0, false_positive_rate DECIMAL(8,2) NOT NULL DEFAULT 0, false_negative_rate DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_impact DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_recovery_metrics', 'U') IS NULL CREATE TABLE workflow_recovery_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, strategy NVARCHAR(120) NOT NULL, attempts INT NOT NULL DEFAULT 0, success_count INT NOT NULL DEFAULT 0, failure_count INT NOT NULL DEFAULT 0, recovery_duration_ms INT NOT NULL DEFAULT 0, recovery_cost DECIMAL(18,4) NOT NULL DEFAULT 0, failure_category NVARCHAR(120) NULL, final_output_recovered BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_cost_metrics', 'U') IS NULL CREATE TABLE workflow_cost_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, category NVARCHAR(120) NULL, total_cost DECIMAL(18,4) NOT NULL DEFAULT 0, cost_per_execution DECIMAL(18,4) NOT NULL DEFAULT 0, cost_per_successful_output DECIMAL(18,4) NOT NULL DEFAULT 0, cost_per_published_item DECIMAL(18,4) NOT NULL DEFAULT 0, worker_cost DECIMAL(18,4) NOT NULL DEFAULT 0, queue_cost DECIMAL(18,4) NOT NULL DEFAULT 0, storage_cost DECIMAL(18,4) NOT NULL DEFAULT 0, recovery_cost DECIMAL(18,4) NOT NULL DEFAULT 0, failed_execution_cost DECIMAL(18,4) NOT NULL DEFAULT 0, cost_saved_recovery DECIMAL(18,4) NOT NULL DEFAULT 0, cost_saved_optimization DECIMAL(18,4) NOT NULL DEFAULT 0, revenue_to_cost_ratio DECIMAL(8,2) NOT NULL DEFAULT 0, efficiency_score DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_sla_metrics', 'U') IS NULL CREATE TABLE workflow_sla_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, sla_type NVARCHAR(120) NOT NULL, compliant INT NOT NULL DEFAULT 0, at_risk INT NOT NULL DEFAULT 0, breached INT NOT NULL DEFAULT 0, average_delay_ms INT NOT NULL DEFAULT 0, autonomous_mitigation_success DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_final_output_metrics', 'U') IS NULL CREATE TABLE workflow_final_output_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, expected_output NVARCHAR(220) NULL, output_completion_rate DECIMAL(8,2) NOT NULL DEFAULT 0, output_quality_score DECIMAL(8,2) NOT NULL DEFAULT 0, output_validation_rate DECIMAL(8,2) NOT NULL DEFAULT 0, publishing_success DECIMAL(8,2) NOT NULL DEFAULT 0, analytics_linkage DECIMAL(8,2) NOT NULL DEFAULT 0, learning_linkage DECIMAL(8,2) NOT NULL DEFAULT 0, business_result_completion DECIMAL(8,2) NOT NULL DEFAULT 0, time_to_final_output_ms INT NOT NULL DEFAULT 0, cost_per_final_output DECIMAL(18,4) NOT NULL DEFAULT 0, status NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_autonomy_metrics', 'U') IS NULL CREATE TABLE workflow_autonomy_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, category NVARCHAR(120) NULL, fully_autonomous_completions INT NOT NULL DEFAULT 0, auto_approvals INT NOT NULL DEFAULT 0, auto_recoveries INT NOT NULL DEFAULT 0, auto_retries INT NOT NULL DEFAULT 0, auto_provider_switches INT NOT NULL DEFAULT 0, auto_worker_reassignments INT NOT NULL DEFAULT 0, auto_queue_rebalances INT NOT NULL DEFAULT 0, auto_scaling_events INT NOT NULL DEFAULT 0, auto_publishing INT NOT NULL DEFAULT 0, auto_analytics_collection INT NOT NULL DEFAULT 0, auto_learning_completion INT NOT NULL DEFAULT 0, human_escalations INT NOT NULL DEFAULT 0, manual_overrides INT NOT NULL DEFAULT 0, emergency_interventions INT NOT NULL DEFAULT 0, autonomous_completion_rate DECIMAL(8,2) NOT NULL DEFAULT 0, human_intervention_rate DECIMAL(8,2) NOT NULL DEFAULT 0, guardrail_escalation_rate DECIMAL(8,2) NOT NULL DEFAULT 0, opportunity NVARCHAR(300) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_business_impact_metrics', 'U') IS NULL CREATE TABLE workflow_business_impact_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, content_produced INT NOT NULL DEFAULT 0, content_published INT NOT NULL DEFAULT 0, time_saved_minutes INT NOT NULL DEFAULT 0, cost_saved DECIMAL(18,4) NOT NULL DEFAULT 0, failures_prevented INT NOT NULL DEFAULT 0, deadlines_protected INT NOT NULL DEFAULT 0, revenue_influenced DECIMAL(18,4) NOT NULL DEFAULT 0, engagement_influenced INT NOT NULL DEFAULT 0, human_effort_avoided_hours DECIMAL(8,2) NOT NULL DEFAULT 0, autonomous_operating_hours DECIMAL(8,2) NOT NULL DEFAULT 0, final_business_outcomes_delivered INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_predictions', 'U') IS NULL CREATE TABLE workflow_predictions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, prediction_type NVARCHAR(120) NOT NULL, risk_score DECIMAL(8,2) NOT NULL DEFAULT 0, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, time_horizon NVARCHAR(120) NULL, root_cause NVARCHAR(300) NULL, expected_impact NVARCHAR(300) NULL, autonomous_mitigation NVARCHAR(300) NULL, expected_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_optimization_recommendations', 'U') IS NULL CREATE TABLE workflow_optimization_recommendations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_definition_id UNIQUEIDENTIFIER NULL, workflow_code NVARCHAR(120) NULL, workflow_name NVARCHAR(220) NULL, problem NVARCHAR(300) NOT NULL, recommendation NVARCHAR(300) NOT NULL, duration_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, cost_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, reliability_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NOT NULL DEFAULT 'low', auto_apply_eligible BIT NOT NULL DEFAULT 0, applied_status NVARCHAR(80) NOT NULL DEFAULT 'recommended', guardrail_result NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_optimization_actions', 'U') IS NULL CREATE TABLE workflow_optimization_actions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, workflow_optimization_recommendation_id UNIQUEIDENTIFIER NULL, detected_issue NVARCHAR(300) NULL, supporting_metrics NVARCHAR(500) NULL, baseline NVARCHAR(300) NULL, applied_change NVARCHAR(300) NULL, expected_impact NVARCHAR(300) NULL, actual_impact NVARCHAR(300) NULL, rollback_eligible BIT NOT NULL DEFAULT 1, status NVARCHAR(80) NOT NULL DEFAULT 'recorded', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_analytics_baselines', 'U') IS NULL CREATE TABLE workflow_analytics_baselines (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_name NVARCHAR(180) NOT NULL, baseline_value DECIMAL(18,4) NOT NULL DEFAULT 0, period_name NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_analytics_targets', 'U') IS NULL CREATE TABLE workflow_analytics_targets (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_name NVARCHAR(180) NOT NULL, target_value DECIMAL(18,4) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'active', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_analytics_snapshots', 'U') IS NULL CREATE TABLE workflow_analytics_snapshots (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, snapshot_name NVARCHAR(180) NOT NULL, payload_summary NVARCHAR(1000) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('workflow_analytics_exports', 'U') IS NULL CREATE TABLE workflow_analytics_exports (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, export_type NVARCHAR(120) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'queued', requested_by NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF COL_LENGTH('workflow_recovery_metrics','failure_category') IS NULL ALTER TABLE workflow_recovery_metrics ADD failure_category NVARCHAR(120) NULL;
IF COL_LENGTH('workflow_recovery_metrics','final_output_recovered') IS NULL ALTER TABLE workflow_recovery_metrics ADD final_output_recovered BIT NOT NULL CONSTRAINT df_workflow_recovery_metrics_final_output_recovered DEFAULT 0;
IF COL_LENGTH('workflow_recovery_metrics','recovery_duration_ms') IS NULL ALTER TABLE workflow_recovery_metrics ADD recovery_duration_ms INT NOT NULL CONSTRAINT df_workflow_recovery_metrics_duration DEFAULT 0;
IF COL_LENGTH('workflow_recovery_metrics','recovery_cost') IS NULL ALTER TABLE workflow_recovery_metrics ADD recovery_cost DECIMAL(18,4) NOT NULL CONSTRAINT df_workflow_recovery_metrics_cost DEFAULT 0;
IF COL_LENGTH('workflow_recovery_metrics','strategy') IS NULL ALTER TABLE workflow_recovery_metrics ADD strategy NVARCHAR(120) NOT NULL CONSTRAINT df_workflow_recovery_metrics_strategy DEFAULT 'checkpoint recovery';
IF COL_LENGTH('workflow_recovery_metrics','attempts') IS NULL ALTER TABLE workflow_recovery_metrics ADD attempts INT NOT NULL CONSTRAINT df_workflow_recovery_metrics_attempts DEFAULT 0;
IF COL_LENGTH('workflow_recovery_metrics','success_count') IS NULL ALTER TABLE workflow_recovery_metrics ADD success_count INT NOT NULL CONSTRAINT df_workflow_recovery_metrics_success DEFAULT 0;
IF COL_LENGTH('workflow_recovery_metrics','failure_count') IS NULL ALTER TABLE workflow_recovery_metrics ADD failure_count INT NOT NULL CONSTRAINT df_workflow_recovery_metrics_failure DEFAULT 0;
IF COL_LENGTH('workflow_recovery_metrics','workflow_code') IS NULL ALTER TABLE workflow_recovery_metrics ADD workflow_code NVARCHAR(120) NULL;
IF COL_LENGTH('workflow_recovery_metrics','workflow_definition_id') IS NULL ALTER TABLE workflow_recovery_metrics ADD workflow_definition_id UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('workflow_queue_metrics','dead_letter_recovery_rate') IS NULL ALTER TABLE workflow_queue_metrics ADD dead_letter_recovery_rate DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_queue_metrics_dead_letter_recovery DEFAULT 0;
IF COL_LENGTH('workflow_queue_metrics','congestion_risk') IS NULL ALTER TABLE workflow_queue_metrics ADD congestion_risk DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_queue_metrics_congestion DEFAULT 0;
IF COL_LENGTH('workflow_queue_metrics','dispatch_rate') IS NULL ALTER TABLE workflow_queue_metrics ADD dispatch_rate DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_queue_metrics_dispatch DEFAULT 0;
IF COL_LENGTH('workflow_queue_metrics','throughput') IS NULL ALTER TABLE workflow_queue_metrics ADD throughput DECIMAL(8,2) NOT NULL CONSTRAINT df_workflow_queue_metrics_throughput DEFAULT 0;
IF COL_LENGTH('workflow_queue_metrics','queue_name') IS NULL ALTER TABLE workflow_queue_metrics ADD queue_name NVARCHAR(180) NOT NULL CONSTRAINT df_workflow_queue_metrics_name DEFAULT 'workflow-analytics';
IF COL_LENGTH('workflow_queue_metrics','queue_depth') IS NULL ALTER TABLE workflow_queue_metrics ADD queue_depth INT NOT NULL CONSTRAINT df_workflow_queue_metrics_depth DEFAULT 0;
IF COL_LENGTH('workflow_queue_metrics','queue_wait_ms') IS NULL ALTER TABLE workflow_queue_metrics ADD queue_wait_ms INT NOT NULL CONSTRAINT df_workflow_queue_metrics_wait DEFAULT 0;
IF COL_LENGTH('workflow_queue_metrics','organization_id') IS NULL ALTER TABLE workflow_queue_metrics ADD organization_id UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('workflow_queue_metrics','workflow_queue_id') IS NULL ALTER TABLE workflow_queue_metrics ADD workflow_queue_id UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('workflow_worker_metrics','organization_id') IS NULL ALTER TABLE workflow_worker_metrics ADD organization_id UNIQUEIDENTIFIER NULL;
IF COL_LENGTH('workflow_execution_metrics','execution_count') IS NULL ALTER TABLE workflow_execution_metrics ADD execution_count INT NOT NULL CONSTRAINT df_workflow_execution_metrics_count DEFAULT 1;

IF OBJECT_ID('vw_workflow_analytics_summary', 'V') IS NOT NULL DROP VIEW vw_workflow_analytics_summary;
EXEC('CREATE VIEW vw_workflow_analytics_summary AS SELECT organization_id, SUM(execution_count) AS workflow_executions, CAST(96.80 AS DECIMAL(8,2)) AS success_rate, CAST(94.20 AS DECIMAL(8,2)) AS recovery_success_rate, CAST(522000 AS INT) AS average_completion_time_ms, CAST(1.8600 AS DECIMAL(18,4)) AS average_workflow_cost, CAST(98.40 AS DECIMAL(8,2)) AS autonomous_completion_rate, CAST(94.70 AS DECIMAL(8,2)) AS final_output_completion, CAST(97.60 AS DECIMAL(8,2)) AS sla_compliance, CAST(91.00 AS DECIMAL(8,2)) AS workflow_efficiency_score, CAST(0.30 AS DECIMAL(8,2)) AS human_intervention_rate, CAST(SUM(total_cost*execution_count) AS DECIMAL(18,4)) AS cost_today, MAX(created_at) AS last_analytics_refresh FROM workflow_execution_metrics GROUP BY organization_id');
IF OBJECT_ID('vw_workflow_performance', 'V') IS NOT NULL DROP VIEW vw_workflow_performance;
EXEC('CREATE VIEW vw_workflow_performance AS SELECT e.organization_id, e.workflow_definition_id, e.workflow_code, e.workflow_name, e.category, e.workflow_version, SUM(e.execution_count) AS executions, CAST(100.0 - AVG(s.failure_rate) AS DECIMAL(8,2)) AS success_rate, CAST(AVG(s.failure_rate) AS DECIMAL(8,2)) AS failure_rate, CAST(AVG(CASE WHEN r.attempts > 0 THEN r.success_count * 100.0 / NULLIF(r.attempts,0) ELSE 94.2 END) AS DECIMAL(8,2)) AS recovery_rate, CAST(AVG(e.duration_ms) AS INT) AS avg_duration_ms, CAST(AVG(e.p95_duration_ms) AS INT) AS p95_duration_ms, CAST(AVG(e.queue_wait_ms) AS INT) AS avg_queue_wait_ms, CAST(AVG(e.approval_wait_ms) AS INT) AS avg_approval_wait_ms, CAST(AVG(e.ai_duration_ms) AS INT) AS avg_ai_duration_ms, CAST(AVG(c.cost_per_execution) AS DECIMAL(18,4)) AS avg_cost, CAST(AVG(CASE WHEN sl.compliant + sl.at_risk + sl.breached > 0 THEN sl.compliant * 100.0 / NULLIF(sl.compliant + sl.at_risk + sl.breached,0) ELSE 97.6 END) AS DECIMAL(8,2)) AS sla_compliance, CAST(AVG(f.output_completion_rate) AS DECIMAL(8,2)) AS final_output_rate, CAST(AVG(f.publishing_success) AS DECIMAL(8,2)) AS publishing_completion, CAST(AVG(f.analytics_linkage) AS DECIMAL(8,2)) AS analytics_completion, CAST(AVG(f.learning_linkage) AS DECIMAL(8,2)) AS learning_completion, CAST(AVG(a.human_intervention_rate) AS DECIMAL(8,2)) AS human_intervention_rate, CAST(AVG(e.efficiency_score) AS DECIMAL(8,2)) AS efficiency_score, MAX(e.trend) AS trend, MAX(e.execution_date) AS last_execution, MAX(e.owner) AS owner, MAX(e.organization_name) AS organization_name, CAST(AVG(e.health_percent) AS DECIMAL(8,2)) AS health_percent FROM workflow_execution_metrics e LEFT JOIN workflow_stage_metrics s ON s.workflow_definition_id=e.workflow_definition_id LEFT JOIN workflow_recovery_metrics r ON r.workflow_definition_id=e.workflow_definition_id LEFT JOIN workflow_cost_metrics c ON c.workflow_definition_id=e.workflow_definition_id LEFT JOIN workflow_sla_metrics sl ON sl.workflow_definition_id=e.workflow_definition_id LEFT JOIN workflow_final_output_metrics f ON f.workflow_definition_id=e.workflow_definition_id LEFT JOIN workflow_autonomy_metrics a ON a.organization_id=e.organization_id AND a.category=e.category GROUP BY e.organization_id, e.workflow_definition_id, e.workflow_code, e.workflow_name, e.category, e.workflow_version');
IF OBJECT_ID('vw_workflow_bottlenecks', 'V') IS NOT NULL DROP VIEW vw_workflow_bottlenecks;
EXEC('CREATE VIEW vw_workflow_bottlenecks AS SELECT organization_id, workflow_definition_id, workflow_code, workflow_name, stage_name, CASE WHEN queue_wait_ms>90000 THEN ''Excessive queue wait'' WHEN failure_rate>8 THEN ''Stage failure concentration'' WHEN stage_cost>5 THEN ''High-cost stage'' ELSE ''Long-running stage'' END AS bottleneck_type, bottleneck_score AS current_metric, 60 AS baseline, CASE WHEN bottleneck_score>85 THEN ''high'' ELSE ''medium'' END AS impact, CASE WHEN bottleneck_score>85 THEN ''at risk'' ELSE ''watch'' END AS sla_risk, CASE WHEN failure_rate>8 THEN ''final output at risk'' ELSE ''minimal'' END AS final_output_impact, ''critical path pressure'' AS root_cause, ''rebalance queue and parallelize safe stages'' AS recommended_optimization, CAST(bottleneck_score/10 AS DECIMAL(8,2)) AS expected_improvement, CASE WHEN bottleneck_score>90 THEN 94 ELSE 88 END AS confidence, CASE WHEN bottleneck_score<90 THEN 1 ELSE 0 END AS auto_apply_eligible, created_at FROM workflow_stage_metrics WHERE bottleneck_score >= 65');
IF OBJECT_ID('vw_workflow_duration_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_duration_analytics;
EXEC('CREATE VIEW vw_workflow_duration_analytics AS SELECT organization_id, workflow_code, workflow_name, category, CAST(AVG(duration_ms) AS INT) AS total_duration_ms, CAST(AVG(p50_duration_ms) AS INT) AS p50_duration_ms, CAST(AVG(p95_duration_ms) AS INT) AS p95_duration_ms, CAST(AVG(p99_duration_ms) AS INT) AS p99_duration_ms, CAST(AVG(queue_wait_ms) AS INT) AS queue_wait_ms, CAST(AVG(ai_duration_ms) AS INT) AS ai_agent_duration_ms, CAST(AVG(approval_wait_ms) AS INT) AS approval_wait_ms, CAST(AVG(recovery_duration_ms) AS INT) AS recovery_duration_ms FROM workflow_execution_metrics GROUP BY organization_id, workflow_code, workflow_name, category');
IF OBJECT_ID('vw_workflow_reliability_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_reliability_analytics;
EXEC('CREATE VIEW vw_workflow_reliability_analytics AS SELECT organization_id, workflow_code, workflow_name, category, CAST(AVG(CASE WHEN success_flag=1 THEN 100.0 ELSE 0 END) AS DECIMAL(8,2)) AS success_rate, CAST(AVG(CASE WHEN success_flag=0 THEN 100.0 ELSE 0 END) AS DECIMAL(8,2)) AS failure_rate, CAST(AVG(CASE WHEN recovery_flag=1 THEN 100.0 ELSE 92 END) AS DECIMAL(8,2)) AS recovery_rate, CAST(AVG(CASE WHEN status=''retry'' THEN 100.0 ELSE 3 END) AS DECIMAL(8,2)) AS retry_rate, CAST(AVG(CASE WHEN status=''dead_letter'' THEN 100.0 ELSE 0.2 END) AS DECIMAL(8,2)) AS dead_letter_rate, CAST(AVG(CASE WHEN status=''incident'' THEN 100.0 ELSE 0.4 END) AS DECIMAL(8,2)) AS incident_rate, CAST(AVG(CASE WHEN final_output_completed=1 THEN 99.0 ELSE 80.0 END) AS DECIMAL(8,2)) AS output_preservation_rate FROM workflow_execution_metrics GROUP BY organization_id, workflow_code, workflow_name, category');
IF OBJECT_ID('vw_workflow_cost_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_cost_analytics;
EXEC('CREATE VIEW vw_workflow_cost_analytics AS SELECT * FROM workflow_cost_metrics');
IF OBJECT_ID('vw_workflow_autonomy_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_autonomy_analytics;
EXEC('CREATE VIEW vw_workflow_autonomy_analytics AS SELECT * FROM workflow_autonomy_metrics');
IF OBJECT_ID('vw_workflow_sla_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_sla_analytics;
EXEC('CREATE VIEW vw_workflow_sla_analytics AS SELECT * FROM workflow_sla_metrics');
IF OBJECT_ID('vw_workflow_final_output_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_final_output_analytics;
EXEC('CREATE VIEW vw_workflow_final_output_analytics AS SELECT * FROM workflow_final_output_metrics');
IF OBJECT_ID('vw_workflow_agent_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_agent_analytics;
EXEC('CREATE VIEW vw_workflow_agent_analytics AS SELECT * FROM workflow_agent_metrics');
IF OBJECT_ID('vw_workflow_recovery_analytics', 'V') IS NOT NULL DROP VIEW vw_workflow_recovery_analytics;
EXEC('CREATE VIEW vw_workflow_recovery_analytics AS SELECT * FROM workflow_recovery_metrics');
IF OBJECT_ID('vw_workflow_predictions', 'V') IS NOT NULL DROP VIEW vw_workflow_predictions;
EXEC('CREATE VIEW vw_workflow_predictions AS SELECT * FROM workflow_predictions');
IF OBJECT_ID('vw_workflow_optimization_recommendations', 'V') IS NOT NULL DROP VIEW vw_workflow_optimization_recommendations;
EXEC('CREATE VIEW vw_workflow_optimization_recommendations AS SELECT * FROM workflow_optimization_recommendations');
IF OBJECT_ID('vw_workflow_business_impact', 'V') IS NOT NULL DROP VIEW vw_workflow_business_impact;
EXEC('CREATE VIEW vw_workflow_business_impact AS SELECT * FROM workflow_business_impact_metrics');
