SET NOCOUNT ON;

IF OBJECT_ID('recovery_policy_categories', 'U') IS NULL CREATE TABLE recovery_policy_categories (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, category_name NVARCHAR(180) NOT NULL,
  total_policies INT NOT NULL DEFAULT 0, active_policies INT NOT NULL DEFAULT 0, recoveries_today INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0,
  average_recovery_time_seconds INT NOT NULL DEFAULT 0, guardrail_blocks INT NOT NULL DEFAULT 0, escalations INT NOT NULL DEFAULT 0,
  final_output_protection_rate DECIMAL(8,2) NOT NULL DEFAULT 0, health_percent DECIMAL(8,2) NOT NULL DEFAULT 0, last_execution DATETIME2 NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('recovery_policies', 'U') IS NULL CREATE TABLE recovery_policies (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, policy_code NVARCHAR(120) NOT NULL, policy_name NVARCHAR(220) NOT NULL,
  description NVARCHAR(1000) NULL, category_id UNIQUEIDENTIFIER NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Draft', current_version INT NOT NULL DEFAULT 1,
  published_version INT NULL, priority INT NOT NULL DEFAULT 50, failure_scope NVARCHAR(220) NULL, severity_range NVARCHAR(120) NULL, primary_strategy NVARCHAR(180) NOT NULL,
  fallback_strategy NVARCHAR(180) NULL, confidence_threshold DECIMAL(8,2) NOT NULL DEFAULT 80, risk_ceiling DECIMAL(8,2) NOT NULL DEFAULT 80,
  cost_ceiling DECIMAL(18,4) NOT NULL DEFAULT 0, time_ceiling_seconds INT NOT NULL DEFAULT 600, max_attempts INT NOT NULL DEFAULT 3,
  checkpoint_required BIT NOT NULL DEFAULT 1, compensation_enabled BIT NOT NULL DEFAULT 0, incident_threshold INT NOT NULL DEFAULT 3,
  human_escalation_enabled BIT NOT NULL DEFAULT 0, owner_id NVARCHAR(180) NULL, organization_name NVARCHAR(180) NULL, environment NVARCHAR(80) NOT NULL DEFAULT 'production',
  executions_today INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_recovery_time_seconds INT NOT NULL DEFAULT 0,
  final_output_protection_rate DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='uq_recovery_policies_org_code' AND object_id=OBJECT_ID('recovery_policies')) CREATE UNIQUE INDEX uq_recovery_policies_org_code ON recovery_policies(organization_id, policy_code);

IF OBJECT_ID('recovery_policy_versions', 'U') IS NULL CREATE TABLE recovery_policy_versions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, version_number INT NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'draft', change_summary NVARCHAR(500) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_scopes', 'U') IS NULL CREATE TABLE recovery_policy_scopes (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, failure_categories NVARCHAR(500) NULL, workflow_categories NVARCHAR(500) NULL, stage_types NVARCHAR(500) NULL, error_codes NVARCHAR(500) NULL, provider_types NVARCHAR(240) NULL, queue_types NVARCHAR(240) NULL, worker_types NVARCHAR(240) NULL, organization_scope NVARCHAR(180) NULL, brand_scope NVARCHAR(180) NULL, environment_scope NVARCHAR(120) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_failure_mappings', 'U') IS NULL CREATE TABLE recovery_policy_failure_mappings (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, failure_type NVARCHAR(180) NOT NULL, severity NVARCHAR(80) NULL, recovery_enabled BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_evidence_requirements', 'U') IS NULL CREATE TABLE recovery_policy_evidence_requirements (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, required_logs BIT NOT NULL DEFAULT 1, required_health_signals BIT NOT NULL DEFAULT 1, required_checkpoint BIT NOT NULL DEFAULT 1, required_output_state BIT NOT NULL DEFAULT 1, required_dependency_state BIT NOT NULL DEFAULT 1, minimum_evidence_count INT NOT NULL DEFAULT 3, confidence_threshold DECIMAL(8,2) NOT NULL DEFAULT 80, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_strategies', 'U') IS NULL CREATE TABLE recovery_policy_strategies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, strategy_name NVARCHAR(180) NOT NULL, strategy_type NVARCHAR(120) NOT NULL, execution_order INT NOT NULL DEFAULT 1, execution_mode NVARCHAR(80) NOT NULL DEFAULT 'sequential', backoff NVARCHAR(120) NULL, cooldown_seconds INT NOT NULL DEFAULT 0, timeout_seconds INT NOT NULL DEFAULT 600, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_fallbacks', 'U') IS NULL CREATE TABLE recovery_policy_fallbacks (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, fallback_strategy NVARCHAR(180) NOT NULL, maximum_attempts INT NOT NULL DEFAULT 2, fallback_order INT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_guardrails', 'U') IS NULL CREATE TABLE recovery_policy_guardrails (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, risk_ceiling DECIMAL(8,2) NOT NULL, cost_ceiling DECIMAL(18,4) NOT NULL, time_ceiling_seconds INT NOT NULL, maximum_retries INT NOT NULL, maximum_workflow_delay_seconds INT NOT NULL, security_boundary NVARCHAR(180) NULL, data_integrity_boundary NVARCHAR(180) NULL, publishing_boundary NVARCHAR(180) NULL, human_escalation_boundary NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_checkpoint_rules', 'U') IS NULL CREATE TABLE recovery_policy_checkpoint_rules (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, required BIT NOT NULL DEFAULT 1, checkpoint_type NVARCHAR(120) NULL, maximum_checkpoint_age_minutes INT NOT NULL DEFAULT 60, context_validation BIT NOT NULL DEFAULT 1, output_validation BIT NOT NULL DEFAULT 1, resume_point NVARCHAR(180) NULL, data_loss_tolerance NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_compensations', 'U') IS NULL CREATE TABLE recovery_policy_compensations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, enabled BIT NOT NULL DEFAULT 0, compensation_actions NVARCHAR(500) NULL, rollback_action NVARCHAR(240) NULL, reversibility NVARCHAR(120) NULL, maximum_compensation_risk DECIMAL(8,2) NOT NULL DEFAULT 0, verification NVARCHAR(240) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_escalations', 'U') IS NULL CREATE TABLE recovery_policy_escalations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, incident_threshold INT NOT NULL DEFAULT 3, incident_severity NVARCHAR(80) NULL, escalation_level NVARCHAR(80) NULL, required_role NVARCHAR(120) NULL, notification_policy NVARCHAR(180) NULL, human_attention_criteria NVARCHAR(300) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_permissions', 'U') IS NULL CREATE TABLE recovery_policy_permissions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, permission_code NVARCHAR(180) NOT NULL, required BIT NOT NULL DEFAULT 1, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_validations', 'U') IS NULL CREATE TABLE recovery_policy_validations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, status NVARCHAR(80) NOT NULL, error_count INT NOT NULL DEFAULT 0, warning_count INT NOT NULL DEFAULT 0, recommendation_count INT NOT NULL DEFAULT 0, validation_score DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_validation_results', 'U') IS NULL CREATE TABLE recovery_policy_validation_results (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_validation_id UNIQUEIDENTIFIER NOT NULL, result_type NVARCHAR(80) NOT NULL, affected_section NVARCHAR(120) NOT NULL, message NVARCHAR(500) NOT NULL, suggested_fix NVARCHAR(500) NULL, auto_fix_available BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_simulations', 'U') IS NULL CREATE TABLE recovery_policy_simulations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, simulation_mode NVARCHAR(120) NOT NULL, failure_type NVARCHAR(180) NOT NULL, selected_policy NVARCHAR(180) NULL, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, risk DECIMAL(8,2) NOT NULL DEFAULT 0, estimated_duration_seconds INT NOT NULL DEFAULT 0, estimated_cost DECIMAL(18,4) NOT NULL DEFAULT 0, final_output_impact NVARCHAR(180) NULL, incident_likelihood DECIMAL(8,2) NOT NULL DEFAULT 0, human_attention_likelihood DECIMAL(8,2) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'completed', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_simulation_steps', 'U') IS NULL CREATE TABLE recovery_policy_simulation_steps (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_simulation_id UNIQUEIDENTIFIER NOT NULL, step_name NVARCHAR(180) NOT NULL, step_order INT NOT NULL, outcome NVARCHAR(180) NULL, duration_ms INT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_executions', 'U') IS NULL CREATE TABLE recovery_policy_executions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, failure_context NVARCHAR(500) NULL, selected_strategy NVARCHAR(180) NULL, fallback_used BIT NOT NULL DEFAULT 0, guardrail_result NVARCHAR(180) NULL, compensation NVARCHAR(240) NULL, escalation NVARCHAR(180) NULL, final_output_impact NVARCHAR(180) NULL, outcome NVARCHAR(120) NOT NULL, duration_seconds INT NOT NULL DEFAULT 0, cost DECIMAL(18,4) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_execution_steps', 'U') IS NULL CREATE TABLE recovery_policy_execution_steps (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_execution_id UNIQUEIDENTIFIER NOT NULL, step_name NVARCHAR(180) NOT NULL, step_order INT NOT NULL, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, risk DECIMAL(8,2) NOT NULL DEFAULT 0, cost DECIMAL(18,4) NOT NULL DEFAULT 0, outcome NVARCHAR(180) NULL, audit_reference NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_decisions', 'U') IS NULL CREATE TABLE recovery_policy_decisions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, recovery_policy_id UNIQUEIDENTIFIER NULL, failure_context NVARCHAR(500) NOT NULL, candidate_policies NVARCHAR(500) NULL, evidence NVARCHAR(500) NULL, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, risk DECIMAL(8,2) NOT NULL DEFAULT 0, cost DECIMAL(18,4) NOT NULL DEFAULT 0, selected_policy NVARCHAR(180) NULL, selected_strategy NVARCHAR(180) NULL, fallback NVARCHAR(180) NULL, guardrail_result NVARCHAR(180) NULL, final_output_impact NVARCHAR(180) NULL, outcome NVARCHAR(180) NULL, human_input_required BIT NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_conflicts', 'U') IS NULL CREATE TABLE recovery_policy_conflicts (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, policies_involved NVARCHAR(500) NOT NULL, failure_scope NVARCHAR(220) NOT NULL, conflict_type NVARCHAR(180) NOT NULL, risk NVARCHAR(80) NOT NULL, execution_ambiguity NVARCHAR(300) NULL, recommended_resolution NVARCHAR(300) NULL, auto_resolution_available BIT NOT NULL DEFAULT 0, governance_review_required BIT NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'open', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_coverage', 'U') IS NULL CREATE TABLE recovery_policy_coverage (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, coverage_row NVARCHAR(180) NOT NULL, retry_status NVARCHAR(80) NOT NULL, checkpoint_status NVARCHAR(80) NOT NULL, worker_failover_status NVARCHAR(80) NOT NULL, queue_failover_status NVARCHAR(80) NOT NULL, provider_failover_status NVARCHAR(80) NOT NULL, model_failover_status NVARCHAR(80) NOT NULL, output_recovery_status NVARCHAR(80) NOT NULL, compensation_status NVARCHAR(80) NOT NULL, incident_escalation_status NVARCHAR(80) NOT NULL, final_output_protection_status NVARCHAR(80) NOT NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_metrics', 'U') IS NULL CREATE TABLE recovery_policy_metrics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, executions INT NOT NULL DEFAULT 0, success_rate DECIMAL(8,2) NOT NULL DEFAULT 0, failure_rate DECIMAL(8,2) NOT NULL DEFAULT 0, average_recovery_time_seconds INT NOT NULL DEFAULT 0, average_recovery_cost DECIMAL(18,4) NOT NULL DEFAULT 0, retry_success DECIMAL(8,2) NOT NULL DEFAULT 0, checkpoint_success DECIMAL(8,2) NOT NULL DEFAULT 0, worker_failover_success DECIMAL(8,2) NOT NULL DEFAULT 0, queue_failover_success DECIMAL(8,2) NOT NULL DEFAULT 0, provider_failover_success DECIMAL(8,2) NOT NULL DEFAULT 0, model_failover_success DECIMAL(8,2) NOT NULL DEFAULT 0, compensation_success DECIMAL(8,2) NOT NULL DEFAULT 0, incident_creation_rate DECIMAL(8,2) NOT NULL DEFAULT 0, human_escalation_rate DECIMAL(8,2) NOT NULL DEFAULT 0, final_output_protection_rate DECIMAL(8,2) NOT NULL DEFAULT 0, sla_protection_rate DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_recommendations', 'U') IS NULL CREATE TABLE recovery_policy_recommendations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, recovery_policy_id UNIQUEIDENTIFIER NULL, policy_code NVARCHAR(120) NULL, problem NVARCHAR(300) NOT NULL, recommendation NVARCHAR(300) NOT NULL, expected_time_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, expected_cost_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, expected_output_improvement DECIMAL(8,2) NOT NULL DEFAULT 0, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, risk NVARCHAR(80) NOT NULL DEFAULT 'low', auto_apply_eligible BIT NOT NULL DEFAULT 0, applied_status NVARCHAR(80) NOT NULL DEFAULT 'recommended', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_change_history', 'U') IS NULL CREATE TABLE recovery_policy_change_history (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, change_type NVARCHAR(120) NOT NULL, change_summary NVARCHAR(500) NULL, changed_by NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_documentation', 'U') IS NULL CREATE TABLE recovery_policy_documentation (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, title NVARCHAR(220) NOT NULL, summary NVARCHAR(1000) NULL, generated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_final_output_links', 'U') IS NULL CREATE TABLE recovery_policy_final_output_links (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, output_chain NVARCHAR(500) NOT NULL, protection_status NVARCHAR(80) NOT NULL, publishing_recovery BIT NOT NULL DEFAULT 1, analytics_recovery BIT NOT NULL DEFAULT 1, learning_recovery BIT NOT NULL DEFAULT 1, degradation_risk NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('recovery_policy_governance_approvals', 'U') IS NULL CREATE TABLE recovery_policy_governance_approvals (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, recovery_policy_id UNIQUEIDENTIFIER NOT NULL, approval_reason NVARCHAR(240) NOT NULL, status NVARCHAR(80) NOT NULL, required_for NVARCHAR(180) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('vw_recovery_policies_list', 'V') IS NOT NULL DROP VIEW vw_recovery_policies_list;
EXEC('CREATE VIEW vw_recovery_policies_list AS SELECT p.*, c.category_name FROM recovery_policies p LEFT JOIN recovery_policy_categories c ON c.id=p.category_id');
IF OBJECT_ID('vw_recovery_policy_summary', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_summary;
EXEC('CREATE VIEW vw_recovery_policy_summary AS SELECT p.organization_id, SUM(c.total_policies) AS total_recovery_policies, SUM(c.active_policies) AS active_policies, CAST(AVG(c.final_output_protection_rate) AS DECIMAL(8,2)) AS recovery_coverage, SUM(c.recoveries_today) AS recoveries_today, CAST(AVG(c.success_rate) AS DECIMAL(8,2)) AS recovery_success_rate, CAST(AVG(c.average_recovery_time_seconds) AS INT) AS average_recovery_time_seconds, SUM(c.guardrail_blocks) AS guardrail_breaches, (SELECT COUNT(*) FROM recovery_policy_conflicts x WHERE x.organization_id=p.organization_id AND x.status=''open'') AS policy_conflicts, CAST(AVG(c.final_output_protection_rate) AS DECIMAL(8,2)) AS final_outputs_protected, COUNT(CASE WHEN p.human_escalation_enabled=1 AND p.status IN (''Warning'',''Invalid'',''Conflicted'') THEN 1 END) AS human_attention_required, MAX(p.updated_at) AS last_recovery_decision FROM recovery_policies p JOIN recovery_policy_categories c ON c.id=p.category_id GROUP BY p.organization_id');
IF OBJECT_ID('vw_recovery_policy_health', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_health;
EXEC('CREATE VIEW vw_recovery_policy_health AS SELECT c.*, c.category_name AS policy_category FROM recovery_policy_categories c');
IF OBJECT_ID('vw_recovery_policy_conflicts', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_conflicts;
EXEC('CREATE VIEW vw_recovery_policy_conflicts AS SELECT * FROM recovery_policy_conflicts');
IF OBJECT_ID('vw_recovery_policy_coverage', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_coverage;
EXEC('CREATE VIEW vw_recovery_policy_coverage AS SELECT * FROM recovery_policy_coverage');
IF OBJECT_ID('vw_recovery_policy_performance', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_performance;
EXEC('CREATE VIEW vw_recovery_policy_performance AS SELECT m.*, p.organization_id, p.policy_code, p.policy_name, c.category_name FROM recovery_policy_metrics m JOIN recovery_policies p ON p.id=m.recovery_policy_id LEFT JOIN recovery_policy_categories c ON c.id=p.category_id');
IF OBJECT_ID('vw_recovery_policy_recommendations', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_recommendations;
EXEC('CREATE VIEW vw_recovery_policy_recommendations AS SELECT r.*, p.policy_name FROM recovery_policy_recommendations r LEFT JOIN recovery_policies p ON p.id=r.recovery_policy_id');
IF OBJECT_ID('vw_recovery_policy_final_output_protection', 'V') IS NOT NULL DROP VIEW vw_recovery_policy_final_output_protection;
EXEC('CREATE VIEW vw_recovery_policy_final_output_protection AS SELECT f.*, p.organization_id, p.policy_code, p.policy_name, c.category_name FROM recovery_policy_final_output_links f JOIN recovery_policies p ON p.id=f.recovery_policy_id LEFT JOIN recovery_policy_categories c ON c.id=p.category_id');

