IF OBJECT_ID('operations_dashboard','U') IS NULL
CREATE TABLE operations_dashboard (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  organization_id UNIQUEIDENTIFIER NOT NULL,
  status NVARCHAR(80) NOT NULL DEFAULT 'active',
  overall_health DECIMAL(8,2) NOT NULL DEFAULT 0,
  source_snapshot NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NULL
);

IF OBJECT_ID('operations_agents','U') IS NULL
CREATE TABLE operations_agents (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  organization_id UNIQUEIDENTIFIER NOT NULL,
  agent_id UNIQUEIDENTIFIER NULL,
  status NVARCHAR(80) NOT NULL,
  health_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  current_task NVARCHAR(300) NULL,
  queue_name NVARCHAR(160) NULL,
  worker_id NVARCHAR(160) NULL,
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('operations_workers','U') IS NULL
CREATE TABLE operations_workers (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  organization_id UNIQUEIDENTIFIER NOT NULL,
  worker_id NVARCHAR(160) NOT NULL,
  queue_name NVARCHAR(160) NULL,
  status NVARCHAR(80) NOT NULL DEFAULT 'running',
  running_jobs INT NOT NULL DEFAULT 0,
  cpu_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  ram_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('operations_queues','U') IS NULL
CREATE TABLE operations_queues (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  organization_id UNIQUEIDENTIFIER NOT NULL,
  queue_name NVARCHAR(160) NOT NULL,
  status NVARCHAR(80) NOT NULL DEFAULT 'healthy',
  waiting_jobs INT NOT NULL DEFAULT 0,
  running_jobs INT NOT NULL DEFAULT 0,
  retry_jobs INT NOT NULL DEFAULT 0,
  dead_letters INT NOT NULL DEFAULT 0,
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('operations_workflows','U') IS NULL
CREATE TABLE operations_workflows (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  organization_id UNIQUEIDENTIFIER NOT NULL,
  workflow_instance_id UNIQUEIDENTIFIER NULL,
  workflow_name NVARCHAR(220) NULL,
  stage_name NVARCHAR(220) NULL,
  status NVARCHAR(80) NOT NULL,
  progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0,
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

IF OBJECT_ID('operations_models','U') IS NULL
CREATE TABLE operations_models (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, provider_name NVARCHAR(160) NULL, model_name NVARCHAR(160) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'healthy', tokens INT NOT NULL DEFAULT 0, latency_ms INT NOT NULL DEFAULT 0, cost DECIMAL(18,4) NOT NULL DEFAULT 0, updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_tools','U') IS NULL
CREATE TABLE operations_tools (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, tool_name NVARCHAR(180) NOT NULL, agent_name NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL, latency_ms INT NOT NULL DEFAULT 0, retries INT NOT NULL DEFAULT 0, updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_memory','U') IS NULL
CREATE TABLE operations_memory (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, agent_name NVARCHAR(180) NULL, memory_type NVARCHAR(120) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'healthy', relevance_score DECIMAL(8,2) NOT NULL DEFAULT 0, updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_rag','U') IS NULL
CREATE TABLE operations_rag (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, query_name NVARCHAR(220) NULL, source_name NVARCHAR(220) NULL, grounding_score DECIMAL(8,2) NOT NULL DEFAULT 0, citation_score DECIMAL(8,2) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'healthy', updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_security','U') IS NULL
CREATE TABLE operations_security (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, event_type NVARCHAR(160) NOT NULL, severity NVARCHAR(80) NOT NULL, status NVARCHAR(80) NOT NULL, details NVARCHAR(700) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_governance','U') IS NULL
CREATE TABLE operations_governance (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, policy_name NVARCHAR(220) NULL, decision NVARCHAR(220) NULL, status NVARCHAR(80) NOT NULL, risk_level NVARCHAR(80) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_learning','U') IS NULL
CREATE TABLE operations_learning (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, signal_type NVARCHAR(160) NULL, insight NVARCHAR(500) NULL, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'active', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_business','U') IS NULL
CREATE TABLE operations_business (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_name NVARCHAR(160) NOT NULL, metric_value DECIMAL(18,4) NOT NULL DEFAULT 0, impact NVARCHAR(220) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'monitoring', updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_events','U') IS NULL
CREATE TABLE operations_events (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, event_type NVARCHAR(180) NOT NULL, source_name NVARCHAR(180) NULL, severity NVARCHAR(80) NOT NULL DEFAULT 'info', message NVARCHAR(700) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('operations_alerts','U') IS NULL
CREATE TABLE operations_alerts (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, alert_type NVARCHAR(160) NOT NULL, severity NVARCHAR(80) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'open', message NVARCHAR(700) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), resolved_at DATETIME2 NULL);
