IF OBJECT_ID('ai_strategy_themes','U') IS NULL
CREATE TABLE ai_strategy_themes (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, theme_name NVARCHAR(220) NOT NULL, objective_count INT NOT NULL DEFAULT 0, program_count INT NOT NULL DEFAULT 0, initiative_count INT NOT NULL DEFAULT 0, planned_investment DECIMAL(18,2) NOT NULL DEFAULT 0, forecast_value DECIMAL(18,2) NOT NULL DEFAULT 0, realized_benefits DECIMAL(18,2) NOT NULL DEFAULT 0, risk_level NVARCHAR(80) NOT NULL DEFAULT 'Observation', progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, executive_owner NVARCHAR(180) NULL, health_percent DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ai_strategy_value_chain','U') IS NULL
CREATE TABLE ai_strategy_value_chain (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, sequence_no INT NOT NULL, stage_name NVARCHAR(180) NOT NULL, item_count INT NOT NULL DEFAULT 0, health_percent DECIMAL(8,2) NOT NULL DEFAULT 0, alignment_percent DECIMAL(8,2) NOT NULL DEFAULT 0, funding_status NVARCHAR(80) NULL, capacity_status NVARCHAR(80) NULL, risk_level NVARCHAR(80) NULL, benefits_status NVARCHAR(80) NULL, final_outcome_linkage DECIMAL(8,2) NOT NULL DEFAULT 0, current_warnings NVARCHAR(500) NULL);
IF OBJECT_ID('ai_strategy_objectives','U') IS NULL
CREATE TABLE ai_strategy_objectives (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, objective_code NVARCHAR(80) NOT NULL, objective_name NVARCHAR(260) NOT NULL, strategic_theme NVARCHAR(180) NULL, executive_owner NVARCHAR(180) NULL, organization_name NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Draft', priority NVARCHAR(80) NOT NULL DEFAULT 'Medium', target_metric NVARCHAR(180) NULL, baseline NVARCHAR(120) NULL, current_value NVARCHAR(120) NULL, target_value NVARCHAR(120) NULL, progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, forecast_value NVARCHAR(120) NULL, ai_contribution DECIMAL(8,2) NOT NULL DEFAULT 0, investment DECIMAL(18,2) NOT NULL DEFAULT 0, expected_value DECIMAL(18,2) NOT NULL DEFAULT 0, realized_value DECIMAL(18,2) NOT NULL DEFAULT 0, risk_level NVARCHAR(80) NOT NULL DEFAULT 'Observation', due_date DATE NULL, program_count INT NOT NULL DEFAULT 0, initiative_count INT NOT NULL DEFAULT 0, final_outcome_linkage DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ai_strategy_portfolios','U') IS NULL
CREATE TABLE ai_strategy_portfolios (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, portfolio_code NVARCHAR(80) NOT NULL, portfolio_name NVARCHAR(220) NOT NULL, portfolio_type NVARCHAR(100) NULL, strategic_theme NVARCHAR(180) NULL, executive_sponsor NVARCHAR(180) NULL, portfolio_manager NVARCHAR(180) NULL, organization_name NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Proposed', program_count INT NOT NULL DEFAULT 0, initiative_count INT NOT NULL DEFAULT 0, planned_investment DECIMAL(18,2) NOT NULL DEFAULT 0, approved_budget DECIMAL(18,2) NOT NULL DEFAULT 0, actual_spend DECIMAL(18,2) NOT NULL DEFAULT 0, expected_value DECIMAL(18,2) NOT NULL DEFAULT 0, realized_value DECIMAL(18,2) NOT NULL DEFAULT 0, forecast_roi DECIMAL(8,2) NOT NULL DEFAULT 0, risk_level NVARCHAR(80) NOT NULL DEFAULT 'Observation', strategic_alignment DECIMAL(8,2) NOT NULL DEFAULT 0, capacity_status NVARCHAR(80) NULL, benefits_status NVARCHAR(80) NULL, portfolio_health DECIMAL(8,2) NOT NULL DEFAULT 0, review_date DATE NULL);
IF OBJECT_ID('ai_strategy_programs','U') IS NULL
CREATE TABLE ai_strategy_programs (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, program_code NVARCHAR(80) NOT NULL, program_name NVARCHAR(220) NOT NULL, portfolio_name NVARCHAR(220) NULL, strategic_objective NVARCHAR(260) NULL, program_owner NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Proposed', priority NVARCHAR(80) NULL, initiative_count INT NOT NULL DEFAULT 0, start_date DATE NULL, target_date DATE NULL, progress_percent DECIMAL(8,2) NOT NULL DEFAULT 0, planned_investment DECIMAL(18,2) NOT NULL DEFAULT 0, actual_spend DECIMAL(18,2) NOT NULL DEFAULT 0, expected_benefits DECIMAL(18,2) NOT NULL DEFAULT 0, realized_benefits DECIMAL(18,2) NOT NULL DEFAULT 0, risk_level NVARCHAR(80) NULL, dependencies INT NOT NULL DEFAULT 0, program_health DECIMAL(8,2) NOT NULL DEFAULT 0);
IF OBJECT_ID('ai_strategy_initiatives','U') IS NULL
CREATE TABLE ai_strategy_initiatives (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, initiative_code NVARCHAR(80) NOT NULL, initiative_name NVARCHAR(260) NOT NULL, portfolio_name NVARCHAR(220) NULL, program_name NVARCHAR(220) NULL, strategic_objective NVARCHAR(260) NULL, category NVARCHAR(120) NULL, stage NVARCHAR(80) NOT NULL DEFAULT 'Idea', status NVARCHAR(80) NOT NULL DEFAULT 'Proposed', priority_score DECIMAL(8,2) NOT NULL DEFAULT 0, executive_sponsor NVARCHAR(180) NULL, business_owner NVARCHAR(180) NULL, product_owner NVARCHAR(180) NULL, planned_investment DECIMAL(18,2) NOT NULL DEFAULT 0, approved_funding DECIMAL(18,2) NOT NULL DEFAULT 0, actual_spend DECIMAL(18,2) NOT NULL DEFAULT 0, expected_value DECIMAL(18,2) NOT NULL DEFAULT 0, forecast_roi DECIMAL(8,2) NOT NULL DEFAULT 0, benefit_score DECIMAL(8,2) NOT NULL DEFAULT 0, strategic_alignment DECIMAL(8,2) NOT NULL DEFAULT 0, risk_score DECIMAL(8,2) NOT NULL DEFAULT 0, feasibility_score DECIMAL(8,2) NOT NULL DEFAULT 0, capacity_requirement NVARCHAR(120) NULL, dependency_count INT NOT NULL DEFAULT 0, target_date DATE NULL, final_outcome_readiness DECIMAL(8,2) NOT NULL DEFAULT 0, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ai_strategy_prioritization','U') IS NULL
CREATE TABLE ai_strategy_prioritization (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, initiative_name NVARCHAR(260) NULL, strategic_score DECIMAL(8,2) NOT NULL DEFAULT 0, value_score DECIMAL(8,2) NOT NULL DEFAULT 0, risk_score DECIMAL(8,2) NOT NULL DEFAULT 0, feasibility_score DECIMAL(8,2) NOT NULL DEFAULT 0, urgency_score DECIMAL(8,2) NOT NULL DEFAULT 0, dependency_score DECIMAL(8,2) NOT NULL DEFAULT 0, capacity_score DECIMAL(8,2) NOT NULL DEFAULT 0, composite_score DECIMAL(8,2) NOT NULL DEFAULT 0, recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_portfolio_balance','U') IS NULL
CREATE TABLE ai_strategy_portfolio_balance (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, balance_dimension NVARCHAR(160) NOT NULL, current_mix DECIMAL(8,2) NOT NULL DEFAULT 0, target_mix DECIMAL(8,2) NOT NULL DEFAULT 0, gap_percent DECIMAL(8,2) NOT NULL DEFAULT 0, recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_funding','U') IS NULL
CREATE TABLE ai_strategy_funding (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, funding_name NVARCHAR(220) NOT NULL, requested_amount DECIMAL(18,2) NOT NULL DEFAULT 0, approved_amount DECIMAL(18,2) NOT NULL DEFAULT 0, committed_spend DECIMAL(18,2) NOT NULL DEFAULT 0, funding_gap DECIMAL(18,2) NOT NULL DEFAULT 0, funding_status NVARCHAR(80) NOT NULL DEFAULT 'Pending', recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_capacity','U') IS NULL
CREATE TABLE ai_strategy_capacity (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, resource_name NVARCHAR(180) NOT NULL, required_capacity DECIMAL(18,2) NOT NULL DEFAULT 0, available_capacity DECIMAL(18,2) NOT NULL DEFAULT 0, capacity_gap DECIMAL(8,2) NOT NULL DEFAULT 0, critical_skills NVARCHAR(300) NULL, recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_demand_forecast','U') IS NULL
CREATE TABLE ai_strategy_demand_forecast (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, resource_name NVARCHAR(180) NOT NULL, forecast_horizon NVARCHAR(80) NOT NULL, forecast_demand DECIMAL(18,2) NOT NULL DEFAULT 0, demand_gap DECIMAL(18,2) NOT NULL DEFAULT 0, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_roadmap','U') IS NULL
CREATE TABLE ai_strategy_roadmap (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, roadmap_name NVARCHAR(220) NOT NULL, phase_name NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Planned', start_date DATE NULL, target_date DATE NULL, risk_level NVARCHAR(80) NULL);
IF OBJECT_ID('ai_strategy_milestones','U') IS NULL
CREATE TABLE ai_strategy_milestones (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, milestone_name NVARCHAR(220) NOT NULL, roadmap_name NVARCHAR(220) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Planned', target_date DATE NULL, actual_date DATE NULL, risk_level NVARCHAR(80) NULL);
IF OBJECT_ID('ai_strategy_stage_gates','U') IS NULL
CREATE TABLE ai_strategy_stage_gates (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, stage_gate_name NVARCHAR(220) NOT NULL, initiative_name NVARCHAR(260) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Pending', review_date DATE NULL, gate_result NVARCHAR(80) NULL, risk_level NVARCHAR(80) NULL);
IF OBJECT_ID('ai_strategy_dependencies','U') IS NULL
CREATE TABLE ai_strategy_dependencies (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, dependency_name NVARCHAR(220) NOT NULL, upstream_item NVARCHAR(220) NULL, downstream_item NVARCHAR(220) NULL, dependency_status NVARCHAR(80) NOT NULL DEFAULT 'Open', risk_level NVARCHAR(80) NULL, recommended_action NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_duplicates','U') IS NULL
CREATE TABLE ai_strategy_duplicates (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, duplicate_name NVARCHAR(220) NOT NULL, candidate_a NVARCHAR(220) NULL, candidate_b NVARCHAR(220) NULL, duplicate_score DECIMAL(8,2) NOT NULL DEFAULT 0, recommended_action NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_benefits','U') IS NULL
CREATE TABLE ai_strategy_benefits (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, benefit_name NVARCHAR(220) NOT NULL, expected_value DECIMAL(18,2) NOT NULL DEFAULT 0, realized_value DECIMAL(18,2) NOT NULL DEFAULT 0, realization_percent DECIMAL(8,2) NOT NULL DEFAULT 0, benefit_owner NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Defined');
IF OBJECT_ID('ai_strategy_benefit_reviews','U') IS NULL
CREATE TABLE ai_strategy_benefit_reviews (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, benefit_name NVARCHAR(220) NOT NULL, review_status NVARCHAR(80) NOT NULL DEFAULT 'Due', review_date DATE NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Open', recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_risks','U') IS NULL
CREATE TABLE ai_strategy_risks (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, risk_name NVARCHAR(220) NOT NULL, risk_domain NVARCHAR(120) NULL, severity NVARCHAR(80) NOT NULL DEFAULT 'Observation', likelihood DECIMAL(8,2) NOT NULL DEFAULT 0, impact DECIMAL(8,2) NOT NULL DEFAULT 0, risk_score DECIMAL(8,2) NOT NULL DEFAULT 0, owner NVARCHAR(180) NULL, mitigation_status NVARCHAR(120) NULL);
IF OBJECT_ID('ai_strategy_assumptions','U') IS NULL
CREATE TABLE ai_strategy_assumptions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, assumption_name NVARCHAR(220) NOT NULL, validation_status NVARCHAR(80) NOT NULL DEFAULT 'Unvalidated', impact NVARCHAR(120) NULL);
IF OBJECT_ID('ai_strategy_constraints','U') IS NULL
CREATE TABLE ai_strategy_constraints (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, constraint_name NVARCHAR(220) NOT NULL, severity NVARCHAR(80) NOT NULL DEFAULT 'Medium', owner NVARCHAR(180) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Open');
IF OBJECT_ID('ai_strategy_scenarios','U') IS NULL
CREATE TABLE ai_strategy_scenarios (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, scenario_name NVARCHAR(220) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Draft', expected_value DECIMAL(18,2) NOT NULL DEFAULT 0, confidence DECIMAL(8,2) NOT NULL DEFAULT 0, updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ai_strategy_decisions','U') IS NULL
CREATE TABLE ai_strategy_decisions (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, decision_title NVARCHAR(260) NOT NULL, priority NVARCHAR(80) NOT NULL DEFAULT 'Review', status NVARCHAR(80) NOT NULL DEFAULT 'Open', owner NVARCHAR(180) NULL, due_at DATETIME2 NULL);
IF OBJECT_ID('ai_strategy_retirements','U') IS NULL
CREATE TABLE ai_strategy_retirements (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, retirement_name NVARCHAR(220) NOT NULL, initiative_name NVARCHAR(260) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Recommended', reason NVARCHAR(500) NULL, recommended_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ai_strategy_maturity_roadmap','U') IS NULL
CREATE TABLE ai_strategy_maturity_roadmap (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, sequence_no INT NOT NULL, maturity_step NVARCHAR(220) NOT NULL, current_level DECIMAL(8,2) NOT NULL DEFAULT 0, target_level DECIMAL(8,2) NOT NULL DEFAULT 0, maturity_gap DECIMAL(8,2) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'Planned');
IF OBJECT_ID('ai_strategy_alignment','U') IS NULL
CREATE TABLE ai_strategy_alignment (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, alignment_name NVARCHAR(220) NOT NULL, alignment_score DECIMAL(8,2) NOT NULL DEFAULT 0, missing_linkage NVARCHAR(260) NULL, recommendation NVARCHAR(260) NULL);
IF OBJECT_ID('ai_strategy_analytics','U') IS NULL
CREATE TABLE ai_strategy_analytics (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, metric_name NVARCHAR(180) NOT NULL, metric_value NVARCHAR(120) NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Observation');
IF OBJECT_ID('ai_strategy_recommendations','U') IS NULL
CREATE TABLE ai_strategy_recommendations (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, recommendation_type NVARCHAR(120) NOT NULL, recommendation NVARCHAR(700) NOT NULL, priority NVARCHAR(80) NOT NULL DEFAULT 'Review', confidence DECIMAL(8,2) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'Open');
IF OBJECT_ID('ai_strategy_final_outcome_traceability','U') IS NULL
CREATE TABLE ai_strategy_final_outcome_traceability (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, final_outcome NVARCHAR(260) NOT NULL, strategy_item NVARCHAR(260) NULL, traceability_score DECIMAL(8,2) NOT NULL DEFAULT 0, status NVARCHAR(80) NOT NULL DEFAULT 'Partial');
IF OBJECT_ID('ai_strategy_reports','U') IS NULL
CREATE TABLE ai_strategy_reports (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, report_name NVARCHAR(220) NOT NULL, status NVARCHAR(80) NOT NULL DEFAULT 'Generated', generated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('ai_strategy_events','U') IS NULL
CREATE TABLE ai_strategy_events (id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY, organization_id UNIQUEIDENTIFIER NOT NULL, event_type NVARCHAR(160) NOT NULL, severity NVARCHAR(80) NOT NULL DEFAULT 'info', message NVARCHAR(700) NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());

IF OBJECT_ID('vw_ai_strategy_summary','V') IS NOT NULL DROP VIEW vw_ai_strategy_summary;
EXEC('CREATE VIEW vw_ai_strategy_summary AS SELECT o.id AS organization_id, CAST(COALESCE(AVG(p.portfolio_health),0) AS DECIMAL(8,2)) AS portfolio_health, COUNT(DISTINCT obj.id) AS active_strategic_objectives, COUNT(DISTINCT prg.id) AS active_programs, COUNT(DISTINCT init.id) AS active_initiatives, COALESCE(SUM(init.planned_investment),0) AS total_planned_investment, COALESCE(SUM(init.expected_value),0) AS expected_portfolio_value, CAST(COALESCE(AVG(init.forecast_roi),0) AS DECIMAL(8,2)) AS forecast_portfolio_roi, CAST(COALESCE(AVG(b.realization_percent),0) AS DECIMAL(8,2)) AS benefits_realized, SUM(CASE WHEN obj.status IN (''At Risk'',''Behind'',''Blocked'') THEN 1 ELSE 0 END) AS strategic_objectives_at_risk, COUNT(DISTINCT d.id) AS human_attention_required, COALESCE(SUM(f.funding_gap),0) AS funding_gap, CAST(COALESCE(AVG(c.capacity_gap),0) AS DECIMAL(8,2)) AS capacity_gap FROM organizations o LEFT JOIN ai_strategy_objectives obj ON obj.organization_id=o.id LEFT JOIN ai_strategy_portfolios p ON p.organization_id=o.id LEFT JOIN ai_strategy_programs prg ON prg.organization_id=o.id LEFT JOIN ai_strategy_initiatives init ON init.organization_id=o.id LEFT JOIN ai_strategy_benefits b ON b.organization_id=o.id LEFT JOIN ai_strategy_decisions d ON d.organization_id=o.id AND d.status<>''Closed'' LEFT JOIN ai_strategy_funding f ON f.organization_id=o.id LEFT JOIN ai_strategy_capacity c ON c.organization_id=o.id GROUP BY o.id');
IF OBJECT_ID('vw_ai_strategy_status','V') IS NOT NULL DROP VIEW vw_ai_strategy_status;
EXEC('CREATE VIEW vw_ai_strategy_status AS SELECT o.id AS organization_id, CASE WHEN COUNT(ev.id)>0 THEN ''Autonomous with Executive Guardrails'' ELSE ''Observation Only'' END AS current_strategy_mode, ''Ready'' AS strategic_objective_registry, ''Ready'' AS portfolio_registry, ''Ready'' AS program_registry, ''Ready'' AS initiative_registry, ''Ready'' AS business_case_engine, ''Ready'' AS prioritization_engine, ''Ready'' AS funding_allocation_engine, ''Ready'' AS capacity_allocation_engine, ''Ready'' AS dependency_analysis_engine, ''Ready'' AS benefits_realization_engine, ''Ready'' AS value_attribution_engine, ''Ready'' AS roadmap_engine, ''Ready'' AS scenario_planning_engine, ''Ready'' AS portfolio_risk_engine, ''Ready'' AS strategic_alignment_engine, ''Ready'' AS recommendation_engine, ''Ready'' AS governance_connector, ''Ready'' AS audit_pipeline, COUNT(DISTINCT obj.id) AS objectives_being_monitored, COUNT(DISTINCT prg.id) AS programs_being_evaluated, COUNT(DISTINCT init.id) AS initiatives_being_scored, COUNT(DISTINCT f.id) AS funding_requests_open, COUNT(DISTINCT s.id) AS portfolio_scenarios_running, COUNT(DISTINCT br.id) AS benefits_reviews_due, COUNT(DISTINCT r.id) AS strategic_risks_open, COALESCE(MAX(r.risk_name),''none'') AS current_portfolio_bottleneck, COALESCE(MAX(rec.recommendation),''none'') AS current_highest_priority_recommendation, COALESCE(MAX(ev.message),''none'') AS last_autonomous_strategy_decision, COUNT(DISTINCT d.id) AS human_attention_required, MAX(ev.created_at) AS last_portfolio_update FROM organizations o LEFT JOIN ai_strategy_events ev ON ev.organization_id=o.id LEFT JOIN ai_strategy_objectives obj ON obj.organization_id=o.id LEFT JOIN ai_strategy_programs prg ON prg.organization_id=o.id LEFT JOIN ai_strategy_initiatives init ON init.organization_id=o.id LEFT JOIN ai_strategy_funding f ON f.organization_id=o.id LEFT JOIN ai_strategy_scenarios s ON s.organization_id=o.id LEFT JOIN ai_strategy_benefit_reviews br ON br.organization_id=o.id LEFT JOIN ai_strategy_risks r ON r.organization_id=o.id LEFT JOIN ai_strategy_recommendations rec ON rec.organization_id=o.id LEFT JOIN ai_strategy_decisions d ON d.organization_id=o.id AND d.status<>''Closed'' GROUP BY o.id');
