export const aiAgentRegistryMockData = {
  summary: {},
  registryHealth: [],
  coveragePipeline: [],
  domains: [],
  agents: [],
  agentDetails: {},
  registrationWizard: [],
  capabilities: [],
  validationResults: [],
  overlapAnalysis: [],
  workflowMappingMatrix: [],
  toolPermissionMatrix: [],
  providerModelMappings: [],
  promptHealth: [],
  memoryRagHealth: [],
  versions: [],
  orphanedAgents: [],
  impactAnalysis: [],
  recommendations: [],
  finalOutputLinkage: [],
}
