import type { LucideIcon } from 'lucide-react'
import {
  Archive,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Code2,
  DollarSign,
  Film,
  FileText,
  GraduationCap,
  LayoutDashboard,
  LifeBuoy,
  MapPin,
  Mic2,
  Monitor,
  Palette,
  Plug2,
  Repeat,
  Bot,
  Search,
  Send,
  Settings2,
  Shield,
  ShieldCheck,
  Share2,
  Sparkles,
  TrendingUp,
  Users,
  Zap,
} from 'lucide-react'

export type NavChild = {
  id: string
  title: string
  href: string
  badge?: string | number
  requiredPermission?: string
}

export type NavItem = {
  id: string
  title: string
  href: string
  icon: LucideIcon
  badge?: string | number
  requiredPermission?: string
  children?: NavChild[]
}

export type NavSection = {
  id: string
  title: string
  items: NavItem[]
}

export const navigationSections: NavSection[] = [
  {
    id: 'command-center',
    title: 'Command Center',
    items: [
      {
        id: 'executive-office',
        title: 'Executive Office',
        href: '/executive-office',
        icon: LayoutDashboard,
        badge: '14',
        children: [
          { id: 'dashboard', title: 'Executive Dashboard', href: '/executive-office/dashboard' },
          { id: 'business-intelligence', title: 'Business Intelligence', href: '/executive-office/business-intelligence' },
          { id: 'organization-health', title: 'Organization Health', href: '/executive-office/organization-health' },
          { id: 'risk-center', title: 'Risk Center', href: '/executive-office/risk-center' },
          { id: 'kpi-center', title: 'KPI Center', href: '/executive-office/kpi-center' },
          { id: 'executive-reports', title: 'Executive Reports', href: '/executive-office/executive-reports' },
        ],
      },
      {
        id: 'organization-management',
        title: 'Organization Management',
        href: '/organization-management',
        icon: Building2,
        badge: '8',
        children: [
          { id: 'organizations', title: 'Organizations', href: '/organization-management/organizations' },
          { id: 'teams', title: 'Teams', href: '/organization-management/teams' },
          { id: 'business-units', title: 'Business Units', href: '/organization-management/business-units' },
          { id: 'fiscal-calendar', title: 'Fiscal Calendar', href: '/organization-management/fiscal-calendar' },
          { id: 'license-management', title: 'License Management', href: '/organization-management/license-management' },
          { id: 'organization-audit', title: 'Organization Audit', href: '/organization-management/organization-audit' },
        ],
      },
      {
        id: 'brand-management',
        title: 'Brand Management',
        href: '/brand-management',
        icon: Palette,
        children: [
          { id: 'brand-guidelines', title: 'Brand Guidelines', href: '/brand-management/brand-guidelines' },
          { id: 'brand-assets', title: 'Brand Assets', href: '/brand-management/brand-assets' },
          { id: 'brand-templates', title: 'Brand Templates', href: '/brand-management/brand-templates' },
          { id: 'brand-approval', title: 'Brand Approval', href: '/brand-management/brand-approval' },
          { id: 'brand-performance', title: 'Brand Performance', href: '/brand-management/brand-performance' },
          { id: 'brand-compliance', title: 'Brand Compliance', href: '/brand-management/brand-compliance' },
        ],
      },
      {
        id: 'channel-management',
        title: 'Channel Management',
        href: '/channel-management',
        icon: Share2,
        children: [
          { id: 'youtube-channels', title: 'YouTube Channels', href: '/channel-management/youtube-channels' },
          { id: 'social-connect', title: 'Channel Connections', href: '/channel-management/channel-connections' },
          { id: 'api-connections', title: 'API Connections', href: '/channel-management/api-connections' },
          { id: 'channel-analytics', title: 'Channel Analytics', href: '/channel-management/channel-analytics' },
          { id: 'channel-health', title: 'Channel Health', href: '/channel-management/channel-health' },
          { id: 'posting-rules', title: 'Posting Rules', href: '/channel-management/posting-rules' },
        ],
      },
    ],
  },
  {
    id: 'content-intelligence',
    title: 'Content Intelligence',
    items: [
      {
        id: 'research-intelligence',
        title: 'AI Research Intelligence',
        href: '/research-intelligence',
        icon: Search,
        badge: 'New',
        children: [
          { id: 'trend-discovery', title: 'Trend Discovery', href: '/research-intelligence/trend-discovery' },
          { id: 'audience-research', title: 'Audience Research', href: '/research-intelligence/audience-research' },
          { id: 'competitor-intelligence', title: 'Competitor Intelligence', href: '/research-intelligence/competitor-intelligence' },
          { id: 'keyword-research', title: 'Keyword Research', href: '/research-intelligence/keyword-research' },
          { id: 'insights', title: 'Research Insights', href: '/research-intelligence/insights' },
          { id: 'research-archive', title: 'Research Archive', href: '/research-intelligence/research-archive' },
        ],
      },
      {
        id: 'content-strategy',
        title: 'Content Strategy',
        href: '/content-strategy',
        icon: MapPin,
        children: [
          { id: 'content-calendar', title: 'Content Calendar', href: '/content-strategy/content-calendar' },
          { id: 'campaign-planner', title: 'Campaign Planner', href: '/content-strategy/campaign-planner' },
          { id: 'topic-planner', title: 'Topic Planner', href: '/content-strategy/topic-planner' },
          { id: 'content-roadmap', title: 'Content Roadmap', href: '/content-strategy/content-roadmap' },
          { id: 'audience-strategy', title: 'Audience Strategy', href: '/content-strategy/audience-strategy' },
          { id: 'strategy-reports', title: 'Strategy Reports', href: '/content-strategy/strategy-reports' },
        ],
      },
      {
        id: 'seo-intelligence',
        title: 'SEO Intelligence',
        href: '/seo-intelligence',
        icon: TrendingUp,
        children: [
          { id: 'keyword-optimizer', title: 'Keyword Optimizer', href: '/seo-intelligence/keyword-optimizer' },
          { id: 'serp-monitoring', title: 'SERP Monitoring', href: '/seo-intelligence/serp-monitoring' },
          { id: 'content-optimization', title: 'Content Optimization', href: '/seo-intelligence/content-optimization' },
          { id: 'seo-audit', title: 'SEO Audit', href: '/seo-intelligence/seo-audit' },
          { id: 'metadata-manager', title: 'Metadata Manager', href: '/seo-intelligence/metadata-manager' },
          { id: 'seo-reports', title: 'SEO Reports', href: '/seo-intelligence/seo-reports' },
        ],
      },
      {
        id: 'analytics-intelligence',
        title: 'Analytics & Intelligence',
        href: '/analytics-intelligence',
        icon: BarChart3,
        children: [
          { id: 'audience-analytics', title: 'Audience Analytics', href: '/analytics-intelligence/audience-analytics' },
          { id: 'content-analytics', title: 'Content Analytics', href: '/analytics-intelligence/content-analytics' },
          { id: 'revenue-analytics', title: 'Revenue Analytics', href: '/analytics-intelligence/revenue-analytics' },
          { id: 'trend-reports', title: 'Trend Reports', href: '/analytics-intelligence/trend-reports' },
          { id: 'predictive-analytics', title: 'Predictive Analytics', href: '/analytics-intelligence/predictive-analytics' },
          { id: 'ai-insights', title: 'AI Insights', href: '/analytics-intelligence/ai-insights' },
        ],
      },
      {
        id: 'ai-learning-center',
        title: 'AI Learning Center',
        href: '/ai-learning-center',
        icon: GraduationCap,
        children: [
          { id: 'learning-models', title: 'Learning Models', href: '/ai-learning-center/learning-models' },
          { id: 'feedback-loop', title: 'Feedback Loop', href: '/ai-learning-center/feedback-loop' },
          { id: 'prompt-optimization', title: 'Prompt Optimization', href: '/ai-learning-center/prompt-optimization' },
          { id: 'agent-performance', title: 'Agent Performance', href: '/ai-learning-center/agent-performance' },
          { id: 'learning-reports', title: 'Learning Reports', href: '/ai-learning-center/learning-reports' },
          { id: 'thumbnail-learning', title: 'Thumbnail Learning', href: '/ai-learning-center/thumbnail-learning' },
        ],
      },
    ],
  },
  {
    id: 'production-studios',
    title: 'Production Studios',
    items: [
      {
        id: 'content-production',
        title: 'Content Production',
        href: '/content-production',
        icon: FileText,
        children: [
          { id: 'content-requests', title: 'Content Requests', href: '/content-production/content-requests' },
          { id: 'script-generator', title: 'Script Generator', href: '/content-production/script-generator' },
          { id: 'article-generator', title: 'Article Generator', href: '/content-production/article-generator' },
          { id: 'blog-generator', title: 'Blog Generator', href: '/content-production/blog-generator' },
          { id: 'newsletter-generator', title: 'Newsletter Generator', href: '/content-production/newsletter-generator' },
          { id: 'ai-content-review', title: 'AI Content Review', href: '/content-production/ai-content-review' },
        ],
      },
      {
        id: 'creative-studio',
        title: 'Creative Studio',
        href: '/creative-studio',
        icon: Sparkles,
        badge: '9',
        children: [
          { id: 'image-generator', title: 'Image Generator', href: '/creative-studio/image-generator' },
          { id: 'thumbnail-designer', title: 'Thumbnail Designer', href: '/creative-studio/thumbnail-designer' },
          { id: 'logo-designer', title: 'Logo Designer', href: '/creative-studio/logo-designer' },
          { id: 'social-graphics', title: 'Social Graphics', href: '/creative-studio/social-graphics' },
          { id: 'creative-templates', title: 'Creative Templates', href: '/creative-studio/creative-templates' },
          { id: 'image-editor', title: 'Image Editor', href: '/creative-studio/image-editor' },
        ],
      },
      {
        id: 'video-studio',
        title: 'Video Studio',
        href: '/video-studio',
        icon: Film,
        children: [
          { id: 'video-projects', title: 'Video Projects', href: '/video-studio/video-projects' },
          { id: 'video-generator', title: 'Video Generator', href: '/video-studio/video-generator' },
          { id: 'storyboard-manager', title: 'Storyboard Manager', href: '/video-studio/storyboard-manager' },
          { id: 'render-queue', title: 'Render Queue', href: '/video-studio/render-queue' },
          { id: 'video-archive', title: 'Video Archive', href: '/video-studio/video-archive' },
          { id: 'quality-review', title: 'Quality Review', href: '/video-studio/quality-review' },
        ],
      },
      {
        id: 'audio-voice-studio',
        title: 'Audio & Voice Studio',
        href: '/audio-voice-studio',
        icon: Mic2,
        children: [
          { id: 'voice-library', title: 'Voice Library', href: '/audio-voice-studio/voice-library' },
          { id: 'voice-generator', title: 'Voice Generator', href: '/audio-voice-studio/voice-generator' },
          { id: 'narration-studio', title: 'Narration Studio', href: '/audio-voice-studio/narration-studio' },
          { id: 'audio-mastering', title: 'Audio Mastering', href: '/audio-voice-studio/audio-mastering' },
          { id: 'podcast-production', title: 'Podcast Production', href: '/audio-voice-studio/podcast-production' },
          { id: 'audio-archive', title: 'Audio Archive', href: '/audio-voice-studio/audio-archive' },
        ],
      },
      {
        id: 'digital-asset-management',
        title: 'Digital Asset Management',
        href: '/digital-asset-management',
        icon: Archive,
        children: [
          { id: 'image-library', title: 'Image Library', href: '/digital-asset-management/image-library' },
          { id: 'video-library', title: 'Video Library', href: '/digital-asset-management/video-library' },
          { id: 'audio-library', title: 'Audio Library', href: '/digital-asset-management/audio-library' },
          { id: 'templates', title: 'Templates', href: '/digital-asset-management/templates' },
          { id: 'asset-search', title: 'Asset Search', href: '/digital-asset-management/asset-search' },
          { id: 'asset-approval', title: 'Asset Approval', href: '/digital-asset-management/asset-approval' },
        ],
      },
    ],
  },
  {
    id: 'distribution-growth',
    title: 'Distribution & Growth',
    items: [
      {
        id: 'publishing-center',
        title: 'Publishing Center',
        href: '/publishing-center',
        icon: Send,
        children: [
          { id: 'scheduled-posts', title: 'Scheduled Posts', href: '/publishing-center/scheduled-posts' },
          { id: 'publishing-queue', title: 'Publishing Queue', href: '/publishing-center/publishing-queue' },
          { id: 'live-publishing', title: 'Live Publishing', href: '/publishing-center/live-publishing' },
          { id: 'publishing-analytics', title: 'Publishing Analytics', href: '/publishing-center/publishing-analytics' },
          { id: 'content-archive', title: 'Content Archive', href: '/publishing-center/content-archive' },
          { id: 'bulk-publishing', title: 'Bulk Publishing', href: '/publishing-center/bulk-publishing' },
        ],
      },
      {
        id: 'marketing-automation',
        title: 'Marketing Automation',
        href: '/marketing-automation',
        icon: Zap,
        children: [
          { id: 'campaign-manager', title: 'Campaign Manager', href: '/marketing-automation/campaign-manager' },
          { id: 'email-campaigns', title: 'Email Campaigns', href: '/marketing-automation/email-campaigns' },
          { id: 'social-campaigns', title: 'Social Campaigns', href: '/marketing-automation/social-campaigns' },
          { id: 'landing-pages', title: 'Landing Pages', href: '/marketing-automation/landing-pages' },
          { id: 'audience-segments', title: 'Audience Segments', href: '/marketing-automation/audience-segments' },
          { id: 'campaign-analytics', title: 'Campaign Analytics', href: '/marketing-automation/campaign-analytics' },
        ],
      },
      {
        id: 'community-management',
        title: 'Community Management',
        href: '/community-management',
        icon: Users,
        children: [
          { id: 'community-inbox', title: 'Community Inbox', href: '/community-management/community-inbox' },
          { id: 'direct-messages', title: 'Direct Messages', href: '/community-management/direct-messages' },
          { id: 'engagement-reports', title: 'Engagement Reports', href: '/community-management/engagement-reports' },
          { id: 'sentiment-analysis', title: 'Sentiment Analysis', href: '/community-management/sentiment-analysis' },
          { id: 'moderation-rules', title: 'Moderation Rules', href: '/community-management/moderation-rules' },
          { id: 'support-tickets', title: 'Support Tickets', href: '/community-management/support-tickets' },
        ],
      },
      {
        id: 'monetization-center',
        title: 'Monetization Center',
        href: '/monetization-center',
        icon: DollarSign,
        children: [
          { id: 'ad-revenue', title: 'Ad Revenue', href: '/monetization-center/ad-revenue' },
          { id: 'memberships', title: 'Memberships', href: '/monetization-center/memberships' },
          { id: 'digital-products', title: 'Digital Products', href: '/monetization-center/digital-products' },
          { id: 'pricing-intelligence', title: 'Pricing Intelligence', href: '/monetization-center/pricing-intelligence' },
          { id: 'payout-tracking', title: 'Payout Tracking', href: '/monetization-center/payout-tracking' },
          { id: 'financial-reports', title: 'Financial Reports', href: '/monetization-center/financial-reports' },
        ],
      },
    ],
  },
  {
    id: 'automation-agents',
    title: 'Automation & Agents',
    items: [
      {
        id: 'ai-agents',
        title: 'AI Agents',
        href: '/ai-agents',
        icon: Bot,
        badge: '27',
        children: [
          { id: 'agent-registry', title: 'Agent Registry', href: '/dashboard/ai-agents/agent-registry' },
          { id: 'agent-capabilities', title: 'Agent Capabilities', href: '/dashboard/ai-agents/agent-capabilities' },
          { id: 'agent-roles-and-teams', title: 'Agent Roles and Teams', href: '/dashboard/ai-agents/agent-roles-and-teams' },
          { id: 'agent-tasks', title: 'Agent Tasks', href: '/dashboard/ai-agents/agent-tasks' },
          { id: 'agent-collaboration', title: 'Agent Collaboration', href: '/dashboard/ai-agents/agent-collaboration' },
          { id: 'prompt-management', title: 'Prompt Management', href: '/dashboard/ai-agents/prompt-management' },
          { id: 'model-provider-management', title: 'Model & Provider Management', href: '/dashboard/ai-agents/model-provider-management' },
          { id: 'tool-registry', title: 'Tool Registry', href: '/dashboard/ai-agents/tool-registry' },
          { id: 'memory-management', title: 'Memory Management', href: '/dashboard/ai-agents/memory-management' },
          { id: 'knowledge-base-management', title: 'Knowledge Base Management', href: '/dashboard/ai-agents/knowledge-base-management' },
          { id: 'rag-management', title: 'RAG Management', href: '/dashboard/ai-agents/rag-management' },
          { id: 'evaluation-benchmarking', title: 'Evaluation & Benchmarking', href: '/dashboard/ai-agents/evaluation-benchmarking' },
          { id: 'autonomous-learning-engine', title: 'Autonomous Learning Engine', href: '/dashboard/ai-agents/autonomous-learning-engine' },
          { id: 'agent-analytics', title: 'Agent Analytics', href: '/dashboard/ai-agents/agent-analytics' },
          { id: 'executive-command-center', title: 'AI Executive Command Center', href: '/dashboard/ai-agents/executive-command-center' },
          { id: 'strategy-portfolio-management', title: 'AI Strategy & Portfolio Management', href: '/dashboard/ai-agents/strategy-portfolio-management' },
          { id: 'operations-center', title: 'Agent Operations Center', href: '/dashboard/ai-agents/operations-center' },
          { id: 'audit-decision-trace', title: 'Audit & Decision Trace', href: '/dashboard/ai-agents/audit-decision-trace' },
          { id: 'governance-center', title: 'Agent Governance Center', href: '/dashboard/ai-agents/governance-center' },
          { id: 'security-center', title: 'Agent Security Center', href: '/dashboard/ai-agents/security-center' },
          { id: 'simulation-studio', title: 'Agent Simulation Studio', href: '/dashboard/ai-agents/simulation-studio' },
          { id: 'version-release-management', title: 'Agent Version & Release Management', href: '/dashboard/ai-agents/version-release-management' },
          { id: 'active-agent-runs', title: 'Active Agent Runs', href: '/dashboard/ai-agents/active-agent-runs' },
          { id: 'agent-marketplace', title: 'Agent Marketplace', href: '/ai-agents/agent-marketplace' },
          { id: 'custom-ai-agents', title: 'Custom AI Agents', href: '/ai-agents/custom-ai-agents' },
          { id: 'agent-workflows', title: 'Agent Workflows', href: '/ai-agents/agent-workflows' },
          { id: 'agent-monitoring', title: 'Agent Monitoring', href: '/ai-agents/agent-monitoring' },
          { id: 'agent-logs', title: 'Agent Logs', href: '/ai-agents/agent-logs' },
          { id: 'agent-prompts', title: 'Agent Prompts', href: '/ai-agents/agent-prompts' },
        ],
      },
      {
        id: 'workflow-automation',
        title: 'Workflow Automation',
        href: '/dashboard/workflow-automation',
        icon: Repeat,
        children: [
          { id: 'workflow-dashboard', title: 'Workflow Dashboard', href: '/dashboard/workflow-automation' },
          { id: 'active-workflows', title: 'Active Workflows', href: '/dashboard/workflow-automation/active-workflows' },
          { id: 'automation-rules', title: 'Automation Rules', href: '/dashboard/workflow-automation/automation-rules' },
          { id: 'triggers', title: 'Triggers', href: '/dashboard/workflow-automation/triggers' },
          { id: 'actions', title: 'Actions', href: '/dashboard/workflow-automation/actions' },
          { id: 'scheduled-workflows', title: 'Scheduled Workflows', href: '/dashboard/workflow-automation/scheduled-workflows' },
          { id: 'workflow-queue', title: 'Workflow Queue', href: '/dashboard/workflow-automation/workflow-queue' },
          { id: 'failed-workflows', title: 'Failed Workflows', href: '/dashboard/workflow-automation/failed-workflows' },
          { id: 'workflow-definitions', title: 'Workflow Definitions', href: '/dashboard/workflow-automation/workflow-definitions' },
          { id: 'workflow-designer', title: 'Workflow Designer', href: '/dashboard/workflow-automation/workflow-designer' },
          { id: 'approval-workflows', title: 'Approval Workflows', href: '/workflow-automation/approval-workflows' },
          { id: 'ai-workflows', title: 'AI Workflows', href: '/workflow-automation/ai-workflows' },
          { id: 'scheduled-jobs', title: 'Scheduled Jobs', href: '/workflow-automation/scheduled-jobs' },
          { id: 'workflow-logs', title: 'Workflow Logs', href: '/dashboard/workflow-automation/workflow-logs' },
          { id: 'workflow-templates', title: 'Workflow Templates', href: '/dashboard/workflow-automation/workflow-templates' },
          { id: 'workflow-versions', title: 'Workflow Versions', href: '/dashboard/workflow-automation/workflow-versions' },
          { id: 'workflow-analytics', title: 'Workflow Analytics', href: '/dashboard/workflow-automation/workflow-analytics' },
          { id: 'autonomous-recovery-policies', title: 'Autonomous Recovery Policies', href: '/dashboard/workflow-automation/autonomous-recovery-policies' },
        ],
      },
      {
        id: 'knowledge-hub',
        title: 'Knowledge Hub',
        href: '/knowledge-hub',
        icon: BookOpen,
        children: [
          { id: 'knowledge-graph', title: 'Knowledge Graph', href: '/knowledge-hub/knowledge-graph' },
          { id: 'prompt-library', title: 'Prompt Library', href: '/knowledge-hub/prompt-library' },
          { id: 'topic-library', title: 'Topic Library', href: '/knowledge-hub/topic-library' },
          { id: 'training-center', title: 'Training Center', href: '/knowledge-hub/training-center' },
          { id: 'knowledge-review', title: 'Knowledge Review', href: '/knowledge-hub/knowledge-review' },
          { id: 'knowledge-reports', title: 'Knowledge Reports', href: '/knowledge-hub/knowledge-reports' },
        ],
      },
      {
        id: 'integrations',
        title: 'Integrations',
        href: '/integrations',
        icon: Plug2,
        children: [
          { id: 'ai-providers', title: 'AI Providers', href: '/integrations/ai-providers' },
          { id: 'cloud-services', title: 'Cloud Services', href: '/integrations/cloud-services' },
          { id: 'api-keys', title: 'API Keys', href: '/integrations/api-keys' },
          { id: 'payment-gateways', title: 'Payment Gateways', href: '/integrations/payment-gateways' },
          { id: 'webhooks', title: 'Webhooks', href: '/integrations/webhooks' },
          { id: 'integration-logs', title: 'Integration Logs', href: '/integrations/integration-logs' },
        ],
      },
    ],
  },
  {
    id: 'governance-operations',
    title: 'Governance & Operations',
    items: [
      {
        id: 'notifications',
        title: 'Notifications',
        href: '/notifications',
        icon: Bell,
        children: [
          { id: 'notification-center', title: 'Notification Center', href: '/notifications/notification-center' },
          { id: 'alerts', title: 'Alerts', href: '/notifications/alerts' },
          { id: 'system-messages', title: 'System Messages', href: '/notifications/system-messages' },
          { id: 'approval-requests', title: 'Approval Requests', href: '/notifications/approval-requests' },
          { id: 'notification-settings', title: 'Notification Settings', href: '/notifications/notification-settings' },
          { id: 'notification-history', title: 'Notification History', href: '/notifications/notification-history' },
        ],
      },
      {
        id: 'reports',
        title: 'Reports',
        href: '/reports',
        icon: FileText,
        children: [
          { id: 'executive-reports', title: 'Executive Reports', href: '/reports/executive-reports' },
          { id: 'content-reports', title: 'Content Reports', href: '/reports/content-reports' },
          { id: 'seo-reports', title: 'SEO Reports', href: '/reports/seo-reports' },
          { id: 'revenue-reports', title: 'Revenue Reports', href: '/reports/revenue-reports' },
          { id: 'custom-reports', title: 'Custom Reports', href: '/reports/custom-reports' },
          { id: 'report-builder', title: 'Report Builder', href: '/reports/report-builder' },
        ],
      },
      {
        id: 'compliance-governance',
        title: 'Compliance & Governance',
        href: '/compliance-governance',
        icon: ShieldCheck,
        children: [
          { id: 'policy-center', title: 'Policy Center', href: '/compliance-governance/policy-center' },
          { id: 'audit-logs', title: 'Audit Logs', href: '/compliance-governance/audit-logs' },
          { id: 'privacy-compliance', title: 'Privacy Compliance', href: '/compliance-governance/privacy-compliance' },
          { id: 'content-moderation', title: 'Content Moderation', href: '/compliance-governance/content-moderation' },
          { id: 'governance-reports', title: 'Governance Reports', href: '/compliance-governance/governance-reports' },
          { id: 'plagiarism-review', title: 'Plagiarism Review', href: '/compliance-governance/plagiarism-review' },
        ],
      },
      {
        id: 'security-center',
        title: 'Security Center',
        href: '/security-center',
        icon: Shield,
        children: [
          { id: 'users', title: 'Users', href: '/security-center/users' },
          { id: 'roles', title: 'Roles', href: '/security-center/roles' },
          { id: 'permissions', title: 'Permissions', href: '/security-center/permissions' },
          { id: 'access-logs', title: 'Access Logs', href: '/security-center/access-logs' },
          { id: 'threat-monitoring', title: 'Threat Monitoring', href: '/security-center/threat-monitoring' },
          { id: 'security-reports', title: 'Security Reports', href: '/security-center/security-reports' },
        ],
      },
      {
        id: 'administration',
        title: 'Administration',
        href: '/administration',
        icon: Settings2,
        children: [
          { id: 'system-settings', title: 'System Settings', href: '/administration/system-settings' },
          { id: 'feature-flags', title: 'Feature Flags', href: '/administration/feature-flags' },
          { id: 'audit-settings', title: 'Audit Settings', href: '/administration/audit-settings' },
          { id: 'billing-settings', title: 'Billing Settings', href: '/administration/billing-settings' },
          { id: 'storage-management', title: 'Storage Management', href: '/administration/storage-management' },
          { id: 'environment-settings', title: 'Environment Settings', href: '/administration/environment-settings' },
        ],
      },
      {
        id: 'developer-center',
        title: 'Developer Center',
        href: '/developer-center',
        icon: Code2,
        children: [
          { id: 'api-explorer', title: 'API Explorer', href: '/developer-center/api-explorer' },
          { id: 'sdk-tools', title: 'SDKs & Tools', href: '/developer-center/sdk-tools' },
          { id: 'webhooks', title: 'Webhooks', href: '/developer-center/webhooks' },
          { id: 'developer-keys', title: 'Developer Keys', href: '/developer-center/developer-keys' },
          { id: 'app-registration', title: 'App Registration', href: '/developer-center/app-registration' },
          { id: 'developer-documentation', title: 'Developer Documentation', href: '/developer-center/developer-documentation' },
        ],
      },
      {
        id: 'system-monitoring',
        title: 'System Monitoring',
        href: '/system-monitoring',
        icon: Monitor,
        children: [
          { id: 'workflow-status', title: 'Workflow Status', href: '/dashboard/system-monitoring/workflow-status' },
          { id: 'implementation-status', title: 'Implementation Status', href: '/dashboard/system-monitoring/implementation-status' },
          { id: 'service-health', title: 'Service Health', href: '/dashboard/system-monitoring/service-health' },
          { id: 'api-status', title: 'API Status', href: '/dashboard/system-monitoring/api-status' },
          { id: 'background-jobs', title: 'Background Jobs', href: '/dashboard/system-monitoring/background-jobs' },
          { id: 'uptime-monitoring', title: 'Uptime Monitoring', href: '/dashboard/system-monitoring/uptime-monitoring' },
          { id: 'logs', title: 'Logs', href: '/dashboard/system-monitoring/logs' },
          { id: 'incident-management', title: 'Incident Management', href: '/dashboard/system-monitoring/incident-management' },
        ],
      },
      {
        id: 'help-support',
        title: 'Help & Support',
        href: '/help-support',
        icon: LifeBuoy,
        children: [
          { id: 'help-center', title: 'Help Center', href: '/help-support/help-center' },
          { id: 'ai-assistant', title: 'AI Assistant', href: '/help-support/ai-assistant' },
          { id: 'user-guides', title: 'User Guides', href: '/help-support/user-guides' },
          { id: 'tutorials', title: 'Tutorials', href: '/help-support/tutorials' },
          { id: 'release-notes', title: 'Release Notes', href: '/help-support/release-notes' },
          { id: 'support-reports', title: 'Support Reports', href: '/help-support/support-reports' },
        ],
      },
    ],
  },
]
